### PR TITLE
Add a non-circ supply address

### PR DESCRIPTION
**Pull request by danpaul000**
Add a Foundation-funded address which will be used to pay out certain small rewards and validator onboarding fees.

### CODE REVIEW

**Comment by danpaul000** [comment]
@mvines I assume this needs backporting to 1.1 and 1.2 to get picked up correctly?

**Comment by danpaul000** [comment]
FYI: @aeyakovenko

**Comment by mvines** [comment]
@danpaul000 - next time can you send a PR from your fork.  Don't create new branches in the shared repo please

**Comment by danpaul000** [comment]
> @danpaul000 - next time can you send a PR from your fork. Don't create new branches in the shared repo please

Sorry about that.  Should I kill this one and re-create from the fork as well?

**Comment by mvines** [comment]
na, just for next time please

**Comment by mvines** [comment]
@danpaul000 - looks like mergify is getting all confused because this is a branch in the main repo after all.

**Pull request closed without merging**
