### PR TITLE
removes old runtime feature gates

### PR DESCRIPTION
**Pull request by behzadnouri**
#### Problem
Redundant code and runtime overhead since the features have been long activated. 

#### Summary of Changes
Removed the runtime features.

### CODE REVIEW

**Comment by behzadnouri** [comment]
@mvines any objection to merging this?

**Comment by mvines** [comment]
None, thanks!   

v1.6 backport?  Mainly asking from a future merge-conflict PoV, as while we're able to kick v1.5 to the curb we'll be living with v1.6 for months still

**Comment by behzadnouri** [comment]
> None, thanks!
> 
> v1.6 backport? Mainly asking from a future merge-conflict PoV, as while we're about to kick v1.5 to the curb we'll be living with v1.6 for months still

sure, backporting to v1.6. any preferences for backporting to v1.5 as well?

**Comment by mvines** [comment]
>  any preferences for backporting to v1.5 as well?
I vote no, since we want to move to v1.6 within a week or so

**Pull request merged**
