### PR TITLE
Push and query the ClusterInfo for votes.

### LINKED ISSUE #2545: Sending vote transactions is unnecessarily complex
#### Problem

Sending vote transactions is unnecessarily complex. VoteSignerProxy currently queries ClusterInfo for the TPU address, wraps the transaction as a blob, sends the blob to a channel. On the other side of that channel is a `responder`, which then unwraps the blob to get that TPU address, and sends it via a UDP socket.  If the sending thread did the TPU query, there'd be no use for the blob type.

#### Proposed Solution A

Instead of sending a blob to a channel, do an async send of the serialized transaction to the UDP socket. Instead of sending it to the real TPU, send it to the TPU port on localhost and let the TPU Forwarder query ClusterInfo and send it.

#### Proposed Solution B

Instead of sending a blob, send the transaction.  Instead of using a `responder`, send it to the same channel the TPU's FetchStage sends transactions. Like the first proposal, let the channel endpoint forward those transactions as needed.

#### Proposed Solution C

Instead of sending the vote to the TPU, send it to ClusterInfo #2562

### PR DESCRIPTION
**Pull request by sagar-solana**
Rebase and ownership change of #2562 

#### Problem

Need a way for the cluster to receive and send all the votes in the network regardless of leader failures.

#### Summary of Changes

Push votes into the crds, which will propagate them around the network. Leaders should call ClusterInfo::get_votes periodically (like on every tick) and process the vector like a batch of transactions. The bank will naturally drop any old, invalid or duplicate votes. The subsequent working leader in the round robin will pick up any pending votes as soon as possible.

Fixes #2545

Added book chapter on design. This PR implements the sub 1k node rollout plan described in the book.

### CODE REVIEW

**Comment by aeyakovenko** [comment]
@sagar-solana id like @garious to approve as well

**Comment by garious** [comment]
No merge commits please. Can you rebase instead?

**Comment by garious** [comment]
And squash a bunch of those top commits

**Comment by sagar-solana** [comment]
> No merge commits please. Can you rebase instead?

Oh, yes I meant to rebase. I'll squash the commits as well.

**Comment by sagar-solana** [comment]
@garious, is this good to go now ?

**Comment by sagar-solana** [comment]
@aeyakovenko @garious, Oh I just remembered. Did we want to keep the old mechanism running alongside this gossip based one? https://github.com/solana-labs/solana/pull/2562#issuecomment-457876125

**Comment by garious** [comment]
hell no

**Comment by rob-solana** [comment]
nevermind

**Pull request merged**
