### PR TITLE
optimizes ReadOnlyAccountsCache LRU eviction implementation

### PR DESCRIPTION
**Pull request by behzadnouri**
#### Problem
ReadOnlyAccountsCache is using a background thread, table scan and sort
to implement LRU eviction policy:
https://github.com/solana-labs/solana/blob/eaa52bc93/runtime/src/read_only_accounts_cache.rs#L66-L73
https://github.com/solana-labs/solana/blob/eaa52bc93/runtime/src/read_only_accounts_cache.rs#L186-L191
https://github.com/solana-labs/solana/blob/eaa52bc93/runtime/src/read_only_accounts_cache.rs#L222

DashMap internally locks each shard when accessed; so a table scan in
the background thread can create a lot of lock contention.

#### Summary of Changes
This commit adds an index-list queue containing cached keys in the order
that they are accessed. Each hash-map entry also includes its index into
this queue.
When an item is first entered into the cache, it is added to the end of
the queue. Also each time an entry is looked up from the cache it is
moved to the end of queue. As a result, items in the queue are always
sorted in the order that they have last been accessed. When doing LRU
eviction, cache entries are evicted from the front of the queue.
Using index-list, all queue operations above are O(1) with low overhead
and so above achieves an efficient implementation of LRU cache eviction
policy.

### CODE REVIEW

**Review by jeffwashington — APPROVED** [review]
lgtm. I have always hated the lru implementation I wrote here. I just haven't yet returned to see how to make it better.

**Comment by jeffwashington** [comment]
> it would be interesting to see if 2 validators against mnb running for a while: 1 with current lru code and 1 with this pr. Checking metrics for cache hits and misses to make sure they are similar (the same?). @behzadnouri I can do this unless you would like to.

I'm starting this validator against mnb to get some data on this:
2YfHpT4grkn2U5rrgmBL4NUArxYoHRYi8s5sfxHeCKqd

**Comment by behzadnouri** [comment]
The eviction logic has not changed (still LRU, just different implementation).
However note that the previous code when [calculating `per_account_size`](https://github.com/solana-labs/solana/blob/eeec1ce2a/runtime/src/read_only_accounts_cache.rs#L91-L94), does not account for:
* The keys in the hash-map for each entry:`std::mem::size_of::<ReadOnlyCacheKey>()`.
* The [`lru.reserve(self.cache.len())`](https://github.com/solana-labs/solana/blob/eeec1ce2a/runtime/src/read_only_accounts_cache.rs#L184); so an additional  `std::mem::size_of::<(Instant, ReadOnlyCacheKey)>()`.

Whereas in the new code, I am accounting for both the keys in the hash-map and in the eviction queue:
```rust
const CACHE_ENTRY_SIZE: usize =
    std::mem::size_of::<ReadOnlyAccountCacheEntry>() + 2 * std::mem::size_of::<ReadOnlyCacheKey>();
```
So with the same
```rust
const MAX_READ_ONLY_CACHE_DATA_SIZE: usize = 200_000_000
```
The new code is allowing fewer entries to be cached, which might slightly change hit/miss stats, but that is just because more accurate accounting for memory usage per cache entry.

Another aspect is the old code was [purging items every 200ms](https://github.com/solana-labs/solana/blob/eeec1ce2a/runtime/src/read_only_accounts_cache.rs#L201), which allows the cache to grow beyond max-size temporarily in between. The new code is enforcing max-size more strictly.

That to be seen how much impact it has. Let me know if you notice significant changes in stats.

**Comment by jeffwashington** [comment]
Sure. Trust, but verify.
So far, the [metrics](https://metrics.solana.com:8889/sources/0/dashboards/1?refresh=60s&tempVars%5Bdb%5D=mainnet-beta&tempVars%5Bhostids%5D=AND%20%22host_id%22%3D%27tTvENthWk6UXNjRzaq6Uzd5nVELaMNjr5nyG3hhpZUz%27%20or%20%22host_id%22%3D%272YfHpT4grkn2U5rrgmBL4NUArxYoHRYi8s5sfxHeCKqd%27&tempVars%5Bgroup_by%5D=%2C%20%22host_id%22&tempVars%5Bstartup%5D=&lower=now%28%29%20-%206h) seem to be tracking as expected.

**Comment by jeffwashington** [comment]
> Sure. Trust, but verify. So far, the [metrics](https://metrics.solana.com:8889/sources/0/dashboards/1?refresh=60s&tempVars%5Bdb%5D=mainnet-beta&tempVars%5Bhostids%5D=AND%20%22host_id%22%3D%27tTvENthWk6UXNjRzaq6Uzd5nVELaMNjr5nyG3hhpZUz%27%20or%20%22host_id%22%3D%272YfHpT4grkn2U5rrgmBL4NUArxYoHRYi8s5sfxHeCKqd%27&tempVars%5Bgroup_by%5D=%2C%20%22host_id%22&tempVars%5Bstartup%5D=&lower=now%28%29%20-%206h) seem to be tracking as expected.
> 
> bottom right contains the 3 metrics: entries, hits, misses Note that the tT machine has been running for a while - surely not based on the same commit.

Your pr appears to perform slightly better on hits than what is running on tT (master from last week probably). Not sure why that would be but I'm certainly happy.
So, I'm satisfied this is better. Reading our code and the code from the crate you added, it looks like the runtime perf should be better. I'm satisfied this is better.
Good job and thanks!

**Comment by behzadnouri** [comment]
thanks @jeffwashington for doing the test run.

**Pull request merged**
