### PR TITLE
explorer: revert original asset links for NFTs due to prettier issue

### PR DESCRIPTION
**Pull request by oJshua**
#### Problem
Prettier is taking issue with the changes in this commit: https://github.com/solana-labs/solana/pull/20709/files 
Somehow it got through CI the first pass.

#### Summary of Changes
Revert commit for now. 

Fixes #

### CODE REVIEW

**Comment by oJshua** [comment]
@roederw Looks like we might be having a deeper CI issue. I'll see if @jstarry has any ideas.

**Comment by carllin** [comment]
It is always checking out master before running the formatter?
master

**Comment by carllin** [comment]
image

Will something like this use the pull request head? For some reason I'm not seeing the runner pick up these edits though

**Comment by carllin** [comment]
> For some reason I'm not seeing the runner pick up these edits though
Ah it's because i need additional changes inside the `explorer` directory for the runner to update, how annoying

**Comment by carllin** [comment]
Hmm seems like you actually need to commit the workflow changes to the default branch, i.e. master, before those updates can be picked up for later pull requests: https://github.community/t/workflow-files-only-picked-up-from-master/16129/37

**Comment by roederw** [comment]
@oJshua You can close this out. @jstarry merged in the formatting changes.

**Pull request closed without merging**
