### PR TITLE
solana-test-validator now uses the BPF JIT by default, `--no-bpf-jit` to disable

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by sakridge** [comment]
We want it as default?

**Comment by mvines** [comment]
> We want it as default?

For dev purposes, I think so.  That'll get us more mileage on the JIT.    In 1.6/1.7 timeframe when we're fully comfortable with the JIT, we could do the same for `solana-validator`

**Comment by sakridge** [comment]
> > We want it as default?
> 
> For dev purposes, I think so. That'll get us more mileage on the JIT. In 1.6/1.7 timeframe when we're fully comfortable with the JIT, we could do the same for `solana-validator`

Oh, my bad. I didn't notice was for test-validator only. No problems there I think.

**Comment by mvines** [comment]
mergify 💔

**Pull request merged**
