### PR TITLE
Fix erasure

### PR DESCRIPTION
**Pull request by carllin**
#### Problem
Erasure FEC coding blocks are overlapping
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by sakridge** [comment]
Which test demostrates the failing case?

**Comment by carllin** [comment]
@sakridge that would be this test here: https://github.com/solana-labs/solana/pull/10095/files#diff-3c5974981a8a8d7ac3a6f5487e7d2e77R106, specifically the checks in the setup code here: https://github.com/solana-labs/solana/pull/10095/files#diff-3c5974981a8a8d7ac3a6f5487e7d2e77R180

**Comment by mvines** [comment]
@carllin - What's your call on a v1.1 backport here?

**Comment by carllin** [comment]
@mvines I think it's a safe change, will add 1.1 tag.

**Pull request merged**
