### PR TITLE
solana-genesis help nit: bpf->sbf

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
The program help text in `solana-genesis` cli is inconsistent with `solana-test-validator` (partly my fault in #29994)

#### Summary of Changes
Fixup

Sorry to add to the pile, @joncinque . I wasn't sure who to ask for review on this tiny change, and you were to mind because of the TestValidator stuff 😅

### CODE REVIEW

**Review by joncinque — APPROVED** [review]
r+ little idea: what about specifying in the help text that the program can be bpf or sbf? ie `Install a SBF or BPF program at the given address` Otherwise people might get confused. Unless the final goal is to fully deprecate the term BPF everywhere, in which case, disregard

**Comment by CriesofCarrots** [comment]
> r+ little idea: what about specifying in the help text that the program can be bpf or sbf? ie `Install a SBF or BPF program at the given address` Otherwise people might get confused. Unless the final goal is to fully deprecate the term BPF everywhere, in which case, disregard

Fair point, I don't mind that approach at all. This PR is the one that changed to SBF for solana-test-validator: https://github.com/solana-labs/solana/pull/28670 Since there is no PR description, it's a little hard to tell the intent or other steps taken toward "bpf" deprecation, but it certainly looks like a wholesale change. cc @dmakarov

**Comment by dmakarov** [comment]
> r+ little idea: what about specifying in the help text that the program can be bpf or sbf? ie `Install a SBF or BPF program at the given address` Otherwise people might get confused. Unless the final goal is to fully deprecate the term BPF everywhere, in which case, disregard

As far as I understand, the goal is to deprecate BPF completely. Moreover, since the beginning BPF programs were not in fact BPF, because of solana specific changes. All new programs should be SBF, but I'm not sure if we ever can completely eliminate legacy BPF programs.

**Comment by CriesofCarrots** [comment]
Okay, I think I'll go ahead and merge this, then. We could also consider deprecating the `--bpf-program` parameter (ie. aliasing it to `--sbf-program`)

**Comment by dmakarov** [comment]
> Okay, I think I'll go ahead and merge this, then. We could also consider deprecating the `--bpf-program` parameter (ie. aliasing it to `--sbf-program`)

The failure in stable-sbf assert_instruction_count test is innocuous, and can be ignored. This is due to a temporary replacement of sbf-tools v1.31,  v1.32, and v1.33 by an older version v1.30.  I'll update the default sbf-tools version to a new release later today, which will fix this.

**Comment by CriesofCarrots** [comment]
Merging on red `assert_instruction_count`. This PR doesn't touch programs or sdk.

**Pull request merged**
