### PR TITLE
Fix ProgramTestContext::set_account not updating programs

### LINKED ISSUE #34728: ProgramTestContext::set_account called twice ignores second call
#### Problem

When calling `ProgramTestContext::set_account` twice for the same `address: &Pubkey`, the second call gets ignored, so the account data will always be the one set on the first call. The following test illustrates the problem:

```rust
    #[tokio::test]
    async fn test_first_helloworld0() {
        let program_id = Pubkey::new_unique();

        let mut context = ProgramTest::default().start_with_context().await;

        set_program_account(&mut context, program_id, "helloworld0.so");

        let result = simulate_transaction(&mut context, program_id).await;
        assert_eq!(
            result.simulation_details.unwrap().logs[1],
            "Program log: Hello World Rust program entrypoint 0"
        );

        set_program_account(&mut context, program_id, "helloworld1.so");

        let result = simulate_transaction(&mut context, program_id).await;
        assert_eq!(
            result.simulation_details.unwrap().logs[1],
            "Program log: Hello World Rust program entrypoint 0" // TODO should be 1
        );
    }

    fn set_program_account(context: &mut ProgramTestContext, program_id: Pubkey, path: &str) {
        let program_data = read_file(path);

        context.set_account(
            &program_id,
            &AccountSharedData::from(Account {
                lamports: Rent::default().minimum_balance(program_data.len()).max(1),
                data: program_data,
                owner: bpf_loader::id(),
                executable: true,
                rent_epoch: 0,
            }),
        );
    }

    async fn simulate_transaction(
        context: &mut ProgramTestContext,
        program_id: Pubkey,
    ) -> solana_banks_interface::BanksTransactionResultWithSimulation {
        let tx = Transaction::new_signed_with_payer(
            &[Instruction::new_with_bytes(
                program_id,
                &[],
                vec![AccountMeta::new_readonly(program_id, false)],
            )],
            Some(&context.payer.pubkey()),
            &[&context.payer],
            context.last_blockhash,
        );

        context.banks_client.simulate_transaction(tx).await.unwrap()
    }
```
The reproduced problem above is extracted from [here](https://github.com/andreisilviudragnea/example-helloworld/blob/program-test-set-account-bug/src/program-rust/src/lib.rs).

#### Proposed Solution
I expect the second call to `ProgramTestContext::set_account` to update the state of the account. I do not know how this could be  fixed, since it is related to Bank forks and I am unfamiliar with that code.

### PR DESCRIPTION
**Pull request by andreisilviudragnea**
#### Problem
`ProgramTestContext::warp_to_slot` ignores `ProgramTestContext::set_account` program updates.

#### Summary of Changes
This PR tries to fix this problem by using `BankForks::insert_from_ledger` (introduced in #31331) instead of `BankForks::insert` everywhere inside `ProgramTestContext`. From my investigations, `ProgramTestContext::set_account` was never able to update program accounts, not even before #31331.

I also added relevant unit tests which verify the bug fix. I did not know how to write them without using precompiled Solana programs. The 3 precompiled Solana programs are variations of the program from [here](https://github.com/andreisilviudragnea/example-helloworld/blob/program-test-set-account-bug/src/program-rust/src/lib.rs).

Fixes #34728

### CODE REVIEW

**Comment by andreisilviudragnea** [comment]
@pgarg66 @Lichtso I pinged you because you are the author and reviewer of #31331.

**Comment by andreisilviudragnea** [comment]
@tiago18c Please have a look at this PR, updating program accounts never worked for me before.

**Comment by buffalojoec** [comment]
@andreisilviudragnea I might be missing something here, but have you tried [`ProgramTest::add_program(..)`](https://github.com/solana-labs/solana/blob/8869d0c8a0b56c4294fe9292bf856e79d16989b5/program-test/src/lib.rs#L622)? Or do you specifically need to add this program using the context post-warp?

I've run into a similar issue before when trying to add an upgradeable program using `ProgramTestContext::add_account(..)` to add both the program and program data accounts, where the program was stuck at `LoadedProgramType::DelayVisibility` in the program runtime.

`ProgramTest::add_program(..)` specifically adds it using [one single program account under the `BpfLoader`](https://github.com/solana-labs/solana/blob/8869d0c8a0b56c4294fe9292bf856e79d16989b5/program-test/src/lib.rs#L652-L661), which seems to shake the delayed visibility issue.

**Comment by andreisilviudragnea** [comment]
@buffalojoec I am trying to re-use the same `ProgramTestContext` with multiple versions of the same Solana program.

I want to be able to simulate Solana transactions on multiple versions of the same program as part of a Tokio web app. And it's not clear to me if `ProgramTestContext` can be cheaply created and destroyed for each transaction simulation request, so I want to re-use an existing `ProgramTestContext` where I update the program account to a new version.

**Comment by buffalojoec** [comment]
> @buffalojoec I am trying to re-use the same `ProgramTestContext` with multiple versions of the same Solana program.
> 
> I want to be able to simulate Solana transactions on multiple versions of the same program as part of a Tokio web app. And it's not clear to me if `ProgramTestContext` can be cheaply created and destroyed for each transaction simulation request, so I want to re-use an existing `ProgramTestContext` where I update the program account to a new version.

I would say unless you specifically need to test the program in state A, then do an upgrade, then test it in state B, all within the same blockstore, then you should use separate `ProgramTestContext` instances.

I can't advise exactly how _cheap_ they are to spin up, but we do this with all of SPL. Here's some examples.

You can see in each test ([here](https://github.com/solana-labs/solana-program-library/blob/268fcbea0364991209a9dd54a225c7b207b16215/token/program-2022-test/tests/initialize_mint.rs#L33-L41), [here](https://github.com/solana-labs/solana-program-library/blob/268fcbea0364991209a9dd54a225c7b207b16215/token/program-2022-test/tests/initialize_mint.rs#L55-L60), and the rest), we're spinning up a new `ProgramTestContext` using [this function here](https://github.com/solana-labs/solana-program-library/blob/268fcbea0364991209a9dd54a225c7b207b16215/token/program-2022-test/tests/program_test.rs#L30-L39).

In your case, you'd just add a different program processor with `add_program(..)` on each `ProgramTest` initialization.

**Comment by Lichtso** [comment]
As explained in https://github.com/solana-labs/solana/issues/34728#issuecomment-1892031043, you have to use the deployment instruction like this test does: https://github.com/solana-labs/solana/blob/8869d0c8a0b56c4294fe9292bf856e79d16989b5/programs/sbf/tests/programs.rs#L1724

That `ProgramTestContext::set_account()` was ever able to upgrade a program was not intended and got removed in v1.16.

**Pull request closed without merging**
