### PR TITLE
chore: Removes InstructionContext::get_instruction_accounts_lamport_sum()

### PR DESCRIPTION
**Pull request by metaproph3t**
An archetypical nit :)

### CODE REVIEW

**Review by joncinque — COMMENTED** [review]
Thanks for your contribution! To be honest, I wonder if we shouldn't just get rid of `get_instruction_accounts_lamport_sum()` considering it's completely unused.

`git blame` says @Lichtso touched it last, so I'll let him comment.

**Comment by Lichtso** [comment]
@joncinque Unused? It is needed to check if the push & pop pair matched.

@metaproph3t If you want to use the method instead of the field, then please update the other occurrences as well.

**Comment by joncinque** [comment]
@Lichtso Oh is this used in another repo? When I grepped on it I found no uses ie https://github.com/search?q=repo%3Asolana-labs%2Fsolana%20get_instruction_accounts_lamport_sum&type=code

**Comment by metaproph3t** [comment]
It appears that there was one other usage of `instruction_context.instruction_accounts_lamport_sum` inside of `push` that my indexer did not pick up. Given that there is precedence in the code for accessing these fields directly rather than through a getter, I have opted for @joncinque's notion of removing the getter altogether.

**Review by Lichtso — APPROVED** [review]

**Pull request merged**
