### PR TITLE
Add perf module to stable-perf CI

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

perf crate not tested in cuda mode

#### Summary of Changes

Add perf module to test-stable-perf CI

Fixes #

### CODE REVIEW

**Comment by sagar-solana** [comment]
Did this end up adding redundant testing to perf ? It seems like a lot of the core non-perf stuff is also compiled into the solana-perf test executable.

**Comment by sakridge** [comment]
> Did this end up adding redundant testing to perf ? It seems like a lot of the core non-perf stuff is also compiled into the solana-perf test executable.

Which stuff do you mean?

**Comment by sagar-solana** [comment]
Oh nvm, for some reason I thought I saw 100+ tests from perf but that's not true. It's working correctly. It does seem like we don't explicitly exclude the perf tests from the non-perf run though.

**Comment by sakridge** [comment]
> Oh nvm, for some reason I thought I saw 100+ tests from perf but that's not true. It's working correctly. It does seem like we don't explicitly exclude the perf tests from the non-perf run though.

That's fine, perf tests should run in non-perf mode as well.

**Pull request merged**
