### PR TITLE
Add skel test which sends a bad transaction, verify it doesn't make it

### PR DESCRIPTION
**Pull request by sakridge**

### CODE REVIEW

**Comment by garious** [comment]
Thanks, but too hacky

**Comment by garious** [comment]
https://github.com/solana-labs/solana/blob/master/src/transaction.rs#L183

And use AccountantStub::transfer_signed(). I'm thinking you shouldn't have to modify AccountantStub at all to implement this test.

**Comment by garious** [comment]
And the test should be on AccountantSkel (the server side). The client side isn't required the reject bad signatures.

**Comment by garious** [comment]
A separate put useful test on AccountantStub would be to enable a debug mode on the Skel (or separate port) that will tell you why a transaction was rejected. There's nothing like that implemented right now since a client could conceivably use it to implement a DoS attack.

**Comment by sakridge** [comment]
Not sure what the reference to the transaction.rs was, but I updated it backing out the changes to the stub and moving the test to the skel.

**Comment by garious** [comment]
Very nice. And I see that I gave confusing feedback. I told you both how to do this with the client-side API and told you it'd be better if it were a skel test. What I meant by that was that there are two different meaningful tests, one for the client, one for the skel. You implemented both parts using the client API inside the server module. No worries though, I'll take it from here. Thanks for doing this!!

**Pull request merged**
