### PR TITLE
set Transfer transaction loaded_accounts_data_size in bench-tps

### PR DESCRIPTION
**Pull request by taozhu-chicago**
#### Problem
#31905 includes CU cost of transaction's loaded_accounts_data_size to cost model. Mentioned [here](https://discord.com/channels/428295358100013066/1031929516383281154/1116747787070079026), if transaction does not explicitly use `ComputeBudgetInstruction::set_loaded_accounts_data_size_limit()` to set accounts data limit, the default 64M (chosen to not to break any existing mainnet-beta programs) will be used. Applying same heap cost (eg 8cu per 32K), that'd add 16K CU to each Transfer transaction, quickly fill up block CU limit, reduce tps.

#### Summary of Changes
- Add `ComputeBudgetInstruction::set_loaded_accounts_data_size_limit(30 * 1024)` to Transfer transaction.

tested and confirmed on single node cluster.

Fixes #

### CODE REVIEW

**Comment by apfitzge** [comment]
> mean_tps: 1961
max_tps: 76859
mean_confirmation_ms: 674
max_confirmation_ms: 2754
99th_percentile_confirmation_ms: 1002
max_tower_distance: 31
last_tower_distance: 31
slots_per_second: 2.815

The mean is still terrible though, @yihau did you test this using the normal system-performance buildkite?
Max is also significantly worse than before, iirc we were around 20k mean / 95k max prior to the feature.

**Comment by yihau** [comment]
yeah. I used the same method which we do system performance tests. I can try it again

**Comment by KirillLykov** [comment]
I'm tried to run it on testnet: https://buildkite.com/solana-labs/bench-tps-dos-quic/builds/73#0188ba8b-ad40-4457-998d-947614e3d67d
In case if you are using testnet for this test as well

**Comment by yihau** [comment]
thank you @KirillLykov. I'm test it on equinix

**Comment by yihau** [comment]
another test report:
```
mean_tps: 2097
max_tps: 71316
mean_confirmation_ms: 681
max_confirmation_ms: 3240
99th_percentile_confirmation_ms: 1112
max_tower_distance: 31
last_tower_distance: 31
slots_per_second: 2.805
```

**Comment by taozhu-chicago** [comment]
Just to confirm that we are running "Nightly - Bare 5 Node CPU Only" test?

Added `loaded_accounts_data_size_limit` ix would sets 0 CU for loading accounts, tho the ix itself adds 150 CU to TX. Maybe that cause TXs to drop due to cu-limit? Anyway, I pushed a update to increase cu-limit. @yihau , can you kick one more run please?

**Comment by yihau** [comment]
btw, @apfitzge found something weird. I share it here too.

f2f1dab5ea
```
mean_tps: 3221
max_tps: 89340
mean_confirmation_ms: 693
max_confirmation_ms: 3099
99th_percentile_confirmation_ms: 1587
max_tower_distance: 32
last_tower_distance: 31
slots_per_second: 2.770
```

8937fd9bd6 (before f2f1....)
```
mean_tps: 25155
max_tps: 97440
mean_confirmation_ms: 827
max_confirmation_ms: 4462
99th_percentile_confirmation_ms: 3105
max_tower_distance: 46
last_tower_distance: 31
slots_per_second: 2.636
```

**Comment by yihau** [comment]
@taozhu-chicago sure!

**Review by apfitzge — APPROVED** [review]
lgtm

**Comment by yihau** [comment]
the result of the latest commit of this PR.
```
mean_tps: 3790
max_tps: 78369
mean_confirmation_ms: 700
max_confirmation_ms: 2766
99th_percentile_confirmation_ms: 1698
max_tower_distance: 32
last_tower_distance: 31.4
slots_per_second: 2.752
```

**Comment by apfitzge** [comment]
Changes here look good; I'm talking with @behzadnouri and continuing to investigate the mean-tps perf-degredation (see https://github.com/solana-labs/solana/pull/32105#issuecomment-1591724079)

**Comment by taozhu-chicago** [comment]
> the result of the latest commit of this PR.
> 
> ```
> mean_tps: 3790
> max_tps: 78369
> mean_confirmation_ms: 700
> max_confirmation_ms: 2766
> 99th_percentile_confirmation_ms: 1698
> max_tower_distance: 32
> last_tower_distance: 31.4
> slots_per_second: 2.752
> ```

This does not come as surprise. Thanks @yihau

**Pull request merged**
