### PR TITLE
Fix - program loading with effective slot at epoch boundary

### PR DESCRIPTION
**Pull request by Lichtso**
#### Problem
The testnet outage 2024/02/21 was caused by a feature activation which affected RBPF and thus changed the program runtime environment. A bug it the program loading caused programs of the new environment after the epoch boundary to be discarded as they had the same effective slot as programs of the old environment before the epoch boundary.

#### Summary of Changes
- Limit effective slot to the begin of the current epoch when there is a relevant feature activation.
- Adds `test_feature_activation_loaded_programs_epoch_transition()`.

### CODE REVIEW

**Comment by t-nelson** [comment]
much more readable! :heart_eyes: 

thoughts on taking this to 1.17? we don't want our hands tied should we need to emergency patch something effects jit output

**Comment by pgarg66** [comment]
Since we are planning to backport this to v1.17, is there a smaller patch that fixes the problem? The cleanup can be done in a follow on PR, that we don't backport. Also, the change that's going into to v1.17 should be audited before making a release out of it.

**Comment by alessandrod** [comment]
> Rewrites test_feature_activation_loaded_programs_recompilation_phase().

Saying what you do is great, but please always say why (and when a change is complex, say how).

I don't think the test change belongs to this PR? Does the (unmodified) test pass with the effective slot change? Changing _existing_ tests when fixing something is not ideal. Why can't we add a new regression test for the specific issue we found, which clearly fails without the fix? Then we can refactor other tests separately.

**Comment by alessandrod** [comment]
(The actual code change looks fine to me, but I'd like to see a regression test :P)

**Review by pgarg66 — APPROVED** [review]

**Pull request merged**
