### PR TITLE
convert std::sync::mpsc to crossbeam_channel

### PR DESCRIPTION
**Pull request by jbiseda**
#### Problem

codebase uses a mix of `crossbeam_channel` and `std::sync::mpsc`. It is unnecessary to use both.

Workarounds for `mpsc` https://github.com/rust-lang/rust/issues/39364#issuecomment-634545136 can be removed by standardizing on `crossbeam_channel`.

#### Summary of Changes

Convert all uses of `mpsc` to `crossbeam_channel`.

sanity test with `solana-bench-streamer` using `custom (e2, 24 vCPU, 64.00 GiB)`
note: solana-bench-streamer was patched with change from #22347

solana-bench-streamer with mpsc:

```
for i in {1..4}; do ./solana-bench-streamer; done
performance: 936221.5754596281
performance: 913881.003353916
performance: 929923.0003435342
performance: 923160.4137368232

for i in {1..4}; do ./solana-bench-streamer --num-recv-sockets 8; done
performance: 924033.3678037219
performance: 932922.6188835779
performance: 925652.7139617476
performance: 921577.2228802667
```

with crossbeam:

```
for i in {1..4}; do ./solana-bench-streamer; done
performance: 908525.4054766926
performance: 935070.9532562166
performance: 940231.1060626787
performance: 913752.0135091533

for i in {1..4}; do ./solana-bench-streamer --num-recv-sockets 8; done
performance: 919216.3952778602
performance: 946301.4314075172
performance: 939579.0559102054
performance: 932590.4763202657
```

Fixes #

### CODE REVIEW

**Review by carllin — DISMISSED** [review]

**Comment by behzadnouri** [comment]
@jbiseda 
There is a functional difference between crossbeam channels and mpsc channels:
https://github.com/solana-labs/solana/pull/16503#issuecomment-819158553

Can you please backport this to v1.9 so it is well soaked?
Also given the size of the change, doing the backport will avoid other backports to merge conflict. thanks.

**Comment by t-nelson** [comment]
Please do _not_ backport this.  1.9 has enough in it already.  It can come with 1.10.  We're running tip of master canaries against mainnet beta and testnet, so please keep an eye on those for problems

**Comment by behzadnouri** [comment]
> Please do _not_ backport this. 1.9 has enough in it already. It can come with 1.10. We're running tip of master canaries against mainnet beta and testnet, so please keep an eye on those for problems

@t-nelson I think this approach is actually exacerbating the problem that the differences between releases are so big that upgrading clusters have become daunting and impossible.

Ideally each commit individually once tested should be backported to testnet; and once soaked there for a while it should be backported to mainnet; and mainnet should always do stage-wise 5%, 10%, ... upgrade.
This way each mainnet upgrade would be a reasonable number of commits which allows finding the culprit if things doesn't look good.

I don't see how piling 1000 commits together would in any form reduce upgrade risks; or help diagnosis when things go wrong.

**Comment by t-nelson** [comment]
We claim that MB is running a "stable" branch, "stable" branches are supposed to receive only "safe" changes that fix known, detrimental flaws.  We have not adhered to this in the past, but given the apparent economic value on the cluster, it's what we must strive for in the future

I do agree that our release cadence is far too long ATM and that that is complicating stabilization. My goal is to get us down to 2wk minor release cycles in 2022.  Unfortunately we've dug ourselves a deep hole by forking 1.8 off of 1.7.  There will be pain while we pay back that debt.

**Comment by mvines** [comment]
Backporting individual PRs at their own cadence doesn't fix this issue though, it makes it even worse.  The fix is to speed up our release cycle and return to a 4 week train that leaves on time, all the time

**Comment by behzadnouri** [comment]
> We claim that MB is running a "stable" branch, "stable" branches are supposed to receive only "safe" changes that fix known, detrimental flaws. We have not adhered to this in the past, but given the apparent economic value on the cluster, it's what we must strive for in the future

The question is not if the mainnet should be stable or not. The question is that what approach provides more stability to mainnet.

My point is piling 1000 commits together is so obviously counterproductive.

> Backporting individual PRs at their own cadence doesn't fix this issue though, it makes it even worse. The fix is to speed up our release cycle and return to a 4 week train that leaves on time, all the time

How does it make it worse? Or, in particular, how is this process I am proposing in [this comment](https://github.com/solana-labs/solana/pull/22264#issuecomment-1012371037) is worse than current situation?

* We have already hit several points that upgrading mainnet has been a problem.
* Diagnosing such problems have become very difficult because of the number of the commits and the non-linear commit history.
* Testnet is very different from mainnet. In particular the stake distribution is very different; and it has almost zero non-builtin transactions. So soaking 1000 commits there is just giving false assurance.

**Pull request merged**
