### PR TITLE
Refactor: move simple vote parsing to runtime

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
Vote parsing logic used in gossip and the runtime currently lives in the `solana-vote-program` crate for no good reason. This implicitly creates an unnecessary dependency from `solana-vote-program` on runtime types and logic.

#### Summary of Changes
Move "simple vote" parsing and `VoteTransaction` type into the runtime.

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
@behzadnouri do you mind sanity checking this? The CI failure is unrelated to this change

**Comment by behzadnouri** [comment]
> @behzadnouri do you mind sanity checking this? The CI failure is unrelated to this change

this is just moving code around, right?
or are there any change of logic as well?

**Comment by jstarry** [comment]
> > @behzadnouri do you mind sanity checking this? The CI failure is unrelated to this change
> 
> this is just moving code around, right? or are there any change of logic as well?

No logic changes, just moving code around and some function renames. Just wanted another eye on this to see if you thought this refactoring makes sense to move code in this way.

**Comment by behzadnouri** [comment]
> an unnecessary dependency from solana-vote-program on runtime types and logic.

Do you mind clarifying what dependency you are referring to? I don't see solana-runtime dependency in `solana-vote-program`:
https://github.com/solana-labs/solana/blob/49443406f/programs/vote/Cargo.toml#L19-L23

Also since logic for `Vote -> Transaction` lives there, doesn't it make sense to keep the other direction `Transaction -> Vote` there as well?

**Comment by jstarry** [comment]
> > an unnecessary dependency from solana-vote-program on runtime types and logic.
> 
> Do you mind clarifying what dependency you are referring to? I don't see solana-runtime dependency in `solana-vote-program`: https://github.com/solana-labs/solana/blob/49443406f/programs/vote/Cargo.toml#L19-L23

I'm in the process of moving `SanitizedMessage` and `SanitizedTransaction` into the runtime, that's the dependency I was referring to.

> Also since logic for `Vote -> Transaction` lives there, doesn't it make sense to keep the other direction `Transaction -> Vote` there as well?

We don't really have a precedent for this but my thinking is that SDKs should be used to construct transactions and only the runtime/core needs to parse and handle tx messages. Right now the runtime/core sometimes enforces that a "simple vote tx" must only have one vote instruction and nothing else, and sometimes we don't care. I'd like to consolidate that runtime logic in one place and pull it out of the SDK because it's not used externally anyways (afaik)

**Comment by behzadnouri** [comment]
okay then, makes sense

**Pull request merged**
