### PR TITLE
Rename remaining uses of fullnode to validator

### PR DESCRIPTION
**Pull request by garious**
#### Problem

Fullnode was renamed to validator everywhere but the shell scripts.

#### Summary of Changes

Renamed fullnode to validator in the shell scripts.

### CODE REVIEW

**Comment by garious** [comment]
@t-nelson, can you take over this PR and get it merged sooner than later?

**Comment by mvines** [comment]
Odds of this breaking something is 100%, but only way do find out is merging.  Since we branch 0.20 at the end of this week, let's land this ASAP.

**Comment by t-nelson** [comment]
Sure!  I'd actually started this at https://github.com/t-nelson/solana/commits/no-fullnode before forgetting about it.  It's basically two commits of "probably safe" and "most likely not safe".  The "not safe" stuff will affect attempting to control with new code testnets started with old code.  Config file contents, log filenames and anything that depends on them will be the problems.  If we are willing to shove some testnets through the upgrade and clean up after them, it's probably mostly fine.

**Comment by mvines** [comment]
> If we are willing to shove some testnets through the upgrade and clean up after them, it's probably mostly fine.

Yeah, use the 🔨

**Comment by t-nelson** [comment]
This misses some instances of "full node".  I'll handle

**Comment by t-nelson** [comment]
I've verified that this at least works with a simple create > start > stop > delete cycle on both GCE and Colo.

Do we want to coordinate merging this in anyway to minimize problems with running testnets?

**Comment by garious** [comment]
:shipit:

**Pull request merged**
