### PR TITLE
Refactor Vote Program account setup

### LINKED ISSUE #2513: Voter registration requires validator signature
#### Problem

Voter registration requires the validator to sign, whereas voting uses the VoteSigner service.

#### Proposed Solution

Remove `VoteInstruction::RegisterAccount` and instead use the VoteSigner service to sign a `SystemInstruction::CreateAccount` transaction.

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

Vote Transaction's `new_account()` would create a transaction to create a `vote_account` as well as to `register()` and store the `vote_state` in the account's `userdata`. This would require the staker's(validator, for now) signature and it involved `register()` being aware of this fact. 

#### Summary of Changes

- Split `new_account()` into `fund_vote_account()` and `register_vote_account()`. 
- Updated staker_id to voter_id, to reflect the vote account
- Ensure rewards are paid into the `voter account` from the `rewards account`
- Updated GenesisBlock to stop auto-generating a leader keypair
- Fixed tests that would randomly double assign vote accounts to nodes
 
Fixes #2513

### CODE REVIEW

**Comment by garious** [comment]
This will take me some time to digest. I had expected this work would allow us to delete a bunch of code in setting up fullnodes (at least by default), but instead it looks to add quite a bit more.

**Comment by sagar-solana** [comment]
@garious, unfortunately that turned out to be the case. I would primarily look at vote_program and vote_instruction. 
All the tests were incorrectly setting up and using vote keypairs and accounts so this ended up having far reaching impact. :(

**Comment by garious** [comment]
What about using that voting keypair/account for everything by default? Is that reasonable? So unit-tests just use the one keypair for the validator node_id, for sending votes the voting account, and as the staking account.

**Comment by garious** [comment]
Also, with the new leader scheduler, the bank no longer needs to submit a vote when processing the genesis block.  I wonder if waiting for that to land can help simplify things here.  Anyway, my brain isn't functioning anymore today, so I'll need to revisit this in the morning.

**Comment by sagar-solana** [comment]
@garious, no worries! 

- Using the same keypair results in a bit of a problem (and more test code churn) because by default accounts are not setup with enough space for the vote_states. So we'll have to setup nodes with "vote_program" accounts first and then give them stake. Doesn't help in terms of reducing the amount of code.
- Waiting for leader scheduler to die will help a little bit but I don't see it changing _that_ much. This PR kinda sets us up for some of the future work, like #2430 

@pgarg66, thoughts?

**Comment by garious** [comment]
I merged Pankaj's PR. I can see it'll be a painful rebase.  Sorry about that.

So thinking more on it, I think what's awkward here is this notion of "registration" instead of "delegation". When I suggested the voting_account be the default `node_id`, what I mean is that that it is up to the stakeholder to delegate its responsibilities.  If it wants a certain validator node in the leader rotation, it should be able to delegate that. If not, then we should see that stakeholder in the leader rotation.

Here's where we've talked the most about this:
https://solana-labs.github.io/book-edge/vote-signer.html

And as it relates to the codebase, here's a description of what's implemented and what's not:
https://github.com/solana-labs/solana/pull/2905

The document was largely written by Anatoly and implemented by Pankaj. As I recall, there are inconsistencies between them. PRs on that document to make it consistent with the implementation would be graciously accepted.

**Comment by sagar-solana** [comment]
Thank you for all the info, I'll try to go over this with Pankaj tomorrow. No worries about the rebase.

**Comment by garious** [comment]
close this one?

**Comment by sagar-solana** [comment]
Replaced by #2992

**Pull request closed without merging**
