### PR TITLE
Add missing solana-program docs

### PR DESCRIPTION
**Pull request by brson**
#### Problem

There are a few undocumented top level items in solana-program

#### Summary of Changes

Add descriptions. Document clone_zeroed and copy_field but make them `doc(hidden)` since they are not useful to program authors.

### CODE REVIEW

**Review by CriesofCarrots — APPROVED** [review]
Looks fine to me. @Lichtso , can you also take a look at this verbiage? Thanks!

**Comment by Lichtso** [comment]
Can this PR be rebased on https://github.com/solana-labs/solana/pull/28771 once it lands?

**Comment by brson** [comment]
> Can this PR be rebased on #28771 once it lands?

Yes.

**Comment by brson** [comment]
Rebased. The clone_zeroed function doesn't exist now.

**Review by CriesofCarrots — APPROVED** [review]
Thanks and sorry for the whiplash on this one!

**Comment by CriesofCarrots** [comment]
Docs-only change; merging without CI

**Pull request merged**
