### PR TITLE
Gmg/bidirectional quic replies (v1.14)

### PR DESCRIPTION
**Pull request by godmodegalactus**
#### Problem

Currently when we send a transaction to the solana cluster, we cannot really debug the lifecycle of the transaction.
The only feedback that we get is if the transaction was included in a block or not. There is no easy way to find out
why multiple transactions are dropping out.

#### Summary of Changes
This PR will help to solve this problem. Normally we open a QUIC uni stream connection with the leader. With this PR i have added a way to create a QUIC bi stream connection. You have to only a bistream connection once, which will be valid until you close the stream on the client side. On this stream client will receive messages about how the transaction was treated and what all errors it faced.

This will make easier to benchmark cluster and find out why we are loosing so many transactions at any particular time.
After playing around a little bit, I found out this issue : https://github.com/solana-labs/solana/issues/29895

I would like this to be deployed on testnet so that we can start testing on testnet lifecycle of transactions.

### CODE REVIEW

**Comment by lijunwangs** [comment]
Have not thoroughly reviewed the code. Just some comment

1. What is driving the bi-directional communication need? Only for debug purpose? Or there is a concrete need from the use case of submitting transactions why it failed to be executed? Or just for benching and debugging purpose? If for the latter -- I think there can be lighter mechanism like logging or metrics improvement on the validator side.
2. Transaction can be forwarded to other validators -- does this try to track through the chain to replay the original submitter the results?

**Comment by godmodegalactus** [comment]
Good questions.
1) Currently when we send a transaction to the cluster, we do not know what happens to the transaction until it is the block. When there is congestion in the network there are multiple transactions that are silently rejected where we have no idea why they are rejected. In this way, we can debug and understand why the transactions are getting dropped. 
Usually, the transaction also gets retried if there is a lock contention or reached the maximum CU per block. So yeah mostly for debugging purpose.

2) It tracks down more indirectly, usually when we send a transaction using tpu client we send it to leaders of 12 next slots. So if the cluster supports bidirectional communication we can follow how the transaction was treated in each of the validators.

3) Yes if we want to move the logic outside of the connection cache we can move it outside.

4) We can make a config where can only get one message per transaction or something like that. This can be implemented.

5) Currently bidirectional reply is optional and disabled by default. But if you activate the bidirectional replies we can only send transactions to the validators where it is implemented. I was planning to implement a fallback mechanism that if we detect that the bidirectional channel is not accepted then we fall back to the unidirectional channel. But this is a point of more discussion.

6) Ok i can add more details to the changes in the summary.

7) Currently client waits for 10 secs to get a reply from the server. If it does not get any reply we timeout and close the connection.

> Have not thoroughly reviewed the code. Just some comments
> 
>     1. What is driving the bi-directional communication need? Only for debug purpose? Or there is a concrete need from the use case of submitting transactions why it failed to be executed? Or just for benching and debugging purpose? If for the latter -- I think there can be lighter mechanism like logging or metrics improvement on the validator side.
> 
>     2. Transaction can be forwarded to other validators -- does this try to track through the chain to replay the original submitter the results?
> 
>     3. The connection-cache quic-client is being or has been made generic to handle other workflows -- not only for transaction. So we do not want to more logic only specific to transaction in quic-client.
> 
>     4. We are not interested in the replay messages all the time, can this work based on configuration?
> 
>     5. How upgrade is being handled? How do you handle talking to a server not supporting the bi-directional stream?
> 
>     6. More detailed change summary is in order for changes of such magnitude and @mvines mentioned, it is better go through a design proposal first.
> 
>     7. How is time-out handled for reply message -- what if server ignores to reply back?

Yes good questions.
1) Currently when we send a transaction to the cluster, we do not know what happens to the transaction until it is the block. When there is congesion in the network there are multiple transactions that are silently

**Comment by KirillLykov** [comment]
I would suggest two things:
* first make a PR to master and later backport for v1.14
* try to split this PR into several smaller PRs. Probably, not functional alone but each one compiles and doesn't break existing functionality

**Comment by KirillLykov** [comment]
Another thing is `Default::default()`, they are not allowed in this repo: https://github.com/solana-labs/solana/blob/master/ci/nits.sh#L45

**Comment by KirillLykov** [comment]
Btw, are we sure that the response coming from validator is always smaller than the request?

**Pull request closed without merging**
