### PR TITLE
datapoint for verify_snapshot_bank

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem
validator startup time is painful - especially as # accounts grows. There will soon be an issue filed for this.
#### Summary of Changes
add metrics for verify_snapshot_bank to track improvements.
Fixes #

### CODE REVIEW

**Comment by jeffwashington** [comment]
from mnb snapshot:
```verify_snapshot_bank clean_us=57710861i shrink_all_slots_us=1 097525i verify_bank_hash_us=19499188i verify_hash_us=2205i```

**Review by sakridge — APPROVED** [review]
lgtm

**Comment by jeffwashington** [comment]
@joeaba this will get us consistent numbers on validator startup that we can track and work on improving.

**Comment by joeaba** [comment]
Thanks! I'll create the issue today

**Comment by solana-grimes** [comment]
:scream: New commits were pushed while the automerge label was present.

**Comment by jeffwashington** [comment]
@mvines I'd like to put this in 1.6. ok?

**Comment by mvines** [comment]
sure

**Pull request merged**
