### PR TITLE
v1.16: unpin tokio for solana client crate

### LINKED ISSUE #32878: solana-client v.1.16 depends on pinned tokio version (~1.14.1) compared to solana-client v.1.14 (tokio ^1)
#### Problem

- [solana-client v1.16.8](https://crates.io/crates/solana-client/1.16.8/dependencies) depends on [tokio ~1.14.1](https://crates.io/crates/tokio/1.14.1) - it allows updating tokio only to `1.14.x` versions
- [solana-client v.14.24](https://crates.io/crates/solana-client/1.14.24/dependencies) depends on [tokio ^1](https://crates.io/crates/tokio/1.32.0) - it allows updating tokio to `1.x.x` versions

Using [solana-client v1.16.8](https://crates.io/crates/solana-client/1.16.8/dependencies) forces the clients of this crate to downgrade `tokio` to a version more than a year old. This problem has been introduced by #29893, when the `tokio` version specified for `solana-client` changed from `^1` to `~1.14.1`.

Fixed by #33058.

### PR DESCRIPTION
**Pull request by afalaleev**
#### Problem

Tokio version specifier "~1.14.1" only allows patch updates and [v1.14.1](https://crates.io/crates/tokio/1.14.1) is more than a year old.

#### Summary of Changes

Change to `tokio = "1"` in the `client/` crate.

Fixes #32878

### CODE REVIEW

**Comment by afalaleev** [comment]
@mvines please review this PR.

**Review by mvines — APPROVED** [review]
thanks, this seems good to me. let's see how CI likes it

**Comment by mvines** [comment]
Looks like we have an audit issue on v1.16 currently. It should be fixed by https://github.com/solana-labs/solana/pull/32948, so once that PR lands please rebase this PR to pick up the audit fix.

**Comment by t-nelson** [comment]
where was the motivation expressed?  all i see is "a year old" which... sounds like a preference.

i'm pretty dubious of the major-only specifier in general. i don't think we want to allow _downgrades_ to below 1.14.1, but i don't recall why we added the `~` here in the first place. i'll have to hunt that up later. dropping the tilde seems less invasive.

vendoring is always an option

**Comment by afalaleev** [comment]
@t-nelson sorry for the lack of motivation in PR.

The reason why v1.16 is locked on the tokio v1.14.1 is described in this issue https://github.com/solana-labs/solana/issues/24644. 
However, in actuality only solana-rpc needs to be pinned to avoid the RPC stalls, and the pin is causing problems for downstream users of the solana client crate.

This PR resolves the issues for downstream users importing the solana client crate.
For example, in this PR https://github.com/solana-labs/solana/pull/26957 the tokio was unpinned.

Please, check that the PR is safe enough.

**Comment by t-nelson** [comment]
seems like bumping to "1.29.1" (as per https://github.com/solana-labs/solana/pull/32430) would be safer that "1" given that there were issues somewhere between "1.14.1" and "1.29.1" that we don't want devs to stumble in to again. which would be possible with "1"

**Comment by mvines** [comment]
> seems like bumping to "1.29.1" (as per #32430) would be safer that "1" given that there were issues somewhere between "1.14.1" and "1.29.1" that we don't want devs to stumble in to again. which would be possible with "1"

Backporting #32430 is way to risky at the moment no? "1" is exactly what the v1.14 version of the solana-client crate requires, so this is actually reverting back to the previous setup that the devs were happy about

**Comment by t-nelson** [comment]
> > seems like bumping to "1.29.1" (as per #32430) would be safer that "1" given that there were issues somewhere between "1.14.1" and "1.29.1" that we don't want devs to stumble in to again. which would be possible with "1"
> 
> Backporting #32430 is way to risky at the moment no? "1" is exactly what the v1.14 version of the solana-client crate requires, so this is actually reverting back to the previous setup that the devs were happy about

"1" allows _any_ version with `major-version=1`, including the range we know has issues.

it's still not clear to me why 1.14.1 is insufficient. without knowing that, i can't really characterize risk. downstream vendoring is sounding more and more like the right solution

**Comment by mvines** [comment]
> "1" allows any version with major-version=1, including the range we know has issues.

Cargo.lock prevents this from happening for our tree. For the crate users, "1" provides the same experience they already have when using the v1.14 version of `solana-client`.

> it's still not clear to me why 1.14.1 is insufficient. without knowing that, i can't really characterize risk

Upgrading the v1.16 branch to any new tokio at this point, including 1.14.1, would be the concern and an additional risk we don't need to take, given this branch is about to hit mainnet.

**Comment by andreisilviudragnea** [comment]
@t-nelson I agree with dropping the tilde only for solana-client, since "1.14.4" allows any update of the form "1.x.x".

**Comment by t-nelson** [comment]
> Cargo.lock prevents this from happening for our tree.


> > "1" allows any version with major-version=1, including the range we know has issues.
> 
> Cargo.lock prevents this from happening for our tree. For the crate users, "1" provides the same experience they already have when using the v1.14 version of `solana-client`.

`Cargo.lock` only applies to published bin crates and local builds. not published lib crates. cargo will take the most recent version that matches the dependency's semver pattern

> > it's still not clear to me why 1.14.1 is insufficient. without knowing that, i can't really characterize risk
> 
> 1.14.1 is fine for the v1.16 validator client, we're not changing that here at all. Again the Cargo.lock file saves us. So there's no risk for us, the only risk is for crates.io consumers but not really because they already deal with this same behaviour ("1") in v1.14

the risk to us is breaking `solana-client` consumers should `tokio` carelessly bump minors during 1.16. the dev community is already annoyed about the 1.16 migration pain from abi/msrv nonsense they've endured, client-side deploy regression, etc. so i'd rather not just yolo a last minute dep bump

---

> seems like bumping to "1.29.1" (as per #32430) would be safer that "1" given that there were issues somewhere between "1.14.1" and "1.29.1" that we don't want devs to stumble in to again. which would be possible with "1"

i realize now that i may not have been clear that i was proposing bumping the `solana-client` tokio dependency to 1.29.1, not taking the workspace to that version. i only referenced #32430 as evidence that 1.29.1 doesn't _not_ work

---

that's the _risk_ i'm considering. i still have no idea what the _reward_ is. if i proposed backporting a dependency version bump to `beta` a week before it's slated to be promoted to `stable` with the justification that "there is a newer version available,"  i certainly hope the response from reviewers would be, "lol, no"

so, ignoring the "age" of 1.14.1, **what is the motivation for this dependency bump?**

**Comment by andreisilviudragnea** [comment]
@t-nelson Tokio is used in an Axum web app that also uses Solana client v1.14 inside it.

We use the latest possible versions for our dependencies. Upgrading Solana to v1.16 forces us to downgrade tokio and with it also Axum.

For me as a developer using a dependency, it is unexpected to be forced to downgrade some of my dependencies when upgrading another dependency.

**Comment by t-nelson** [comment]
> @t-nelson Tokio is used in an Axum web app that also uses Solana client v1.14 inside it.

got it.  so taking `solana-client` to `1.29.1` instead of `1` would be sufficient?  looks like `axum` is `^1.25.0`

> For me as a developer using a dependency, it is unexpected to be forced to downgrade some of my dependencies when upgrading another dependency.

understood, but we can't force preferences like this on the entire developer ecosystem without evidence of broad advantage

> We will probably use our Solana fork for unpinning Tokio version on v1.16.

vendoring is always an option!

---

once we clear 1.16, these long latent dependencies and msrv should be in our past.  we're well aware of the pain that they cause. we feel it too :slightly_smiling_face:

**Comment by fabioberger** [comment]
@andreisilviudragnea is your fork available for others to use? We have this exact same issue.

**Comment by andreisilviudragnea** [comment]
Hi @fabioberger,

Please show your support for #32878 and comment on the issue with the details of your problem. I still believe this is a problem that should be fixed by Solana team and not by the users of the library.

We use a backport of #32430 on branch v1.16 https://github.com/neonlabsorg/solana/tree/backport-32430, which will be rebased constantly over the latest changes from v1.16 branch.

**Comment by CriesofCarrots** [comment]
In the interest of thoroughness, noting that we lost the more permissive tokio definition in `solana-client` and `solana-storage-bigtable` when we switched to workspace dependencies. Looks like this was inadvertent.

**Comment by afalaleev** [comment]
The better decision is suggested in #33058

**Pull request closed without merging**
