### PR TITLE
retain prior metric behavior for invalid_cached_stake_accounts

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by HaoranYi** [comment]
To be honest, I like the old code better. In this change, invalid_cached_stake_accounts is confusing without looking at the code. 
The `real` invalid cache count is actually the difference between these two counters. I am not a fan of dogmatically keeping the old counter behavior where the true meaning of the counter is more important.

**Comment by jeffwashington** [comment]
> To be honest, I like the old code better. In this change, invalid_cached_stake_accounts is confusing without looking at the code. The `real` invalid cache count is actually the difference between these two counters. I am not a fan of dogmatically keeping the old counter behavior where the true meaning of the counter is more important.

https://github.com/solana-labs/solana/pull/26143#discussion_r905044227

I prefer the metric to become the 'real' meaning as well, but I understand @behzadnouri 's perspective. I figured a proposed change like this was the way to chart a path forward.

**Review by behzadnouri — DISMISSED** [review]
lgtm

**Review by HaoranYi — CHANGES_REQUESTED** [review]
I prefer not to commit.

**Comment by jeffwashington** [comment]
talked with haoran and behzad.
Seems reasonable to put this in. I hope to get rid of the cause of this soon.

**Pull request merged**
