### PR TITLE
Simd poh

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Scalar Poh verify is too slow on CPU-only systems causing nodes to get behind when verifying large numbers of poh forks.

#### Summary of Changes

Add avx2 simd poh verify which is 5-8x faster.

Fixes #

### CODE REVIEW

**Comment by aeyakovenko** [comment]
Do we need to tell everyone to use perf libs on the next release?  I think we need this for 1.2 as well

**Comment by sakridge** [comment]
> Do we need to tell everyone to use perf libs on the next release? I think we need this for 1.2 as well

I think it should just work. The perf libs are shipped in the release already and as long as dlopen can find the library it should use it.

**Comment by sakridge** [comment]
Also yea, I'm working on backporting, 1.1 as well?

**Comment by aeyakovenko** [comment]
@sakridge lets not touch 1.1 unless we have to :)

**Pull request merged**
