### PR TITLE
perf: use saturating/checked integer arithmetic

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

Integer arithmetic in perf crate

#### Summary of Changes

Use saturating/checked math instead

### CODE REVIEW

**Comment by sakridge** [comment]
Any perf difference?

**Review by sakridge — DISMISSED** [review]
lgtm

**Comment by t-nelson** [comment]
> Any perf difference?

`bench_get_offsets` is ~4us slower on average.  Other two are unaffected

**Comment by t-nelson** [comment]
https://github.com/solana-labs/solana/pull/16042/commits/2c24fbbb3090d1e14b82f4e99d1b8e6feba65dac gets a couple `us` back

**Comment by t-nelson** [comment]
> [2c24fbb](https://github.com/solana-labs/solana/commit/2c24fbbb3090d1e14b82f4e99d1b8e6feba65dac) gets a couple `us` back

@sakridge mind taking a peek at this optimization pass before I merge?

**Review by sakridge — APPROVED** [review]
looks good, thanks

**Pull request merged**
