### PR TITLE
RPC: Add ability to get information about all available snapshots on the cluster

### PR DESCRIPTION
**Pull request by diman-io**
#### Problem

There is no simple way to get information about available snapshots on the cluster.

#### Summary of Changes

Add optional param `withSnapshots` to `getClusterNodes` rpc request.

**Request**:

`curl http://localhost:8899 -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0", "id":1, "method":"getClusterNodes", "params":[{"withSnapshots":true}]}'`

**Result (`| jq '.'`)**:
```
{
  "jsonrpc": "2.0",
  "result": [
    {
      "featureSet": 3605932003,
      "fullSnapshots": [
        [
          144515460,
          "EQcYuGoyMbKAxNVEW5pCSPQwybwdNYtVEcJ4vHD66sMD"
        ]
      ],
      "gossip": "135.181.60.221:8000",
      "incrementalSnapshots": [
        [
          144515460,
          144537749,
          "CNULcPDhJdayFX1kxQB7hnTtoZU3zmBtpYtmPtMSPg1p"
        ]
      ],
      "pubkey": "111AA9fqgNXBnzzV4Ef1CpNZbWqFvzKoT9vyYqDHSkF",
      "rpc": null,
      "shredVersion": 33548,
      "tpu": "135.181.60.221:8003",
      "version": "1.12.0"
    },
    {
      "featureSet": 3605932003,
      "fullSnapshots": [
        [
          144476180,
          "AFeNP6yMqZFac1LzfP1SVrBGSZdhugHxigjYqibUvEPK"
        ],
        [
          144515460,
          "EQcYuGoyMbKAxNVEW5pCSPQwybwdNYtVEcJ4vHD66sMD"
        ]
      ],
      "gossip": "144.76.60.22:8000",
      "incrementalSnapshots": [
        [
          144515460,
          144533663,
          "3J95De9FtFtS3cgE7K83uFzEn9XAuNKHtF2YTFUoKRzR"
        ],
        [
          144515460,
          144535162,
          "Fa9PvgA2hTMKEaGikzZHQhuBsdFpeSMNnvDZ7zYYykGv"
        ],
        [
          144515460,
          144537446,
          "3Thsk76kYvDGiWXMhVmbN7kqxgUqi4CfderaJUD4Jvtn"
        ],
        [
          144515460,
          144538245,
          "CeHwyC4QtJDeki3f2Bc5Pm14pgE5gFBHJ4ttd7TX74Me"
        ]
      ],
      "pubkey": "52GEvaeCcEyAUKrfoPcey6vdyw6th588nYPuCkn3Kxes",
      "rpc": "144.76.60.22:8899",
      "shredVersion": 33548,
      "tpu": "144.76.60.22:8003",
      "version": "1.11.5"
    },
...
```

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Can you please expand the problem statement? When and why do you need information about all the snapshots available in the cluster?

**Comment by diman-io** [comment]
This will be friendly for third-party tools, such as [snapshot-finder](https://github.com/c29r3/solana-snapshot-finder).

PS. I don't really like this (I think the solana-validator needs to be improved), but at the same time it's undeniable that a lot of validators use it. So I just help python guys.

**Comment by CriesofCarrots** [comment]
Hmm, I'm not sure of the use case for that tool. Can you say more?
@brooksprumo , do you have any thoughts on this?

**Comment by diman-io** [comment]
Now the snapshot-finder goes through all the nodes of the cluster and tries to download both the full snapshot and the incremental one in order to (a) determine if they are there at all and (b) find out the snapshot slot number. There is currently no other way to get this information.

**Comment by diman-io** [comment]
> Is there a guideline for RPC methods on how much data they return, and/or how long the methods take to run?
In practice, not now, you can, for example, request all system accounts in json :)

> Full snapshots could be an array of { slot: 123, hash: abc }, and incremental snapshots would be an array of { base: 123, slot: 456, hash: abc }
I don't remember why I chose array of array, some other RPC method had an effect.

**Comment by CriesofCarrots** [comment]
> Is there a guideline for RPC methods on how much data they return, and/or how long the methods take to run?

As diman-io said, no we don't really have any prescriptions for response length.

I do think a separate RPC method would be best, and agree with using JSON maps.

Is there a reasonable way to do some sort of sorting or filtering on the responses so the response doesn't have to include all nodes?

**Pull request closed without merging**
