### PR TITLE
try to reduce boilerplate

### PR DESCRIPTION
**Pull request by rob-solana**
for discussion

### CODE REVIEW

**Comment by rob-solana** [comment]
@garious @mvines

**Comment by garious** [comment]
No dice. That whole module is moving to the _api crate.  If CI wasn't so damn slow today,  it'd already be done.

**Comment by rob-solana** [comment]
more interested in whether you like the approach

**Comment by garious** [comment]
Love the approach. It'll be a little harder than that across crates. Have you done the C-preprocessor equivalent of `##` in Rust macros?

**Comment by rob-solana** [comment]
> Love the approach. It'll be a little harder than that across crates. Have you done the C-preprocessor equivalent of `##` in Rust macros?

in another life (3 months ago)...  will look at your polished config and budget for further inspiration

**Pull request closed without merging**
