### PR TITLE
Add broken link checking to the Docs build subsequence

### PR DESCRIPTION
**Pull request by rmshea**
* Thanks, devs!

* Add broken link highlighting

#### Problem

We can't tell if our links are broken!

#### Summary of Changes

Add an automatic broken link checker. Bump Docusaurus to alpha v67

Fixes #

### CODE REVIEW

**Comment by jackcmay** [comment]
@rmshea Sweet!  Did you verify that indeed a broken link is flagged and breaks CI?  I'm kinda surprised my latest changes don't have at least one broken link ;-)

**Comment by danpaul000** [comment]
+1 with evidence of a failing job that catches a known broken link.

**Comment by danpaul000** [comment]
Once this is working, this should merge into 1.4 as well.

**Comment by jackcmay** [comment]
@rmshea @danpaul000 

Looks like in order to fail CI we needed to set the level to `throw`.  Check out this PR, I was able to confirm it failed CI with broken links, then I fixed them all :-)
https://github.com/solana-labs/solana/pull/13540

Thanks for finding the broken link setting @rmshea , we can probably close this PR once #13540 is commited.

**Comment by rmshea** [comment]
@jackcmay Thanks for taking this one across the line!

**Pull request closed without merging**
