### PR TITLE
all TestValdiators act like validators

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem
#23309
#### Summary of Changes

Fixes #

### CODE REVIEW

**Review by mvines — APPROVED** [review]
thanks for tolerating my bike shedding!

**Comment by jeffwashington** [comment]
A risk here is that some existing or new code path, cli, or test will now not get tested with the nightly buildkite build that tests the disk accounts index.

**Comment by mvines** [comment]
> A risk here is that some existing or new code path, cli, or test will now not get tested with the nightly buildkite build that tests the disk accounts index.

TestValidator is really just a tool for downstream program/client testing, it's not used to test anything within the monorepo.  The intent is that it behave as closely as possible to `solana-validator` as possible whilst including extra knobs useful for downstream testing

**Review by t-nelson — DISMISSED** [review]
also wfm

**Pull request merged**
