### PR TITLE
Add SVGs for Gitbook

### PR DESCRIPTION
**Pull request by ryan-shea**
#### Problem

For Gitbook to display our diagrams, we need to keep them live in the repo.

#### Summary of Changes

Generated latest SVGs, uploaded them.

### CODE REVIEW

**Comment by garious** [comment]
@mvines, regenerating SVGs will be a bit of a burden for book maintenance. Any way to avoid it?

**Comment by garious** [comment]
@ryan-shea, can you rebase? Would be great to get those images back in the book before the release.

**Comment by garious** [comment]
If we decide to move forward with this one, please use the `book/.gitattributes` file to cut down on the diff noise:

https://github.com/solana-labs/solana/blob/master/book/.gitattributes

**Comment by mvines** [comment]
> @mvines, regenerating SVGs will be a bit of a burden for book maintenance. Any way to avoid it?

There doesn't seem to be a way right now.  But we can make this easier by:
1) Adding a script to easily re-generate the SVGs as needed
2) Augment ci/test-checks.sh to confirm all SVGs are current

**Comment by garious** [comment]
@ryan-shea, can you get this rebased and merged before the release? We might be branching for release as early as tomorrow.

**Comment by garious** [comment]
Merge?

**Comment by garious** [comment]
crickets...  @mvines, Can you take care of this before we branch for release?

**Comment by mvines** [comment]
Yeah I see the cries for help and it's already on my radar.  :)

**Comment by ryan-shea** [comment]
@garious @mvines sorry. didn't see this until now https://github.com/solana-labs/solana/pull/6009

**Pull request closed without merging**
