### PR TITLE
Look for dynamic lib filenames with hashes in native loader

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
Cargo adds an extra hash in the file name for dependencies from git and crates.io so native loader cannot deterministically find the file path of a native program dynamic library.

#### Summary of Changes
Search exe directory for dynamic libraries ignoring hashes in the file names

Fixes https://github.com/solana-labs/solana/issues/5966

### CODE REVIEW

**Comment by garious** [comment]
I don't understand the problem description. How does that hash affect determinism?

**Comment by jstarry** [comment]
@garious I think I described it better in the issue, take a look here: https://github.com/solana-labs/solana/issues/5966

**Comment by garious** [comment]
Seems like this change sets you up for additional nondeterminism if you then go and change the git dependency, leaving you with two binaries.

**Comment by jstarry** [comment]
@garious ah yes, great point. I'll investigate a more deterministic approach

**Pull request closed without merging**
