### PR TITLE
Update TVU with transaction status service

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

There is no storage stage, but it's listed in the doc and transaction status service is not

#### Summary of Changes

Add transaction status service and remove storage stage.

Fixes #

### CODE REVIEW

**Review by CriesofCarrots — APPROVED** [review]
Sure, this is okay with me.
It's a little ambiguous because the Transaction Status Service doesn't do anything, unless the node has a geyser plugin loaded or has (rocksdb) transaction history enabled. But technically all transactions do get pipelined through there.

**Comment by sakridge** [comment]
> Sure, this is okay with me. It's a little ambiguous because the Transaction Status Service doesn't do anything, unless the node has a geyser plugin loaded or has (rocksdb) transaction history enabled. But technically all transactions do get pipelined through there.

That's true, I can put something like "(optional)" on there.

**Comment by t-nelson** [comment]
removal of the storage step is intentional? agreed that TSS is more of a sidecar service

**Comment by sakridge** [comment]
> removal of the storage step is intentional? agreed that TSS is more of a sidecar service

Storage stage was originally for archivers, which is now deprecated.

**Comment by t-nelson** [comment]
> Storage stage was originally for archivers, which is now deprecated.

ah, i thought it was referencing blockstore.  better deleted than ambiguous!

**Pull request merged**
