### PR TITLE
[docs] Fix `dataSlice` definition

### PR DESCRIPTION
**Pull request by steveluscher**
#### Problem

One of these is wrong (the one attached to `getAccountInfo`) and the rest could use clarification.

#### Summary of Changes

Before:

image

After:

image

### CODE REVIEW

**Comment by steveluscher** [comment]
cc/ @nickfrosty

**Review by CriesofCarrots — APPROVED** [review]
Seems nicer to me :)

**Review by jacobcreech — APPROVED** [review]
Much nicer!

**Comment by nickfrosty** [comment]
@steveluscher are you still thinking they need more clarification and/or any are wrong?

**Comment by steveluscher** [comment]
> @steveluscher are you still thinking they need more clarification and/or any are wrong?

Nope! Just tagged you because I can't add you as a reviewer (you have to request triage perms to this repo).

**Comment by steveluscher** [comment]
@mergify backport

**Pull request merged**
