### PR TITLE
validator: remove optional remote accounts hash consistency check

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

old debug code lying around doing old debug code things

#### Summary of Changes

remove it

### CODE REVIEW

**Comment by HaoranYi** [comment]
No, we don't rely on this cli argument for the fault injection test.

**Review by steviez — COMMENTED** [review]
Given Brook's insight about accounts hashes becoming part of consensus, that makes me feel better about ripping this check out altogether.

I thought about whether keeping a warning in place would be useful, but I don't think it would be.
- Suppose a node `N` is running with this flag for a set of known validators `{K1, K2, ..., Kn}`
- If one of the known validators `Ki` deviates, `N` would get a warning.
- But, `N`'s operator can't do anything to fix `Ki` directly, so seemingly not super helpful

**Comment by steviez** [comment]
I think we still want this - I just had one minor request and looks like things need a merge resolution now

**Review by steviez — APPROVED** [review]
LGTM.

Looking at this again after a few weeks, I still think ripping this out is the right move. If this flag had wide adoption, a single node experiencing a bug or fault could cause a domino effect.

Additionally, we can't know if the node that we're checking against or we deviated on a slot, yet, this code makes only our node panic. Hypothetically, we could do some sampling of `N` nodes, but to make this robust we're basically trying to implement a stripped down consensus. Better to kill this altogether and let the feature Brooks previously mentioned (accounts hash becoming part of consensus) take effect.

**Comment by t-nelson** [comment]
Screenshot from 2023-05-16 13-20-00

no idea why we're wasting ci/dev resources to keep this list sorted...

**Pull request merged**
