### PR TITLE
add feature activation schedule

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

Feature activation is poorly coordinated and communicated

#### Summary of Changes

Proposed evolving feature activation schedule

Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
Love the idea, does this really belong in the repo though? It'll get forked out to release branches, where wouldn't we just want a single instance of the schedule?

Perhaps a wiki page in https://github.com/solana-labs/solana/wiki would work better in this case?

**Comment by jackcmay** [comment]
> Love the idea, does this really belong in the repo though? It'll get forked out to release branches, where wouldn't we just want a single instance of the schedule?
> 
> Perhaps a wiki page in https://github.com/solana-labs/solana/wiki would work better in this case?

Yeah, single instance, and wiki is probably better.  I was hoping to be able to do a pr process for any changes so folks and review and provide feedback directly for any change to the schedule.

**Comment by mvines** [comment]
>  I was hoping to be able to do a pr process for any changes so folks and review and provide feedback directly for any change to the schedule.

Perhaps  a weekly 5min process whereby the activation schedule for the next 2-3 weeks in announced in Discord? If nobody says anything then it's happening! 🤝

**Comment by jackcmay** [comment]
Moved it to a wiki

**Pull request closed without merging**
