### PR TITLE
Move get_clients into gossip_service

### LINKED ISSUE #3908: Share bench-exchange::get_clients logic with bench-tps
#### Problem

bench-tps and bench-exchange need to filter multiple client nodes by whoever has rpc and tpu enabled which is in the bench-exchange::get_clients function.

#### Proposed Solution

Maybe move get_clients to the client module and share with bench-tps.

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Couple versions of get_clients filtering/ThinClient creation function.

#### Summary of Changes

Unify to one in gossip_service

Fixes #3908

### CODE REVIEW

**Comment by sakridge** [comment]
Any better place for this?

**Comment by garious** [comment]
Looks like ClientInfo is missing a method that does this:

```rust
            let cluster_addrs = self.client_facing_addr();
            if Self::is_valid_address(&cluster_addrs.0)
                && Self::is_valid_address(&cluster_addrs.1) {
                    Some(cluster_addrs)
            } else {
                    None
           }
```

And if that existed, the function you're moving here might be so simple, you'd just inline it.

**Comment by sakridge** [comment]
@garious ClientInfo or ContactInfo?

**Comment by garious** [comment]
ContactInfo,  sorry. If you want to put this in gossip_service, that seems fine. Or copy-pasta it since it's pretty simple.

```rust
pub fn get_clients(nodes: &[ContactInfo]) -> Vec<ThinClient> {
    nodes
        .iter()
        .filter_map(ContactInfo::valid_client_facing_addr)
        .map(|addrs| create_client(addrs,  FULLNODE_PORT_RANGE)
        .collect()
}
```

**Comment by sakridge** [comment]
@garious cool. That's cleaner, thanks.

**Pull request merged**
