### PR TITLE
Added release-notes for v1.8.11

### PR DESCRIPTION
**Pull request by bji**

### CODE REVIEW

**Comment by mvines** [comment]
Release notes belong in the release directly: https://github.com/solana-labs/solana/releases/tag/v1.8.11
I'm not interested in maintaining additional release nodes in the git repo itself

A couple options here:
* Community release notes could be maintained outside of the monorepo, and we could link to those from the official release notes
* Unfortunately to modify release notes directly, it looks like Github requires the user have write access to the repo. I'd be willing to grant you write access @bji but that approach probably doesn't scale

**Comment by bji** [comment]
Hm thanks for your feedback.  Before even trying to address the correct place for these to live -- do you think that these release notes are adding anything of value?  I am not an expert in the Solana code base and I don't want to provide inaccurate or incomplete information that may be worse than no information at all.

I would be fine with either linking out to my release notes, or for me to update the release notes in the release directly, whichever you think is best.  You guys have a better feel for how you want to communicate this information than I do.  Thank you.

**Comment by mvines** [comment]
It's definitely valuable, there's certainly a level of release note fatigue going on.  Earlier releases are definitely more descriptive than what happens these days.  I sent you an invite that should grant you write access to the monorepo release notes, let's try that!

**Comment by bji** [comment]
I have updated the release notes directly and will close this pull request.  Thank you!

**Pull request closed without merging**
