### PR TITLE
Remove releases from readme

### PR DESCRIPTION
**Pull request by garious**
#### Problem

Duplicate release documentation.

#### Summary of Changes

Delete the copy in the readme.  Use the "Install Solana" page in the docs instead.

### CODE REVIEW

**Comment by lazaridiscom** [comment]
closes: #8181

**Comment by lazaridiscom** [comment]
@garious , where did you move this info to?

**Comment by garious** [comment]
https://docs.solana.com/v/master/install-solana

**Comment by lazaridiscom** [comment]
this read nice, but shouldn't you add the text you removed from the readme, at least in a separate page in the docs, thus those channels are available to those who want to install them manually?

**Comment by garious** [comment]
The docs I deleted solved a problem we didn't have.

**Comment by lazaridiscom** [comment]
??? I don't understand.

You mean "documenting the different release-channels is redundant"?

I believe it is relevant, but if you think its not, fine, just close #8181 then.

**Pull request merged**
