### PR TITLE
Fix/remove short circuit logic in ledger_purge_batch (&& -> &)

### PR DESCRIPTION
**Pull request by sunnygleason**
**Credit**: found/fixed by @sdhawan

#### Problem

The product is currently not purging ledger storage correctly, it may fail
to purge slots from later column families based on earlier column family
purge results due to short-circuit logic.

#### Summary of Changes

* Remove short-curcuit logic: `&& -> &`

Fixes: (partial fix for https://github.com/solana-labs/solana/issues/7499)

We likely need additional fixes to compact storage.

### CODE REVIEW

**Comment by mvines** [comment]
@t-nelson is fixing this nonce CI error, you'll need to rebase on his fix once it lands

**Comment by t-nelson** [comment]
Fix is here. https://github.com/solana-labs/solana/pull/7527

**Comment by sunnygleason** [comment]
> #7527

tysm! 💯

**Comment by sagar-solana** [comment]
Wanna pull in the test changes from my pr too?

**Pull request merged**
