### PR TITLE
chore: bump toml from 0.8.8 to 0.8.10

### PR DESCRIPTION
**Pull request by yihau**
#### Problem

dependabot doesn't create this bumping PR, #35103, correctly so I create this one manually.

#### Summary of Changes

```bash
$ sed -i 's/toml = "0.8.8"/toml = "0.8.10"/g' Cargo.toml
$ scripts/cargo-for-all-lock-files.sh tree
```

---

Close #35103

### CODE REVIEW

**Review by CriesofCarrots — APPROVED** [review]
I can't see any difference with https://github.com/solana-labs/solana/pull/35103 🤷‍♀️ 
But no objections

**Comment by yihau** [comment]
thank you! #35103 tried to do
```
scripts/cargo-for-all-lock-files.sh programs/sbf/Cargo.lock -- update -p toml:0.8.8 --precise 0.8.10
```
but no luck. I tried it manually, and no luck either. I suspect it's about the workspace 🤔

**Comment by CriesofCarrots** [comment]
It looks like toml in `programs/sbf/Cargo.lock` is at v0.5.8, so that command definitely won't work. I'm not sure how the lock files got out of sync, but will probably need to be updated manually

**Comment by yihau** [comment]
yeah, you're right. I don't know how I misread this command 🤦‍♂️. I thought it failed at the top level of Cargo.toml... 
hope that we can get rid of the old borsh asap!

**Pull request merged**
