### PR TITLE
move rpc types from client to client-types crate

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

ledger crate has too many dependencies causing slow build times.

#### Summary of Changes

Separate out RPC types used by ledger into another crate, so that ledger doesn't need to depend on client. This removes about 50 dependent crates from the ledger tree.

Fixes #

### CODE REVIEW

**Comment by garious** [comment]
Looks like ledger-tool shouldn't depend on anything called "client" or even "rpc". How about calling this crate "solana-transaction-status"? And if time allows, strip the Rpc prefix from any struct that ledger-tool or ReplayStage depends on?

**Comment by sakridge** [comment]
> 
> 
> Ha, thanks. Knew this was in our future at some point.
> 
> Any reason not to move all the rpc types to that crate? Seems like a maintenance burden to keep them in 2 places. If we add new types in the future, the distinction between client and client-types may not be clear.

There is one that has an rpc_error dependency which seemed like it might be some work to untangle. Otherwise I can bring in the others.

**Comment by garious** [comment]
@sakridge, bringing in more RPC stuff is the opposite of what I suggested. Do you really need an "RPC types" crate?

**Comment by sakridge** [comment]
> @sakridge, bringing in more RPC stuff is the opposite of what I suggested. Do you really need an "RPC types" crate?

I was just considering both approaches. I'll go with the transaction-status crate with the rename.

**Comment by sakridge** [comment]
> 
> 
> Looks like ledger-tool shouldn't depend on anything called "client" or even "rpc". How about calling this crate "solana-transaction-status"? And if time allows, strip the Rpc prefix from any struct that ledger-tool or ReplayStage depends on?

@garious if I strip Rpc, the names conflict with existing types, any idea for another prefix?

**Comment by garious** [comment]
@sakridge, it's not obvious to me why we're storing RPC-friendly structs in the ledger.  Sounds like unnecessary bloat. Maybe the prefix needs to be "Bloated" until that's addressed. :)

**Comment by sakridge** [comment]
> 
> 
> So nice, thanks for taking care of this!

Thanks for the reviews @garious and @CriesofCarrots

**Pull request merged**
