### PR TITLE
Extract duplicate clap helpers into clap-utils

### PR DESCRIPTION
**Pull request by ryoqun**
From @mvines's [comment](https://github.com/solana-labs/solana/pull/6790#discussion_r343505652) _(emphasis mine)_:

> I’d rather not have validator depend on cli. **It’s long overdue that we create a common clap-validators/ crate where we can easily share these validators between all the tools.**
> 
> **Care to add that common crate first and then do the input validator cleanup here? We can do that in a separate PR from the check_vote_account() changes here.**

Let's clean up! :)

Because of a blocker for https://github.com/solana-labs/solana/pull/6790, this might be back-ported to 0.20.x as well.

### CODE REVIEW

**Comment by mvines** [comment]
Yay!  


Let's discuss the name of the crate a little.   We already have `solana-netutil`, and now we'll have a `solana-clap-utils`.   `util` vs `utils`, we should be consistent here.  Some alternative names I see:
1. `solana-clap-util` (`solana_clap_util` in code)
2. `solana-claputil` (`solana_claputil` in code)

On the other hand, I see many .rs files with `utils` in them:
```
./ledger/src/genesis_utils.rs
./ledger/src/leader_schedule_utils.rs
./ledger/src/staking_utils.rs
./ledger/src/snapshot_utils.rs
./ledger/src/bank_forks_utils.rs
./core/src/genesis_utils.rs
./core/src/broadcast_stage/broadcast_utils.rs
./runtime/benches/transaction_utils.rs
./runtime/src/genesis_utils.rs
./runtime/src/loader_utils.rs
./runtime/src/transaction_utils.rs
./runtime/src/storage_utils.rs
./runtime/src/serde_utils.rs
./programs/btc_spv_api/src/utils.rs
./sdk/src/account_utils.rs
./sdk/src/instruction_processor_utils.rs
./client/src/perf_utils.rs
```
and perhaps `solana-netutil` is the one that is misnamed!

@CriesofCarrots - do you have a preference?

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots - do you have a preference?

I am a little ambivalent, as I see the argument that netutil is wrong. But ultimately, I like the simplicity of `solana-claputil` (`solana_claputil` in code, `claputil` as directory name) best.
(There's a nice semantic and logical difference between the crate names and _utils modules.)

**Comment by ryoqun** [comment]
@CriesofCarrots @mvines 

I like these kinds of discussions and happy to have one with both you. Surely both of you pay great attentions to details. I believe naming is very important to avoid any cognitive loads.

With that said...

> > @CriesofCarrots - do you have a preference?
> 
> I am a little ambivalent, as I see the argument that netutil is wrong. But ultimately, I like the simplicity of `solana-claputil` (`solana_claputil` in code, `claputil` as directory name) best.
> (There's a nice semantic and logical difference between the crate names and _utils modules.)

I'd like the simplicity of `claputil` and also I agree with the difference of crates and modules. However, in the end, I think the consistent convention wins.

As this PR is the case, I don't think it's rare to promote modules to its own crate over the evolution of code base. So, choosing different naming convention for modules and crates introduces a bit extra effort. Otherwise, renaming all `???-utils` modules to `???util` would take some cost and become a bit awkward to visually recognize for long words like `instruction_processorutil`.

After considering your thoughts, I'd like to keep this PR as this is, and rename `netutil` to `net-utils` (in separate PR?).


Just for the record, following is the omitted reasoning for this naming `solana-clap-utils` crate (`solana::clap_utils` in code, `clap-utils` in dir):

- **`-` over `_`**: `-` is used more often than `_` for crate names and dirs in the solana and the rust universe.
  - not rigoulirous check but just looking (`git ls-files :**.rs | while read -r f; do echo $(dirname $f); done | sort | uniq | grep '[-_]'` and `find ~/.cargo/registry/src/ -name '*.rs' | while read -r f; do echo $(dirname $f); done | sort | uniq | grep '[-_]'`) (convention first)
- **`clap*` over `cli*`**: Although I slightly slanted to the generic term `cli` as `netutil`, I chose `clap`. That's because I thought this crate will always be auxiliary/complement to the `clap` crate justifying explicit mention of the crate for this symbiotic relationship, and being dependant on/exposing the clap API pass-through, not encapsulating it at all.
- **`utils` over `util`**, **`???-util(s)` over `???util(s)`**: As said, in accord with the convention.

**Comment by ryoqun** [comment]
@mvines Thx for the approval. I'd rather refrain from merging this right now because it's midnight there in San Francisco. Because this would be my first time to merge a sizable PR with backporting, I'd like to take a safer timing (i.e. daytime in SF). :)

Also, feel free to merge this. I'm sleeping :zzz:

**Comment by ryoqun** [comment]
According to [this](https://github.com/solana-labs/solana/pull/6790), I merged this without backporting!

**Pull request merged**
