### PR TITLE
Add spacing in templates

### PR DESCRIPTION
**Pull request by brooksprumo**
### Problem

The templates aren't as friendly to fill out, due to a lack of newlines. Specifically, with the old templates, I'd have to add new lines in every PR/Issue to ensure there was a newline between the sections.

### Summary of Changes

Add newlines to the templates.

### CODE REVIEW

**Comment by mvines** [comment]
I prefer the current header size myself. But I also would prefer more that the templates be deleted outright, I never liked them since day 1. I may be in the oppressed minority here and will bend to the will of the team.

**Comment by t-nelson** [comment]
Eh. Either size is fine by me.  How do we make people fill it out before submitting :wink:

**Comment by mvines** [comment]
> Eh. Either size is fine by me. How do we make people fill it out before submitting 😉

Heh that’s a great way to get me to rage quit

**Comment by CriesofCarrots** [comment]
> Heh that’s a great way to get me to rage quit

A personal thank you from me for submitting PRs with some kind of description, though! I do a lot of scanning of github email notifications to see what PRs I should go to github to look at more closely.

I don't have a strong opinion on the template.

**Comment by mvines** [comment]
I’m 100% for descriptions to be clear. Forced templates just bring me back to big company trauma.

**Comment by t-nelson** [comment]
oh idgaf about the template, just that there's a good description of what the changes are so i know if i should look at it or not

**Comment by jstarry** [comment]
I like the "problem" prompt because I tell what someone is actually trying to fix. But quite often it's overkill so I don't mind downgrading it to a commented out prompt

**Comment by brooksprumo** [comment]
Ok, I've reverted the changes to the size of the headers.

It would still be beneficial in my usage to have the newlines added. What do y'all think about that?

**Review by mvines — APPROVED** [review]

**Review by CriesofCarrots — APPROVED** [review]
Wfm. Will probably have to do some kind of bypass to not hit that sanity error on blank lines at EOF

**Pull request merged**
