### PR TITLE
Add handling of program accounts owned by upgradeable loader

### PR DESCRIPTION
**Pull request by dmakarov**
#### Problem

`InvokeContext::prepare_instruction` returns indices of program accounts. For instruction with programs owned by upgradeable loader two indices are expected -- one of program account itself and another is of programdata account that contains the actual executable module in its data. 

#### Summary of Changes

This change adds handling of instructions with programs owned by upgradeable loader to correctly return both indices of program and program data accounts.

### CODE REVIEW

**Comment by pgarg66** [comment]
@dmakarov is this resulting in a failure? The program data accounts were removed from the program indices as an optimization as part of new program cache. If the program already exists in the cache, it avoids loading the program and program data accounts in the accounts DB. The feature is still in progress. So, some of the code paths may look odd. But if its breaking something, we should certainly find a way to fix it.

**Comment by dmakarov** [comment]
> @dmakarov is this resulting in a failure? The program data accounts were removed from the program indices as an optimization as part of new program cache. If the program already exists in the cache, it avoids loading the program and program data accounts in the accounts DB. The feature is still in progress. So, some of the code paths may look odd. But if its breaking something, we should certainly find a way to fix it.

The problem came about while I've been working on moving rbpf-cli functionality to ledger-tool.  The idea is to run rbpf programs outside validator with ledger data being available to the program.  This is requested by Neon Labs, they analyze traces produced by rbpf-cli, but they would like to have complete traces, including CPI calls.  When a mocked transaction and instruction is being processed to run a program, there's no executor cache, and it seems difficult to add it (no public api outside bank to access its executor cache).  So when a CPI call is being processed for the mocked transaction, bpf_loader::load_program_from_account fails because it expects two program accounts being provided in actual parameters, one being the program data account.  The program data account is supposed to be provided by InvokeContext::prepare_instruction, which this PR is trying to fix.

**Comment by pgarg66** [comment]
> > @dmakarov is this resulting in a failure? The program data accounts were removed from the program indices as an optimization as part of new program cache. If the program already exists in the cache, it avoids loading the program and program data accounts in the accounts DB. The feature is still in progress. So, some of the code paths may look odd. But if its breaking something, we should certainly find a way to fix it.
> 
> The problem came about while I've been working on moving rbpf-cli functionality to ledger-tool. The idea is to run rbpf programs outside validator with ledger data being available to the program. This is requested by Neon Labs, they analyze traces produced by rbpf-cli, but they would like to have complete traces, including CPI calls. When a mocked transaction and instruction is being processed to run a program, there's no executor cache, and it seems difficult to add it (no public api outside bank to access its executor cache). So when a CPI call is being processed for the mocked transaction, bpf_loader::load_program_from_account fails because it expects two program accounts being provided in actual parameters, one being the program data account. The program data account is supposed to be provided by InvokeContext::prepare_instruction, which this PR is trying to fix.

So, the executor cache is `None` in this use-case? We'll be replacing bank's executor cache with a global instance of `LoadedPrograms`. That should make it easier to pre-populate the cache with loaded programs. That would be ideal way to take it forward.
Is this an urgent fix? If so, maybe its ok for now. But, we'll need to update this again once the cache gets replaced.

**Comment by dmakarov** [comment]
> So, the executor cache is `None` in this use-case? We'll be replacing bank's executor cache with a global instance of `LoadedPrograms`. That should make it easier to pre-populate the cache with loaded programs. That would be ideal way to take it forward. Is this an urgent fix? If so, maybe its ok for now. But, we'll need to update this again once the cache gets replaced.

The executor cache is not None, but default(), ie not populated with any data. I’d like to move forward with this change, because I can’t make CPI programs run without this in ledger-tool for mocked transaction. It’s not urgent, in a sense that something existing is broken otherwise. I believe the control flow paths in validator will remain the same for all cases with this change. Only one index will be returned if program data account is not in the transaction context as is the case without this change. LoadedPrograms definitely will be useful, and I’ll be glad to update ledger-tool to use it when it becomes available.

**Comment by Lichtso** [comment]
@dmakarov I now see what the problem is you are trying to solve. Well, we changed the loading strategy from lazy to eager, so the correct way is now to load all programs a transaction needs (including all possible CPI calls) upfront. Take a look at `replenish_executor_cache()` in https://github.com/solana-labs/solana/blob/4b0e16d06f87999ed3ed7031ce78c9677e29bfae/runtime/src/bank.rs#L4443

Do you use the Bank directly? If not maybe we can do a call tomorrow and I can walk you through the necessary changes.

**Comment by dmakarov** [comment]
> @dmakarov I now see what the problem is you are trying to solve. Well, we changed the loading strategy from lazy to eager, so the correct way is now to load all programs a transaction needs (including all possible CPI calls) upfront. Take a look at `replenish_executor_cache()` in
> 
> https://github.com/solana-labs/solana/blob/4b0e16d06f87999ed3ed7031ce78c9677e29bfae/runtime/src/bank.rs#L4443
> 
> Do you use the Bank directly? If not maybe we can do a call tomorrow and I can walk you through the necessary changes.

Yes, I also use bank 
``` rust
    let (bank_forks, ..) = load_bank_forks(
        arg_matches,
        &genesis_config,
        Arc::new(blockstore),
        process_options,
        snapshot_archive_path,
        incremental_snapshot_archive_path,
    )
    .unwrap_or_else(|err| {
        eprintln!("Ledger loading failed: {err:?}");
        exit(1);
    });
    let bank = bank_forks.read().unwrap().working_bank();
```
However, all executor related stuff is internal to a bank with a public API, so it seems easier for now not to interfere with bank's API w.r.t. executor cache.

**Comment by dmakarov** [comment]
Finally, it doesn't seem feasible to require pre-loading all program accounts in transitive CPI invocation chains.  For example, I develop a program X, and I need to make a CPI call to program Y. I add the program Y account pubkey to invoke Instruction. However, if program Y makes a CPI call to program Z, I may not know that, and may not be able to include the program Z account pubkey in my Instruction that I wrote to invoke the program Y.

**Comment by pgarg66** [comment]
> Finally, it doesn't seem feasible to require pre-loading all program accounts in transitive CPI invocation chains. For example, I develop a program X, and I need to make a CPI call to program Y. I add the program Y account pubkey to invoke Instruction. However, if program Y makes a CPI call to program Z, I may not know that, and may not be able to include the program Z account pubkey in my Instruction that I wrote to invoke the program Y.

My understanding is that all accounts pubkeys (e.g. Z in this case) have to be included with the instruction. If not, we have a problem here.

**Comment by Lichtso** [comment]
The rules says they have to be included in the callers instruction yes. But technically, we could soften the requirement to only having them in the transaction (not the specific instruction).

**Comment by dmakarov** [comment]
> The rules says they have to be included in the callers instruction yes. But technically, we could soften the requirement to only having them in the transaction (not the specific instruction).

It implies a developer of X has to know all chains of CPI calls of Y and further when they want to call Y, doesn’t it? It seems this information may not be always available to users of Y, if source code of Y and all of its transitive callers is not available…

**Comment by Lichtso** [comment]
Yes, the program-runtime-v1 is overly restrictive. The next version will only require the programs to be known to the transaction. I don't want to change the rules in v1 because that might have unforseen consequences.

**Pull request closed without merging**
