### PR TITLE
Time out async sends to avoid slackers stuck in the queue for too long

### PR DESCRIPTION
**Pull request by lijunwangs**
#### Problem
Time out async sends to avoid slackers stuck in the queue for too long impacting future sends.

#### Summary of Changes

Use Tokio::timeout to timeout the async sends.

Fixes #

### CODE REVIEW

**Review by ryleung-solana — COMMENTED** [review]
I think in the case of the batch send, the timeout should be calculated based on the size of the batch. Otherwise, LGTM.

**Comment by lijunwangs** [comment]
> I think in the case of the batch send, the timeout should be calculated based on the size of the batch. Indeed, we could have a constant MAX_AVERAGE_TIME that each element should take to send, and calculate the timeout for the batch that way. Individual non-batch sends would then just have a timeout of MAX_AVERAGE_TIME. Also, it would be nice to get some tests done to ensure that these constants are both large enough under normal conditions, but not too large. Otherwise, LGTM.

I am already considering the batch send's size. See

let time_out = SEND_TRANSACTION_TIMEOUT_MS * buffers.len() as u64;

The value taken is 10 second -- is pretty conservative: more than 10 times of the node being a leader. This is just a defensive measure guarding against transaction  stuck extremely long time, for example against malicious leader. bench-ups does not show any issues as normally the transaction is sent in much shorter time.

**Comment by pgarg66** [comment]
Are we seeing problems due to the current code in testnet/mainnet? Wondering how the problem manifests. And, if we ran this PR on the cluster to see the imrpovements.

**Comment by lijunwangs** [comment]
> Are we seeing problems due to the current code in testnet/mainnet? Wondering how the problem manifests. And, if we ran this PR on the cluster to see the imrpovements.

No -- I have not seen concrete issues from MB yet. As I said this is a defensive measure especially we are limiting the number tasks in the runtime. Attached is some send-us time measured in microseconds in MB. You can see some sends can really take some extreme time 20 (seconds).
Screen Shot 2022-10-25 at 9 36 27 AM

**Comment by pgarg66** [comment]
> > Are we seeing problems due to the current code in testnet/mainnet? Wondering how the problem manifests. And, if we ran this PR on the cluster to see the imrpovements.
> 
> No -- I have not seen concrete issues from MB yet. As I said this is a defensive measure especially we are limiting the number tasks in the runtime. Attached is some send-us time measured in microseconds in MB. You can see some sends can really take some extreme time 20 (seconds). Screen Shot 2022-10-25 at 9 36 27 AM

Is it possible to run this PR in the above scenario and see the improvements?
Also, can we add the stats to the PR? It'll help correlate the issue with the fix.

**Comment by lijunwangs** [comment]
> > > Are we seeing problems due to the current code in testnet/mainnet? Wondering how the problem manifests. And, if we ran this PR on the cluster to see the imrpovements.
> > 
> > 
> > No -- I have not seen concrete issues from MB yet. As I said this is a defensive measure especially we are limiting the number tasks in the runtime. Attached is some send-us time measured in microseconds in MB. You can see some sends can really take some extreme time 20 (seconds). Screen Shot 2022-10-25 at 9 36 27 AM
> 
> Is it possible to run this PR in the above scenario and see the improvements? Also, can we add the stats to the PR? It'll help correlate the issue with the fix.

I have added send_timeout stats

**Review by ryleung-solana — APPROVED** [review]

**Review by pgarg66 — APPROVED** [review]

**Comment by lijunwangs** [comment]
> 
This is the send_timeout captured running against the testnet

Screen Shot 2022-10-31 at 1 42 26 PM

**Pull request merged**
