### PR TITLE
Purge banks, with the same slot, sequentially

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

In https://github.com/solana-labs/solana/pull/32536, we purged dropped banks in parallel. We then observed asserts where the reclaims were not correct (https://github.com/solana-labs/solana/issues/33026).

If we have two (or more) banks with the same slot (i.e. from different forks) that get dropped *concurrently*, then it is possible multiple threads get a list of pubkeys to purge and then both try to purge those pubkeys. The first will succeed, and subsequent ones will assert because the number of pubkeys purged will not match what was expected.

#### Summary of Changes

Purge banks with the same slot sequentially. Different slots are still purged in parallel.

Fixes: #33026

### CODE REVIEW

**Comment by carllin** [comment]
Was this caused by duplicate blocks causing two version of a bank to be produced for the same slot? Then one gets dropped when the other one gets created, but it's possible that if the AccountsBackgroundService queue is large, the second also gets added to the channel before the first one is processed?

**Review by jeffwashington — APPROVED** [review]
lgtm

**Comment by AshwinSekar** [comment]
Does this imply that someone on mnb has been submitting duplicate blocks? Or is there a non duplicate situation where we submit a slot multiple times for purging?

**Comment by carllin** [comment]
is this block one that the validator itself is the leader for? I know there's a bug where the leader can potentially recreate the block twice if the first one was on an invalid fork

**Comment by AshwinSekar** [comment]
> I think it is a bad block/wrong fork that gets dropped then the correct fork is chosen. 
But it must have been for the same `Slot` right? Which would indicate that someone has produced multiple banks for the same slot? Do we know if the bank ids are also different?

**Comment by AshwinSekar** [comment]
> Given the above, if a node is replaying 4, then sees it is on the wrong fork and switches to 4', won't it still have to replay 2' and 3'? If yes, what happens to banks 2 and 3? I would expect that they need to be dropped, and rollback any AccountsDb state changes in slots 2 and 3.

Yes that's correct, but that goes back to my initial concern. This implies that someone is submitting duplicate blocks on mnb. Are there logs somewhere I can dig into?

**Comment by AshwinSekar** [comment]
```
grep "purging slot\|Notifying repair service to repair duplicate slot\|DuplicateState" solana-validator.log.1
``` 
returns nothing, it seems the slot was not a duplicate, and was not dumped then repaired through the duplicate pipeline. 

Perhaps something else is going on? I was drawn to slot `217986968` because it triggered an `accounts_db` `ERROR` log below. But it looks like the slot was dead, so maybe this is a red herring. 
```
INFO  solana_core::replay_stage] new fork:217986968 parent:217986963 root:217986932
INFO  solana_ledger::blockstore_processor] Too few entry ticks found in slot: 217986968 3967053 
WARN  solana_ledger::blockstore_processor] TooFewTicks, slot: 217986968, entry len: 0, tick_height: 13951166011, last entry: 4N41KJMCb5gToUJvSU8eU2vKafwzEETvvCD6J4HCeBek, last_blockhash: B78Bb6fxBZGxjxZiUd9qYJUosdNUTA835yK4X8Su7CT9, shred_index: 1, slot_full: true
3967054 
INFO  solana_core::repair::cluster_slot_state_verifier] check_slot_agrees_with_cluster() slot: 217986968, root: 217986936, slot_state_update: Dead(DeadState { cluster_confirmed_hash: None, is_slot_duplicate: false })

[...]

INFO  solana_core::repair::repair_service] repair_stats: [(217986968, 2)]
WARN  solana_ledger::blockstore_processor] slot 217986968 failed to verify: failed to load entries, error: blockstore error
INFO  solana_core::replay_stage] new fork:217986968 parent:217986963 root:217986951
ERROR solana_accounts_db::accounts_db] set_hash: already exists; multiple forks with shared slot 217986968 as child (parent: 217986963)!?
INFO  solana_core::repair::cluster_slot_state_verifier] check_slot_agrees_with_cluster() slot: 217986968, root: 217986951, slot_state_update: Dead(DeadState { cluster_confirmed_hash: None, is_slot_duplicate: false })
```

**Comment by AshwinSekar** [comment]
Seeing a similar story right before the panic there as well:
```
INFO  solana_core::replay_stage] new fork:215484960 parent:215484955 root:215484924
INFO  solana_ledger::blockstore_processor] Too few entry ticks found in slot: 215484960
WARN  solana_ledger::blockstore_processor] TooFewTicks, slot: 215484960, entry len: 0, tick_height: 13791037493, last entry: 85qbJZ1m9ratY744A7B12yXxM9ZKudmk6CHztX4YDtKA, last_blockhash: 9ryDXHSze4nabYjrRGe1tPj7Gozzs5XMo3tjntTQtJLb, shred_index: 1, slot_full: true
INFO  solana_core::repair::cluster_slot_state_verifier] check_slot_agrees_with_cluster() slot: 215484960, root: 215484928, slot_state_update: Dead(DeadState { cluster_confirmed_hash: None, is_slot_duplicate: false })

INFO  solana_core::repair::repair_service] repair_stats: [(215484959, 1), (215484962, 6), (215484960, 12)]
WARN  solana_ledger::blockstore_processor] slot 215484960 failed to verify: failed to load entries, error: blockstore error
INFO  solana_core::replay_stage] new fork:215484960 parent:215484955 root:215484934

ERROR solana_accounts_db::accounts_db] set_hash: already exists; multiple forks with shared slot 215484960 as child (parent: 215484955)!?

INFO  solana_core::repair::cluster_slot_state_verifier] check_slot_agrees_with_cluster() slot: 215484960, root: 215484934, slot_state_update: Dead(DeadState { cluster_confirmed_hash: None, is_slot_duplicate: false })
```

**Pull request merged**
