### PR TITLE
remove bpf_c feature-ization

### PR DESCRIPTION
**Pull request by rob-solana**
#### Problem
 bpf_loader seems to always rebuild with bpf_c turned on

 #### Summary of Changes
 whack bpf_c as a feature flag

Fixes #

### CODE REVIEW

**Comment by rob-solana** [comment]
note that I've disabled the make command, too...

**Comment by garious** [comment]
Does this change imply that one could no longer `cargo install solana` without first figuring out some version of llvm that needs to be installed?

**Comment by garious** [comment]
I'm pretty against this - it'll be a community killer. rocksdb needs a better solution too. A key-value store isn't rocket science. There's gotta be a pure Rust one we can use when performance isn't a requirement.

**Comment by jackcmay** [comment]
If we are ok with rocker as a deep we can provide llvm via a rocker image

**Comment by garious** [comment]
I'm not okay with docker as a dep either. Not only is it a massive dep (far bigger than llvm), but then you'll have CI doing docker inside of docker, which generally works these days, but seems pretty hideous.

**Comment by garious** [comment]
How about figuring out what's broken in cargo, fixing that, and then trying out best to ignore the rebuilds until that cargo release makes it to stable?

**Pull request closed without merging**
