### PR TITLE
chore: workspace inheritance

### PR DESCRIPTION
**Pull request by yihau**
#### Problem

reopen for https://github.com/solana-labs/solana/pull/29509 which reverted at https://github.com/solana-labs/solana/pull/29892

### CODE REVIEW

**Comment by yihau** [comment]
wasm-pack doesn't support workspace inheritance well. I think maybe we can wait for this PR being merged https://www.github.com/rustwasm/wasm-pack/pull/1185

**Comment by yihau** [comment]
the wasm test passed. this one should be fine to merge again 🪖

**Review by steviez — APPROVED** [review]
Same as before, I ran `cargo tree` on tip of master and this branch, and observed no difference in the generated output.

**Comment by yihau** [comment]
there are some conflicts when I would like to merge this one 😢 @steviez could you take another look at this PR please. thank you!

**Review by steviez — APPROVED** [review]

**Comment by jamesmichaeltate1** [comment]
I don't no what I'm doing but I no I have not used spent or traded any stock are crypto .

**Pull request merged**
