### PR TITLE
token: Add features for new program releases

### PR DESCRIPTION
**Pull request by joncinque**
#### Problem

We need to release new token-v3 and associated-token-account programs.  More information is in the feature gate issues.

#### Summary of Changes

Add new features and program ids for the updated programs.

Feature Gate Issue: #24741
Feature Gate Issue: #24740

### CODE REVIEW

**Review by CriesofCarrots — DISMISSED** [review]
🎉🎉

**Comment by CriesofCarrots** [comment]
Hey fyi, that `test_rent_eager_collect_rent_in_partition` test failure will be consistent. Its magic number evidently needs to be bumped by 1 for every new feature added, cc https://github.com/solana-labs/solana/pull/24722 and @jeffwashington 
Hopefully we can come up with something less brittle soon.

**Comment by joncinque** [comment]
Oh wow thanks for pointing this out! I was so confused about the failure.  I'll fix this up

**Comment by CriesofCarrots** [comment]
> Oh wow thanks for pointing this out! I was so confused about the failure. I'll fix this up

I just chatted with Jeff. I'll push something that should work as a less-brittle stopgap in just a few.

**Pull request merged**
