### PR TITLE
Use assert_eq instead of assert_matches

### LINKED ISSUE #1010: Use assert_eq, not assert_matches, where possible
Following the Rule of Least Power (https://en.wikipedia.org/wiki/Rule_of_least_power), look for code such as:

```rust
assert_matches!(rv, Err(Error::CrdtError(CrdtError::NoPeers)));
```

and drop the dependency on the `matches` crate. Change them to:

```rust
assert_eq!(rv, Err(Error::CrdtError(CrdtError::NoPeers)));
```

If you see something with an underscore in it, such as:

```rust
assert_matches!(addr_parse_error(), Err(Error::AddrParse(_)));
```

That's a correct use of the `matches` crate. No update needed there.

### PR DESCRIPTION
**Pull request by Atul9**
closes #1010

### CODE REVIEW

**Comment by garious** [comment]
That change made the lines shorter, so `cargo fmt` will shorten a bunch of code. Can you run it and add the patch to this PR?

```bash
$ rustup component add rustfmt-preview
$ cargo fmt
```

**Comment by Atul9** [comment]
@garious done. I have updated the PR

**Comment by garious** [comment]
And the modified source should compile. :)

Looks like PartialEq is missing from some error types. Here's an example of one that has it:

https://github.com/solana-labs/solana/blob/master/src/bank.rs#L38

You can add that to CrdtError to get those to compile. Adding it to the one in result.rs may not go as smoothly. If so, you'd need to either figure out why or revert those ones back to `assert_matches`.

**Comment by Atul9** [comment]
I checked - https://github.com/solana-labs/solana/blob/master/src/crdt.rs#L50
Its added to CrdtError. I have added it to Error enum in result.rs to check if it works.

**Comment by garious** [comment]
I'll sync locally and see what's going on

**Comment by garious** [comment]
So some standard library implementations of Error don't implement PartialEq (i.e. io::Error), so result::Error won't be able to implement it. To add to the problem, modules such as crdt.rs use result::Error for no particularly good reason.

I recommend bailing on this PR for now. A better "first issue" would be to knock out some of those unnecessary uses of result::Error (like `Crdt::new()`). Thanks so much for giving this a shot. Sorry it didn't go as planned!

**Comment by Atul9** [comment]
okay, can I close this PR? Can you update the issue / add another issue?

**Comment by garious** [comment]
Done, https://github.com/solana-labs/solana/issues/1033

**Pull request closed without merging**
