### PR TITLE
chore: condition generate test statistics

### PR DESCRIPTION
**Pull request by yihau**

### CODE REVIEW

**Comment by yihau** [comment]
I haven't found how to print origin output and JSON out at the same time so I used branchs to control the result as a temporary solution. for now, only the master will generate the test result. behaviors in PR, 1.10, 1.11 are the same as before.

**Review by CriesofCarrots — APPROVED** [review]
Thanks, this seems better, for now at least.
I do look at master branch job failures sometimes too, but could learn to go to analytics, if that's the way

**Comment by yihau** [comment]
oh! thank you!
yeah. I think we will add everyone to datadog soon 😈

**Comment by yihau** [comment]
pick this PR's features to #27591

**Pull request closed without merging**
