### PR TITLE
Feature: disable CPI setting `is_executable` and `rent_epoch`

### PR DESCRIPTION
**Pull request by Lichtso**
#### Problem
#19762 added `is_executable` and `rent_epoch` to be deserialized in CPI. These two fields however are not deserialized at the return edge of BPF programs.

#### Summary of Changes
Stop setting `is_executable` and `rent_epoch` in CPI after the newly added feature `disable_cpi_setting_executable_and_rent_epoch` is active.

Feature Gate Issue: #26988

### CODE REVIEW

**Review by jstarry — APPROVED** [review]

**Comment by jstarry** [comment]
> Removes TEST_EXECUTABLE_LAMPORTS

Actually, could you add tests that enforce the new behavior of ignoring changes to executable / rent_epoch?

**Review by jstarry — APPROVED** [review]

**Comment by Lichtso** [comment]
I already opened a feature gate issue: #26988

**Comment by jstarry** [comment]
Yes, I saw that. Why did you remove the label? The feature-gate label was intended to make it easy to search for PRs that created or modified a feature.

**Comment by Lichtso** [comment]
Oh, ok I thought it was only for the feature issues

**Pull request merged**
