### PR TITLE
Moar rolling upgrade

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

testing upgrade version test is hard and required local patches to be merged into stable and beta release channels
and supporting the combination of newer `net/*.sh` and older validator seems tedious and basically unmaintained.

#### Summary of Changes

basic idea is like this

1. git reset --hard `$HEAD_OF_STABLE_OR_WHATEVER_PR_ON_STABLE_BRANCH`
1. build locally
1. scp binaries
1. ./net/start.sh ...
1. git reset --hard `$HEAD_OF_BETA_OR_WHATEVER_PR_ON_STABLE_BRANCH`
1. build locally
1. scp binaries
1. ./net/start.sh ...

This is reboot of #9212 op top of #12337 . #9212 originally [closed without merging because building local version is supported without that pr](https://github.com/solana-labs/solana/pull/9212#issuecomment-607015733). But now we want to support to building multiple versions locally. So I think this justifies the need of this pr.

Fixes #

### CODE REVIEW

**Comment by ryoqun** [comment]
@t-nelson Yay, this worked nicely: https://buildkite.com/solana-labs/rolling-upgrade-tests/builds/113

with

```
CHANNEL=local
LOCAL_BUILD_BRANCH=pull/12387/head
UPGRADE_CHANNEL=local
UPGRADE_LOCAL_BUILD_BRANCH=v1.3
```

So, the rolling upgrade test passed only when #12387 applied.

**Comment by ryoqun** [comment]
> supporting the combination of newer `net/*.sh` and older validator seems tedious and basically unmaintained.

Well, this pr currently doesn't solve this part

**Comment by t-nelson** [comment]
Hey thanks for taking a stab at this.  I have a somewhat embarrassing hack to get similar.  We can actually avoid the local builds entirely, passing them off as optional buildkite jobs that store the release as artifacts.  Then testnet-automation can resolve and download the right builds at runtime

Gross script: https://github.com/t-nelson/solana/commit/b17c75dadcf8946c71e238284462d69ce7008b09

Buildkite:
Screen Shot 2020-09-22 at 10 39 03

**Comment by t-nelson** [comment]
> > supporting the combination of newer `net/*.sh` and older validator seems tedious and basically unmaintained.
> 
> Well, this pr currently doesn't solve this part

Hehe, true.  I believe this is one of our, perhaps unstated, devops goals, though.  We no intention of actually supporting features back to stable, just that the master/HEAD scripts executing on the stable/HEAD bins should work.  This mostly just means backporting hidden stubs so clap doesn't blow up when parsing the command line.

**Comment by ryoqun** [comment]
>  We can actually avoid the local builds entirely, passing them off as optional buildkite jobs that store the release as artifacts. ...

@t-nelson I see. Glad to see that you had similar one. Yeah, these're very similar. So, it seems that we can polish your separate buildkite job approach. Are you going to polish it at #12337? Alternatively, I can work on polishing it if you're busy with other things. :)

**Comment by t-nelson** [comment]
> @t-nelson I see. Glad to see that you had similar one. Yeah, these're very similar. So, it seems that we can polish your separate buildkite job approach. Are you going to polish it at #12337? Alternatively, I can work on polishing it if you're busy with other things. :)

I was hoping to get back to it after cleaning up the SPL Token CLI (probably EOW), but if you've got room on your plate, fee free to take over!  I'll consolidate my changes into the branch pointed at #12337 (and rip out the junk debugging commits).

**Pull request closed without merging**
