### PR TITLE
Add vote instruction count metrics

### PR DESCRIPTION
**Pull request by HaoranYi**
#### Problem

In https://github.com/solana-labs/solana/pull/24696, we removed the processed vote instruction counters because of spamming. 

However, it is useful to know how many vote instructions per second are processed by the validator. 

#### Summary of Changes

Add vote instruction counter metrics.

Fixes #

### CODE REVIEW

**Comment by HaoranYi** [comment]
image

We are processing about 3K vote programs per second.

**Comment by sakridge** [comment]
We may port this to BPF in the future, will this strategy work in a world where the program is a standard bpf program?

**Comment by HaoranYi** [comment]
> We may port this to BPF in the future, will this strategy work in a world where the program is a standard bpf program?

No, it won't work with a standard bpf program. But it will work for any other builtin programs. 

For standard bfp program, we could collect and report the matrix at a higher level in the call stack [here](https://github.com/solana-labs/solana/blob/daa2449ad4b4dc0cc83a4be1968653815e2e4a8c/program-runtime/src/message_processor.rs#L138).

**Comment by HaoranYi** [comment]
> lazy_static is not ideal also, but I can see the benefit of accumulating the counters closer to where we do the actual vote processing

Yes. Not ideal. I had thought about to attach the metrics to `invoke_context`. But it will affect all program execution. So I decided to keep it local and use `lazy_staic`.

**Comment by jeffwashington** [comment]
> lazy_static is not ideal also, but I can see the benefit of accumulating the counters closer to where we do the actual vote processing

What are the objections to `lazy_static` here?

**Comment by HaoranYi** [comment]
> > lazy_static is not ideal also, but I can see the benefit of accumulating the counters closer to where we do the actual vote processing
> 
> What are the objections to `lazy_static` here?

lazy_static is like global variable. And global varaible make code smells.

**Comment by sakridge** [comment]
I'm fine with the lazy_static, just wanted to make sure we considered all the options since as haoran said it's like a global variable and we should avoid it if possible. And it could give incorrect metrics within the same process if you had multiple validators running.

**Comment by jeffwashington** [comment]
> Yes, it won't give you vote instruction metrics for individual validators. But it can provide the aggregated vote metric all the validators.

I think it will 'give you vote instruction metrics for individual validators', as long as you aren't running multiple validators concurrently in the same process, right?

**Comment by jeffwashington** [comment]
@behzadnouri had mentioned these metrics would be useful to restore, I believe.

**Comment by willhickey** [comment]
This repository is no longer in use. Please re-open this pull request in the agave repo: https://github.com/anza-xyz/agave

**Pull request closed without merging**
