### PR TITLE
cargo generate-lockfile

### PR DESCRIPTION
**Pull request by mvines**
Run `cargo generate-lockfile` to update all the things at once

Nod to @leoluk who wanted to do this for v1.5 earlier today

### CODE REVIEW

**Comment by t-nelson** [comment]
Do we want to roll these dice on stable? `./scripts/cargo-for-all-lockfiles.sh tree` will resync the lockfile w/o updates. I'm probably the culprit here. I may have forgotten to bump the lock with the audit fix on Monday

**Comment by mvines** [comment]
> Do we want to roll these dice on stable? 

I guess I was thinking yes, for v1.6.   But I'm not thinking of backporting this PR to v1.5

**Comment by t-nelson** [comment]
> I guess I was thinking yes, for v1.6. But I'm not thinking of backporting this PR to v1.5

Got it!  Sorry, I misread the description :confused:

**Comment by leoluk** [comment]
I suppose running `./scripts/cargo-for-all-lockfiles.sh tree` would've been the right way to do #15371?

**Comment by t-nelson** [comment]
> I suppose running `./scripts/cargo-for-all-lockfiles.sh tree` would've been the right way to do #15371?

Yep!  The v1.5.9 version bump commit picked up the discrepancy though

**Comment by mvines** [comment]
Na, forget it

**Pull request closed without merging**
