### PR TITLE
v1.13: Admin RPC Service: move post-init activation to before wait-for-supermajority (backport of #30544)

### PR DESCRIPTION
**Pull request by fanatid**
Backport of https://github.com/solana-labs/solana/pull/30544 to v1.13

### CODE REVIEW

**Comment by steviez** [comment]
The backport itself looks fine / equivalent to the initial PR; however, there were some mixed thoughts about whether it was appropriate to backport this or not.

I'm leaning towards agreeing with @CriesofCarrots in wanting to [backport this](https://github.com/solana-labs/solana/pull/30544#issuecomment-1447532839), but @mvines was [against backporting at the time](https://github.com/solana-labs/solana/pull/30544#issuecomment-1448608094).

In typical situations, we'd also probably want a beta (v1.14) backport to before considering a stable (v1.13) backport, altho this change might be small enough to forego that.

**Comment by linuskendall** [comment]
This is pretty breaking for anyone using this tool for security reasons (to load privkeys) in case there would be a network restart.

**Comment by fanatid** [comment]
@steviez if it's required, I can create backport for v1.14 too :slightly_smiling_face:

**Comment by linuskendall** [comment]
> > This is pretty breaking for anyone using this tool for security reasons
> 
> To be clear, you mean the code/order of operations before this change is breaking, right @linuskendall ?
> 
> > In typical situations, we'd also probably want a beta (v1.14) backport to before considering a stable (v1.13) backport
> 
> Yes, we definitely need to backport to v1.14 before v1.13. In fact, I think v1.14 might be sufficient. Either way, let's start there @fanatid

Yea, before this change settings keys dynamically is pretty broken because it won't work during restarts of the network so it will lead to having to store the key material on disk/tmpfs specifically during a restart which creates a securty hazard (particularly at such a sensitive time as during a restart!).

**Comment by CriesofCarrots** [comment]
I don't feel strongly that this needs to be backported to v1.13 now. The time to do it was probably in v1.13.7
If we end up needing more v1.13 patches, I'll reassess.

**Pull request closed without merging**
