### PR TITLE
Rpc to return software version

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
No easy way to figure out what software version a testnet is running.
Versions may feature breaking changes, so a mismatch with an entrypoint node can cause unexpected errors for validators.

#### Summary of Changes
Adds getSoftwareVersion rpc that reports the solana-core version number of the compiled crate. I put the VERSION const in its own module because it didn't seem to sort anywhere else, but it could easily go in rpc.rs and be accessed locally if it seems like too much muss as is.

Toward #5435

### CODE REVIEW

**Comment by garious** [comment]
Can we call it "protocol-version" instead of "software-version"

**Comment by mvines** [comment]
Protocol version to me is different from the software version that implements a particular version of the protocol.   We don't even version the protocol right now (beyond baking it implicitly into the software version).

**Comment by garious** [comment]
Okay. How about validator-version then?

**Comment by garious** [comment]
Technically `core-version` is what's returned

**Comment by mvines** [comment]
How about a `getVersion` that returns:
```json
{
  "solana-core": "0.17.1",
}
```

This leaves us room for a "protocol" version or any other number of version fields

**Comment by CriesofCarrots** [comment]
I like `getVersion`. Will work better for the follow-up wallet command too (something like `compare-version`)

**Comment by garious** [comment]
Sounds good to me, thanks.

**Pull request merged**
