### PR TITLE
Change average TPS to max average tps seen for any node and...

### PR DESCRIPTION
**Pull request by sakridge**
add script to collect perf stats

### CODE REVIEW

**Comment by pgarg66** [comment]
Is input to perf-stats.py the output of bench-tps?

**Comment by sakridge** [comment]
@pgarg66 It will parse any input file with the "COUNTER:{..}" logs in it.

**Comment by garious** [comment]
tox and pytest are the cat's pajamas. Can you take a stab at adding pytest sanity check on those scripts and adding that to CI?

**Comment by garious** [comment]
For reference: https://github.com/codebom/codebom/blob/master/tox.ini

**Comment by sakridge** [comment]
@garious I filed an issue for it, it doesn't look that simple.

**Comment by garious** [comment]
How will I know if I can replace your `sum` function with the builtin?

https://docs.python.org/3/library/functions.html#sum

**Pull request merged**
