### PR TITLE
Cleanup old features

### PR DESCRIPTION
**Pull request by jackcmay**
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by jackcmay** [comment]
@mvines Cleaning up features older than 2 epochs, any objections?

**Comment by sakridge** [comment]
We won’t be able to replay old ledger

**Comment by mvines** [comment]
> We won’t be able to replay old ledger

We generally have this problem anyway.   When we archive ledger slices after a new epoch, we also record the solana version that was used so you can find the compatible release if needed

> Cleaning up features older than 2 epochs, any objections?

Nope

**Comment by jackcmay** [comment]
> We won’t be able to replay old ledger

@sakridge You good?

**Pull request merged**
