### PR TITLE
Remove move_loader and librapay

### PR DESCRIPTION
**Pull request by garious**
#### Problem

The Move build introduces dependency conflicts.

#### Summary of Changes

Remove it. If needed, it can be resurrected in the SPL repo.

### CODE REVIEW

**Comment by jackcmay** [comment]
Should we also remove mention of Libra Move from the doc's implemented-proposals?

**Comment by jackcmay** [comment]
Also need to remove `sdk/src/move_loader.rs` and related artifacts

**Comment by garious** [comment]
@jackcmay, looks like CI is about to pass. This look good to you?

**Comment by garious** [comment]
post-merge reviews welcome

**Comment by CriesofCarrots** [comment]
I'm excited about the 30min this cut off stable CI

**Pull request merged**
