### PR TITLE
Mark *.sh files with `#!` as executable

### PR DESCRIPTION
**Pull request by kevinji**
#### Problem
Not all *.sh flags had the `+x` bit set.

#### Summary of Changes
Ran `fd --extension sh` and ran `chmod a+x` on all files with a `#!` that weren't executable already.

### CODE REVIEW

**Review by mvines — CHANGES_REQUESTED** [review]
Not all .sh files in the repo are intended to be executable. A large number of them are libraries that one is expected to `source`

**Comment by kevinji** [comment]
@mvines Thanks for letting me know. I've updated the PR to only include the files with a shebang (`#!`) and excluded the files that specifically mention `source`ing.

**Review by mvines — APPROVED** [review]
I think this looks good to me. @yihau, can you please take a look as well?

**Review by yihau — APPROVED** [review]
These changes look harmless to me. However, I don't see why scripts with a shebang should be executable.

**Comment by kevinji** [comment]
The shebang is only used if the script is executed directly when it is marked executable. If the script is only indirectly called from another script, the shebang is just parsed as a comment, so it should probably be removed for clarity.

**Comment by yihau** [comment]
thank you for your contribution!

**Pull request merged**
