### PR TITLE
cli: get command now shows default values instead of 'not set'

### PR DESCRIPTION
**Pull request by mvines**
#### Old
```
$ solana get
Wallet Config: /Users/mvines/.config/solana/wallet/config.yml
* url: (not set)
* keypair: (not set)
```

#### New
```
$ solana get
Wallet Config: /Users/mvines/.config/solana/wallet/config.yml
* url: http://127.0.0.1:8899
* keypair: /Users/mvines/.config/solana/id.json
```

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
I dig, but do we want some indication that these are default values? (Potentially including the default Wallet Config path)
I would wonder where these values come from if I saw this populated, but don't have the config.yml file in question.

**Comment by mvines** [comment]
> I dig, but do we want some indication that these are default values? (Potentially including the default Wallet Config path)

I had a "(default)" indicator initially, but then concluded that I didn't actually care if it was default or not, so the extra indicator just felt like clutter.  Adding it is easy if you feel it adds some value though.

**Comment by CriesofCarrots** [comment]
> Adding it is easy if you feel it adds some value though.

I think it does. Just a little indication that it is something that can be configured. And I don't think it clutters things too much.

**Comment by mvines** [comment]
How about this?
```
$ solana get
Wallet Config: /Users/mvines/.config/solana/wallet/config.yml
* url: http://127.0.0.1:8899 (default)
* keypair: /Users/mvines/.config/solana/id.json (default)
```

**Comment by mvines** [comment]
test_snapshots_blocktree_floor...

**Pull request merged**
