### PR TITLE
Augment BPF binary dumps to resolve call instruction targets

### PR DESCRIPTION
**Pull request by dmakarov**
#### Problem

Disassembler dump of BPF binaries doesn't show symbolic names of call instruction targets

#### Summary of Changes

Added a script that parses a disassembler output and inserts symbolic names of call targets

Fixes #

For example, current disassembler output looks like this

```
00000000000070f0 <memcmp>
    3614	85 10 00 00 ff ff ff ff	call -0x1
    3615	95 00 00 00 00 00 00 00	exit
```

The updated script makes reading the disassembled code easier by changing the output to
```
00000000000070f0 <memcmp>
    3614	85 10 00 00 ff ff ff ff	call -0x1 ; sol_memcmp_
    3615	95 00 00 00 00 00 00 00	exit
```

### CODE REVIEW

**Review by jackcmay — COMMENTED** [review]
Very cool!

This adds a python dependency, do you know how broadly this code works across python versions?

**Comment by dmakarov** [comment]
I believe it works on python3. It doesn't use anything other than `re` package.

**Comment by mvines** [comment]
🙈 on that python dep, but we should turn this entire thing into a Rust program eventually

**Comment by dmakarov** [comment]
I guess I can rewrite dump in Rust. In current setup is there a way to use Rust for working with C/C++ programs?
Suppose `cargo build-bpf --bpf-sdk=../../../../sdk/bpf --dump` implemented entirely in Rust (no dump.sh) will it be available for using with binaries built from C/C++?

**Comment by jackcmay** [comment]
Are you thinking of linking in utility binaries built with c/c++, I haven't done that but you can probably create an extern interface for it and link it in?  If you wanted to issue a command instead (like calling readelf or objdump you can use rust's [Command](https://doc.rust-lang.org/std/process/struct.Command.html)

**Comment by dmakarov** [comment]
I think that if I move `dump.sh` functionality into cargo-build-bpf/src/main.rs, we'll have to keep dump.sh around for binaries that are built by clang toolchain, just like `install.sh` is needed for C/C++ toolchain install.

**Comment by jackcmay** [comment]
Could cargo-build-bpf link in the readelf and objdump utility libraries?

**Comment by dmakarov** [comment]
I don't know. But why, if it can invoke them as external commands?

**Comment by jackcmay** [comment]
Or call the linked utility library directly via FFI calls.

**Comment by dmakarov** [comment]
@jackcmay, @mvines, I reimplemented the python logic in Rust in `cargo-build-bpf/src/main.rs`, not touching `dump.sh` for now. Is this acceptable?

**Comment by Lichtso** [comment]
The mentioned RBPF CLI tool supports most of the use cases already (including tracing, resolving and demangling of function names). However, it is currently stand alone and should be integrated in this repo here, so that it can run the programs directly without the need to extract programs first and then feed in the data separately.

**Comment by jackcmay** [comment]
I'd like to see the rbpf cli tool rolled into our solana or bpf tools releases, it's not very accessible to developers where it lives now.

**Comment by dmakarov** [comment]
Not sure where this discussion will end, but for now is it ok to merge? I'd really like to have call symbols in the disasm dump.

**Review by mvines — APPROVED** [review]

**Comment by Lichtso** [comment]
Yes, go ahead. However, we should not spend to much time improving it as it will be rendered obsolete as soon as we integrate the RBPF CLI tool here.

**Review by jackcmay — APPROVED** [review]

**Comment by dmakarov** [comment]
Some ideas for rbpf cli. I have a script that post process an RBPF trace, and indents control flow, so it's more visual where control transferred to a callee and returns. I also found it useful to see which memory locations were written and what data was stored (a poor-man's debugger). When control enters a new function or returns from it, I dump the addresses and values of store insns seen so far. This really helps to debug a trace. Here's a fragment of my postprocessed trace, with several register values removed from each line for shortening the lines here

```
        0 [0000000000000000, 0000000200001000, 000000000000004A]   103: lddw r1, 0x101010101010101
        1 [0000000000000000, 0000000200001000, 000000000000004C]   105: stxdw [r10+0xfd58], r1
        2 [0000000000000000, 0000000200001000, 000000000000004D]   106: stxh [r10+0xfd68], r1
        3 [0000000000000000, 0000000200001000, 000000000000004E]   107: stxdw [r10+0xfd60], r1
        4 [0000000000000000, 0000000200001000, 000000000000004F]   108: mov64 r6, 0x0
        5 [0000000000000000, 0000000200001000, 0000000000000050]   109: stxb [r10+0xfd58], r6
        6 [0000000000000000, 0000000200001000, 0000000000000051]   110: stxb [r10+0xfd7f], r6
        7 [0000000000000000, 0000000200001000, 0000000000000052]   111: mov64 r3, r10
        8 [0000000000000000, 0000000200001000, 0000000000000053]   112: add64 r3, 0xfffffd7f
        9 [0000000000000000, 0000000200001000, 0000000000000054]   113: stxdw [r10+0xfd70], r3
       10 [0000000000000000, 0000000200001000, 0000000000000055]   114: mov64 r1, 0x1
       11 [0000000000000000, 0000000200001000, 0000000000000056]   115: stxdw [r10+0xff28], r1
       12 [0000000000000000, 0000000200001000, 0000000000000057]   116: mov64 r1, r10
       13 [0000000000000000, 0000000200001000, 0000000000000058]   117: add64 r1, 0xfffffd58
       14 [0000000000000000, 0000000200001000, 0000000000000059]   118: stxdw [r10+0xff20], r1
       15 [0000000000000000, 0000000200001000, 000000000000005A]   119: mov64 r2, 0x1
       16 [0000000000000000, 0000000200001000, 000000000000005B]   120: mov64 r4, 0x1
                                200010D58: 0
                                200010D60: 101010101010101
                                200010D7F: 0
                                200010D70: 200000d7f
                                200010F28: 1
                                200010F20: 200000d58
       17 [0000000000000000, 0000000200001000, 000000000000005C]   121: call <core::slice::cmp::<impl core::cmp::PartialEq<[B]> for [A]>::eq>
       18 [0000000000000000, 0000000200003000, 0000000000000000]    29:   mov64 r5, r2
       19 [0000000000000000, 0000000200003000, 0000000000000001]    30:   mov64 r0, 0x0
       20 [0000000000000000, 0000000200003000, 0000000000000002]    31:   jne r5, r4, +9
       21 [0000000000000000, 0000000200003000, 0000000000000003]    32:   mov64 r0, 0x1
       22 [0000000000000000, 0000000200003000, 0000000000000004]    33:   jeq r1, r3, +7
       23 [0000000000000000, 0000000200003000, 0000000000000005]    34:   mov64 r2, r3
       24 [0000000000000000, 0000000200003000, 0000000000000006]    35:   mov64 r3, r5
       25 [0000000000000000, 0000000200003000, 0000000000000007]    36:   call <memcmp>
       26 [0000000000000000, 0000000200005000, 00000000000017A8]  6085:     mov64 r0, 0x0
       27 [0000000000000000, 0000000200005000, 00000000000017A9]  6086:     mov64 r4, r3
       28 [0000000000000000, 0000000200005000, 00000000000017AA]  6087:     add64 r4, 0x7
       29 [0000000000000000, 0000000200005000, 00000000000017AB]  6088:     mov64 r6, 0xf
       30 [0000000000000000, 0000000200005000, 00000000000017AC]  6089:     mov64 r5, 0x0
       31 [0000000000000000, 0000000200005000, 00000000000017AD]  6090:     jgt r6, r4, +23
       32 [0000000000000000, 0000000200005000, 00000000000017C5]  6114:     jsge r5, r3, +13
       33 [0000000000000000, 0000000200005000, 00000000000017C6]  6115:     add64 r1, r5
       34 [0000000000000000, 0000000200005000, 00000000000017C7]  6116:     add64 r2, r5
       35 [0000000000000000, 0000000200005000, 00000000000017C8]  6117:     sub64 r3, r5
       36 [0000000000000000, 0000000200005000, 00000000000017C9]  6118:     ja +0x4
       37 [0000000000000000, 0000000200005000, 00000000000017CE]  6123:     ldxb r4, [r2+0x0]
       38 [0000000000000000, 0000000200005000, 00000000000017CF]  6124:     ldxb r5, [r1+0x0]
       39 [0000000000000000, 0000000200005000, 00000000000017D0]  6125:     jeq r5, r4, -7
       40 [0000000000000000, 0000000200005000, 00000000000017CA]  6119:     add64 r1, 0x1
       41 [0000000000000000, 0000000200005000, 00000000000017CB]  6120:     add64 r2, 0x1
       42 [0000000000000000, 0000000200005000, 00000000000017CC]  6121:     add64 r3, 0xffffffff
       43 [0000000000000000, 0000000200005000, 00000000000017CD]  6122:     jeq r3, 0x0, +5
       44 [0000000000000000, 0000000200005000, 00000000000017D3]  6128:     exit
       45 [0000000000000000, 0000000200003000, 0000000000000008]    37:   mov64 r1, r0
       46 [0000000000000000, 0000000200003000, 0000000000000009]    38:   mov64 r0, 0x1
       47 [0000000000000000, 0000000200003000, 000000000000000A]    39:   jeq r1, 0x0, +1
       48 [0000000000000000, 0000000200003000, 000000000000000C]    41:   and64 r0, 0x1
       49 [0000000000000000, 0000000200003000, 000000000000000D]    42:   exit
       50 [0000000000000000, 0000000200001000, 000000000000005D]   122: jeq r0, 0x0, +546
````

**Pull request merged**
