### PR TITLE
Remove runtime dependency from config program unit tests and move back to config program

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

Config tests had an unnecessary dependency on `runtime` which created a circular dependency if the config tests weren't in their own package.

#### Summary of Changes

Remove `runtime` dependency and move unit tests back to the config program

One of three parts of #7263

Fixes #

### CODE REVIEW

**Comment by garious** [comment]
This deletes good integration tests. Is there some way you can break the cycle by removing the runtime dependency on config instead? Factoring out the stake/vote/stroage dependencies is also needed to get the runtime out of this git repo and call it sealevel.  Ideally, each program would depend on the sdk (which could be renamed `solana-program`) and its integration tests could depend on the runtime (which could be renamed to `sealevel-runtime`).

**Comment by jackcmay** [comment]
What part of the original config tests were good integration tests?

**Comment by jackcmay** [comment]
This is also one of many steps to extract the programs out

**Comment by garious** [comment]
at least `test_config_initialize_no_panic`

**Comment by garious** [comment]
You're breaking the loop by dropping the dependency from a program's test suite to the runtime, but that's an acceptable (and even preferred) dependency. `BankClient` tests represent the lowest level code that looks like user-level `RpcClient` usage.  Deleting that is effectively deleting executable usage documentation.

**Comment by jackcmay** [comment]
At best that test was already in the wrong place, at worst runtime doesn't already have an equivalent.  I'll check if runtime does or not and add one if not.

**Comment by garious** [comment]
It's not a runtime test.  Every program needs at least a unit test (not necessarily an integration test) for that particular case. It ensures the program isn't blindly indexing accounts.

As it relates to my previous comment, that's not the test that justifies a runtime/BankClient dependency. It's any sunny day integration test that demonstrates how to use the program.

**Comment by jackcmay** [comment]
> You're breaking the loop by dropping the dependency from a program's test suite to the runtime, but that's an acceptable (and even preferred) dependency. `BankClient` tests represent the lowest level code that looks like user-level `RpcClient` usage. Deleting that is effectively deleting executable usage documentation.

Config usage is still documented, just not with bank_client, but bank_client's should not be required to document Config program's behaviors.

**Comment by jackcmay** [comment]
I added back `test_config_initialize_no_panic`

**Pull request merged**
