### PR TITLE
proposal: private p2p network doc draft

### PR DESCRIPTION
**Pull request by jbiseda**
#### Problem
Need design for private P2P networks.

#### Summary of Changes
Draft doc to outline high level concept, goals. More details TBD.

Fixes #

### CODE REVIEW

**Review by t-nelson — COMMENTED** [review]
great start! can you wrap lines at ~80char to ease future review?

**Comment by jbiseda** [comment]
> > These unstaked nodes consume cluster resources by
> > directly connecting to the pubilc cluster without participating in
> > voting.
> 
> is that the main thing this thing is solving? What are the resources that these nodes are consuming? does turbine take more work per RPC node? or gossip? by how much?

I don't think RPC nodes consume more resources. The main goal is to reduce the number of nodes directly connected to the cluster. @t-nelson is there an additional motivation for this?

**Comment by t-nelson** [comment]
it's less about the resources that they consume and more about their lack of contribution back to the cluster.  being as they're unstaked and therefore low candidates to receive repair and gossip requests.  any additional resources that they consume would likely be due to their populating the lowest layer of the turbine tree and more likely to fall victim to path failure and need to repair.  these repair requests then of course go to higher staked nodes

**Review by sowhu — COMMENTED** [review]
I have a couple questions.
1. In Would be the guestway-p2p-1_1 and gateway-pip-1_m act the same to the other nodes in the Private P2P Network 1, ie, forwarding the same packets to other nodes in the P2P network? Or they are responsible for forwarding packets to different nodes in the same network?
2.  How does a private p2p network join? Let's say we have a new private P2P network X which contains multiple private nodes. It can look for a gateway node which is already announced itself. However, to make the public existing gateway node to understand network topology of this new private network doesn't seem to bey easy.

**Comment by jbiseda** [comment]
Closing this. See discussion discord #proj-private.

**Pull request closed without merging**
