### PR TITLE
Upgrade to Rust 1.43.0

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by mvines** [comment]
@jackcmay - could you please take a look at this build error with 1.43.0, it's in the xargo goo that you're the most familiar with:
```
error: the `-Z unstable-options` flag must also be passed to enable `--extern crate_name` without `=path`
```

STR:
1. `cargo +1.43.0 test --manifest-path programs/bpf/Cargo.toml     --no-default-features --features=bpf_c,bpf_rust --verbose -- --nocapture`

**Comment by jackcmay** [comment]
@mvines I can recreate locally, I'll dig into it

**Comment by jackcmay** [comment]
@mvines, I have a fix, just need this to land first:
https://github.com/solana-labs/solana/pull/9781

**Comment by mvines** [comment]
Sweet

**Comment by mvines** [comment]
@mergifyio rebase

**Comment by jackcmay** [comment]
The following PR fixes the CI issue seen in this PR
https://github.com/solana-labs/solana/pull/9783

**Comment by mvines** [comment]
@Mergifyio rebase

**Comment by mvines** [comment]
ok thank you so much but can you stop now @mergifyio?

**Comment by jackcmay** [comment]
@mvines v1.0 and v1.1 will probably also need the rust-bpf bump and possibly related cache fix

**Comment by mvines** [comment]
> @mvines v1.0 and v1.1 will probably also need the rust-bpf bump and possibly related cache fix

yeah I was thinking that.  Can you backport those too?

**Comment by mvines** [comment]
Ok here we go!

**Pull request merged**
