### PR TITLE
docs: Add versioned tx info to exchange integration guide

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
Lack of info on how exchanges need to handle versioned transactions while doing deposit detection.

#### Summary of Changes
- Add migration section to the docs explaining additional parameters needed to properly support versioned transactions
- Update RPC example requests with additional required parameters

Fixes #

### CODE REVIEW

**Comment by yihau** [comment]
do we would like to provide an extra example for v0 transaction? or we can do more detail thing on cookbook?

**Comment by jstarry** [comment]
> do we would like to provide an extra example for v0 transaction? or we can do more detail thing on cookbook?

Sure, what type of extra example do you mean?

**Comment by yihau** [comment]
oh yeah. I mean maybe we could give them another tx which used address lookup table. like:

<details>
  <summary>request</summary>

```
curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getTransaction",
    "params": [
      "4Cswku8E9sm8TVZ4kP4iHbwCQygMDx78SXSURBkJuJAaXCbL9eYM8RPS2BDooLd5ftML4JjQrohe4deJrFkVzPBa",
      {"encoding": "jsonParsed", "maxSupportedTransactionVersion": 0}
    ]
  }
'
```
</details>

<details>
  <summary>response</summary>

```
{
  "jsonrpc": "2.0",
  "result": {
    "blockTime": 1660763773,
    "meta": {
      "err": null,
      "fee": 5000,
      "innerInstructions": [],
      "loadedAddresses": {
        "readonly": [],
        "writable": [
          "2xNweLHLqrbx4zo1waDvgWJHgsUpPj8Y8icbAFeR4a8i"
        ]
      },
      "logMessages": [
        "Program 11111111111111111111111111111111 invoke [1]",
        "Program 11111111111111111111111111111111 success"
      ],
      "postBalances": [
        2078778739,
        1,
        26396753106
      ],
      "postTokenBalances": [],
      "preBalances": [
        2078783740,
        1,
        26396753105
      ],
      "preTokenBalances": [],
      "rewards": [],
      "status": {
        "Ok": null
      }
    },
    "slot": 155713260,
    "transaction": {
      "message": {
        "accountKeys": [
          {
            "pubkey": "9aE476sH92Vz7DMPyq5WLPkrKWivxeuTKEFKd2sZZcde",
            "signer": true,
            "writable": true
          },
          {
            "pubkey": "11111111111111111111111111111111",
            "signer": false,
            "writable": false
          }
        ],
        "addressTableLookups": [
          {
            "accountKey": "3LZbwptsCkv5R5uu1GNZKiX9SoC6egNG8NXg9zH5ZVM9",
            "readonlyIndexes": [],
            "writableIndexes": [
              1
            ]
          }
        ],
        "instructions": [
          {
            "parsed": {
              "info": {
                "destination": "2xNweLHLqrbx4zo1waDvgWJHgsUpPj8Y8icbAFeR4a8i",
                "lamports": 1,
                "source": "9aE476sH92Vz7DMPyq5WLPkrKWivxeuTKEFKd2sZZcde"
              },
              "type": "transfer"
            },
            "program": "system",
            "programId": "11111111111111111111111111111111"
          }
        ],
        "recentBlockhash": "9nLh3gmVhyjrh68UeV1rafyo8BFNyZtHSRUUjZYikveh"
      },
      "signatures": [
        "4Cswku8E9sm8TVZ4kP4iHbwCQygMDx78SXSURBkJuJAaXCbL9eYM8RPS2BDooLd5ftML4JjQrohe4deJrFkVzPBa"
      ]
    },
    "version": 0
  },
  "id": 1
}
```
</details>

**Comment by willhickey** [comment]
Updated label to v1.14 which is effectively the new v1.11 See discussion on Discord in #releng and #proj-quic-tpu for more context.
https://discord.com/channels/428295358100013066/910937142182682656/1019051275318476881

**Pull request merged**
