### PR TITLE
Use SSD for perf testnet

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
The standard hard drive is not providing enough read/write throughput for database backed ledger/window.
 
#### Summary of Changes
Switch to SSD

Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
Should we add this flag to https://github.com/solana-labs/solana/blob/master/ci/testnet-automation.sh#L26-L30 as well?

**Comment by pgarg66** [comment]
That's true. I'll add it there as well. Thanks!

**Comment by pgarg66** [comment]
There's a slight problem, though. Our current quota won't let 100 nodes have an SSD.

**Comment by mvines** [comment]
Ask for more!

**Comment by pgarg66** [comment]
Yes, last time they gave me hard time for this much SSD quota as well :)
If I change it right now, without getting more quota, testnet automation will fail everytime.

**Comment by mvines** [comment]
nbd, we can do that later

**Pull request merged**
