### PR TITLE
Explorer: add candy machine v2 to known program addresses

### PR DESCRIPTION
**Pull request by ngundotra**
#### Problem

Candy Machine V2 program ID not searchable on explorer

#### Summary of Changes

Add CMv2 program Id to all clusters

Fixes #

### CODE REVIEW

**Comment by ngundotra** [comment]
CI build is timing out, but it actually builds

**Comment by jstarry** [comment]
Why is your pr so large for a simple change?

**Comment by t-nelson** [comment]
> Why is your pr so large for a simple change?

bad gitfu. looks like they rammed a couple bad rebases in.  just the top commit looks fine

**Comment by ngundotra** [comment]
apologies, will redo.

**Comment by t-nelson** [comment]
you don't need to open a new PR, just force push to your branch after you've fixed it to overwrite history

**Comment by ngundotra** [comment]
@t-nelson it was just way easier to create new PR (https://github.com/solana-labs/solana/pull/24072)

**Comment by jstarry** [comment]
> @t-nelson it was just way easier to create new PR (#24072)

If you know how to use force push, it's the easiest way. Please learn how to use it and do it next time to avoid PR spam

**Comment by ngundotra** [comment]
Will do, thanks @jstarry

**Pull request closed without merging**
