### PR TITLE
Clean up wallet URL paths

### PR DESCRIPTION
**Pull request by danpaul000**
#### Problem
Wallet doc URLs are 🤢 

#### Summary of Changes
Make them better

### CODE REVIEW

**Comment by danpaul000** [comment]
I think `wallet-guide` is the cleanest for the top level, then plurals all the way down below this.

**Comment by danpaul000** [comment]
Thinking about this, I'd rather not break every link we ever sent out that goes to `docs.solana.com/wallet` .. maybe we can put a redirect at that URL to `docs.solana.com/wallet-guide` when this lands.

**Comment by garious** [comment]
Yeah, big +1 on the redirect

**Comment by danpaul000** [comment]
@garious perhaps a little clunky looking but it seems relatively straightforward to edit the .gitbook.yaml to add redirects.  For any user-entered URL, give it the .md it should land on.  I put a redirect for each sub page in the wallet section, as we are breaking all existing links here.

**Pull request merged**
