### PR TITLE
Add design for vote signing

### PR DESCRIPTION
**Pull request by aeyakovenko**
#### Problem

Vote signing configuration is not clear.  The book should separate out what is currently implemented, proposed for the immediate future, and long term future plans.

#### Summary of Changes

WIP, adding sections.

Fixes #

tag: @garious @pgarg66 would love some early feedback and help identifying what is in done, scheduled, and future work.

### CODE REVIEW

**Comment by garious** [comment]
Awesome! I was going to do this myself as soon as I finished up my VoteProgram PR. Keep running with this and I'll check back in a bit later and see if we can get this all synced up with the implementation.

**Comment by garious** [comment]
So there's also a keypair used for signing messages in ClusterInfo and StorageStage. Currently, its `keypair.pubkey()` is used in leader rotation, but instead we should rotate with the staking account's pubkey, right?

**Comment by aeyakovenko** [comment]
> So there's also a keypair used for signing messages in ClusterInfo and StorageStage. Currently, its `keypair.pubkey()` is used in leader rotation, but instead we should rotate with the staking account's pubkey, right? That is, it's really the staker that's authorized to produce the next block, not the validator node.

I was thinking that the stake weight that is authorized to the validators key is what we use.  So a stake owner just sets "authorized validator key" and that is it.  The validator just needs to include that key in its transaction while its voting along with any other staking keys that may have been delegated to it.

When the accounts are scanned you can compute the size of the delegated stakes to all the current validators.

**Comment by aeyakovenko** [comment]
@garious, and validators don’t need special accounts.  They just need to be set by the stake owner

**Comment by garious** [comment]
Yep, I agree. I think that's the mistake in the current implementation that caused so much copypasta.  The leader scheduler queries for `VoteProgram` accounts, which contain a `node_id`. The tokens in that `node_id` account are what's used for stake weight. As a result of that decision, every test that creates a fullnode first transfers tokens into both the [insecure] `node_id` account for staking and the [secure] `VoteProgram` account for voting. Instead, the `VoteProgram` should hold the stake, and therefore the `node_id` account doesn't need to exist.

**Pull request merged**
