### PR TITLE
remove repetitive words

### PR DESCRIPTION
**Pull request by gcmutator**
remove repetitive words

### CODE REVIEW

**Review by steviez — APPROVED** [review]
Thanks for the contribution - these are all comments so gonna skip CI

**Comment by CriesofCarrots** [comment]
@steviez , this is on the solana repo. I left it to ask why it wasn't closed automatically.

**Comment by steviez** [comment]
@CriesofCarrots - Shoot, you're right; had a lapse and completely missed this being the old repo.

@gcmutator - Apologies; this repo is not being maintained; we have some automation that has failed us that should have automatically closed your PR and given you a note. The TLDR is this repo shouldn't be accepting any new pull requests; however, I'd be happy to take a look if you make a similar PR over at https://github.com/anza-xyz/agave

**Comment by yihau** [comment]
@willhickey do you have any idea? I think the pipeline was working correctly when we merged it 🤔

**Comment by steviez** [comment]
> @willhickey do you have any idea? I think the pipeline was working correctly when we merged it 🤔

```
Run gh pr close "$PR_NUMBER" --comment "$COMMENT"
  gh pr close "$PR_NUMBER" --comment "$COMMENT"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    PR_NUMBER: 35436
    GH_TOKEN: ***
    GH_REPO: solana-labs/solana
    COMMENT: This repository is no longer in use. Please re-open this pull request in the agave repo: https://github.com/anza-xyz/agave
  
GraphQL: Resource not accessible by integration (addComment)
```
I got this on my new PR that I just opened. Talking with Tyera, this might have gotten through since I was being "smart" and didn't run CI since it was only comment changes. And since this person is a new contributor, CI didn't run automatically

**Pull request merged**
