### PR TITLE
Sanitize zero lamport accounts in append vecs

### PR DESCRIPTION
**Pull request by ryoqun**
~~(this hampers TdS snapshot restore as it contain some now-illegalized account data; I'm planning to fix it against the live TdS cluster)~~ (fixed that)

#### Problem

Snapshot can contain any state for 0 lamport accounts, which can be exposed to the runtime. And cause cluster forks like did #8590.

#### Summary of Changes

Like #8657, which normalized the account state when saving, this pr does sanitize the account state when restored from snapshot.

Part of #7167

### CODE REVIEW

**Comment by mvines** [comment]
> (this hampers TdS snapshot restore as it contain some now-illegalized account data; I'm planning to fix it against the live TdS cluster)

@ryoqun - did you observe a problem with the current TdS cluster here?

**Comment by ryoqun** [comment]
> > (this hampers TdS snapshot restore as it contain some now-illegalized account data; I'm planning to fix it against the live TdS cluster)
> 
> @ryoqun - did you observe a problem with the current TdS cluster here?

@mvines Yeah, that's because TdS cluster still holds ill-state zero lamport accounts before we had #8657.. I'm purging it by `solana pay` now..

**Comment by ryoqun** [comment]
The bad ones are like this (Note that `rent_epoch`...):

```
[runtime/src/append_vec.rs:99] ("bad", self.meta.pubkey, self.clone_account()) = (
    "bad",
    5pxapmiZ6CcePZU4cGVb6nHynhXzMXhDUBgvP9CPgpJJ,
    Account { lamports: 0 data.len: 0 owner: 11111111111111111111111111111111 executable: false rent_epoch: 18 hash: 11111111111111111111111111111111 },
)
[runtime/src/append_vec.rs:296] self = AppendVec {
    path: "/home/ryoqun/work/solana/solana/check4/accounts/2017204.7486295",
    map: MmapMut {
        ptr: 0x00007f4a7cc00000,
        len: 4194304,
    },  
    append_offset: Mutex {
        data: 191944,
    },  
    current_len: 191944,
    file_size: 4194304,
}   
[runtime/src/append_vec.rs:99] ("bad", self.meta.pubkey, self.clone_account()) = (
    "bad",
    3Z5XVczCTXeYeFABoeFm1LngC9657kZMVGNFzqFXviHb,
    Account { lamports: 0 data.len: 0 owner: 11111111111111111111111111111111 executable: false rent_epoch: 14 hash: 11111111111111111111111111111111 },
)   
[runtime/src/append_vec.rs:296] self = AppendVec {
    path: "/home/ryoqun/work/solana/solana/check4/accounts/290195.1111884",
    map: MmapMut {
        ptr: 0x00007f4a59400000,
        len: 4194304,
    },  
    append_offset: Mutex {
        data: 51318,
    },  
    current_len: 51318,
    file_size: 4194304,
}   

```

**Comment by ryoqun** [comment]
> > > (this hampers TdS snapshot restore as it contain some now-illegalized account data; I'm planning to fix it against the live TdS cluster)
> > 
> > 
> > @ryoqun - did you observe a problem with the current TdS cluster here?
> 
> @mvines Yeah, that's because TdS cluster still holds ill-state zero lamport accounts before we had #8657.. I'm purging it by `solana pay` now..

Now, I've fixed all those!

@sakridge Prime time for review!

**Pull request merged**
