### PR TITLE
Pass the correct program_id to programs

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

Loader's are passed the program_id of the program they are loading and not their own in opposition to this documentation:

https://github.com/solana-labs/solana/blob/b85d7c1f70f317717e6f94ad58da334733b38099/sdk/src/entrypoint.rs#L19

#### Summary of Changes

Pass the program id of the currently running program to the program

Fixes #

### CODE REVIEW

**Comment by jackcmay** [comment]
@garious 👀 
Is this also your understanding that ALL programs should be passed their own program_id?

**Comment by garious** [comment]
@jackcmay, the program should be passed the `program_id` in the transaction's `Instruction`.  The purpose of the parameter is to allow the same program to support multiple program IDs.  It's something that @aeyakovenko added in the earliest days. I'm not sure anything uses the feature yet.  I think the idea was that some program IDs might all map to the same underlying interpreter (i.e. the Lua or Move interpreter), and the interpreter would maintain its own map from program ID to internal program.

**Comment by jackcmay** [comment]
@garious Interesting, I'm not sure if any of that jives with the current implementation.  For example, before the changes in this PR the BPFLoader was passed the program_id of the program it is being asked to run but that is also available via keyed_account[0] which is the direct result of the program_id in the instruction, seems redundant and doesn't appear conducive to the intent you outlined above.  The changes in this PR seems to more closely match the intent, in that the program ID associated with the program rather than the downstream final program ID is passed to the program.  One other interesting thing is if programs aren't passed their own program ID then they don't know how to determine if they are the owner of accounts passed to them.

@garious @aeyakovenko Is there a proposal that outlines the requirements of program_id?  If not a more detailed description or concrete example of its usage would help.

**Comment by garious** [comment]
I think you're right. Here's how I reason through it with the concrete example of one program with one loader:

Given:
    * `Instruction {program_id: FOO, ..}`
    * `KeyedAccount {key: FOO, account: Account {owner: BPF_LOADER}}`

`process_instruction()` aims to deconstruct `Instruction`. It's parts are `program_id`, `accounts` and `data`.  However, `program_id` has already been used to load `BPF_LOADER`. At that time, the runtime shifts `program_id` into `accounts[0]`. Thus, if the role of the runtime it to provide the program with all available context, it must pass `BPF_LOADER` as the `program_id`, not `FOO`.

And in that way, the purpose of `program_id` is simply to allow the same code to be uploaded to multiple program IDs, and that code can behave differently, depending on the program used to invoke it.

Agreed, this information really needs a home in the docs. I'll file an issue.

**Comment by jackcmay** [comment]
@jstarry If @garious approves I'll merge this PR but would love any feedback you might have as well

**Pull request merged**
