### PR TITLE
Fix syntax for sed inline edit of .toml files

### PR DESCRIPTION
**Pull request by danpaul000**
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by danpaul000** [comment]
Increment version script for the Cargo.toml files had invalid "sed -i" syntax.  Not sure how this was running in the past.  sed -i requires [backup file extn] [files], not just [files].

**Comment by rob-solana** [comment]
my reading of `man sed` indicates that a backup SUFFIX is an optional parameter, which is why this code is working just fine

**Comment by rob-solana** [comment]
further:
```bash
[rwalker@nom-de-plume solana]$ sed -e 's/foo/workspace/' -i '' Cargo.toml
sed: can't read : No such file or directory
```

**Comment by danpaul000** [comment]
I realized after submitting this that the change is in the version of bash I was using.  My new Macbook shipped with 3.2.57(1)-release, but others are on a newer version of bash (4.x) which supports the suffix as optional, whereas it was mandatory in my shell.

**Comment by rob-solana** [comment]
bash?  I thought we were talking about sed...  what version of sed do you have?

we moved on to bash 4.x via brew (or whatever) a good while ago

**Comment by rob-solana** [comment]
I just checked my Mac.  I can only get sed as "gsed" via brew.  I think your change might be the right thing, Dan.  I figure Mike never tried these scripts on a Mac.

**Comment by rob-solana** [comment]
make it work on a Linux box first ;)

**Comment by rob-solana** [comment]
How about `-i~` ?  It will:
satisfy MacOS sed
satisfy Gnu sed
run under the radar of our .gitgnore

**Comment by danpaul000** [comment]
Sure thing.  I'm just onboarding so don't yet have all the same toolchains or VMs that the rest of the team has been using.

**Comment by mvines** [comment]
@danpaul000 - can we close this and/or get it landed?

**Comment by danpaul000** [comment]
GNU sed on Linux and sed on Mac seem to have incompatible syntax for the issue at hand.  Plus it runs way faster on my linux VM, so going to leave it as it has been.

**Pull request closed without merging**
