### PR TITLE
Upgrade to rust 1.39.0

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by garious** [comment]
I expect you'll be blocked by the upcoming rocksdb release https://github.com/rust-rocksdb/rust-rocksdb/pull/351

**Comment by mvines** [comment]
Yeah I did see some rockdb compile errors fly by.   There's some clippy that needs to be dealt with too.  I didn't try very hard yet, I posted this PR early so that other eager upgraders spot it and build on it instead of duplicating

**Comment by mvines** [comment]
cc: #6952

**Comment by mvines** [comment]
> test test_exchange_local_cluster ... test test_exchange_local_cluster has been running for over 60 seconds

I've seen this too much recently, almost time to ignore...

**Pull request merged**
