### PR TITLE
Make borsh 0.9 dependency optional

### PR DESCRIPTION
**Pull request by mina86**
Introduce borsh0-9 feature which determines whether the borsh 0.9
dependency is used and borsh0_9 module provided.

The dependency is enabled by default but still this commit is
technically a breaking change for anyone using solana-program
dependency with default features enabled.

### CODE REVIEW

**Comment by joncinque** [comment]
Thanks for your contribution! What's the motivation for this change? Crate features can create annoyance for downstream users through multiple recompilations or unclear compilation, so unless there's a good reason to remove this dependency, I prefer to keep it as it is.

**Comment by mina86** [comment]
Not having multiple versions of the same crate which creates annoyance by conflicting with `multiple-versions = "deny"`.

**Comment by joncinque** [comment]
In this case, we intend to have multiple versions, whereas the lint is typically to help avoid multiple versions when you *don't* want that.

I can appreciate the increased compilation time, but I don't think it's currently worth the potential annoyance of dealing with a feature. We're tentatively planning on cutting a new major version sometime in the next 12 months, so we can totally drop support at that point.

If we get a lot of feedback asking for this feature, however, we can certainly reverse course.

**Comment by mina86** [comment]
> whereas the lint is typically to help avoid multiple versions when
> you don't want that.

Yes, I, as a downstream user, don’t want multiple versions and
solana-program makes it impossible to enforce.

> I can appreciate the increased compilation time, but I don't think
> it's currently worth the potential annoyance of dealing with
> a feature.

I’ve only mentioned compilation time because you put forth multiple
recompilations as an argument against the feature.

Meanwhile, now with the feature enabled by default, the annoyance of
the feature should be barely perceivable by anyone.

**Pull request closed without merging**
