### PR TITLE
add retry for flakey local cluster test

### PR DESCRIPTION
**Pull request by HaoranYi**
#### Problem

https://github.com/solana-labs/solana/issues/29221

local_cluster_flakey tests failed from time to time. And usually a manual retry (or a few) will likely to pass the test. It, therefore, is good to let the test retry by itself.

#### Summary of Changes

Add retry for flakey local cluster test

Fixes #

### CODE REVIEW

**Comment by steviez** [comment]
Do. we know why this test is flaky to start with? The retry mechanism would likely get us to be able to consistently pass (assuming the failure rate is low enough) the test, but wondering if we should try to address the underlying issue instead

**Comment by HaoranYi** [comment]
There is a race between restore from the persisted tower and voting. When
voting happened before restoring persisted tower, we will still see
different vote, which panics. Adding retry will tolerate such race. That's
my understanding.

In other words, without persisted tower, no matter how many times we retry,
the test will continue fail. With retry, we will significantly, if not
completely, get rid of the chance of failure.

If we see failure after retry, we will be more sure that something is
broken. Unlike, currently, when this test fails, we are less sure if
something is broken.

**Comment by AshwinSekar** [comment]
I think it's fine as a stop gap but I'll look into making this more reliable

**Comment by steviez** [comment]
> I think it's fine as a stop gap but I'll look into making this more reliable

Gotcha; you're more familiar in this area so I'm good deferring to you. However, I think we should keep the issue that this PR states it fixes open to track the work of making the test more reliable without the retry mechanism

**Comment by HaoranYi** [comment]
Sounds good. Merged. And I keep the issue open and assigned it to @AshwinSekar .

**Pull request merged**
