### PR TITLE
Add jsonParsed option for EncodedTransactions; add memo parser

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
We need an easy way for users to view SPL Token (and other program) instructions without having to resort to client-side language-specific decoding libraries.

#### Summary of Changes
- Add TransactionEncoding::JsonParsed and enum to handle multiple RpcInstruction types
- Add parse module and populate with Memo program

Next Steps (separate prs):
- [ ] Add parsing of a native program (probably system) to set a precedent for parsing programs with instruction sets that are more complex than memo
- [ ] Add similar parsing for program accounts (#10475 ), maybe in this same crate?
- [ ] Consider renaming this crate to transaction-parsing; or something more generic, if accounts are included

Toward #10476

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
@mvines , can you please take a peek and see if this seems like a reasonable direction for instruction parsing?

Here's what a confirmed block with a memo transaction looks like:
```
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getConfirmedBlock", "params":[189,"jsonParsed"]}' 127.0.0.1:8899

{
  "jsonrpc": "2.0",
  "result": {
    "blockhash": "2V6577QoupLTaeTuiGno32BgwVhKwTa7m9v6FyRz9ncz",
    "parentSlot": 188,
    "previousBlockhash": "8pkj38CNrsjUdiZVZ51zLWCXn5cmnd1ETdcbkh3ZzkYj",
    "rewards": [],
    "transactions": [
      {
        "meta": {
          "err": null,
          "fee": 5000,
          "postBalances": [
            499999917500,
            115627449357,
            1,
            1,
            1
          ],
          "preBalances": [
            499999922500,
            115627449357,
            1,
            1,
            1
          ],
          "status": {
            "Ok": null
          }
        },
        "transaction": {
          "message": {
            "accountKeys": [
              "A5V6fjwGL7w9p2vxWX8JmdGuwKDd3wuHyaJKa1vzo6Jb",
              "EM62zUL2mWZia1MmBSX64e2E3iLSpe4cp4ybUqUKMG6h",
              "SysvarS1otHashes111111111111111111111111111",
              "SysvarC1ock11111111111111111111111111111111",
              "Vote111111111111111111111111111111111111111"
            ],
            "header": {
              "numReadonlySignedAccounts": 0,
              "numReadonlyUnsignedAccounts": 3,
              "numRequiredSignatures": 1
            },
            "instructions": [
              {
                "accounts": [
                  1,
                  2,
                  3,
                  0
                ],
                "data": "37u9WtQpcm6ULa3WUh3HZ4qUcZfzZEuE5QVnfh7YMHUx5A956Wngqu3VXHZwYavGG4Zo4Q1m",
                "programIdIndex": 4
              }
            ],
            "recentBlockhash": "8pkj38CNrsjUdiZVZ51zLWCXn5cmnd1ETdcbkh3ZzkYj"
          },
          "signatures": [
            "3noHrBt71USRvoXunGRn5q9Hfwq9ZCKHiuKTUL8A3bq71H79jkaNfQqoQxeM782LKk5EiEEpBmjaQYpFJviuJcDX"
          ]
        }
      },
      {
        "meta": {
          "err": null,
          "fee": 5000,
          "postBalances": [
            9878055320,
            121159680
          ],
          "preBalances": [
            9878060320,
            121159680
          ],
          "status": {
            "Ok": null
          }
        },
        "transaction": {
          "message": {
            "accountKeys": [
              "Bbqg1M4YVVfbhEzwA9SpC9FhsaG83YMTYoR4a8oTDLX",
              "Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo"
            ],
            "header": {
              "numReadonlySignedAccounts": 0,
              "numReadonlyUnsignedAccounts": 1,
              "numRequiredSignatures": 1
            },
            "instructions": [
              {
                "memo": "🦖"
              }
            ],
            "recentBlockhash": "GM6BWUzL3DtrEdXGXttDKhYD14S8qJsMBcNV1cBPk7ZA"
          },
          "signatures": [
            "3vus9eKzCGEsCFDLMnFeWmPSV8GT8BpEZq6g69jEW3vDrPjDogqCfEcGUNsNv4pkigo2nfDGizho2orx5tU7e6Vz"
          ]
        }
      }
    ]
  },
  "id": 1
}
```

**Comment by mvines** [comment]
Neat!

```
        "instructions": [
          {
            "memo": "🦖"
          }
        ],
```
1. Would unknown program instructions just show up as raw bytes?
2. We could see things like "system", "stake", "vote", "token" in the future in addition to "memo" right?  I'm slightly concerned about the name space being limited.  Maybe we use "system", "stake", "vote", "bpfloader" since these are built-in programs but then "spl-memo", "spl-token" for SPLs to allocate room in the namespace for other future program libraries that deserve to be promoted into RPC.

In this context:
```
"header": {
          "numReadonlySignedAccounts": 0,
          "numReadonlyUnsignedAccounts": 1,
          "numRequiredSignatures": 1
        },
```
feels vestigial to me. As a user of this output I'm not sure what I would use it for.

**Comment by CriesofCarrots** [comment]
>     1. Would unknown program instructions just show up as raw bytes?

Yeah, they would show up as the unparsed Json does now.

>     2. We could see things like "system", "stake", "vote", "token" in the future in addition to "memo" right?  I'm slightly concerned about the name space being limited.  Maybe we use "system", "stake", "vote", "bpfloader" since these are built-in programs but then "spl-memo", "spl-token" for SPLs to allocate room in the namespace for other future program libraries that deserve to be promoted into RPC.

Ah, great point. I'll change to `splMemo`

> In this context:
> 
> ```
> "header": {
>           "numReadonlySignedAccounts": 0,
>           "numReadonlyUnsignedAccounts": 1,
>           "numRequiredSignatures": 1
>         },
> ```
> 
> feels vestigial to me. As a user of this output I'm not sure what I would use it for.

Right now, aside from the instructions, this returns the same transaction parts as the unparsed Json. Perhaps I should take this futher (to a new ParsedRpcMessage) that lists the accounts with writable/signer labels?

**Comment by mvines** [comment]
> Ah, great point. I'll change to `splMemo`

I think in this case, kabab case reads nicer: "spl-memo".   It'd be good to solicit input from others though

> Right now, aside from the instructions, this returns the same transaction parts as the unparsed Json. Perhaps I should take this futher (to a new ParsedRpcMessage) that lists the accounts with writable/signer labels?

Sure let's see how that feels.  That does seem more user friendly

**Comment by CriesofCarrots** [comment]
Here is the parsed transaction:

```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getConfirmedTransaction", "params":["3vus9eKzCGEsCFDLMnFeWmPSV8GT8BpEZq6g69jEW3vDrPjDogqCfEcGUNsNv4pkigo2nfDGizho2orx5tU7e6Vz","jsonParsed"]}' 127.0.0.1:8899

{
  "jsonrpc": "2.0",
  "result": {
    "meta": {
      "err": null,
      "fee": 5000,
      "postBalances": [
        9878055320,
        121159680
      ],
      "preBalances": [
        9878060320,
        121159680
      ],
      "status": {
        "Ok": null
      }
    },
    "slot": 189,
    "transaction": {
      "message": {
        "accountKeys": [
          {
            "Bbqg1M4YVVfbhEzwA9SpC9FhsaG83YMTYoR4a8oTDLX": [
              "writable",
              "signer"
            ]
          },
          {
            "Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo": []
          }
        ],
        "instructions": [
          {
            "spl-memo": "🦖"
          }
        ],
        "recentBlockhash": "GM6BWUzL3DtrEdXGXttDKhYD14S8qJsMBcNV1cBPk7ZA"
      },
      "signatures": [
        "3vus9eKzCGEsCFDLMnFeWmPSV8GT8BpEZq6g69jEW3vDrPjDogqCfEcGUNsNv4pkigo2nfDGizho2orx5tU7e6Vz"
      ]
    }
  },
  "id": 1
}
```

**Comment by CriesofCarrots** [comment]
I'm going to merge this chunk, as it seems low-risk and compartmentalized. Parsing a complete Instruction enum (like System) into useful, human-friendly json is a greater lift, so I'll do that separately.

**Pull request merged**
