### PR TITLE
v1.17: bump shlex to 1.3.0

### PR DESCRIPTION
**Pull request by yihau**
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by yihau** [comment]
the audit doesn't accept 1.2.1 🫠
https://buildkite.com/solana-labs/solana/builds/107060#018d32a0-a18f-44e8-a066-2375642039e3

**Comment by t-nelson** [comment]
wow it looks like 2024 is the year of dependencies showing their ass. one more for the "to remove" list

**Comment by t-nelson** [comment]
can you squash the 1.2.1 attempt away?

**Comment by solana-grimes** [comment]
:scream: New commits were pushed while the automerge label was present.

**Review by t-nelson — APPROVED** [review]

**Pull request merged**
