### PR TITLE
Admin RPC Service: move post-init activation to before wait-for-supermajority

### LINKED ISSUE #30530: Admin Interface Not Available During Restarts
#### Problem
The validator admin interface will not accept validator identities during a restart. We were waiting for 80% and saw this:

```
solana@my-rpc-node:~$ solana-validator --ledger /solana/ledger/ set-identity
[key-here]New validator identity: [validator-ID]
setIdentityFromBytes request failed: Server returned rpc error Invalid params: Retry once validator start up is complete
```

#### Proposed Solution
1) No more restarts!
2) Allow an operator to use the admin interface during a restart when we are waiting for 80%

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
The validator admin interface will not accept validator identities while a node is waiting for supermajority during a restart, because the post-init setting doesn't happen until after Validator::new() returns.

#### Summary of Changes
Move AdminRpcRequestMetadataPostInit to solana core so it can be used inside Validators::new(). Write admin_rpc_service_post_init just before `wait_for_supermajority()`

Fixes #30530

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
What do you think about this @mvines ? The request seemed reasonable to me, and this was a light way to accomplish it.

**Comment by mvines** [comment]
> What do you think about this @mvines ? The request seemed reasonable to me, and this was a light way to accomplish it.

This seems reasonable, I can't think of a reason currently why moving `admin_rpc_service_post_init` earlier would be an issue.

**Comment by CriesofCarrots** [comment]
Curious for your thoughts on backporting. I feel ambivalent, since it will otherwise be a long time until this available to validator operators.

**Comment by mvines** [comment]
I don't see a strong reason for a backport right now

**Comment by CriesofCarrots** [comment]
> I don't see a strong reason for a backport right now

Fine. Will you have time to review the actual code sometime soon?

**Review by mvines — APPROVED** [review]
oops, sry. i reviewed last night but failed to press the "Submit review" button!

**Pull request merged**
