### PR TITLE
Fixed a race condition creating useless connections in MT env

### PR DESCRIPTION
**Pull request by lijunwangs**
#### Problem

Useless connections are being created which overloads the server and cause unreliable
connections on the client side.
This is due to the race in the connection cache for creating connections given a remote address. It was possible for multiple threads to create duplicate connections which only one of being used. This can overloads the server. 

#### Summary of Changes

After write lock is taken, check if the connection is available. If so, return without creating a new connection.

Fixes #

### CODE REVIEW

**Comment by pgarg66** [comment]
I has tried something similar here: https://github.com/solana-labs/solana/pull/24857/commits/22fc8f65d35bc01a7fd95f3e91b97105ecc2bbd6

Could you please test the timing of `get_connection` with this PR by connecting to testnet? 
IIRC, the performance was impacted by the change I had tried.

**Review by ryleung-solana — APPROVED** [review]

**Comment by lijunwangs** [comment]
> I tried something similar here: [22fc8f6](https://github.com/solana-labs/solana/commit/22fc8f65d35bc01a7fd95f3e91b97105ecc2bbd6)
> 
> Could you please test the timing of `get_connection` with this PR by connecting to testnet? IIRC, the performance was impacted by the change I had tried.
> 
> The change by itself makes sense.

I think the correctness has to come before the performance. I think we can improve that. The locks probably is too big in my option, maybe a more granular "dictionary lock" can be used to protect a certain remote address to guard against wasteful dup connections. I can do the test, can you share what is the way to capture the metrics? From the bench-tps tool?

**Comment by pgarg66** [comment]
> > I tried something similar here: [22fc8f6](https://github.com/solana-labs/solana/commit/22fc8f65d35bc01a7fd95f3e91b97105ecc2bbd6)
> > Could you please test the timing of `get_connection` with this PR by connecting to testnet? IIRC, the performance was impacted by the change I had tried.
> > The change by itself makes sense.
> 
> I think the correctness has to come before the performance. I think we can improve the performance. The locks probably is too big in my opinion, maybe a more granular "dictionary lock" can be used to protect a certain remote address to guard against wasteful dup connections. I can do the test, can you share what is the way to capture the metrics? From the bench-tps tool?

The performance degradation was originally noticed in the packet forwarding. You can run a node with this PR along with a bench-tps instance that always sends transactions to your node. This will cause the node to forward the packets to the leader for the slot.

IIRC, sometimes the `get_connection` was taking multiple seconds. With that level of performance degradation the feature can not be used for isolating/testing any other downstream issues.

**Comment by lijunwangs** [comment]
Will check in this connection issue with multi-threaded env first. Other performance issue due to one lengthy connection causing locking problems and delays in other connections will be addressed in a separate PR.

**Pull request merged**
