### PR TITLE
Convert Measure::this to measure! and remove Measure::this

### PR DESCRIPTION
**Pull request by apfitzge**
#### Problem
Having an empty `()` everwhere this was used. We can use the measure! macro instead.

#### Summary of Changes
Remove Measure::this, and replace with the measure! macro

Fixes #

### CODE REVIEW

**Comment by brooksprumo** [comment]
I'd recommend changing all of these to use `measure!()` instead. That'll simplify this code even more.

**Comment by brooksprumo** [comment]
And to be more explicit, don't both changing `Measure::this()`. Instead, just remove `Measure::this()` entirely.

Note, I am not saying you need to do that in this PR though (but you can if you'd like)!

**Comment by apfitzge** [comment]
Changed all the instances of `Measure::this` to `measure!`, and deleted `Measure::this` from the code.

**Review by brooksprumo — APPROVED** [review]
Thanks so much for this cleanup! I've want to do this very thing _many_ times, so I appreciate the time to go through all these.

**Comment by apfitzge** [comment]
> Thanks so much for this cleanup! I've want to do this very thing _many_ times, so I appreciate the time to go through all these.

No problem, happy to clean these things up as well!

**Pull request merged**
