### PR TITLE
Load nonce with fixed root

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

Nonce loading uses the slower method of loading accounts

#### Summary of Changes

Use the faster way since we are always loading from within the bank

Fixes #

### CODE REVIEW

**Comment by jackcmay** [comment]
@carllin Any behavior change here that needs to be featurized when calling `get_account_with_fixed_root` rather than `get_account`?

**Review by carllin — APPROVED** [review]
Looks good to me!

**Comment by jackcmay** [comment]
@carllin Cool, but also are there any behavior changes between the two calls that might cause a fork?

**Comment by carllin** [comment]
@jackcmay the two different types of loads should be be indistinguishable in this path, shouldn't cause any behavior divergence.

**Comment by t-nelson** [comment]
> the two different types of loads should be be indistinguishable in this path, shouldn't cause any behavior divergence.

Signalling intent here is good though!

**Pull request merged**
