### PR TITLE
Move register_entry_id() call out of write stage

### PR DESCRIPTION
**Pull request by pgarg66**
- Write stage is MIPS intensive and has become a bottleneck for
  TPU pipeline
- This will reduce the MIPS requirements for the stage

### CODE REVIEW

**Comment by pgarg66** [comment]
https://github.com/solana-labs/solana/issues/1164

**Comment by rob-solana** [comment]
the more I look at this, the more I think record_stage should just go away and we can let the banking_stage do entry generation.

consider: record_stage used not to have to know about the bank and while this should help with OOM, it's only a "first step" for LastIdNotFound.

**Comment by rob-solana** [comment]
landing this PR could be a "half of step one", though...

**Comment by rob-solana** [comment]
#1200

**Comment by garious** [comment]
@rob-solana, indeed, the proposed solution in #1200 is to remove the RecordStage and move that functionality into BankStage. This PR is a step in that direction. Good stuff!

**Pull request merged**
