### PR TITLE
Added a feature flag to use recycler

### PR DESCRIPTION
**Pull request by pgarg66**
- Without the flag, the recyclables won't be added to landfill

### CODE REVIEW

**Comment by rob-solana** [comment]
what's the goal here?

**Comment by pgarg66** [comment]
@rob-solana . it's related to OOM (https://github.com/solana-labs/solana/issues/1164)
I have posted an update to the issue.

**Comment by rob-solana** [comment]
cc #1164 

if this is a fix, I'd prefer you just removed recycler

**Comment by pgarg66** [comment]
Sure, will kill it. I'll push an update.

**Comment by rob-solana** [comment]
there's a bunch of code that uses blobs that is doing extra work (like resetting flags, etc.) because it expects a "used" buffer to be coming from allocate().  all that code can disappear, too.

**Comment by sakridge** [comment]
Can we have some performance analysis of doing this change?

**Comment by pgarg66** [comment]
Sure @sakridge , will run the numbers on the tip of master with and without the change.

**Comment by pgarg66** [comment]
Killing this and starting a new PR, as the scope of the PR has changed.

**Pull request closed without merging**
