### PR TITLE
Add callback for new bank when processing blocktree

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
The TdS winner tool needs a hook to mutate the bank before each block is processed

***Note:** The TdS winner tool needs this because there is no current way to load native programs from another cargo project which uses crates.io dependency for the solana runtime. Each bank must have native program instructions intercepted with `bank.add_instruction_processor(..)`.*

#### Summary of Changes
Add an optional callback which will run each time a new bank is created

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
@sakridge it's a work around for another issue.

The issue is that `solana-runtime` cannot currently load native programs properly when the dependency is through crates.io or git. This is because it looks for a specific file in the execution directory when loading native programs. This works fine for local path based dependencies because the file name is deterministic, but cargo / rustc adds a hash to dependency dynamic lib filenames for crates.io or git dependencies so the file cannot be found. AFAIK there's no way to disable that hash extension or deterministically determine which should be used.

In order to get around the dynamic lib not found issue, I added a callback in this PR so that I can intercept native program instructions and process them directly with the native program. See here: https://github.com/solana-labs/tour-de-sol/pull/20/files#diff-69c184a9c7bce2c16d29851280d961faR122

**Comment by jstarry** [comment]
Part of problem is that we don't seem to be cloning the `instruction_processors` from `MessageProcessor` when creating a new bank. Would that be a better fix? That would remove the need for this hack

**Comment by sakridge** [comment]
@jstarry I think you might want to just do what the blockstreamer is doing. This approach seems really hacky.

**Comment by jstarry** [comment]
Closing in favour of fixing native program loading: https://github.com/solana-labs/solana/issues/5966

**Pull request closed without merging**
