### PR TITLE
Program tests now check signature status

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

The bank reports a transaction succeeds even if a program fails (it did run and the fee was collected).  Program tests were expecting the transaction to fail.  The result was that program tests would pass even if the program failed to run successfully.

#### Summary of Changes

- Program tests now check the signature status
- Added a program that intentionally fails to ensure the tests are handling programs failures correctly

Fixes #

### CODE REVIEW

**Comment by garious** [comment]
Do we think that Ok() is desirable?

**Comment by garious** [comment]
Also, that top-level programs.rs seems odd to me. Can this stuff be pushed down into the individual programs like we did here:
https://github.com/solana-labs/solana/blob/master/programs/native/rewards/tests/rewards.rs

**Comment by jackcmay** [comment]
Want to elaborate on why you think `Ok(())` may not be appropriate"?

The purpose of programs is to test all the programs (look at C for example where we run all the test programs through).  Creating a test harness for each individual test program sounds like a lot of copypasta and only worth it if there is something unique that needs to be tested that is not covered by the general case.

**Comment by garious** [comment]
I misread the diff. I see now the `Ok(())` was for noop, not failure.

No copypasta please. If you don't see the value, no worries,  so much to do.

**Pull request merged**
