### PR TITLE
web3.js: Remove bn.js from dependencies

### PR DESCRIPTION
**Pull request by macalinao**
#### Problem

BN.js is bulky

#### Summary of Changes

Removes BN.js

### CODE REVIEW

**Comment by steveluscher** [comment]
Yeah! This is in progress, in: https://github.com/solana-labs/solana/pull/27532

In any case, this PR doesn't get rid of `bn.js` because of its membership in `borsh`. Throw some love behind this PR: https://github.com/near/borsh-js/pull/60

**Comment by macalinao** [comment]
> Yeah! This is in progress, in: https://github.com/solana-labs/solana/pull/27532
> 
> 
> 
> In any case, this PR doesn't get rid of `bn.js` because of its membership in `borsh`. Throw some love behind this PR: https://github.com/near/borsh-js/pull/60

Is there a benefit to backing PublicKey with an integer rather than a Uint8Array?

**Comment by macalinao** [comment]
> Yeah! This is in progress, in: https://github.com/solana-labs/solana/pull/27532
> 
> 
> 
> In any case, this PR doesn't get rid of `bn.js` because of its membership in `borsh`. Throw some love behind this PR: https://github.com/near/borsh-js/pull/60

Added some comments to your PR

We actually had a lot of Saber users with BigInt issues back when we added a Pyth integration-- I would prefer JSBI instead if possible

**Comment by steveluscher** [comment]
Oh? What were the issues?

By users,  I presume you mean developers, right?

BigInt now has support in most browsers [since ~Sep 2020](https://caniuse.com/bigint), and it finally got first class [support in React Native / Hermes](https://twitter.com/steveluscher/status/1565232097044099073).

**Pull request closed without merging**
