### PR TITLE
Fix caller write privileges for native cpi

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
Caller write privileges are not created correctly for native cpi. The `caller_write_privileges` vector should match up with `message.account_keys` because they will be indexed the same.

#### Summary of Changes
- Remove incorrect write privilege value insertion
- Match up write privileges vector with the `accounts` vector built from `message.account_keys`

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
Since `native_invoke` is only called for the bpf upgradeable program and that program doesn't modify caller accounts before invoking the native create account instruction, there shouldn't be any change of behavior here.

**Comment by jackcmay** [comment]
Do you have a test that highlights the issue?

**Comment by jstarry** [comment]
Not yet, just running through CI first to see what pops up. Should have opened as draft

**Comment by jstarry** [comment]
Hmm looks like there aren't any tests for native cpi yet beyond bpf loader integration tests, I don't have the time to put a test suite together right now so I'll write up an issue instead.

**Comment by jstarry** [comment]
Issue here: https://github.com/solana-labs/solana/issues/18629

**Pull request closed without merging**
