### PR TITLE
v1.16: Upgrade quinn to 0.9.4

### PR DESCRIPTION
**Pull request by lijunwangs**
#### Problem
Updated Quinn library to 0.9.4 in v.16 branch which solve part of excessive packets build-up problem in the transmit queue from endpoint generated stateless packets.

The master uses 0.10.1 which Quinn has not released the corresponding 0.10.2 fix yet due to another memory issue tracked by https://github.com/quinn-rs/quinn/pull/1611#discussion_r1272580474

#### Summary of Changes
Upgraded Quinn libs to 0.9.4

Fixes #

### CODE REVIEW

**Review by behzadnouri — APPROVED** [review]

**Comment by willhickey** [comment]
Hey @joncinque & @jacobcreech, any concerns here about breaking ecosystem builds? I think we're ok based on the dependents and the fact that it's a patch bump.
```
$ ./cargo tree --invert quinn --depth 2
+ exec cargo +1.69.0 tree --invert quinn --depth 2
quinn v0.9.3
├── solana-client v1.16.5 (/Users/willhickey/github/solana/client)
│   ├── solana-accounts-cluster-bench v1.16.5 (/Users/willhickey/github/solana/accounts-cluster-bench)
│   ├── solana-banking-bench v1.16.5 (/Users/willhickey/github/solana/banking-bench)
│   ├── solana-banks-server v1.16.5 (/Users/willhickey/github/solana/banks-server)
│   │   [dev-dependencies]
│   ├── solana-bench-tps v1.16.5 (/Users/willhickey/github/solana/bench-tps)
│   ├── solana-cli v1.16.5 (/Users/willhickey/github/solana/cli)
│   ├── solana-core v1.16.5 (/Users/willhickey/github/solana/core)
│   │   [dev-dependencies]
│   ├── solana-dos v1.16.5 (/Users/willhickey/github/solana/dos)
│   ├── solana-gossip v1.16.5 (/Users/willhickey/github/solana/gossip)
│   ├── solana-local-cluster v1.16.5 (/Users/willhickey/github/solana/local-cluster)
│   │   [dev-dependencies]
│   ├── solana-rpc v1.16.5 (/Users/willhickey/github/solana/rpc)
│   ├── solana-rpc-test v1.16.5 (/Users/willhickey/github/solana/rpc-test)
│   ├── solana-send-transaction-service v1.16.5 (/Users/willhickey/github/solana/send-transaction-service)
│   ├── solana-test-validator v1.16.5 (/Users/willhickey/github/solana/test-validator)
│   │   [dev-dependencies]
│   └── solana-transaction-dos v1.16.5 (/Users/willhickey/github/solana/transaction-dos)
├── solana-quic-client v1.16.5 (/Users/willhickey/github/solana/quic-client)
│   └── solana-client v1.16.5 (/Users/willhickey/github/solana/client) (*)
└── solana-streamer v1.16.5 (/Users/willhickey/github/solana/streamer)
    ├── solana-accounts-cluster-bench v1.16.5 (/Users/willhickey/github/solana/accounts-cluster-bench)
    ├── solana-banking-bench v1.16.5 (/Users/willhickey/github/solana/banking-bench)
    ├── solana-bench-streamer v1.16.5 (/Users/willhickey/github/solana/bench-streamer)
    ├── solana-bench-tps v1.16.5 (/Users/willhickey/github/solana/bench-tps) (*)
    ├── solana-client v1.16.5 (/Users/willhickey/github/solana/client) (*)
    ├── solana-client-test v1.16.5 (/Users/willhickey/github/solana/client-test)
    ├── solana-core v1.16.5 (/Users/willhickey/github/solana/core) (*)
    ├── solana-dos v1.16.5 (/Users/willhickey/github/solana/dos)
    ├── solana-gossip v1.16.5 (/Users/willhickey/github/solana/gossip) (*)
    ├── solana-ledger-tool v1.16.5 (/Users/willhickey/github/solana/ledger-tool)
    ├── solana-local-cluster v1.16.5 (/Users/willhickey/github/solana/local-cluster) (*)
    ├── solana-quic-client v1.16.5 (/Users/willhickey/github/solana/quic-client) (*)
    ├── solana-rpc v1.16.5 (/Users/willhickey/github/solana/rpc) (*)
    ├── solana-rpc-test v1.16.5 (/Users/willhickey/github/solana/rpc-test)
    ├── solana-test-validator v1.16.5 (/Users/willhickey/github/solana/test-validator) (*)
    ├── solana-transaction-dos v1.16.5 (/Users/willhickey/github/solana/transaction-dos)
    ├── solana-udp-client v1.16.5 (/Users/willhickey/github/solana/udp-client)
    └── solana-validator v1.16.5 (/Users/willhickey/github/solana/validator)
    [dev-dependencies]
    ├── solana-cli v1.16.5 (/Users/willhickey/github/solana/cli) (*)
    └── solana-tokens v1.16.5 (/Users/willhickey/github/solana/tokens)
    ```

**Comment by joncinque** [comment]
Looks good to me @willhickey

**Comment by jacobcreech** [comment]
Seems fine

**Comment by lijunwangs** [comment]
Did a rebase. @behzadnouri can you re-approve this PR? Thanks

**Review by behzadnouri — APPROVED** [review]

**Pull request merged**
