### PR TITLE
Fix blatant md formatting at the very top

### PR DESCRIPTION
**Pull request by tredondo**

### CODE REVIEW

**Review by jstarry — APPROVED** [review]
Thanks for fixing!

**Comment by tredondo** [comment]
Happy to fix, but what's the CD cycle? I still see [week-old fixes not live](https://github.com/solana-labs/solana/commit/073c5359b0e39a4e27d085c4d222925f58c40c09#commitcomment-57045863).

**Comment by jstarry** [comment]
Ah docs.solana.com is published from the v1.6 feature branch... I'll backport fixes now, hold tight

**Comment by mvines** [comment]
> Ah docs.solana.com is published from the v1.6 feature branch... I'll backport fixes now, hold tight

It should be published from v1.6 actually, if v1.6 caused a publish then we may have a bug in CI

**Comment by jstarry** [comment]
> > Ah docs.solana.com is published from the v1.6 feature branch... I'll backport fixes now, hold tight
> 
> It should be published from v1.6 actually, if v1.6 caused a publish then we may have a bug in CI

You said v1.6 twice 🤔

**Comment by mvines** [comment]
😅 "It should be published from v1.7..."

**Pull request merged**
