### PR TITLE
Add Burn program

### LINKED ISSUE #9773: Add a mechanism to burn SOL
There's currently no mechanism to burn an arbitrary amount of SOL in a method that would cause [getTotalSupply](https://docs.solana.com/apps/jsonrpc-api#gettotalsupply) to decrease.  

The key is to cause a decrease in https://github.com/solana-labs/solana/blob/aac580686fe77a2d24d8e07b21191f05d32bb6b1/runtime/src/bank.rs#L264 as a result of the transaction being executed.  A couple options for this:
1) A new `Burn111...` program that's implemented within bank.rs that ignores any instruction data and burns the full balance of any provided signer keys that are owned by the `Burn111...` program to cause the decrease in bank capitalization.  
2) <s>A special `Burn111...` blockhash </s>

### PR DESCRIPTION
**Pull request by mvines**
TODO:
* [ ] More tests
* [ ] Tweak `solana burn` CLI interface

Fixes #9773

### CODE REVIEW

**Comment by garious** [comment]
What about a sysvar containing the total supply, and that the special case is that any tokens added to it are subtracted from the bank's total supply after the transaction succeeds?

**Comment by mvines** [comment]
Oh wait!  That gave me another idea - `Sysvar1nc1nerator111111111111111111`.   The balance of the incinerator sysvar will be cleared when a bank is frozen, and any lamports credited it removed from the capitalization.   The benefits:
1. No need for a burn program at all
2. Any program can burn tokens
3. No runtime rule changes required to support burning, just some trivial code in Bank::freeze()
4. `solana transfer Sysvar1nc1nerator111111111111111111 42` works

Essentially most of this PR melts away

**Comment by garious** [comment]
Oh yeah!!!

**Comment by ryoqun** [comment]
> Oh wait! That gave me another idea - `Sysvar1nc1nerator111111111111111111`. The balance of the incinerator sysvar will be cleared when a bank is frozen, and any lamports credited it removed from the capitalization. The benefits:
> 
>     1. No need for a burn program at all
> 
>     2. Any program can burn tokens
> 
>     3. No runtime rule changes required to support burning, just some trivial code in Bank::freeze()
> 
>     4. `solana transfer Sysvar1nc1nerator111111111111111111 42` works
> 
> 
> Essentially most of this PR melts away

@mvines @garious This sounds very nice and I like the simpler approach!

But, if burning is anticipated to be common across smart contracts, would that mean we're kind of creating a lock contention for the write lock of the burning sysvar? I may be wrong, but I saw somewhere, we can't parallelize access to a single account within a slot/tick?

**Comment by garious** [comment]
@ryoqun, let's cross that bridge later. The burn account gets credited, so we could consider reintroducing parallel modifications for credit-only accounts. Last attempt added too much code complexity, but nothing theoretically with that parallelism.  Alternatively, we can extend this feature to any account that starts with `Sysvar1nc1nerator` and have the user pick one at random.

**Pull request closed without merging**
