### PR TITLE
Add alt_bn128 syscall tests (and fix related issues)

### PR DESCRIPTION
**Pull request by vadorovsky**
* Fix C headers (the name of the syscall was incorrect).
* Add C SBF tests using the alt_bn128 syscall.
* Fix the Rust SBF program:
  * Do not use serde and array-bytes, provide test cases as byte arrays directly.
  * Use the `custom_heap_default` macro.
  * Replace `bpf` with `sbf` in the crate name.
* Execute both previously existing Rust tests and new C tests in `programs/sbf/tests`, so they are actually tested on CI.

/cc @Lichtso @ananas-block

### CODE REVIEW

**Review by Lichtso — DISMISSED** [review]

**Comment by Lichtso** [comment]
@CriesofCarrots We need one more approval on this.

**Review by CriesofCarrots — DISMISSED** [review]
Merge commit 😞

**Comment by Lichtso** [comment]
@vadorovsky Can you delete the last two commits and rebase?

**Review by Lichtso — DISMISSED** [review]

**Comment by vadorovsky** [comment]
@Lichtso @CriesofCarrots done, thank you for quick reaction!

**Review by Lichtso — APPROVED** [review]

**Comment by mvines** [comment]
CI is green, PR is approved. Doing a drive-by merge-assist on this.

**Pull request merged**
