### PR TITLE
Remove test_replay

### LINKED ISSUE #2358: test_replay is ignored and bitrotting
#### Problem
test_replay() is ignored, but appears to be the only "unit" test for the data plane

#### Proposed Solution
ensure there are actual unit tests for each of the sub-units of test_replay, retire test_replay, and restructure to test the glue in this file

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

test_replay() was not exactly testing anything. 

It had two parts 
- Simulate a bank transfers manually (with ticks)
- Test retransmits between dummy validator nodes

Bank has enough transfer tests and there was nothing being asserted for the retransmits making this test useless. 

#### Summary of Changes

Removed the test. What ever this test was trying to do is covered elsewhere.

Fixes #2358

### CODE REVIEW

**Comment by sakridge** [comment]
Where else do we test that blobs get to the bank correctly in TVU?

**Comment by sagar-solana** [comment]
@sakridge, this test wasn't even testing that. It just makes the bank process the transfers directly, so that balances will always be correct. The tvu wasn't really doing anything here.
Also the test freezes because storage_stage is stuck trying to get last_id from a bogus leader node.

I guess either way we'll need new replay stage tests with Bank forking coming in.

**Comment by sakridge** [comment]
@sagar-solana I'm not sure what you mean by process transfers directly because it's not doing like `bank.process_transaction`, it's generating the blobs and sending them on the socket. The last_id thing could be fixed.

**Comment by sagar-solana** [comment]
@sakridge, sorry I should have specified that this test is calling process_tick on the bank. Which is incorrect. That stops the tvu from being able to process the entries that are generated (since it's bank's last_id has moved before it even got the entries). 

Maybe I can remove the bank calls and let tvu handle it all. But still we have to deal with the fact that storage_stage freezes after those two asserts when tvu.close() is called.

**Comment by sagar-solana** [comment]
@garious, @sakridge pointed out that this test might actually have some value. Its just that with all the churn it's ended up becoming something else. I'll take another stab at fixing it. 
Current outstanding problem with it is that the test can't shutdown properly because it's expecting the leader's rpc to be real.

**Pull request closed without merging**
