### PR TITLE
Add support for alt_bn128 syscalls

### PR DESCRIPTION
**Pull request by ai-trepalin**
#### Compatibility

This is an updated version of previous pull request (https://github.com/solana-labs/solana/pull/25464) for Solana v1.10.x

#### Problem

Contracts written in the Solidity language cannot work in Solana if they contain calls to the following precompiled contracts:

bn256Add — Performs addition on the elliptic curve operations.
bn256ScalarMult — Performs scalar multiplication on the elliptic curve operations.
bn256Pairing — Elliptic curve pairing operations to perform zkSTARKs verification within the block gas limit.

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-196.md
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-197.md

The Neon EVM requires the implementation of system calls in Solana for these contracts.

Solution

In order for the precompiled contracts to be used in Solana, it is proposed to implement sys-calls inside the Solana core. That is, to perform an implementation similar to the erc-recover implementation.

#### Summary of Changes

This merge request adds implementation of bn256 (alt_bn128) precompiles.

#### About compute budget costs

We need to know, how much BPF instructions will be used for every operation on elliptic curves. We can't to know it directly, but we can compare the time needed for these operations and time, needed for Keccak hash for the same data.

We added benchmarks, that allow us to approximately define the amount of data in bytes for elliptic curves operations and Keccak hash and compare result times.

The repository with benchmarks is here: https://github.com/neonlabsorg/alt-bn128-bench

Fixes #

### CODE REVIEW

**Comment by ananas-block** [comment]
Regarding the compute units pricing.

Based on @Lichtso s’  comment that compute units can be either calculated by bytes copied (one CU per byte) or compute duration of 33 ns per CU, I did some basic benchmarks for the bn254 sycalls on a c6a.2xlarge AWS instance.

**Bench Results:**
test alt_bn128_addition_test       ... bench:      11,025 ns/iter (+/- 208)
test alt_bn128_multiplication_test ... bench:   2,286,847 ns/iter (+/- 5,903)
test alt_bn128_pairing_test        ... bench:  40,395,211 ns/iter (+/- 68,481)
Code: https://github.com/ananas-block/altbn128_syscall_benches/blob/alt_bn128_precompiles/sdk/benches/bn_syscalls.rs

**Possible pricing based on 33ns execution time per CU:**
Addition: 	 11,025 ns / 33ns = 334 CUs
Multiplication: 2,286,847 ns / 6 testcases / 33ns = 11,550 CUs
Pairing: 	 40,395,211 ns / 3 testcases / 3 pairings per testcase / 33ns = 136,011 CUs (per pairing)

@ai-trepalin @Lichtso thoughts?

**Comment by ai-trepalin** [comment]
> Regarding the compute units pricing.
> 
> Based on @Lichtso s’ comment that compute units can be either calculated by bytes copied (one CU per byte) or compute duration of 33 ns per CU, I did some basic benchmarks for the bn254 sycalls on a c6a.2xlarge AWS instance.
> 
> **Bench Results:** test alt_bn128_addition_test ... bench: 11,025 ns/iter (+/- 208) test alt_bn128_multiplication_test ... bench: 2,286,847 ns/iter (+/- 5,903) test alt_bn128_pairing_test ... bench: 40,395,211 ns/iter (+/- 68,481) Code: https://github.com/ananas-block/altbn128_syscall_benches/blob/alt_bn128_precompiles/sdk/benches/bn_syscalls.rs
> 
> **Possible pricing based on 33ns execution time per CU:** Addition: 11,025 ns / 33ns = 334 CUs Multiplication: 2,286,847 ns / 6 testcases / 33ns = 11,550 CUs Pairing: 40,395,211 ns / 3 testcases / 3 pairings per testcase / 33ns = 136,011 CUs (per pairing)
> 
> @ai-trepalin @samkim-crypto @Lichtso thoughts?

Hello! It seems so! There was indeed an error in my benchmarks, which caused the compute budget to be calculated incorrectly. But after fixing, I got similar values. The only thing is that the pairing took me 2-3 times more compute budget than yours, but I'm thinking towards the imperfection of my bench algorithm.

@samkim-crypto @Lichtso thoughts?

**Comment by Lichtso** [comment]
Apart from the average we also want to know the variance in execution timings. Because, if the spread is too wide the factors leading to that would have to be explicitly modeled into the cost function. So, it would be helpful to have a histogram of the performance benchmarks.

**Comment by samkim-crypto** [comment]
I think curve Add is implemented in constant time and it appears the ScalarMult implementation here is also constant time (is this correct? @ai-trepalin). But I believe the pairing operation is generally implemented in variable-time as it is usually used for publicly-run verification. If there is a mathematically determined worst-case input to the pairing function, then we can conservatively base the cost on that, but I am not sure if it exists. Otherwise, as per @Lichtso,  it would be good to know the how the pairing execution timings vary on different inputs.

**Comment by ai-trepalin** [comment]
@Lichtso @samkim-crypto Thank you. We will prepare these histograms.

**Comment by ananas-block** [comment]
You are right @samkim-crypto, Add and ScalarMult are implemented in constant time.
Execution time for the pairing implementation follows a linear equation:
``pairingCU = firstPairingExecutionTime + (numberOfPairings - 1) *  otherPairingsExecutionTime``

This equation computes the compute units charged ([implementation](https://github.com/solana-labs/solana/pull/26629/files#diff-b14136045f27f9243e9dd10de415a3e3f4e43e9b9fcf31d28e316fd24588853eR2558-R2569)).

The equation results from the arkwork [products of pairings implementation](https://docs.rs/ark-ec/0.3.0/src/ark_ec/lib.rs.html#96-101) which executes a miller loop for every pairing and only one final exponentiation.

In Ethereum gas costs for the pairing operation are calculated [similarly](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-197.md#gas-costs).


@ai-trepalin and I changed the underlying library to arkworks for significant performance improvements see below for the new bench results.

**Possible pricing based on 33ns execution time per CU:**

Addition: ``334 CU``
Multiplication: ``3,840 CU``
Pairing: ``36,364 CU + (numberOfPairings - 1) * 12,121 CU``

Comput units for one G1 multiplication: ``126.71 * 1000 / 33 = 3,840 CU``
Compute units for the first pairing: ``1.2ms * 1_000_000 / 33 (ns per CU) = 36,364 CU``
Compute units for one additional pairing: ``0.4ms * 1_000_000 / 33 (ns per CU) = 12,121 CU``
(Both 1.2ms and 0.4ms have been selected as upper bounds with buffer based on the bench results below.)



**Bench Results:**
Benchmarks were conducted on an aws c6a.2xlarge instance, see [detailed bench results](https://github.com/ananas-block/altbn128_syscall_benches/tree/alt_bn128_precompiles_arkworks/criterion) and [bench implementation](https://github.com/ananas-block/altbn128_syscall_benches/blob/alt_bn128_precompiles/sdk/benches/bn_syscalls.rs#L213-L241).

**Summary:**

[G1 mul time:](https://github.com/ananas-block/altbn128_syscall_benches/blob/alt_bn128_precompiles_arkworks/criterion/mul%20rnd/report/mean.svg) [126.64 us 126.68 us 126.71 us]
Found 8 outliers among 100 measurements (8.00%) 1 (1.00%) low severe 3 (3.00%) low mild 3 (3.00%) high mild 1 (1.00%) high severe

[2 pairings time: ](https://github.com/ananas-block/altbn128_syscall_benches/blob/alt_bn128_precompiles_arkworks/criterion/pairing%202/report/median.svg)[1.3630 ms 1.3718 ms 1.3839 ms]
Found 6 outliers among 100 measurements (6.00%) 2 (2.00%) high mild 4 (4.00%) high severe

[3 pairings time: ](https://github.com/ananas-block/altbn128_syscall_benches/blob/alt_bn128_precompiles_arkworks/criterion/pairing%203/report/median.svg)[1.6807 ms 1.6819 ms 1.6835 ms]
Found 6 outliers among 100 measurements (6.00%) 1 (1.00%) high mild 5 (5.00%) high severe

[4 pairings time:](https://github.com/ananas-block/altbn128_syscall_benches/blob/alt_bn128_precompiles_arkworks/criterion/pairing%204/report/median.svg) [1.9977 ms 1.9980 ms 1.9983 ms]
Found 3 outliers among 100 measurements (3.00%) 3 (3.00%) high mild

[5 pairings time:](https://github.com/ananas-block/altbn128_syscall_benches/blob/alt_bn128_precompiles_arkworks/criterion/pairing%205/report/median.svg) [2.3224 ms 2.3227 ms 2.3230 ms]
Found 3 outliers among 100 measurements (3.00%) 3 (3.00%) high mild

@samkim-crypto @Lichtso @ai-trepalin thoughts?

**Comment by Lichtso** [comment]
Closing in favor of #27659.

**Pull request closed without merging**
