### PR TITLE
Add process for making architectural changes

### PR DESCRIPTION
**Pull request by garious**
#### Problem

It's neither documented nor obvious how RFCs should be used, when they should be updated, and whether their contents represent proposed architectures, accepted architectures, or accepted and implemented architectures.

#### Summary of Changes

* Defines `doc/` as the description of the architecture
* Defines a PR to `rfcs/` as a proposed architectural change
* Defines the contents of `rfcs/` as accepted changes to the architecture over the lifetime of the project

### CODE REVIEW

**Comment by aeyakovenko** [comment]
@garious why are those docs "WIP"?  i think its cleaner if the doc itself marks whats proposed and whats implemented since its not an all or nothing thing.  

* https://github.com/rust-lang/rfcs#the-rfc-life-cycle
example rfc
* https://github.com/rust-lang/rfcs/blob/master/text/0066-better-temporary-lifetimes.md
Header tags the issue tracking it and the PR where the review comments for the RFC have piled up.

RFC has become a common software industry term for proposed changes, I don't see a reason why we should break from it.

**Comment by garious** [comment]
Okay, I'll make a Solana-oriented variation of that process (hopefully something a little lighter).

**Comment by garious** [comment]
@aeyakovenko, I updated this PR with what I think is a reasonable subset of the Rust process. The Rust process has some nice automation, and without it, some of the process seems like overkill and would likely be ignored (like the back-reference to the PR).

**Comment by garious** [comment]
Also, I removed versions from the RFC. I think the documentation we add to `doc/` should reflect the current codebase, and that once in doc, any changes to the architecture should come in as a new RFC.

**Comment by aeyakovenko** [comment]
@garious awesome!  i like it!

**Comment by garious** [comment]
@sakridge, @mvines, @ericlwilliams, any comments or should I merge it?

**Pull request merged**
