### PR TITLE
builtin program consumes default cost if instruction not manually deduct units

### PR DESCRIPTION
**Pull request by taozhu-chicago**
#### Problem
builtin programs not consuming compute units. #30639 mandates builtins to have a default compute unit cost, it can be used to deduct from budget if its instruction(s) don't manually consume units.

#### Summary of Changes
- consumes builtin.default_compute_unit_cost if its instruction didn't deduct units.

Feature Gate Issue: #30620

### CODE REVIEW

**Review by joncinque — COMMENTED** [review]
The change looks good, but doesn't this need to use the feature gate mentioned at #30620?

**Comment by taozhu-chicago** [comment]
> The change looks good, but doesn't this need to use the feature gate mentioned at #30620?

Yes you are right. Was meant to highlight the main change before it's buried by many other changes to tests and necessary stuffs like feature gate. Sorry for generating additional notification. 

Also, @Lichtso brought up the change conflict [here](https://github.com/solana-labs/solana/pull/30639#issuecomment-1466014875). I'll work with him to solve that conflict first (before getting back to this PR)

**Comment by taozhu-chicago** [comment]
what do you guys think about [this](https://github.com/solana-labs/solana/pull/30702) approach? doesn't need to add `default_compute_unit_cost` to builtin, each instruction can consume different units at beginning of processing.

**Comment by taozhu-chicago** [comment]
both this and #30702 will have tons of failed tests since they are charging units for builtins now. I will clean them up once winner is picked 🏆

**Comment by taozhu-chicago** [comment]
close this, and revert #30639 in favor of #30702

**Pull request closed without merging**
