### PR TITLE
ci: add macos clippy test

### PR DESCRIPTION
**Pull request by yihau**
#### Problem

we may accidentally merge some code that can break the macOS/Windows build

#### Summary of Changes

run clippy for macos.

(I would like to have Windows as well but it takes me too much time to fix 😢 so let's ship macos first)

### CODE REVIEW

**Comment by t-nelson** [comment]
thanks! looking pretty good. is this a problem?

Screenshot from 2023-11-29 15-00-33

also i think @CriesofCarrots mentioned that there's a bench that still fails macos clippy, but i don't see it raised here. not sure if it's been fixed or we aren't running against benches?

**Comment by yihau** [comment]
> is this a problem?

where did you get this one 🤔  this is mine from [here](https://github.com/solana-labs/solana/actions/runs/7037311835/job/19151828050)
<details>
  <summary>screenshot</summary>
  <image src="https://github.com/solana-labs/solana/assets/8209234/515addf7-1ad9-4c6b-80d7-b85db3e1cbbf"/>
</details>

--- 

> also i think CriesofCarrots mentioned that there's a bench that still fails macos clippy, but i don't see it raised here. not sure if it's been fixed or we aren't running against benches?

weird. I don't see any complains from this pipeline. let's wait for her insight!

**Comment by t-nelson** [comment]
> where did you get this one 🤔 this is mine from [here](https://github.com/solana-labs/solana/actions/runs/7037311835/job/19151828050)

weird. looks fine on this run. not sure how to dig through historical ones, but it showed an error when i first reviewd

**Review by CriesofCarrots — APPROVED** [review]
That bench that fails clippy on my machine is doing so because it calls `jit_compile()`, which is only available for x86_64. I'm on silicon and do not have rosetta installed, whereas the CI runner is intel.
I think we can move forward with this PR for now, but it might be nice to add an arm64 runner in the future.
Meanwhile, I'll PR tagging that bench as x86_64-only.

**Comment by yihau** [comment]
@CriesofCarrots sorry for the force push. I didn't notice you already have a PR for tagging. just removed mine.

**Review by CriesofCarrots — APPROVED** [review]

**Comment by CriesofCarrots** [comment]
Hey @yihau , the macos clippy job didn't run on [this PR](https://github.com/solana-labs/solana/pull/34374) to v1.16, and hence [automerge did not work](https://github.com/solana-labs/solana/runs/19465977129).
I think we need to backport this to fix automerge for stable and beta?

**Comment by yihau** [comment]
yeah! we should have it for v1.16 and v1.17! thank you for brining this up!

**Pull request merged**
