### PR TITLE
BorrowedAccount: tweak data APIs

### PR DESCRIPTION
**Pull request by alessandrod**
Introduce `extend_from_slice(data)`, so that the following:

	let mut data = account.get_data_mut(); // malloc + memcpy if the underlying refcount > 1
	data.extend_from_slice(data_to_append); // memcpy
	account.set_data(&data) // malloc + memcpy to make the data owned, free(data)

Becomes:

	// malloc + memcpy if the underlying refcount > 1, + memcpy to append the data
	account.extend_from_slice(data_to_append);

Also make `set_data(data)` itself take data by value. Most callers were doing `set_data(&vec![...])`, which incurs in the extra malloc + memcpy + free as shown above.

Finally, this removes `AccountSharedData::set_data_from_slice(data)`. There are no users left and it had bad perf characteristics.

### CODE REVIEW

**Comment by jeffwashington** [comment]
As a reviewer, I would prefer `extend_from_slice` get introduced first or whatever makes sense, in its own pr. Since there are 'alsos' here, I have to keep several different complicated changes in my head at once and think about correctness, why it may have been like that, why it should change, etc.

**Comment by alessandrod** [comment]
> As a reviewer, I would prefer `extend_from_slice` get introduced first or whatever makes sense, in its own pr. Since there are 'alsos' here, I have to keep several different complicated changes in my head at once and think about correctness, why it may have been like that, why it should change, etc.

I don't mind creating a separate PR, but I've split it in two separate commits on purpose. If in the review tab you click on the commits individually, you can review each individually.

**Comment by jeffwashington** [comment]
Yes, but the first is both
add extend_from_slice
and
change signature of set_data
Those are the 2 i'd like separated. Commits or prs. I like prs myself. But, I'm ok either way.

**Comment by alessandrod** [comment]
I'm closing this in favor of https://github.com/solana-labs/solana/pull/27836 since I've changed things and the current description doesn't apply anymore. Then I have two more PRs I'll submit separately.

**Pull request closed without merging**
