### PR TITLE
Revert "Migrate from ring to ed25519-dalek"

### LINKED ISSUE #1789: Fix TPS regression
#### Problem
Something broke with master over the weekend. TPS on gce testnets seems to average out to num validators.

#### Proposed Solution
Debug and fix the broken tip.

### PR DESCRIPTION
**Pull request by sagar-solana**
This reverts commit 7c610b216b86c796977493b7441e88fd390cb72e.

#### Problem
Moving to ed25519-dalek broke something with transactions. 

#### Summary of Changes
Reverted change to pull in ed25519-dalek.

Fixes #1789

### CODE REVIEW

**Comment by sagar-solana** [comment]
Confirmed this revert fixes the low tps issue. Ran my gce testnet and tps looked good.
Please take a look at the revert since I had a lot of manual conflict resolving to do to revert this.

**Comment by mvines** [comment]
oh nm :)

**Comment by mvines** [comment]
"Ran my gce testnet and tps looked good." -- that's a better state than we're currently in, so assuming CI is green then my r+ holds

**Comment by mvines** [comment]
Bummer:
```
error[E0599]: no method named `to_bytes` found for type `ring::signature::KeyPair` in the current scope
--
  | --> src/wallet.rs:1257:45
  | \|
  | 1257 \|             read_keypair(&outfile).unwrap().to_bytes().to_vec(),
  | \|
```

**Comment by sagar-solana** [comment]
I knew it! should have run test before submitting. I'll update it.

**Pull request merged**
