### PR TITLE
Rename `AccountsDataMeter::consume`

### LINKED ISSUE #23022: Rename AccountsDataMeter::consume()
nit: I found the name of this function and it's description like reading double negatives.  Maybe `consume` is not the best name for this function because we are not just using up a resource, but also replenishing it.  Maybe rename to `adjust_delta`, `adjust_remaining` or something along those lines?

_Originally posted by @jackcmay in https://github.com/solana-labs/solana/pull/22986#discussion_r802163403_

### PR DESCRIPTION
**Pull request by mooori**
#### Problem

The name of `AccountsDataMeter::consume()` might be misleading.

#### Summary of Changes

- Rename it `AccountsDataMeter::adjust_delta`
- Update doc-comment
- Update names of test functions and comments inside tests

Fixes #23022

### CODE REVIEW

**Comment by mooori** [comment]
Triggered CI a few times, it keeps failing with:
```
Received cancellation signal, interrupting
```

This PR just changes function names and updates comments, so I'm marking as ready for review despite the failure.

**Comment by brooksprumo** [comment]
Thanks for this work, @mooori! 

There's actually a decent chance that we need to move in a different direction for the overarching design and use of `AccountsDataMeter`, which may obviate the need for this change. Let me try to resolve that first; thanks in advance for understanding!

**Comment by mooori** [comment]
@brooksprumo rebase/resolve are done. In the meantime `consume_unchecked` was added, which I renamed to `adjust_delta_unchecked` to match the rest of the PR.

**Review by brooksprumo — APPROVED** [review]
Looks good! Thanks for your submission, @mooori 🙌

**Pull request merged**
