### PR TITLE
On-chain test program for Lamport transfer using CPI

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
Currently `bench-tps` uses system program to perform transfer operation. It doesn't exercise bulk of runtime/VM and CPI code path.

#### Summary of Changes
This PR adds a new on chain program that performs transfer using CPI. The bench-tps tool can be updated to use this program for testing and benchmarking.

Fixes #

### CODE REVIEW

**Comment by KirillLykov** [comment]
Looks good, the thing that I don't know if we have convention to put all the programs to programs repo or not. Because previously added program to test transactions with configurable number of accounts is not part of this repo. @joncinque do we have some convention?

Another thing is maybe we would like to make this program configurable so that it can be used to imitate CU-heavy txs or CPI calls. If this is the case, maybe call it a bit more generic? Or we can rename later

**Review by KirillLykov — APPROVED** [review]

**Comment by pgarg66** [comment]
> Looks good, the thing that I don't know if we have convention to put all the programs to programs repo or not. Because previously added program to test transactions with configurable number of accounts is not part of this repo. @joncinque do we have some convention?
> 
> 
> 
> Another thing is maybe we would like to make this program configurable so that it can be used to imitate CU-heavy txs or CPI calls. If this is the case, maybe call it a bit more generic? Or we can rename later

Both are fair points. I'll rename it to remove "transfer" from its name. Happy to move it elsewhere if that aligns better. The reason to put it next to bench-tps was to indicate its purpose and prevent accidental changes to it without corresponding updates to bench.

**Comment by pgarg66** [comment]
Updated the program name to make it more generic.

**Comment by joncinque** [comment]
You can already do this in bench-tps with the instruction padding program! If you deploy https://github.com/solana-labs/solana/blob/master/bench-tps/tests/fixtures/spl_instruction_padding.so to a cluster, and use its program id with 0 padding bytes, it'll do exactly what you want.

For example, you can do:

```
$ solana-bench-tps --instruction-padding-data-size 0 --instruction-padding-program-id <your_program_id> <all_other_args>
```

**Comment by pgarg66** [comment]
> You can already do this in bench-tps with the instruction padding program! If you deploy https://github.com/solana-labs/solana/blob/master/bench-tps/tests/fixtures/spl_instruction_padding.so to a cluster, and use its program id with 0 padding bytes, it'll do exactly what you want.
> 
> For example, you can do:
> 
> ```
> $ solana-bench-tps --instruction-padding-data-size 0 --instruction-padding-program-id <your_program_id> <all_other_args>
> ```

That's pretty cool. I'll close this PR.

**Pull request closed without merging**
