### PR TITLE
Undo breaking rpc removal of getSignatureConfirmation

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#9245 for v1.0

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
@mvines , it's kind of tempting to backport this as well, so that these are real cluster confirmations: https://github.com/solana-labs/solana/commit/50fa577af85ea60e3f73de3c8bfc057b8ad0e157
It doesn't matter for the purposes of unbreaking TW, though.

**Comment by mvines** [comment]
meh let's do the minimum to unblock TW, and then get them to move to the API we want going for the future

**Comment by CriesofCarrots** [comment]
> meh let's do the minimum to unblock TW, and then get them to move to the API we want going for the future
The confirmations fix applies to `getSignatureStatus` as well, but np, I won’t let that hold this up.

**Comment by mvines** [comment]
Got it, yeah I'd be fine with a backport of 50fa577 as well if that improves the explorer/TW experience

**Pull request merged**
