### PR TITLE
Make debug_id available to all Pubkeys

### PR DESCRIPTION
**Pull request by garious**
Has `debug_id` been generally useful? If so, let's improve the ergonomics by pulling it into Pubkey.

### CODE REVIEW

**Comment by aeyakovenko** [comment]
Debug id is slightly faster then the format string for Pubkey.   I think we can get rid of it in favor of just using the default format for the Pubkey type

**Comment by garious** [comment]
@aeyakovenko, so do you want to move forward with this change? Can we finalize something different? I'd prefer to get a half-baked solution out of there. It makes some refactoring tricky to drag around larger data types for its `debug_id()` method. Sounds like we could create a DebugId trait?

**Comment by aeyakovenko** [comment]
@garious, the annoying thing is that the encoding for debug_id is different than for the format of the Pubkey. I think we can just boot this and print the Pubkey directly.

**Comment by garious** [comment]
Sounds good, thanks.

**Pull request closed without merging**
