### PR TITLE
Change cargo fmt to --check instead of --write-mode

### PR DESCRIPTION
**Pull request by sakridge**
argument has changed

### CODE REVIEW

**Comment by mvines** [comment]
What’s the reason for this change?  I’m not too familiar with the different cargo fmt modes

**Comment by mvines** [comment]
Hmm, stable doesn’t understand —check?

**Comment by sakridge** [comment]
@mvines https://github.com/rust-lang-nursery/rustfmt/issues/2832#issuecomment-403317829

Seems that rust 1.28 stable will not recognize --write-mode. Anatoly reported it in discord, but I'm not sure where he saw it. I think we are still using 1.27, so maybe this change is premature until we update.

**Comment by mvines** [comment]
#842

**Pull request closed without merging**
