### PR TITLE
Colo: Don't fail without a message

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

Some logical failures can exit without printing

#### Summary of Changes

Print a messages wherever we can exit with failure

### CODE REVIEW

**Comment by t-nelson** [comment]
cc/ @pgarg66 Give this a try once it's merged

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Pull request merged**
