### PR TITLE
Sanitize preflight

### LINKED ISSUE #11371: Invalid transaction data can cause node to panic
#### Problem
Invalid transaction data can cause unexpected node termination.
Further details to be provided under separate cover.

Found in TdS Stage ##6

#### Proposed Solution
To be discussed.

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

RPC preflight checks don't verify transaction sanity

#### Summary of Changes

Check it

Fixes #11371

### CODE REVIEW

**Comment by t-nelson** [comment]
https://github.com/solana-labs/solana/pull/11373/commits/7d093f4beeab5a4ca797fb6018733279f575550c feels kinda wrong, but sigverifying an unsanitized tx is kinda ambiguous anyway

**Comment by mvines** [comment]
> [7d093f4](https://github.com/solana-labs/solana/commit/7d093f4beeab5a4ca797fb6018733279f575550c) feels kinda wrong, but sigverifying an unsanitized tx is kinda ambiguous anyway

I was about to comment on that, it does seem wrong.   Can we explicitly sanitize first?  That's essentially what happens in the normal pipeline anyway

**Comment by t-nelson** [comment]
> Can we explicitly sanitize first?

We can, yeah.  It makes me a little uneasy that there's not OneGoodSpot(TM) for this check, though.  TX sanity isn't actually checked until just before (literally same function) we take account locks.  I think that's the first actual use since deser, but they're so far apart in the code that it seems like it'll be pretty easy to wedge a DoS opportunity in between them by accident.

**Comment by mvines** [comment]
> > Can we explicitly sanitize first?

Actually I think we can just revert 7d093f4.   You're right, we don't sanitize before sigverifying in the normal flow so let's be consistent here too.   

> We can, yeah. It makes me a little uneasy that there's not OneGoodSpot(TM) for this check, though. TX sanity isn't actually checked until just before (literally same function) we take account locks. I think that's the first actual use since deser, but they're so far apart in the code that it seems like it'll be pretty easy to wedge a DoS opportunity in between them by accident.

Yeah this isn't great.  @Reisen had a similar comment a while ago about how we don't have that OneGoodSpot either :-/

**Comment by t-nelson** [comment]
https://github.com/solana-labs/solana/commit/7d093f4beeab5a4ca797fb6018733279f575550c has been dropped

**Pull request merged**
