### PR TITLE
Generate coverage with Rust nightly

### LINKED ISSUE #177: Test-drive new coverage tooling in Rust nightly
Here's how they hacked it in without Rust modifications:

https://jbp.io/2017/07/19/measuring-test-coverage-of-rust-programs.html

But that was unappealing to us because of the hardcoded LLVM paths and versions. However, in the nightly build, they added a `-Zprofile` which points the compiler to its own copy of LLVM.

Perhttps://github.com/rust-lang/rust/pull/42433:

```
@ofek Same as https://jbp.io/2017/07/19/measuring-test-coverage-of-rust-programs, but use -Zprofile instead of -Cpasses=insert-gcov-profiling -L/usr/lib/llvm-3.8/lib/clang/3.8.1/lib/linux/ -lclang_rt.profile-x86_64.
```

But per https://github.com/rust-lang/rust/issues/42524, it looks like we an expect trouble if we don't pin down the nightly version:

https://github.com/rust-lang/rust/issues/50203

### PR DESCRIPTION
**Pull request by garious**
Fixes #177

Thanks @marco-c!

### CODE REVIEW

**Comment by mvines** [comment]
Need to update https://github.com/solana-labs/solana/blob/master/ci/coverage.sh#L13 as well

**Comment by garious** [comment]
Hey @mvines, I can't seem to reproduce the nightly build within docker on macos. It gets stuck compiling pnet_transport when installing cargo-cov.

In CI, this build fails because gcov fails, which is called by the codecov bash script. To fix, we probably need a gcov version that matches Rust's coverage instrumentation. The cargo-cov repo suggests installing `libclang-common-6.0-dev` on Ubuntu. I assume that'll install `llvm.gcov`. We'd need to tell the codecov script to use that `gcov_exe` instead of `gcov`.  Ideally, Rust would deploy `llvm.gcov`. There's an open ticket to add some LLVM tools, but that list doesn't currently include `llvm.gcov`: https://github.com/rust-lang/rust/issues/49584   @marco-c, any related info we should be aware of?

**Comment by marco-c** [comment]
The problem is that the codecov tool is trying to use `gcov`, but `gcov` is the gcc tool which parses a different version of the gcno/gcda format.
It should use `llvm-cov`.
A possible solution is to generate the codecov output yourself (e.g. using [grcov](https://github.com/mozilla/grcov)) and upload it yourself. Perhaps we should add this to cargo-cov.

**Comment by marco-c** [comment]
Or you could try this "hack": https://github.com/codecov/codecov-bash/issues/55#issuecomment-370807218.

**Comment by marco-c** [comment]
(to use grcov with Rust-generated files you need to pass the `--llvm` option)

**Comment by garious** [comment]
Thanks @marco-c, I confirmed that adding the `--llvm` option gets `grcov` to run out-of-the-box on macOS.

**Pull request merged**
