### PR TITLE
Revert "Revert "revert-revert-erasure and erasure fixes (#3833)" (#3855)"

### PR DESCRIPTION
**Pull request by rob-solana**
This reverts commit 596f611ede4018b5ccfcff533b1464c3dcbef946.

 #### Problem
 one more try!

 #### Summary of Changes
 on master, with Entry::serialized_size() fix

### CODE REVIEW

**Comment by rob-solana** [comment]
@pgarg66 can you see if this still blows up immediately?

**Comment by pgarg66** [comment]
> @pgarg66 can you see if this still blows up immediately?

Sure, I'll cherry pick it.

**Comment by pgarg66** [comment]
@rob-solana , it's crashing with this PR as well.

```
[2019-04-18T22:30:50.393235150Z WARN  solana::cluster_info] EBQTDCxKq3MQGzqcCk9SLK3mhosvVyGVUyYiCGPw7F5K: LEADER_UP
DATE TO EBQTDCxKq3MQGzqcCk9SLK3mhosvVyGVUyYiCGPw7F5K from EBQTDCxKq3MQGzqcCk9SLK3mhosvVyGVUyYiCGPw7F5K
./multinode-demo/bootstrap-leader.sh: line 88: 13009 Illegal instruction     (core dumped) $program --identity "$bo
otstrap_leader_id_path" --voting-keypair "$bootstrap_leader_vote_id_path" --vote-account "$bootstrap_leader_vote_id
" --ledger "$SOLANA_CONFIG_DIR"/bootstrap-leader-ledger --accounts "$SOLANA_CONFIG_DIR"/bootstrap-leader-accounts -
-gossip-port 8001 --rpc-port 8899 --rpc-drone-address 127.0.0.1:9900 "${extra_fullnode_args[@]}" > >($bootstrap_lea
der_logger) 2>&1
./multinode-demo/bootstrap-leader.sh: line 88: kill: (13009) - No such process
```

**Comment by rob-solana** [comment]
are you on tip of master?  you also 

> @rob-solana , it's crashing with this PR as well.
> 
> ```
> [2019-04-18T22:30:50.393235150Z WARN  solana::cluster_info] EBQTDCxKq3MQGzqcCk9SLK3mhosvVyGVUyYiCGPw7F5K: LEADER_UP
> DATE TO EBQTDCxKq3MQGzqcCk9SLK3mhosvVyGVUyYiCGPw7F5K from EBQTDCxKq3MQGzqcCk9SLK3mhosvVyGVUyYiCGPw7F5K
> ./multinode-demo/bootstrap-leader.sh: line 88: 13009 Illegal instruction     (core dumped) $program --identity "$bo
> otstrap_leader_id_path" --voting-keypair "$bootstrap_leader_vote_id_path" --vote-account "$bootstrap_leader_vote_id
> " --ledger "$SOLANA_CONFIG_DIR"/bootstrap-leader-ledger --accounts "$SOLANA_CONFIG_DIR"/bootstrap-leader-accounts -
> -gossip-port 8001 --rpc-port 8899 --rpc-drone-address 127.0.0.1:9900 "${extra_fullnode_args[@]}" > >($bootstrap_lea
> der_logger) 2>&1
> ./multinode-demo/bootstrap-leader.sh: line 88: kill: (13009) - No such process
> ```

are you on tip of master?  you need the entry::serialized_size fix, first

**Comment by pgarg66** [comment]
I am at this commit: 060793f45194cb025902b79f32e30fb6085866e3

**Comment by rob-solana** [comment]
ok, close enough ;)

**Pull request merged**
