### PR TITLE
Drop storage lock

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Locks not dropped in a consistent order.

#### Summary of Changes

Drop storage, then accounts lock

Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
Does this affect v1.0 too?

**Comment by sakridge** [comment]
> Does this affect v1.0 too?

yes

**Comment by mvines** [comment]
@Mergifyio backport v1.0

**Comment by mvines** [comment]
🤦‍♂ epic mergify fail

**Pull request merged**
