### PR TITLE
Add SOLANA_MAX_DEDUPER_AGE_MILLIS as an env-var

### PR DESCRIPTION
**Pull request by apfitzge**
#### Problem
#33406
Want to test & evaluate using a longer interval for the `Dedup`.
The current maximum age allows for many duplicate forwarded packets into banking stage. 

#### Summary of Changes
SOLANA_MAX_DEDUPER_AGE_MILLIS environment variable can be used to control the maximum deduper age in SigVerifyStage.
If it is not set, it defaults to the current value of 2s (2_000 millis).

Fixes #

### CODE REVIEW

**Comment by apfitzge** [comment]
Chose to use an environment variable, because if we want testing on MNB we may want to backport this.
Using an env-var requires significantly fewer conflicts since we don't need to pipe a variable all the way from cli to sigverify

**Comment by steviez** [comment]
We do have some staked nodes on testnet that you can try things out with. I haven't looked recently so not sure if the forward load would be comparable or not, but just throwing that out there incase you were unaware. I'm not sure of the process for getting that node, can probably ping one of the Slack channels tho

Also, is age the only parameter that would need to be tuned? Do you know if the deduper is getting saturated as-is / would get saturated if it resets less often ?

**Comment by behzadnouri** [comment]
I totally agree that `MAX_DEDUPER_AGE` could possibly be optimized. For turbine for example we use 5 minutes:
https://github.com/solana-labs/solana/blob/cc4e9283d/turbine/src/sigverify_shreds.rs#L22
Turbine is more tolerant of false positives though, because 50% of shreds are redundant anyways and there is also a separate repair path. TPU obviously has different tolerance profile with respect to false positives.

That being said, I am kind of hesitant to check in an env variable config into the master branch code, because:
* We obviously don't want to encourage (or make it easier for) operators to mis-config this code.
* On machines/environments that we can set env variables, we already have the full ability to build from a custom branch code, so no need to merge the change into the master.

**Comment by apfitzge** [comment]
> On machines/environments that we can set env variables, we already have the full ability to build from a custom branch code, so no need to merge the change into the master.

Fair enough

**Pull request closed without merging**
