### PR TITLE
RPC: respect data slice config if account parsing fails

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
RPC account encoding ignores the data slice config when falling back to base64 encoded account data when `jsonParsed` encoding fails

#### Summary of Changes
If `jsonParsed` encoding fails, ensure that the data slice config is still used when doing base64 encoding

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
Hmm looks like RPC explicitly rejects using the data slice config in `check_slice_and_encoding` if `jsonParsed` is used. I think it's ok to pass it in case parsing fails. Thoughts @CriesofCarrots?

**Review by CriesofCarrots — APPROVED** [review]
Agreed, I like it.

That is to say: I think we can update `check_slice_and_encoding` to relax that behavior. Since jsonParsed falls back to base64, it definitely seems useful to allow data slice config. We just need to document that the slice only applies to accounts that aren't parsed, and ones that are parsed reflect all data.

**Comment by jstarry** [comment]
> That is to say: I think we can update check_slice_and_encoding to relax that behavior (ie. remove that method). Since jsonParsed falls back to base64, it definitely seems useful to allow data slice config. We just need to document that the slice only applies to accounts that aren't parsed, and ones that are parsed reflect all data.

I appended another commit to this PR which removes that method and updates the documentation for `dataSlice`

**Review by CriesofCarrots — APPROVED** [review]
Nice, thank you!

**Pull request merged**
