### PR TITLE
Disable parent dir removal on accounts drop

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Crashes in CI because accounts dirs are removed.

#### Summary of Changes

Don't delete parent accounts dir on accounts drop.

Fixes #

### CODE REVIEW

**Comment by rob-solana** [comment]
this fix is roughly right...  I have reworked my #5230 to make accounts_db own/create/remove the directories

the race condition: when any bank drops one of the test-based Accounts instance, the directory gets whacked.  this usually doesn't matter unless we're trying to create a new appendvec right at that instant between when accounts_db calls create_dir_all() and the append_vec creates its file.

other appendvecs continue to work fine because the open file descriptors keep the storage around, even though we've created a bunch of directories that have come and gone with the banks

**Comment by sakridge** [comment]
> this fix is roughly right... I have reworked my #5230 to make accounts_db own/create/remove the directories
> 
> the race condition: when any bank drops one of the test-based Accounts instance, the directory gets whacked. this usually doesn't matter unless we're trying to create a new appendvec right at that instant between when accounts_db calls create_dir_all() and the append_vec creates its file.
> 
> other appendvecs continue to work fine because the open file descriptors keep the storage around, even though we've created a bunch of directories that have come and gone with the banks
> 
> updated in #5230

Each accounts has that unique pubkey dir though. Shouldn't it be destroying it's own unique dir?

**Comment by rob-solana** [comment]
> > this fix is roughly right... I have reworked my #5230 to make accounts_db own/create/remove the directories
> > the race condition: when any bank drops one of the test-based Accounts instance, the directory gets whacked. this usually doesn't matter unless we're trying to create a new appendvec right at that instant between when accounts_db calls create_dir_all() and the append_vec creates its file.
> > other appendvecs continue to work fine because the open file descriptors keep the storage around, even though we've created a bunch of directories that have come and gone with the banks
> > updated in #5230
> 
> Each accounts has that unique pubkey dir though. Shouldn't it be destroying it's own unique dir?

nope the pubkey is from accounts0, bank0: https://github.com/solana-labs/solana/blob/5608af0246b2a236e1e400d069b18db433031064/runtime/src/accounts.rs#L128

**Comment by sakridge** [comment]
@rob-solana ok. should we merge this then?

**Comment by rob-solana** [comment]
no, #5230

**Pull request closed without merging**
