### PR TITLE
SDK: Allow `RecentBlockhashes` to hold the entire `BlockhashQueue`

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

`RecentBlockhashes` sysvar only hold a subset of the `BlockhashQueue`, limiting its potential

#### Summary of Changes

Bump `recent_blockhashes::MAX_ENTRIES`
Add a test that `RecentBlockhashes` can hold the entire `BlockhashQueue`
Fix up some naughty users hardcoding the `MAX_ENTRIES` value

### CODE REVIEW

**Comment by t-nelson** [comment]
@mvines as discussed in #8609

**Comment by mvines** [comment]
Looks good but we might only need `MAX_PROCESSING_AGE` blockhashes, as the bottom 50% aren't accepted for new transactions anymore

**Comment by t-nelson** [comment]
Moving that `MAX_PROCESSING_AGE` is just a runtime change, right?  Whereas moving `MAX_RECENT_BLOCKHASHES` would break snapshot (and potentially this) ABI.  Just thinking, "How easy can/should this change?"

**Comment by mvines** [comment]
It should be hard to change, but until ABI lockdown lands I guess it's up to us.  MAX_PROCESSING_AGE is likely to not change so not too worried in the meantime.  

But beyond that, MAX_RECENT_BLOCKHASHES / 2 makes sense right?

**Comment by t-nelson** [comment]
Oh yeah, it's totally plenty, IMO.  I'm just cautious to put that ABI requirement on `MAX_PROCESSING_AGE`

**Comment by t-nelson** [comment]
@mvines what's the word here.  Go with just `MAX_PROCESSING_AGE` and hope we don't need to move that value?

**Comment by mvines** [comment]
> @mvines what's the word here. Go with just `MAX_PROCESSING_AGE` and hope we don't need to move that value?

Yep!  `MAX_PROCESSING_AGE` hasn't changed in over a year.  It's pretty stable.   If it needs to change later we'll figure it out

**Comment by garious** [comment]
@t-nelson, @mvines, need this to be all 300 blockhashes. If not in the 150, you can stop resending retries, but you can't yet resign and send a new transaction. To resign, you need to be sure the leader's block isn't still in flight. The RPC node will accept transaction if its blockhash is anywhere in that full 300.

**Comment by t-nelson** [comment]
@mvines is there an upcoming regularly scheduled ABI breakage we can slip this in with?

**Comment by mvines** [comment]
New github issue please, let's not discuss on merged pull requests

**Pull request merged**
