### PR TITLE
Remove unused deps

### PR DESCRIPTION
**Pull request by kevinheavey**
#### Problem
A lot of the crates in here have unused dependencies.

#### Summary of Changes

Removed some unused dependencies that I noticed. This is not intended to be comprehensive.

### CODE REVIEW

**Comment by kevinheavey** [comment]
I think the two failing checks are fine?

**Comment by behzadnouri** [comment]
> I think the two failing checks are fine?

Try running
```
./scripts/cargo-for-all-lock-files.sh tree
```
and commit its changes.

**Comment by kevinheavey** [comment]
Ok test-stable-bpf.sh and test-wasm.sh are failing but the errors don't mean a lot to me

**Comment by joncinque** [comment]
Thanks for your contribution! I dug in a little bit, and found a fix for it. In `sdk/Cargo.toml`, `rand` needs to have the `wasm-bindgen` feature, ie:

```
-rand = { version = "0.7.0", optional = true }
+rand = { version = "0.7.0", optional = true, features = ["wasm-bindgen"] }
```

**Comment by kevinheavey** [comment]
These coverage failures don't mean much to me, anyone got any ideas?

**Comment by CriesofCarrots** [comment]
> These coverage failures don't mean much to me, anyone got any ideas?

We're currently chasing some flakiness in that coverage step; not related to your changes.

Btw, we're not too keen on merge commits. Could you `git pull --rebase` in future?

**Comment by kevinheavey** [comment]
Anyone got any idea what the latest CI failures are?

**Comment by CriesofCarrots** [comment]
> Anyone got any idea what the latest CI failures are?

@dmakarov , can you please consult on the solana-program rebuilds regression?

**Comment by dmakarov** [comment]
The extra dependencies are needed to reduce the amount of redundant rebuilds when crates in `programs/bpf/rust/` are built in our CI. Please, do not remove them only because they seem unused. They allow us to control specific versions of indirectly dependent crates pulled by cargo when solana-program crate is being built. A lot of effort went into tuning the *.toml files.

**Comment by kevinheavey** [comment]
Which dependencies need to stay?

**Comment by dmakarov** [comment]
See #26369

**Comment by kevinheavey** [comment]
> See #26369

The one Cargo.toml in common between that PR and this one is sdk/program/Cargo.toml,, where I removed the dependency `tiny-bip39 = "0.8.2"`. Are you saying I should add this dependency back?

**Comment by dmakarov** [comment]
if you rebase and buildkite/solana/checks pass, then it should be ok to remove the dependencies.

**Comment by kevinheavey** [comment]
I can't tell which change is the source of that regression, so sounds like it might be easier if I make separate PRs for each crate. I'll leave this PR open for now in case I figure it out

**Pull request closed without merging**
