### PR TITLE
Add .codecov.yml with checks disabled

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

restored codecov caused some issues: https://discord.com/channels/428295358100013066/560503042458517505/1083472186305675435

this is original yml (no text; took only screenshot when reviewing codecov's settings before enabling; never expected this would cause troubles and yml is nuked now... lol):

image

#### Summary of Changes

- Removed `fixes: ... web3` thing (no longer needed thanks to #30062)
- Added `github_checks: false`. (this is crucial not to block merge, i think)

#### Sanity checks

```
$ curl --data-binary @.codecov.yml https://codecov.io/validate
Valid!

{
  "comment": {
    "behavior": "default",
    "layout": "diff",
    "require_changes": false
  },
  "coverage": {
    "precision": 1,
    "range": [
      50.0,
      100.0
    ],
    "round": "down",
    "status": {
      "patch": false,
      "project": false
    }
  },
  "github_checks": false
}

```

### CODE REVIEW

**Review by yihau — DISMISSED** [review]
🪖

**Comment by ryoqun** [comment]
previously, the final codecov.yml got resolved like this (see `github_checks`):

image

**Comment by ryoqun** [comment]
if things are working correctly, this pr _itself_ start to show **no** codecov checks displayed like below (affected prs needs to rebase after this pr got merged):

https://github.com/solana-labs/solana/pull/30654:

image



https://github.com/solana-labs/solana/pull/30616

image

**Comment by ryoqun** [comment]
image

@yihau /me sad: https://github.com/solana-labs/solana/pull/30666/commits/88256530515260f6436bc4087cd3114831a34fe5

**Comment by ryoqun** [comment]
> @yihau /me sad: [8825653](https://github.com/solana-labs/solana/commit/88256530515260f6436bc4087cd3114831a34fe5)

this is actually (hopefully) the last nicety to flush out from my brain; full ci build should be triggered for any `./ci` `./script` changes for careless part-time ci contributors. lol

**Review by yihau — APPROVED** [review]
the tricky part is that you only add .codecov.yml in this PR. CI doesn't know this new guy haha

**Comment by ryoqun** [comment]
> @[ryoqun](https://github.com/ryoqun) ryoqun added the v1.14 label now

This is required because i think backported prs is affected as well.

**Comment by yihau** [comment]
not sure do we need to backport. according to this one. https://docs.codecov.com/docs/codecov-yaml#default-branch I think codecov is the same as mergify. it will always take the default branch's config file

**Comment by ryoqun** [comment]
> if things are working correctly, this pr _itself_ start to show **no** codecov checks displayed like below (affected prs needs to rebase after this pr got merged):

it is working. codecov is gone from the checks committee:

image

**Pull request merged**
