### PR TITLE
Add compute_budget_program to the native_program_id list

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

Compute budget program id missing from native program id list

#### Summary of Changes

Add it

Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
Do we really need to whitelist all new native programs here?  I feel it's overkill and causes feature activation pain (eg, what's happening over yonder in https://github.com/solana-labs/solana/pull/19266)

**Comment by jackcmay** [comment]
@t-nelson Thoughts on whether we need to whitelist all native programs when computing program addresses?

**Comment by jackcmay** [comment]
> @t-nelson Thoughts on whether we need to whitelist all native programs when computing program addresses?

Trent reminded me of: https://github.com/solana-labs/solana/security/advisories/GHSA-gh6m-fpgg-f9m8#advisory-comment-66920

@mvines @t-nelson 

Looks like we added these native program checks for good measure without citing a direct threat.  

I think we can probably exclude precompiles in that list since there aren't any accounts owned by them and they aren't programs that can be directly called via cpi.  This would mean removing the secp256k1 program and not including the compute_budget_program.

Thoughts on whether we should include the rest of the builtins?  If so I have a pr in progress that will allow us to featurize any changes to the list as well as keep the list in sync with the featurized one.

**Comment by mvines** [comment]
> I think we can probably exclude precompiles in that list since there aren't any accounts owned by them and they aren't programs that can be directly called via cpi. This would mean removing the secp256k1 program and not including the compute_budget_program.

Keeping secp256k1 at this point seems harmless, I agree on not including compute_budget_program, or the upcoming ed25519_program

> Thoughts on whether we should include the rest of the builtins? If so I have a pr in progress that will allow us to featurize any changes to the list as well as keep the list in sync with the featurized one.

The current list again seems like we can just leave as it, the ROI on pruning it seems low.

**Comment by jackcmay** [comment]
> The current list again seems like we can just leave as it, the ROI on pruning it seems low.

My concern is the longer-term confusion as to why we are including some ids and not others.  For example, we are working on a new program ABI that will come along with new loaders, should those loaders be added to the list?  They will interact with accounts they own and very probably use PDAs...

**Comment by jackcmay** [comment]
> Yeah totally. Comments in the code on the motivation for that list could help as well

Yup, but that's the thing, we don't have a clear motivation besides, to be on the safe side, but the safe side of what? ;-)

Possible clear lines could one of the following:
-  all natively known ids except pre-compiles
-  any program that interacts with accounts it owns or depends on an account being signed

This list is also troubling because there isn't anything unique about these programs compared to developer deployed programs except they are known and some perform cluster critical duties.  Maybe that's enough, but one could raise the question of if we are protecting these programs against threat X, how are we protecting developer's programs against threat X.

**Comment by mvines** [comment]
Amen brother! I'm not a fan of the list at all, because like you said it makes native programs subtly different from non-native programs.

**Comment by jackcmay** [comment]
> Amen brother! I'm not a fan of the list at all, because like you said it makes native programs subtly different from non-native programs.

Check with @CherryWorm who initially brought up the threat related to this check being added and they said they don't see any reason to keep  the check either, so: https://github.com/solana-labs/solana/pull/19595

**Comment by jackcmay** [comment]
We are removing the list altogether so closing his PR: https://github.com/solana-labs/solana/pull/19595

**Pull request closed without merging**
