### PR TITLE
Upgrade to Rust v1.63.0

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by mvines** [comment]
Two "coverage" job attempts on different machines failed at:
```
bank::tests::test_remove_unrooted_before_scan
bank::tests::test_remove_unrooted_scan_interleaved_with_remove_unrooted_slots
bank::tests::test_remove_unrooted_scan_then_recreate_same_slot_before_scan
```

**Comment by mvines** [comment]
Same coverage failures as before, but https://github.com/solana-labs/solana/pull/26115 resolves most of the latest nightly clippy issues to avoid bloating the scope of this issue

**Comment by brennanwatt** [comment]
Looks like we are timing out in `test_store_scan_consistency` scanning banks for all 3 of these test failures. We will loop waiting for ~200 seconds for 5 bank scans to complete. I'm guessing this is a soft timeout as opposed to some sort of deadlock because the tests are passing on my laptop. I'll try increasing the wait time to confirm before diving into what might have slowed down after moving to 1.62

**Comment by mvines** [comment]
I just added Rust 1.63.0 here

**Comment by joncinque** [comment]
Interestingly, 1.62 was hanging on some tests at `recv_mmsg`.  When I tried to dig in, the Linux-specific implementation using the `recv_mmsg` syscall didn't make a difference. With the upgrade to 1.63, those issues went away.

**Comment by brennanwatt** [comment]
New set of failures for the following tests:
```
blockstore_processor::tests::test_process_blockstore_with_dead_slot
blockstore_processor::tests::test_process_blockstore_with_invalid_slot_tick_count
blockstore_processor::tests::test_process_blockstore_with_slot_with_trailing_entry
blockstore_processor::tests::test_process_blockstore_with_supermajority_root_with_blockstore_root
blockstore_processor::tests::test_process_blockstore_with_supermajority_root_without_blockstore_root
blockstore_processor::tests::test_process_ledger_options_full_leader_cache
```
Looks like they're all failing the assert check at the end of flush due to bucket age advancing unexpectedly.

**Comment by brennanwatt** [comment]
> > New set of failures for the following tests:
> > ```
> > blockstore_processor::tests::test_process_blockstore_with_dead_slot
> > blockstore_processor::tests::test_process_blockstore_with_invalid_slot_tick_count
> > blockstore_processor::tests::test_process_blockstore_with_slot_with_trailing_entry
> > blockstore_processor::tests::test_process_blockstore_with_supermajority_root_with_blockstore_root
> > blockstore_processor::tests::test_process_blockstore_with_supermajority_root_without_blockstore_root
> > blockstore_processor::tests::test_process_ledger_options_full_leader_cache
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Looks like they're all failing the assert check at the end of flush due to bucket age advancing unexpectedly.
> 
> @jeffwashington Looks like there may be some lingering races still in the bucket aging? Not sure if this is something new with rust v1.63, or just exasperated by.

Yeah, I can repro this easily on my laptop if I put the non-advancing thread to sleep before this assert check.

Looks like thread index 0 can advance the age even if other threads are holding the flush lock through this path:
image

**Comment by brennanwatt** [comment]
Don't fully understand what's going on yet, but this function is the problem:
```
impl<'a> FlushGuard<'a> {
    /// Set the `flushing` atomic flag to true.  If the flag was already true, then return `None`
    /// (so as to not clear the flag erroneously).  Otherwise return `Some(FlushGuard)`.
    #[must_use = "if unused, the `flushing` flag will immediately clear"]
    fn lock(flushing: &'a AtomicBool) -> Option<Self> {
        let already_flushing = flushing.swap(true, Ordering::AcqRel);
        (!already_flushing).then_some(Self { flushing })
    }
}
```
If it is changed to the following, the lock actually seems to work
```
impl<'a> FlushGuard<'a> {
    /// Set the `flushing` atomic flag to true.  If the flag was already true, then return `None`
    /// (so as to not clear the flag erroneously).  Otherwise return `Some(FlushGuard)`.
    #[must_use = "if unused, the `flushing` flag will immediately clear"]
    fn lock(flushing: &'a AtomicBool) -> Option<Self> {
        let already_flushing = flushing.swap(true, Ordering::AcqRel);
        if !already_flushing {
            Some(Self { flushing })
        } else {
            None
        }
    }
}
```

**Comment by brennanwatt** [comment]
> Does the version in master work?
> 
> ```rust
> (!already_flushing).then(|| Self { flushing })
> ```
> 
> I'm guessing this was a clippy lint that caused the change in this PR.

Yep, master version seems to work.

This problem can be simplified down to this basic unit test:
`cargo test --package solana-runtime --lib -- in_mem_accounts_index::tests::test_flush_guard --exact --nocapture`

**Comment by brennanwatt** [comment]
@brooksprumo - Do you mean keep the version in master?:
`(!already_flushing).then(|| Self { flushing })`

**Comment by brennanwatt** [comment]
Able to get a green CI (over at #27095) after the lock changes discussed above

**Comment by brennanwatt** [comment]
Created #27148 based on this PR + fixes discussed above

**Comment by Lichtso** [comment]
Closing this one as #27148 has been merged.

**Pull request closed without merging**
