### PR TITLE
Add tests to detect binary changes in serialized contract userdata

### PR DESCRIPTION
**Pull request by mvines**
When this changes we need to update SDKs so it's nice to know it happened.

### CODE REVIEW

**Comment by garious** [comment]
I don't like this as-is. Too early for this kind of lockdown. I think it would slow advances to the transaction format. That said, I like the goal of the PR and agree we need a solution to notify SDK devs that the transaction format changed. I propose you write a script to generate all the binary arrays (aka "gold copies"), and then have the tests output a message saying to go run that script if the test failed due to an intended change to the binary format. Bonus points if the test outputs an array diff instead of the full actual/expected arrays.

**Comment by mvines** [comment]
That's essentially what this does but without the external files.   When the format changes, `cargo test` outputs the correct value and one just needs to update the inlined vectors to continue.  I don't see why this would slow advances down.

**Comment by garious** [comment]
Yeah, okay. That's not too bad. Let's move forward and see if it's a pain point.

**Comment by mvines** [comment]
Cool.  Yeah we can streamline for sure.  I'm just going for the MVP here that hopefully is not too painful but also helps me unbreak the web3.js SDK.  I'll make it better based on the intensity of the complaints :)

**Pull request merged**
