### PR TITLE
BugFix: InfluxDB Metrics Precision should be ns not n

### PR DESCRIPTION
**Pull request by DaveWK**
According to the influxdb line protocol specification: In the "legacy 1.x" docs:
https://docs.influxdata.com/influxdb/v1.3/tools/api/#write and in the v2.x "legacy 1.x compatibility" docs:
https://docs.influxdata.com/influxdb/v2.7/reference/api/influxdb-1x/write/#precision

the precision should of the values: [ns,u,ms,s,m,h]

it appears there may have been a documentation bug back in 2017 which may have been the reason this parameter was set to "n" and not "ns": https://github.com/influxdata/docs.influxdata.com-ARCHIVE/issues/1029

according to:
https://github.com/influxdata/influxdb/issues/7985#issuecomment-281457056 `If you set the precision to ns or n, InfluxDB writes the timestamp in nanoseconds`

So any versions of influxdb which support `n` should also support `ns`. This also prevents issues with InfluxDB line protocol v1 compatible endpoints (such as the opentelemetry-contrib collector in my case).

#### Problem

When using an InfluxDB v1 line protocol compatible collector, such as the opentelemetry-contrib collector, it rejects metrics submissions with an http 400 and prints:
`[2023-07-17T21:40:17.431493735Z WARN  solana_metrics::metrics] submit response unsuccessful: 400 Bad Request unrecognized precision 'n'`

in the logs.

#### Summary of Changes

Changes influxdb metrics submissions to use `ns` instead of `n` for precision, which should be "backwards/bug side effect" compatible.

### CODE REVIEW

**Comment by pprkut** [comment]
Just a heads-up. We ran into the same problem regarding `ns` vs `n`, but the assumption that it's a docs issue didn't hold for us. Our InfluxDB 1.x instance rejected measurements with precision `ns`, and our InfluxDB 2.x instance rejected measurements with precision `n`. Your mileage may vary, but just so you know that you might want to actually test this rather than trusting the docs or a 6 year old github issue :slightly_smiling_face:

**Comment by pprkut** [comment]
FWIW, we tested with `1.8.3`

**Comment by steviez** [comment]
@joeaba is probably the most knowledgable in regards to the influx DB's we're running for clusters at the moment

**Comment by joeaba** [comment]
We are using Influx Enterprise v1.10 and it actually accepts both precision=n and precision=ns

**Pull request closed without merging**
