### PR TITLE
Zelcore wallet support for SOL/SPLs info added

### PR DESCRIPTION
**Pull request by trial123Zel**
I have added a quick infodump about Zelcore wallet supporting various features of the Solana ecosystem. I looked at previous commits and it seemed adding to the top of the file was the norm, but please feel free to move around if needed.

#### Problem
N/A

#### Summary of Changes
Initial addition of Zelcore supporting SOL assets

Fixes #
N/A

### CODE REVIEW

**Comment by trial123Zel** [comment]
Hi, I know you guys are all super busy. Would love a review for adding info about our wallet that supports SOL and SRM. Thanks.

**Comment by mvines** [comment]
Hoping @danpaul000 can review and decide what we want to do about the top posting.  I think sorting alphabetically is probably the fairest way.  Then AAAAAAAAAAWallet will be first

**Comment by trial123Zel** [comment]
unstale bump

**Comment by mvines** [comment]
Thanks, if you update the PR to place your wallet in alphabetical order I'll merge it!

**Comment by trial123Zel** [comment]
> 
> 
> Thanks, if you update the PR to place your wallet in alphabetical order I'll merge it!

Thank you. I have moved Zelcore to the bottom of the file.

**Review by mvines — APPROVED** [review]

**Pull request merged**
