### PR TITLE
clippy

### PR DESCRIPTION
**Pull request by aeyakovenko**
Fix clippy warnings reported by stable clippy

### CODE REVIEW

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by CriesofCarrots** [comment]
I don't think CI is updated to the new Rust yet.

**Comment by mvines** [comment]
We're on `1.28` right now: https://github.com/solana-labs/solana/blob/master/ci/buildkite.yml#L2

**Comment by mvines** [comment]
Ugh, 1.29 isn't in the official rust docker image yet: https://hub.docker.com/r/library/rust/tags/

**Pull request merged**
