### PR TITLE
optimize bench-tps and rpc_request

### LINKED ISSUE #1887: local testnet demo fails if bench-tps is built in release mode
#### Problem
bench-tps stalls out at the initial token distribution phase when built in release mode

#### Proposed Solution
??

#### STR
```
unset NDEBUG # (the default as of 33a5d5fe9348b41c08a22d257abc5989e527fbed)
killall -r solana-\.*
./multinode-demo/setup.sh
./multinode-demo/drone.sh  &
./multinode-demo/leader.sh &
export NDEBUG=1
./multinode-demo/client.sh 
```
Eventually, the client will stall, emit an error similar to: 
```
no balance CJjQKjZfUUweFRzjmQV9vwP2cgXb2L3Y2m7mk9mAVBQA source bal: 1 Transaction { signatures: [2FLu29BVke3qydxJaDLKtDhhTvbeDdjMni7zFPsgX4LjnWWo2NDYNTfxaWnh8iftqijt3L18N1BpaMbho9YVb2sZ], account_keys: [8FKvhzTWKE8AyS6XLzaSEyAZW3U4RUMNiZFFf1y9mrVX, CJjQKjZfUUweFRzjmQV9vwP2cgXb2L3Y2m7mk9mAVBQA, 2GL1hz5LMSa8zBwz3ZdQVo29xRkYYr8sG39cY5oZbq75, 5hC3KWGstZ23LmpsBE7XSGFwVKtQNa6yafkuaT8oRTj4, HtUqpq5hmVewch8ZvJ1u2Ac5FeMTvrPGTUABKgS9oXu7], last_id: BpyhpvLsBzbJk6cd7Khxv5LWCdoPRCnuzR7EM4rb5PCT, fee: 0, program_ids: [11111111111111111111111111111111], instructions: [Instruction { program_ids_index: 0, accounts: [0, 1], userdata: [2, 0, 0, 0, 110, 25, 0, 0, 0, 0, 0, 0] }, Instruction { program_ids_index: 0, accounts: [0, 2], userdata: [2, 0, 0, 0, 110, 25, 0, 0, 0, 0, 0, 0] }, Instruction { program_ids_index: 0, accounts: [0, 3], userdata: [2, 0, 0, 0, 110, 25, 0, 0, 0, 0, 0, 0] }, Instruction { program_ids_index: 0, accounts: [0, 4], userdata: [2, 0, 0, 0, 110, 25, 0, 0, 0, 0, 0, 0] }] }
```
Running everything in debug mode works fine.  Running the client in debug mode and the network in release mode works fine.

### PR DESCRIPTION
**Pull request by rob-solana**
#### Problem
 multinode-demo doesn't generally work on a local, leader+drone only testnet
 for non-GNU Linux hosts (e.g. WSL or MacOS), falling over in the "fund" phase
 of bench-tps setup, which tended to
    1. have some packet loss
    2. run the RPC server out of sockets
    3. sink into a vicious cycle of failed txs resulting in retrying
         txs that would be more likely to fail

 #### Summary of Changes
 * verify every tx in the fund phase
 * make verification and rpc_request more efficient generally by hanging onto
     the reqwest client, which allows pipelining, keep-alives, etc.

Fixes #1887

### CODE REVIEW

**Comment by aeyakovenko** [comment]
@rob-solana do we need this step
```
verify every tx in the fund phase
```
it might take a looooong time to fund 1m accounts that way.

**Comment by aeyakovenko** [comment]
@rob-solana is that on the cluster?  or just local?

**Comment by rob-solana** [comment]
local testing

**Comment by aeyakovenko** [comment]
@rob-solana at least verifying the source is 0 would take 1/5th the time.  I guess we can see how long that takes in the deployment.

**Comment by rob-solana** [comment]
what the code does is verify that at least one of the dests has its money, which is equivalent (and easier to test), right?

**Comment by rob-solana** [comment]
on my WSL box, the funding stage would always fail, now it works
on my Linux box, funding stage before took ~150 seconds, now takes ~300 seconds

**Pull request merged**
