### PR TITLE
Rust v1.63

### PR DESCRIPTION
**Pull request by brennanwatt**
#### Problem
Upgrading Rust to v.1.63 (again!). Last attempt was reverted due to regression for QUIC tests. Problem was identified as incompatible change to ip/port connection layout between std lib and quinn. Resolved by updating to quinn-udp v1.1.3

#### Summary of Changes
Upgrade default and nightly versions. Resolve some clippy lints. Update quinn-udp crate version

### CODE REVIEW

**Review by joncinque — APPROVED** [review]
The additional fix is simple and clean, nice!

**Comment by apfitzge** [comment]
A new clippy lint was added in 1.63 that we're seeing a several instances of: https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq.

I think most of them are coming from prost only adding PartialEq to the derive line, and not Eq. We'll probably want to tell clippy to ignore these, wait for prost to fix it, or open a PR in prost.

**Comment by CriesofCarrots** [comment]
I know this was a while ago, but could you add a quick comment as to why the `quinn-udp` dependency was needed? @brennanwatt

**Comment by brennanwatt** [comment]
> I know this was a while ago, but could you add a quick comment as to why the `quinn-udp` dependency was needed? @brennanwatt

I can definitely add this. Are you thinking a comment in the toml file?

**Comment by CriesofCarrots** [comment]
> Are you thinking a comment in the toml file?

I was thinking more detailed explanation on this PR, but a brief comment in the toml file would be great, if indeed that dependency needs to be retained, even though it doesn't appear to be being used anywhere.

**Comment by brennanwatt** [comment]
> I was thinking more detailed explanation on this PR, but a brief comment in the toml file would be great, if indeed that dependency needs to be retained, even though it doesn't appear to be being used anywhere. Thank you!

Root cause of this issue was an incompatible change to ip/port connection layout between std lib and quinn. The whole structure was getting copied over and assuming matching bit/byte layouts, but that assumption crashed and burned after std lib updates that modified the layout. The Quinn authors realized this and [resolved](https://github.com/quinn-rs/quinn/commit/5b714a3a5b66cd8e2fa6759c4a42f0c38a101a17) in quinn-udp v1.1.3, but the quinn library we were using was still pointing to a prior quinn-udp version.

**Comment by CriesofCarrots** [comment]
@brennanwatt , shouldn't that be a purely Cargo.lock change? I think the dependency added to client and streamer may be superfluous...?

**Comment by brennanwatt** [comment]
> @brennanwatt , shouldn't that be a purely Cargo.lock change? I think the dependency added to client and streamer may be superfluous...?

Yep, I think you're right. I can remove the superfluous dependencies

**Comment by brennanwatt** [comment]
I'm seeing [downstream-projects](https://buildkite.com/solana-labs/solana/builds/86751#01851be7-4c1b-4830-b24a-966f1d0e9b16) portion of CI failing after [removing the quinn-udp dependencies](https://github.com/solana-labs/solana/pull/28962). Not sure exactly why this is the case, but putting on the backburner for now

**Pull request merged**
