### PR TITLE
WIP: Boot recycler

### PR DESCRIPTION
**Pull request by garious**
Needs benchmarks to confirm no slowdown

### CODE REVIEW

**Comment by aeyakovenko** [comment]
On newton with recycler 37ktps without 33ktps

**Comment by aeyakovenko** [comment]
https://github.com/aeyakovenko/silk/tree/without_recycler_test?files=1

**Comment by garious** [comment]
Without the recycler, it looks like we can also get rid of the receiver and responder threads, and instead do the recv_loop, process the requests, and send all the responses.

**Comment by garious** [comment]
But yeah, with this PR as-is, I'm also consistently 5ktps worse.

**Comment by garious** [comment]
Single-threaded plus recycling is also an option.

**Comment by aeyakovenko** [comment]
The threads that do io cant do anything else if we are at the max

**Comment by garious** [comment]
Have you benchmarked that? I'd think the OS would queue packets.

**Comment by garious** [comment]
This brought TPS up to 17ktps on my MBP and down to 27ktps on newton. The recycler will live another day.

**Pull request closed without merging**
