### PR TITLE
chore: bump assert_matches to 1.5.0

### LINKED ISSUE #29670: bump assert_matches to 1.5.0

### PR DESCRIPTION
**Pull request by yihau**
close #29670

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Should we restore this one @yihau ?

**Comment by yihau** [comment]
Hey! Sorry for the very late response. I got distracted by other things last week. Sure. I will continue the path of upgrade 🤞

**Comment by CriesofCarrots** [comment]
Is this and #29606 ready for review? They say draft. Also, what's up with the CI agent?

**Comment by yihau** [comment]
oh damm. I don't suppose you will receive the notification until I `Ready for review`. will ping you when everything ready!

**Comment by CriesofCarrots** [comment]
> oh no. I don't suppose you will receive the notification until I `Ready for review`. will ping you when everything is ready!

No, I don't think github notifies on "ready for review" 😞 TIA for the ping!

**Comment by yihau** [comment]
@CriesofCarrots it's all green 🎉

**Review by CriesofCarrots — APPROVED** [review]

**Pull request merged**
