### PR TITLE
Remove `total_data_size` and `data_size_changed` from `ExecuteDetailsTimings`

### LINKED ISSUE #26990: Double counting in total size of transaction accounts metric
#### Problem
The total account data size metric recorded after transaction processing can include double counted account data lengths because the `LoadedTransaction::accounts` field can contain duplicate accounts.

https://github.com/solana-labs/solana/blob/09e26c7d29296c3a3d7b1b5820574dce3716e4b4/sdk/src/transaction_context.rs#L933-L948

#### Proposed Solution
Only count the data size of accounts referenced from a transaction's account keys list

### PR DESCRIPTION
**Pull request by Lichtso**
#### Problem
See #26990

#### Summary of Changes
Removes `total_data_size` and `data_size_changed` from `ExecuteDetailsTimings`.

Fixes #26990

### CODE REVIEW

**Review by jstarry — COMMENTED** [review]
Can you add tests for this? I don't think this will work because I believe that there are placeholder accounts in the transaction context

**Comment by Lichtso** [comment]
Depends on what you think the expected behavior is. The implementation in this PR would effectively ignore all executable accounts, because the placeholders are empty (so they are counted by don't contribute). Only the first executable account in each executable chain is referenced in the message keys.

**Comment by jstarry** [comment]
These stats were added quite awhile ago by @jeffwashington in https://github.com/solana-labs/solana/pull/15638. Maybe we can remove them (`total_data_size` and `data_size_changed`) if they're no longer needed. They were pretty corrupted before this fix anyways.

**Comment by jeffwashington** [comment]
> These stats were added quite awhile ago by @jeffwashington in #15638. Maybe we can remove them (`total_data_size` and `data_size_changed`) if they're no longer needed. They were pretty corrupted before this fix anyways.

fine by me

**Review by jstarry — APPROVED** [review]

**Pull request merged**
