### PR TITLE
Add Merkle Tree implementation

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem
We need a Merkle Tree implementation for SPV

#### Summary of Changes
Add a Merkle Tree implementation

Fixes #

### CODE REVIEW

**Comment by t-nelson** [comment]
CI failures seem unrelated?

**Comment by mvines** [comment]
yeah, unrelated.  
`test_replicator_startup_2_nodes` 🔪

**Comment by mvines** [comment]
Looks good, land it?

**Comment by t-nelson** [comment]
Whoops, sorry.  Just pushed a rebase.  Changes are untouched, though.

Good to go after CI passes

**Comment by mvines** [comment]
Sweet, you can use the "automerge" label in these cases.   If it doesn't go in CI will let you know, otherwise you just forget about it.

**Pull request merged**
