### PR TITLE
Remove vote instruction counters

### PR DESCRIPTION
**Pull request by HaoranYi**
#### Problem

(https://github.com/solana-labs/solana/issues/24319

https://github.com/solana-labs/solana/issues/24414

For rpc node, the metric agent is unable to catching up with the log at *info* level. `vote-native` is one of the heaviest loggers.
`("vote-native", 11763907)`. 

Every vote instruction will submit one counter point, which is overwhelming for the metric agent to process. 

#### Summary of Changes
- Remove vote instruction counters from vote_processor, which is no longer needed, as we have added the aggregated counters on the leader slot stats.

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
Cool, can you remove them from the metrics dashboard config too (cluster-monitor.json)

**Comment by behzadnouri** [comment]
@HaoranYi can you update the change description pointing to the metrics that should be used instead?

**Comment by HaoranYi** [comment]
> @HaoranYi can you update the change description pointing to the metrics that should be used instead?
Right now, we only have the metrics for dropped vote counts. I will add the metric for vote instruction in a new PR.

**Comment by HaoranYi** [comment]
> > @HaoranYi can you update the change description pointing to the metrics that should be used instead?
> 
> Right now, we only have the metrics for dropped vote counts. I will add the metric for vote instruction in a new PR.

With https://github.com/solana-labs/solana/pull/35015, you can look at "vote_instructions_processed" metrics. 
I have deployed it to my node. We are processing about 3K vote programs per second.
@behzadnouri

**Pull request merged**
