### PR TITLE
Remove budget program from cli

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
Solana-cli includes functionality that depends on the (currently native) Budget program. However, this program will not be available in SLP1

#### Summary of Changes
- Strip out all Budget-related functionality from solana-cli
- Fixup usage docs

Toward #6370 , #5757 

Fyi @garious

### CODE REVIEW

**Comment by mvines** [comment]
Why bother?

**Comment by CriesofCarrots** [comment]
> Why bother?

Seems icky to continue to offer cli subcommands that are just going to fail on-chain.
Also I believe @garious is planning to strip out the Budget native program (and potentially rework in BPF), so the budget_instructions will all need to go at that point anyway.

**Comment by mvines** [comment]
These commands will continue to work on a testnet though.

But I don't mind removing them but doing so isn't blocking SLP1 in any way though as the Budget native program will simply be disabled via #5757

**Comment by mvines** [comment]
If we're going to do this, might as well rip out Budget entirely as that program is now basically unusable without a front-end interface

**Comment by CriesofCarrots** [comment]
> If we're going to do this, might as well rip out Budget entirely as that program is now basically unusable without a front-end interface

Technically, solana-web3.js still offers an interface to the Budget program.
We could remove Budget plus that JS interface now as well. I don't have a very strong opinion about that.

I do think the purpose/shape of solana-cli has shifted quite a lot, and the Budget functionalities are now kind of tangential. But I think you have a much clearer idea in your head than I do of what #5757 is going to look like. So if you think this is pointless, and/or we should do all ripping at one time in the future, I will close.

**Comment by mvines** [comment]
> But I think you have a much clearer idea in your head than I do of what #5757 is going to look like. So if you think this is pointless, and/or we should do all ripping at one time in the future, I will close.

Maybe :) . #5757 is literally next on my TODO list.  I've done a bunch of prototyping work already (more than a month ago now!) and just need to formalize and socialize.  Essentially genesis starts with a small handful of native programs, and additional native programs can be added once the cluster reaches pre-determined block heights.   Certain cluster parameters (fees) may need to be tweaked at  pre-determined block heights as well.

> I do think the purpose/shape of solana-cli has shifted quite a lot, and the Budget functionalities are now kind of tangential.

Yeah I agree.   If we keep the Budget program I'd certainly want to keep the parts of the cli that work with Budget too somewhere.  If not `solana-cli`, then a `solana-budget-cli`-like thing that doesn't currently exist.  But making a `solana-budget-cli` feels premature now, so my vote is to close this PR and deal with Budget as a whole later :)

**Pull request closed without merging**
