### PR TITLE
Revert etcd-client bump

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
Rpc nodes are seeing rpc-service stalls on v1.9.15+. Haven't totally pinned down the reason yet, but the stalls don't occur with the etcd-client bump from #24159 reverted

#### Summary of Changes
Revert that dependency bump

The commits are verbose because i decided the easiest way to ensure the proper things were backed out was to revert the whole 24159 commit and redo the bumps we want to preserve.

### CODE REVIEW

**Comment by jstarry** [comment]
Do you mind kicking `programs/bpf/Cargo.lock` as well?

**Comment by CriesofCarrots** [comment]
> Do you mind kicking `programs/bpf/Cargo.lock` as well?

I don't mind, but the original PR didn't touch that lock file. What would you like me to change there?

**Comment by jstarry** [comment]
> I don't mind, but the original PR didn't touch that lock file. What would you like me to change there?

It is out of sync with the main workspace `Cargo.lock` file. The original PR didn't touch it but it was updated later in https://github.com/solana-labs/solana/commit/59a58f6716bd12fb262a5ca163b658b6606edc26

**Comment by CriesofCarrots** [comment]
Ah got it. Odd that the checks CI job didn't care about that.

**Review by jstarry — APPROVED** [review]

**Comment by jstarry** [comment]
> Ah got it. Odd that the checks CI job didn't care about that.

Yeah I think they check that on master, not sure why v1.9 allows it

**Pull request merged**
