### PR TITLE
add freeze_lock() and fix par_process_entries() failure to detect self conflict

### PR DESCRIPTION
**Pull request by rob-solana**
#### Problems
 1. bank hashes, which are required for vote transactions to succeed, cannot be correctly calculated until all banking_stage accounts in flight have been committed.  this can lead to leaders rejecting valid votes because they saved their delta hash before some accounts were committed

 2. a bug in process_entries allowed for a self-conflicting entry to get through if the previous entry had a conflict with its predecessor.

 #### Summary of Changes
 1. hold a read lock in banking stage on the bank's freeze() hash (freeze() already goes after a write lock)
 2. rewrote the process_entries loop so that lock results are _**always**_ checked for self-conflict

Fixes #

### CODE REVIEW

**Comment by rob-solana** [comment]
with this, we can remove record_locks logic

@carllin that test I added fails without the fixups to process_entries()

**Comment by aeyakovenko** [comment]
😮

**Comment by sagar-solana** [comment]
This is so simple and :sparkles:

**Comment by rob-solana** [comment]
yeah, but there's a single sync point now ;)

**Comment by sagar-solana** [comment]
Yeah I was just talking to @carllin about that. We also lose some "next slot" leader time because of this.

**Comment by rob-solana** [comment]
we can put metrics in to see what we're leaving on the table...

**Pull request merged**
