### PR TITLE
bump solana_rbpf from 0.2.5 to 0.2.7

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by mvines** [comment]
@Lichtso - looks like 0.2.7 has build issues with master

**Comment by jackcmay** [comment]
> @Lichtso - looks like 0.2.7 has build issues with master

@mvines I'm looking into it

**Comment by Lichtso** [comment]
I am on it already, just waiting for my local tests to run through

**Comment by mvines** [comment]
Cool, I'd like this to make it into v1.6 before we ship a new release to testnet, to give some soak time before upgrading mainnet to use it.   I was hoping we'd ship a new 1.6 release today

**Comment by Lichtso** [comment]
@mvines You will have to pull the commit in here: https://github.com/Lichtso/solana/tree/bump_rbpf

**Comment by mvines** [comment]
> @mvines You will have to pull the commit in here: https://github.com/Lichtso/solana/tree/bump_rbpf

Can you just push to this PR?

**Comment by Lichtso** [comment]
@mvines I see, and done

**Comment by mvines** [comment]
`syscalls::tests::test_translate_type` failed.

@Lichtso - if this is getting late for you, we can delay shipping the next 1.6 release until tomorrow

**Comment by Lichtso** [comment]
Argh, that was stupid mistake of mine and [here](https://github.com/solana-labs/rbpf/pull/153) is the fix in RBPF.

Instead of releasing an entire new version for this hot fix I would suggest to just deactivate the last two lines of the test temporarily (until the next RBPF release), as the method `resize_region` is not used anywhere else.

**Comment by jackcmay** [comment]
@mvines I can help with the backporting while @Lichtso is sleeping

**Pull request merged**
