### PR TITLE
web3: restructure files into more directories

### PR DESCRIPTION
**Pull request by jstarry**
#### Summary of Changes
- Added the `transaction` and `message` directories that will hold new code that will be added soon to support versioned transactions.
- Added the `programs` and `program-tests` directories to make it easier to see which programs are supported by this library
- Renamed `util` directory to `utils`

Fixes #

### CODE REVIEW

**Review by jstarry — COMMENTED** [review]
@steveluscher any high level concerns or comments here?

**Comment by steveluscher** [comment]
More module boundaries the better!

**Review by steveluscher — APPROVED** [review]

**Comment by steveluscher** [comment]
Thanks for totally screwing my future rebase of https://github.com/solana-labs/solana/pull/25839 tho. 😘

**Comment by jstarry** [comment]
> Thanks for totally screwing my future rebase of https://github.com/solana-labs/solana/pull/25839 tho. 😘

Oh dang, I forgot to follow up on that. Let's definitely get yours in first. This restructure isn't that pressing

**Comment by steveluscher** [comment]
Oh, by all means. No problem. Rebases are afraid of me, not the other way around.

**Pull request merged**
