### PR TITLE
Add a node-specific ip echo service to remove dependency on ifconfig.co

### LINKED ISSUE #936: panic when pinging ifconfig.co on the perf testnet
Maybe add some retries?

### PR DESCRIPTION
**Pull request by mvines**
#### Problem
1. We use ifconfig.co to figure a node's public IP address
2. The `--public-address` flag to solana-{fullnode,replicator,gossip} is annoying and error prone.  Why does it exist again?  Oh, because we use ipconfig.co to figure a node's public IP address.
3. IPv6 address can sneak into gossip because we use ipconfig.co to figure a node's public IP address (#4095)

#### Summary of Changes
* Each node now runs an ifconfig.co-like ip echo service on the TCP port corresponding to the node's gossip UDP port.
* When a node tries to join a cluster it first asks the entrypoint node what its public IP address is.  This works for both "private" and "public" clusters

Fixes #936 #4095 #4100

### CODE REVIEW

**Comment by rob-solana** [comment]
This is a step in the right direction: inter-node routes may have to be sensitive to the infra between them.  At some point we may have to bite the bullet and do STUN/TURN/WebRTC something?

What's the strategy for this use case: 2 nodes in a NAT form a network, they each look like 192.168.1. to each other, even though they want to be a public cluster.  3rd node from outside that network can't see any of their ports?

**Comment by mvines** [comment]
> At some point we may have to bite the bullet and do STUN/TURN/WebRTC something?

Yeah I think so, but also not super eager to open up that box.  Expanding a node's ContactInfo to support multiple IP addresses seems like a nice future improvement too. 

> What's the strategy for this use case: 2 nodes in a NAT form a network, they each look like 192.168.1. to each other, even though they want to be a public cluster. 3rd node from outside that network can't see any of their ports?

We use this mainly for max TPS testing when we want to ensure all nodes are staying within the the cloud provider's local interconnect to avoid network ingress fees that are incurred when using the public IP address.   They don't want to be a public cluster, nobody else should attach to the cluster. I think I failed to describe this well above :)

**Comment by rob-solana** [comment]
> > At some point we may have to bite the bullet and do STUN/TURN/WebRTC something?
> 
> Yeah I think so, but also not super eager to open up that box. Expanding a node's ContactInfo to support multiple IP addresses seems like a nice future improvement too.

I thought about that possibility, but determining route-ability to a peer might be no fun.

> 
> > What's the strategy for this use case: 2 nodes in a NAT form a network, they each look like 192.168.1. to each other, even though they want to be a public cluster. 3rd node from outside that network can't see any of their ports?
> 
> We use this mainly for max TPS testing when we want to ensure all nodes are staying within the cloud provider's local interconnect to avoid network ingress fees that are incurred when using the public IP address. They don't want to be a public cluster, nobody else should attach to the cluster. I think I failed to describe this well above :)

I think I missed this part: how does the bootstrap leader find himself?

**Comment by mvines** [comment]
> I think I missed this part: how does the bootstrap leader find himself?

It needs to be told.   

By default it's 127.0.0.1:
https://github.com/solana-labs/solana/blob/f9c093022cd3fd362b1616d30529a570d8b2edb5/fullnode/src/main.rs#L196

and in a `net/`-based deployment, we give the bootstrap leader a private or public cloud address (depending on how the testnet was configured) right here:
https://github.com/solana-labs/solana/blob/f9c093022cd3fd362b1616d30529a570d8b2edb5/net/remote/remote-node.sh#L87

**Pull request merged**
