### PR TITLE
Web3.js - enable maxRetries option to SendOptions

### PR DESCRIPTION
**Pull request by hareeshnagaraj**
#### Problem

Detailed summary here - https://github.com/solana-labs/solana/pull/21181/files

#### Summary of Changes

Exposes the maxRetries option in solana/web3.js for developers to leverage the strategies specified here https://solanacookbook.com/guides/retrying-transactions.html#an-in-depth-look-at-sendtransaction

Fixes #

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Hi @hareeshnagaraj , do you mind running `npm run pretty` to pass our style linter? I think it's just a missing comma after your addition in `src/util/send-and-confirm-transaction.ts`, heh

**Comment by hareeshnagaraj** [comment]
> Hi @hareeshnagaraj , do you mind running `npm run pretty` to pass our style linter? I think it's just a missing comma after your addition in `src/util/send-and-confirm-transaction.ts`, heh

Thanks @CriesofCarrots ! Just ran the prettier:fix, hopefully that covers it 🤞

**Comment by CriesofCarrots** [comment]
Thanks @hareeshnagaraj , this looks good.
Something up with our CI; I'm going to try to get it through before merging

**Comment by CriesofCarrots** [comment]
All set. Thank you!

**Pull request merged**
