### PR TITLE
ci: remove ejson

### PR DESCRIPTION
**Pull request by yihau**
#### Problem

I think the only variable we used in ejson is `CODECOV_TOKEN`. I've added it to all our ci machines so maybe it's the time to remove this mechanism.

#### Summary of Changes

remove ejson related code

### CODE REVIEW

**Comment by yihau** [comment]
are you referring to this one 🤔 
Screenshot 2023-03-10 at 12 48 36 PM

I can only remember we use it on buildkite.

**Comment by t-nelson** [comment]
> are you referring to this one thinking Screenshot 2023-03-10 at 12 48 36 PM

smells right!

> I can only remember we use it on buildkite.

i take it this can go too, being as we don't have the bin installed and ci still works :sweat_smile: 

if so, there are also a bunch of references in `.buildkite/env/README.md`

**Comment by yihau** [comment]
yeah. It happened in the pre-command. it only complained but was still working so hard haha

btw, I also removed `.buildkite/env/*` in this PR. 😈

**Review by t-nelson — APPROVED** [review]
:shipit:

**Pull request merged**
