### PR TITLE
Ignore ProgramError() in bank execute transactions

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
The confirmation time is continuously increasing on testnet.

#### Summary of Changes
bank::record_transaction() is ignoring ProgramError, but later the same results vector is passed on to commit_transactions() and unlock_accounts(). The error is not ignored there.

### CODE REVIEW

**Comment by mvines** [comment]
Is there any way we can add a test for this (and #2509).   Debugging by testnet metrics dashboard is brutal.  The patch itself looks find to me though

**Comment by pgarg66** [comment]
The following tests are failing as process_transaction no longer return ProgramError. Should this condition in the tests be ignored?

```
test_detect_failed_duplicate_transactions_issue_1157
test_insufficient_funds
test_one_tx_two_out_atomic_fail
```

**Comment by pgarg66** [comment]
@mvines , seems the accounts get updated even though there are program errors. Wondering if that's the correct behavior?

**Comment by mvines** [comment]
Whoa that definitely seems wrong

**Pull request closed without merging**
