### PR TITLE
Older votes no longer receive credit towards rewards

### PR DESCRIPTION
**Pull request by mvines**
Deny credits for votes that are too far behind the current bank's slot. 

TODO:
* [ ] Do we even want this?
* [ ] What's a good cut-off. This PR arbitrarily picks 10 for now.

### CODE REVIEW

**Comment by mvines** [comment]
> I think that old votes should still get at least 1 credit to incentivize voting on old but not yet confirmed slots. Otherwise there is no incentive (other than just wanting the block chain to actually work!) for voting on old slots that have not been confirmed.

The slot age here is not an absolute slot number, but rather based on the history of slots in the current fork.  So if the current fork looked like this 0 -> 100 -> 101 -> 102, a vote for slot 0 would still receive credit if it was processed during slot 102

**Comment by bji** [comment]
> The slot age here is not an absolute slot number, but rather based on the history of slots in the current fork. So if the current fork looked like this 0 -> 100 -> 101 -> 102, a vote for slot 0 would still receive credit if it was processed during slot 102

Ah good point.  So if you set it to 32 then you'd at least be awarding credits for all votes that could potentially contribute to consensus.  But then you'd still be leaving a pretty large window for votes to be lagged.

**Comment by bji** [comment]
It was my assumption that the reason that slot_history is so large is because the block chain wants to incentivize even late voting, well later than consensus.  Because otherwise there is a disincentive for voting on old blocks that might not have achieved consensus yet, but that if they are old enough, and if old votes were disregarded, would likely not earn any credits.  But all votes should be encouraged, right?  To avoid starving old non-finalized slots of votes?

I dunno, maybe I'm not helping.  I think you've probably thought through this more than I have.

**Comment by bji** [comment]
Also in the "do we even want this", I'd say yes, because while "public" validators may respond to shame pressure or whatever, there is no incentive for private 100% commission validators to vote in a timely fashion.  They can vote behind consensus for maximum returns on their self-stake and no one would be able to influence them short of manual slashing (seems hard to organize and a poor strategy for dealing with this sort of thing) or blocking their IP and shunning them from the cluster (also seems like a messy strategy).

**Comment by mvines** [comment]
> Ah good point. So if you set it to 32 then you'd at least be awarding credits for all votes that could potentially contribute to consensus. But then you'd still be leaving a pretty large window for votes to be lagged.

32 feels a little too high.  10 (or less maybe?) seems better but I also want to see how this runs on mainnet first as well.  Once the validator catches up, all its votes would be credited though provided it's not lagging.  An unmodified validator should only not receive less credit for valid votes than it would without this change when it's initially catching or recovering from a lockout or other form of delinquency.

**Comment by bji** [comment]
I'm just having a hard time thinking through this because it's based on gating credits for older votes when they reach full lockout based on the "vote distance" of the vote that caused the older vote to reach lockout.  Isn't it?

It feels like there could be weird ways to game this.  Queue up a 30 votes and submit them all at once when their newest vote is no older than 10 slots old?  Maybe I am confused.

**Comment by bji** [comment]
I believe this change allows voters to vote in groups of 10 votes at once and still get maximum credits.

**Comment by mvines** [comment]
> I believe this change allows voters to vote in groups of 10 votes at once and still get maximum credits.

All votes deeper than 10 slot_hashes in the bank that the vote instruction executes in are not credited for rewards.  If a "vote copier" can land their copied votes quickly enough then they can still get max credits, preventing that is quite hard without some larger change to how voting is done.  

What this change does is:
1. Prevent a node from batching more than 10 votes at once to obtain maximum credits while paying 1/10 or less of the voting fee (which is essentially what http://replicantstaking.com/ was doing before they got called out).
2. Encourage poorly performing nodes to improve their setups.  While running this change, I see that notably 
[Forbole](https://www.validators.app/validators/forb5u56XgvzxiKfRt4FVNFQKJrd2LWAfNCsCqL6P7q) and [Kraken](https://www.validators.app/validators/krakeNd6ednDPEXxHAmoBs1qKVM8kLg79PvWF2mhXV1) miss out on some vote credits (amongst some other smaller validators). I have no absolutely reason to suspect either of them are acting maliciously but their voting performance is poor so giving them a kick in the pants by denying reward credits seems healthy.

So it doesn't prevent vote copying outright but at least filters out some naive implementations and at worst requires vote copiers to pay more.  But (2) alone is worth it IMO, there's currently consistently ~5 validators on mainnet-beta that will get credits dropped as a result of this change

**Comment by bji** [comment]
> > I believe this change allows voters to vote in groups of 10 votes at once and still get maximum credits.
> 
> All votes deeper than 10 slot_hashes in the bank that the vote instruction executes in are not credited for rewards. If a "vote copier" can land their copied votes quickly enough then they can still get max credits, preventing that is quite hard without some larger change to how voting is done.
> 
> What this change does is:
> 
> 1. Prevent a node from batching more than 10 votes at once to obtain maximum credits while paying 1/10 or less of the voting fee (which is essentially what http://replicantstaking.com/ was doing before they got called out).
> 2. Encourage poorly performing nodes to improve their setups.  While running this change, I see that notably
>    [Forbole](https://www.validators.app/validators/forb5u56XgvzxiKfRt4FVNFQKJrd2LWAfNCsCqL6P7q) and [Kraken](https://www.validators.app/validators/krakeNd6ednDPEXxHAmoBs1qKVM8kLg79PvWF2mhXV1) miss out on some vote credits (amongst some other smaller validators). I have no absolutely reason to suspect either of them are acting maliciously but their voting performance is poor so giving them a kick in the pants by denying reward credits seems healthy.
> 
> So it doesn't prevent vote copying outright but at least filters out some naive implementations and at worst requires vote copiers to pay more. But (2) alone is worth it IMO, there's currently consistently ~5 validators on mainnet-beta that will get credits dropped as a result of this change

I'm really sorry to be so dense but please explain to me why someone can't do this after your change:

- Save up 8 votes that they would have cast
- Submit them in one transaction (8 slot later than the first vote would have been cast had it been cast immediately)
- Repeat

In each batch of 8, every vote will still be newer than the 10 slot hashes needed to be counted.  So each will pass the "if next_vote_slot >= oldest_credit_eligible_slot" test and each will allow 1 credit to be added as the oldest vote that is in the lockouts queue falls off the back.  Then once they all do that duty, they remain in the lockouts queue, ready to be pushed out by a future batch of 8 votes.

**Comment by bji** [comment]
Perhaps the batching issue can be handled by using the distance from the voted-on slot and the slot the vote lands in as a multiplier of credits on all votes in the transaction.  This wouldn't require any changes to data structures and thus wouldn't require the complexities involved in that.  Something like:

<
if next_vote_slot >= oldest_credit_eligible_slot {
    self.increment_credits(epoch, credits_to_award);
}
>

where 'credits_to_award' is more or less what I compute it to be in my change.  (the idea being to use leader slot group distance to avoid leaders deferring other validators' votes to the end of their group, and the overall distance creating greater rewards for voting as soon as possible).

I'm going to code this up and make a PR for it ...

**Comment by behzadnouri** [comment]
@mvines where did you land on this that decided to close the pr?

context: I was looking at  #28162 and #28126 and recalled this one.

**Comment by bji** [comment]
@mvines I think that this question may be holding up the review of #28162, would you have a chance to answer behzadnouri?  Thanks.

**Pull request closed without merging**
