### PR TITLE
Added a new remote node configuration script to set rmem/wmem

### PR DESCRIPTION
**Pull request by pgarg66**

### CODE REVIEW

**Comment by mvines** [comment]
Won't this get overridden by https://github.com/solana-labs/solana/blob/386a96b7e01215cae737137770d23563bdd96430/multinode-demo/common.sh#L106-L116?

**Comment by pgarg66** [comment]
I don't think that common.sh is being called from net/gce.sh or net/net.sh.
There's another net/common.sh that's being used in these scripts. But that does not set the rmem/wmem.

**Comment by mvines** [comment]
Hmm, net/remote/remote-node.sh calls multinode-demo/leader.sh calls multinode-demo/common.sh so I think it probably does get overridden.

At the least we should set the multinode-demo/common.sh values to be the same right?

**Comment by pgarg66** [comment]
Sure, I'll update common.sh to the same values.

**Pull request merged**
