### PR TITLE
increase rolling slot width to 4M

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem
#16570

#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by jeffwashington** [comment]
I confirmed I could start a mainnet-beta validator using ryo's snapshot with this increase to 4M.

**Comment by sakridge** [comment]
Do we know that 4m will be enough?

**Comment by jeffwashington** [comment]
> Do we know that 4m will be enough?

I don't yet know if this is enough. This is harmless and gets around the current situation. But, I'm not ready to submit this yet. I'm debugging shortly the actual situation in the snapshot. I also have a full revert pr ready in case we want to go that route.

**Comment by sakridge** [comment]
> > Do we know that 4m will be enough?
> 
> I don't yet know if this is enough. This is harmless and gets around the current situation. But, I'm not ready to submit this yet. I'm debugging shortly the actual situation in the snapshot. I also have a full revert pr ready in case we want to go that route.

ok, sounds good.

**Comment by jeffwashington** [comment]
@carllin is running into this, too. 4M is enough to get around the current issues and still well within the performance envelope while we figure out why old stores/accounts aren't getting cleaned.

**Pull request merged**
