### PR TITLE
feat(web3.js): add buffer-layout for stake account

### PR DESCRIPTION
**Pull request by atharmohammad**
This PR adds :-
1). Buffer Layout for stake account in web3.js
2). Tests for Layout for different stake states

### CODE REVIEW

**Comment by jstarry** [comment]
Can you explain why you need this? The RPC server can already return parsed stake accounts to clients so that they don't need to manually deserialize.

**Comment by atharmohammad** [comment]
> Can you explain why you need this? The RPC server can already return parsed stake accounts to clients so that they don't need to manually deserialize.

Was needed for stake pool in solana programming library to parse the stake account from getAccountInfo, will getAccountInfo returns a parse stake account or is there any other function ?

**Comment by jstarry** [comment]
> Was needed for stake pool in solana programming library to parse the stake account from getAccountInfo, will getAccountInfo returns a parsed stake account or is there any other function ?

You can use `Connection.getParsedAccountInfo` and then copy these json validators used by the explorer to get a typed response: https://github.com/solana-labs/solana/blob/master/explorer/src/validators/accounts/stake.ts

**Comment by atharmohammad** [comment]
> > Was needed for stake pool in solana programming library to parse the stake account from getAccountInfo, will getAccountInfo returns a parsed stake account or is there any other function ?
> 
> You can use `Connection.getParsedAccountInfo` and then copy these json validators used by the explorer to get a typed response: https://github.com/solana-labs/solana/blob/master/explorer/src/validators/accounts/stake.ts

ok , cool , will be closing this PR then :) thanks

**Comment by jstarry** [comment]
No problem! @CriesofCarrots maybe we should find a place in the docs to document which accounts RPC has `jsonParsed` support for

**Comment by CriesofCarrots** [comment]
> No problem! @CriesofCarrots maybe we should find a place in the docs to document which accounts RPC has `jsonParsed` support for

Agreed. I'll work something up

**Pull request closed without merging**
