### PR TITLE
feat: support commitment in getConfirmed methods

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
Various solana rpc methods that used to only return finalized data now support confirmed commitment. But solana-web3 does not expose a commitment parameter for these methods.

#### Summary of Changes
Add commitment to methods that target `getConfirmedBlock`, `getConfirmedTransaction`, and `getConfirmedSignaturesForAddress2` endpoints.

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
These rpc endpoints do not support `processed` commitment, so when that commitment is passed (or a `processed` Connection is used), the web3 methods will throw:
```
Error: failed to get confirmed signatures for address: Method does not support commitment below `confirmed`
```
That seems okay to me, but we could check the commitment before submitting the request. Wdyt?

**Comment by jstarry** [comment]
Thanks for adding this!

> so when that commitment is passed (or a processed Connection is used), the web3 methods will throw

I would prefer if it was harder to misuse this API. How about typing the `commitment` directly as `"confirmed" | "finalized"`?

Another thing is that `_buildArgs` falls back to the commitment set on the `Connection` class. If it's set to `processed` these methods would use that commitment by default. For these methods I think we might want to use something different from `_buildArgs`

**Comment by CriesofCarrots** [comment]
> I would prefer if it was harder to misuse this API. How about typing the `commitment` directly as `"confirmed" | "finalized"`?

Sure, that makes sense.

> Another thing is that `_buildArgs` falls back to the commitment set on the `Connection` class. If it's set to `processed` these methods would use that commitment by default. For these methods I think we might want to use something different from `_buildArgs`

Well, I do think the api should work without an explicit commitment, if the Connection commitment is confirmed or finalized. Are you thinking something like a `_buildArgsIfAtLeastConfirmed` to handle the commitment check and throw a client error? (as opposed the the rpc error above, which currently gets thrown)

**Comment by jstarry** [comment]
> Well, I do think the api should work without an explicit commitment, if the Connection class-defined commitment is confirmed or finalized. Are you thinking something like a _buildArgsIfAtLeastConfirmed to handle the commitment check and throw a client error? (as opposed the the rpc error above, which currently gets thrown)

Yeah, that sounds like a good solution to me

**Comment by CriesofCarrots** [comment]
@jstarry , I think this is ready for another look. Will squash before merge.
Alternate, better names for the `_buildArgsAtLeastConfirmed` method very welcome!
Also, I waffled about a new CommitmentAtLeastConfirmed type to make the methods less brittle, should we add additional at-least-confirmed commitment variants upstream. Wdyt?

**Comment by jstarry** [comment]
> @jstarry , I think this is ready for another look. Will squash before merge.

Looks great!

> Alternate, better names for the `_buildArgsAtLeastConfirmed` method very welcome!

It's descriptive and internal, seems fine to me!

> Also, I waffled about a new CommitmentAtLeastConfirmed type to make the methods less brittle, should we add additional at-least-confirmed commitment variants upstream. Wdyt?

Hmm what about calling it `Finality` where `Finality` is a stricter subset of `Commitment` which just includes optimistic confirmation ("confirmed") and finalized?

**Review by jstarry — APPROVED** [review]

**Pull request merged**
