### PR TITLE
Show Glow ID account information in the Explorer

### PR DESCRIPTION
**Pull request by vpontis**
#### Summary of Changes

We are rolling out a Glow ID system that allows people to easily register and update their Glow ID on the Solana blockchain.

This adds an update to Solana explorer to support Glow ID in two ways:

- if you search for `x.glow`, we will search to see if a corresponding `.glow` exists
- if you open a `x.glow` account, you'll see information about the profile (screenshot below)

You can test this by typing in `victor.glow`. 

CleanShot 2022-09-18 at 11 00 01@2x

### CODE REVIEW

**Comment by ngundotra** [comment]
@vpontis Can you rebase your changes so I can preview this branch?

**Comment by vpontis** [comment]
Yea @ngundotra if it looks good, do you think this is something we could get in? I haven't kept it up to date since I opened it 2 months ago and haven't heard from anyone here.

**Comment by ngundotra** [comment]
@vpontis honestly, I'm not 100% sure that this will get merged. If it's performant code (ie doesn't spam public RPCs) and it adds useful features, then I'm for it.

Your PR has more changes than I'm keen to review at the moment. Can you edit your PR description with before/after screenshot for the same page? This can help me identify what to look for when reviewing your code

**Comment by vpontis** [comment]
Awesome will do all of that later today 👍

**Comment by ngundotra** [comment]
@vpontis can you also open an Issue that describes what `glow` domains are, how to register them, etc. Also can you link to github repos for any packages you're adding?

**Comment by ngundotra** [comment]
@vpontis if you'd like to resusitate this, I would appreciate your feedback on community pages here: https://github.com/solana-labs/solana/issues/29556

**Pull request closed without merging**
