### PR TITLE
Refactor bank unprocessed indices update

### PR DESCRIPTION
**Pull request by HaoranYi**
#### Problem
The code that manages unprocessed packet within a batch in banking_stage.rs can be simplified. 

#### Summary of Changes
Refactor the code to simplify the unprocessed packet management and make it easier to understand.

Fixes #

### CODE REVIEW

**Comment by t-nelson** [comment]
> we should update the original_unprocessed_indexes to empty too

why tho?  Can you elaborate the description

**Comment by HaoranYi** [comment]
The process_loop (line: 847) will break out when buffered_packet_batches is empty. 

In fn update_buffered_packets_with_new_unprocessed, we should update original_unprocessed_indexes to empty when new_unprocessed_indexes is empty, so that we can break out the loop earlier. We calculate new_unprocessed_indexes in two places: 1. filter out invalid packets line:575; 2. retriable transaction_indexes line:630. If either of these two are empty, we should set buffered_packet_batches to empty and break out the process_loop.

In the old code, we only update original_unprocessed_indexes, when new_unprocessed_indexes are *not* empty. 

Does it make sense?

**Comment by jstarry** [comment]
> The process_loop (line: 847) will break out when buffered_packet_batches is empty.
> 
> In fn update_buffered_packets_with_new_unprocessed, we should update original_unprocessed_indexes, which points to buffered_packet_batches, to empty when new_unprocessed_indexes is empty, so that we can break out the loop earlier. We calculate new_unprocessed_indexes in two places: 1. filter out invalid packets line:575; 2. retriable transaction_indexes line:630. If either of these two are empty, we should set buffered_packet_batches to empty and break out the process_loop.
> 
> In the old code, we only update original_unprocessed_indexes, when new_unprocessed_indexes are _not_ empty, which won't let us break out the loop in the above condition.
> 
> Does it make sense?

When there are no more packets in a batch, the batch is dropped. I think you are confusing individual packet batches with a collection of packet batches

**Comment by HaoranYi** [comment]
@jstarry Thanks for the comments. Yes, the main loop looking at a vec of batches. But original_unprocessed_indexes points to one batches in the vec (line: 562). Also, original_unprocessed_index may not be a good name. It represent the unprocessed packet currently in the batch. I pushed a commit to refactor the code, which simplify the logic and hope this make code better to understand.

**Comment by jstarry** [comment]
> @jstarry Thanks for the comments. Yes, the main loop is looking at a vec of batches. But original_unprocessed_indexes points to one batches in the vec (line: 562). Also, original_unprocessed_index may not be a good name. It represent the unprocessed packet currently in the batch. I squash this commit with another refactor commit to refactor the code, which simplifies the logic and hope this makes code better to understand. Let me know what you think.

The refactor is much easier to understand, but just to be clear, there was nothing broken right?

**Comment by HaoranYi** [comment]
Yes, nothing broken with the original code.

**Comment by jstarry** [comment]
Cool, @HaoranYi can you fix your typo that's causing the CI failure, then happy to accept this change

**Review by jstarry — APPROVED** [review]
lgtm, cc @carllin

**Comment by HaoranYi** [comment]
Thanks @mvines I will give it a try. 
It also looks like the following change fix the build on windows. 

> modified   frozen-abi/macro/build.rs
> @@ -1 +1 @@
> -../build.rs
> \ No newline at end of file
> +include!("../build.rs");
> \ No newline at end of file
> 

Is there is a reason against using include! macro in build.rs?

**Comment by mvines** [comment]
yes, that will break after the crate is published

**Comment by HaoranYi** [comment]
I see. Thanks @mvines ! The above code snippet works for me on windows.

**Comment by jstarry** [comment]
@HaoranYi do you still plan to try to merge this?

**Comment by HaoranYi** [comment]
Ah. Yes. I will take a look and resolve the conflicts. Thanks.

**Comment by HaoranYi** [comment]
This change is stale. The recent changes in the master makes some part of the change in this pull request no longer necessary. So, I opened another pull request for the relevant changes.  
https://github.com/solana-labs/solana/pull/23805

**Pull request closed without merging**
