### PR TITLE
Include nanoseconds in log timestamp

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by sakridge** [comment]
cool, been wanting this too

**Comment by garious** [comment]
What ticket is this for?

**Comment by mvines** [comment]
No issue exists for this PR

**Comment by garious** [comment]
Why add this much precision to the logs? Is it being used for microbenchmarking?

**Comment by mvines** [comment]
The current precision of 1 second is insufficient for debugging,  I’d be happy with ms but upstream supports ns so why not!

**Comment by garious** [comment]
Can you add a ticket to track env_logger 0.5.12?

**Comment by mvines** [comment]
Yep, filed https://github.com/solana-labs/solana/issues/791

**Pull request merged**
