### PR TITLE
doc: update validator-info publish arguments

### PR DESCRIPTION
**Pull request by mvines**
cc: @jackcmay

### CODE REVIEW

**Comment by jackcmay** [comment]
@mvines I've already committed updates to this doc and it looks like this PR has not been rebased with those changes.

**Comment by mvines** [comment]
Where did you commit?  I don't see it.
https://i.kym-cdn.com/photos/images/original/001/043/243/419.gif

**Comment by jackcmay** [comment]
hmm, I updated the link directly, so it only went in 19 (https://github.com/solana-labs/solana/blob/v0.19.0/book/src/running-validator/validator-info.md)

**Comment by mvines** [comment]
ah, ok.  yeah that means it won't get picked up for anything after 0.19.0

**Comment by jackcmay** [comment]
@mvines, how about this: https://github.com/solana-labs/solana/pull/6152

**Pull request merged**
