### PR TITLE
web3.js: remove Buffer from PublicKeyInitData

### PR DESCRIPTION
**Pull request by macalinao**
#### Problem

Removes a redundant Buffer declaration

Addresses #27590.

### CODE REVIEW

**Comment by steveluscher** [comment]
Once something is added to the public interface, it's very difficult to remove. In particular, if anyone tries to pass a `Buffer` into the `PublicKey` constructor, this change will make Typescript newly fail on their project.

Thoughts on that?

**Review by steveluscher — CHANGES_REQUESTED** [review]
Once something is added to the public interface, it's very difficult to remove. In particular, if anyone tries to pass a `Buffer` into the `PublicKey` constructor, this change will make Typescript newly fail on their project.

Thoughts on that?

**Comment by macalinao** [comment]
> Once something is added to the public interface, it's very difficult to remove. In particular, if anyone tries to pass a `Buffer` into the `PublicKey` constructor, this change will make Typescript newly fail on their project.
> 
> Thoughts on that?

This is not true because `Buffer` implements `Uint8Array`

**Comment by steveluscher** [comment]
Right! I had that backwards; you're right.

```

const buffer: Buffer = null as any;
function takesAUint8Array(thing: Uint8Array) {}
takesAUint8Array(buffer); // OK

const byteArray: Uint8Array = null as any;
function takesABuffer(thing: Buffer) {}
takesABuffer(byteArray); // ERROR
```

**Comment by macalinao** [comment]
Finally my first PR into Solana core!! :D

**Pull request merged**
