### PR TITLE
ci: remove unused buildkite pipelines

### PR DESCRIPTION
**Pull request by yihau**
#### Summary of Changes

remove unused buildkite pipelines

### CODE REVIEW

**Review by t-nelson — COMMENTED** [review]
we like the red lines!  let's get jwash sign-off

**Comment by CriesofCarrots** [comment]
I also defer to @jeffwashington

**Comment by jeffwashington** [comment]
are these tests not running at all right now in master? In 1.14, we reverted the change that set disk index to true by default. Until disk index is turned on by default everywhere, we should still need these tests.
I think @willhickey set these tests up. Maybe they run nightly?
I think the idea is that we wanted a set of tests that would test every test with and without the disk index so we could keep them both fully tested at all times.

**Comment by yihau** [comment]
oh yeah. iirc this one ran nightly on Buildkite with some special env. I found it disappeared for a while so I made this PR. maybe someone run this one in other places 🤔

**Pull request closed without merging**
