### PR TITLE
Add --allow-private-addr to bootstrap-validator.sh

### LINKED ISSUE #30157: bench-tps fails to discover local bootstrap validator
#### Problem
bench-tps failing to discover my bootstrap validator.

Steps to reproduce:
Terminal 1: `$ NDEBUG=1 ./multinode-demo/setup.sh && NDEBUG=1 ./multinode-demo/faucet.sh`
Terminal 2: `$ NDEBUG=1 ./multinode-demo/bootstrap-validator.sh`
Terminal 3: `$ NDEBUG=1 ./multinode-demo/bench-tps.sh`

#### Proposed Solution
git bisect and figure out where this got broken

### PR DESCRIPTION
**Pull request by apfitzge**
#### Problem
#30157

#### Summary of Changes
Add `--allow-private-addr` to `bootstrap-validator.sh` default args.

Fixes #30157

### CODE REVIEW

**Comment by bw-solana** [comment]
+ @behzadnouri 

This is actually what I had originally for #29992 , but `bootstrap-validator.sh` is used for more than just local clusters, so we upleveled setting of the flag. Argument was that being able to emulate the actual testnet/MNB configuration when using, for example, the `net` scripts is valuable

**Comment by bw-solana** [comment]
> Ah, I'm seeing now that in the original PR (that added this) you considered it for bootstrap-validator already. I wonder what you think of adding it as a default argument; does that mess something up for the multinode case on gce?

I don't see a huge downside. It doesn't mess things up really because it allows more IPs to be considered valid (the same set we allowed before #29992 ). The only risk would be if this divergence between our testing and "real" cluster behavior caused us to miss something

**Comment by behzadnouri** [comment]
yeah, `--allow-private-addr` is a backdoor hack.
Better not to be there by default, but only instead just use it when needed.

**Comment by apfitzge** [comment]
> yeah, --allow-private-addr is a backdoor hack.
Better not to be there by default, but instead just use it when needed.

Definitely it's a hack to use on the validator, but running bench-tps locally is a very common (if not most common) use case, so the change broke workflows. Which is how I noticed.

> The only risk would be if this divergence between our testing and "real" cluster behavior caused us to miss something

Yeah, seems like a reasonable concern. I'll leave it as is and close the issue/PR - hopefully searching github can save the next person from bisecting 😆

**Comment by KirillLykov** [comment]
> > yeah, --allow-private-addr is a backdoor hack.
> > Better not to be there by default, but instead just use it when needed.
> 
> Definitely it's a hack to use on the validator, but running bench-tps locally is a very common (if not most common) use case, so the change broke workflows. Which is how I noticed.
> 
> > The only risk would be if this divergence between our testing and "real" cluster behavior caused us to miss something
> 
> Yeah, seems like a reasonable concern. I'll leave it as is and close the issue/PR - hopefully searching github can save the next person from bisecting 😆

well, not really I've bisected as well to later find the commit, author, this PR :-\

**Comment by behzadnouri** [comment]
Okay if many are hitting this issue, I guess it is fine to add this flag by default to `multinode-demo/bootstrap-validator.sh`.

**Review by bw-solana — APPROVED** [review]
LGTM. Wondering if we want to make the same change in `validator.sh`

**Comment by apfitzge** [comment]
> LGTM. Wondering if we want to make the same change in `validator.sh`

Yeah, will probably have to. I broke CI with my second "clean up" commit 🤦
Fixing it shortly

**Review by bw-solana — APPROVED** [review]

**Comment by KirillLykov** [comment]
Thanks for adding it by default, I think it makes general sense for localnet setup (because otherwise default parameters are not operational).
I think the only place where it is used except for localnet testing is private cluster tests: https://github.com/solana-labs/solana/blob/08d71ae8a140b0dced579ab11d4dda5e6650f306/net/remote/remote-node.sh#L307
So should be safe

**Comment by andreisilviudragnea** [comment]
@apfitzge I ended up bisecting the same commit for https://github.com/solana-labs/solana/issues/33205 too.

This issue affects Solana v1.16.x validator Docker images too.

**Pull request merged**
