### PR TITLE
Fix a typo & phrasing of `bpf_loader_upgadeable` docs

### PR DESCRIPTION
**Pull request by metaproph3t**
Original PR: [32813](https://github.com/solana-labs/solana/pull/32813)

### CODE REVIEW

**Review by pgarg66 — APPROVED** [review]

**Comment by t-nelson** [comment]
i wonder how this landed with the trailing whitespace error :thinking:

**Comment by t-nelson** [comment]
oh...
Screenshot from 2023-09-05 15-56-42

cc/ @yihau.  is there some way we can block merge if ci-gate is hung? i almost merged a pr under the same conditions last week

**Comment by pgarg66** [comment]
> > i wonder how this landed with the trailing whitespace error :thinking: 
> 
> 
> 
> oh...
> 
> Screenshot from 2023-09-05 15-56-42
> 
> 
> 
> cc/ @yihau.  is there some way we can block merge if ci-gate is hung? i almost merged a pr under the same conditions last week
> 
> 
> 
> EDIT: hmm... maybe the problem is that gh actions aren't blocked by the `CI` label for `community` labeled prs, like buildkite is?

Oh dang, seemed like a harmless PR to merge. Thanks for digging into the details.

**Comment by metaproph3t** [comment]
I am sorry for my crimes :(

**Pull request merged**
