### PR TITLE
WIP: Web3.js/signing performance

### PR DESCRIPTION
**Pull request by bartosz-lipinski**
#### Problem

Right now, within web3.js, we are using a javascript port of [tweetnacl](https://github.com/dchest/tweetnacl-js), which result in performance degradation. 

As proposed in the https://github.com/solana-labs/solana-web3.js/issues/974, I have created a new package @solana/wasm using rust and compile it using [wasm-pack](https://github.com/rustwasm/wasm-pack) into WebAssembly. 

This PR is also an initial prototype that could address:
* "Research Rust <-> WASM for solana-web3.js" https://github.com/solana-labs/solana/issues/3693
* "Add support for creating libra transactions in a Wasm SDK"  https://github.com/solana-labs/solana/issues/5418

#### Summary of Changes

This is still a work in progress but wanted to start a discussion around interface changes. 

Main points of concern:
* `@solana/web3.js` will now requite clients to await the initialization function `waitReady` - I decided to create a single initialization function instead of converting every available method that we have into Promise.
* Existing client would also need to change their webpack configuration to ensure that the wasm file is properly loaded (I created Babel transformation and Webpack plugin to make that transition easier) - please take a look at the example: `wasm/examples/webpack`
* I needed to create a custom rollup plugin to build an isomorphic library that could be used in both Web (webpack) and Node.JS environment. This is primarily related to how the wasm-pack generates code used as a wasm npm package.  It is possible to simplify our build process at the expense of maintaining two separate packages, one for Node.js and one for the Web. 

Smaller changes:
* Use `customize-cra` to change CRA
* Update unit test with `beforeAll` method and move some initialization code from `describe` to `before*` method per [jest doc](https://jestjs.io/docs/en/setup-teardown#order-of-execution-of-describe-and-test-blocks)
* 

TODO:
- [x] Remove any references to `tweetnacl`
    - [x] Implement missing methods in Rust
- [x] Add benchmark unit-tests to verify performance improvements - based on the initial benchmarks I am expecting a 3-4x improvement in singing performance 
- [ ] Finish IIFE package setup - right now ESM and CJS works
- [ ] Add plain old web example with just scripts (no-bundlers)
- [x] Add readme to @solana/wasm and setup linter and unit-tests
- [x] Investigating linking with solana-core to share code
- [ ] Add build optimization to reduce the size of the wasm file

Fixes #
https://github.com/solana-labs/solana-web3.js/issues/974
https://github.com/solana-labs/solana/issues/5418

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
Looks like I cannot reference `solana-sdk` directly because it is dependent on `net2` which doesn't support WASM as a compilation target. If we want to increase code sharing between wasm and code/sdk we would need to somehow decouple those references. 

Two targets that we would need to support: `wasm32-unknown-unknown` and `wasm32-wasi`

**Comment by bartosz-lipinski** [comment]
@jstarry, @sakridge after running a basic benchmark on sign method it looks like we will be able to achieve on avg. 20-25x performance improvement.

**Comment by jstarry** [comment]
Hey @bartosz-lipinski this is really exciting and awesome perf improvements! It's hard to find the time to power through an 8k+ line code review so that's the reason for the review delay.

> This is still a work in progress but wanted to start a discussion around interface changes.

Sounds good, I agree that we should have more discussion about this!

> @solana/web3.js will now requite clients to await the initialization function waitReady - I decided to create a single initialization function instead of converting every available method that we have into Promise.

Yeah, this is the trickiest part of integrating wasm right now. This initialization function is going to be a big migration pain, I think we could think more about the best dev integration experience. No matter what we do, I think that wasm integration will probably result in a major version bump for the web3 sdk. It's hard to imagine this being an incremental change.

**Comment by bartosz-lipinski** [comment]
@jstarry fair enough I will split this PR into two separate ones. The new one will only include @solana/wasm and this one will contain all the changes required to start using it which could be gradual migration.

**Comment by bartosz-lipinski** [comment]
I've created PR with only @solana/wasm (https://github.com/solana-labs/solana/pull/12581) once integrated I will update this one.

**Pull request closed without merging**
