### PR TITLE
Update gossip vote listener to repeat latest votes

### LINKED ISSUE #6675: VoteListener doesn't retry votes even if they don't land in a bank
#### Problem
The vote listener will pull a vote off of gossip, record the timestamp of that vote, and then attempt to run the vote through banking stage. If the vote doesn't land, the vote listener will not reattempt to play that vote again.

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

The vote listener will pull a vote off of gossip, record the timestamp of that vote, and then attempt to run the vote through banking stage. If the vote doesn't land, the vote listener will not reattempt to play that vote again.

#### Summary of Changes

Updated the vote listener to always pull the latest vote of gossip every time it runs. 
As opposed to pulling the latest and then only looking for newer votes. 
This should allow the latest vote to play on multiple banks 

Fixes #6675

### CODE REVIEW

**Comment by aeyakovenko** [comment]
you can keep a timestamp per bank, and have the child inherit it.

**Comment by sagar-solana** [comment]
@aeyakovenko so looks like I actually don't even need the timestamp in my PR right now. I might as well always return all the votes. As we discussed earlier this will cause duplicate signature errors on each bank. 

The more complete solution is to have a cache per bank that says which votes made it through so that we can then skip playing them repeatedly. But how many votes would I track? At the moment there's no way to track timestamp inside the bank since it receives votes as a "Packets" in its banking stage thread. No timesstamps for it to look at.

**Comment by aeyakovenko** [comment]
You don’t need a cache, just ts per bank and run the current algo.  That will force us to retry old votes on banks on older forks.

**Comment by sagar-solana** [comment]
@aeyakovenko so move the HashMap I have in the vote_listener to live inside the bank (Arc and rwlock) and inherit it for each child child bank? 

Then should I also do a strictly greater than check?

**Comment by aeyakovenko** [comment]
@sagar-solana @carllin 

I guess the right way to do this would be to keep a 120 + 32 block hash cache of all the votes.  Then apply to them to each bank and expire the old ones as banks are rooted.  

I wonder if we need gossip to maintain a queue, so all the nodes globally continuously share all the votes.  Otherwise there is a chance that I submit vote

Vote1:  slot 1, 2, 3
Vote2: slot 1, 2, 3, 5

Vote1 may not propagate everywhere, and Bank4 cannot apply Vote2 because the BankHash and BlockHash are for Bank5.

**Comment by sagar-solana** [comment]
not the right fix

**Pull request closed without merging**
