### PR TITLE
use gh cli to get affected files

### PR DESCRIPTION
**Pull request by yihau**
#### Problems

TLDR: We don't handle pagination for github api in our ci-gate bot. Use gh cli tool to get affected files instead.

https://discord.com/channels/428295358100013066/560503042458517505/1066925491401019462

#### Summary of Changes

use gh cli to get affected files

### CODE REVIEW

**Comment by yihau** [comment]
need https://github.com/mvines/ci-gate/pull/316

**Comment by yihau** [comment]
seems it got affected files correctly 
Screenshot 2023-01-24 at 2 20 46 AM

**Comment by mvines** [comment]
Oh, it looks like the `CI_BRANCH` env var is set to something reasonable, `"pull/29823/head"` in this case. wdyt about pulling the PR number out of there instead of relying on ci-gate for this info. One less thing to undo if/when we can finally get rid of ci-gate

**Comment by yihau** [comment]
That's a good idea! Now it filters the PR number from `CI_BRANCH` 😈

**Review by mvines — APPROVED** [review]

**Pull request merged**
