### PR TITLE
geyser: add `is_reload` argument to `on_load`

### PR DESCRIPTION
**Pull request by fanatid**
#### Problem

Plugins are not able to distinguish loading and reloading.

#### Summary of Changes

Add `is_reload` argument to `on_load` plugin function.

### CODE REVIEW

**Comment by lijunwangs** [comment]
This changes the interface. Why does a plugin care about if it is reload or a new load?

**Comment by fanatid** [comment]
> This changes the interface. Why does a plugin care about if it is reload or a new load?

The plugin can have a special logic for accounts from snapshot and will not work on reloading / loading through rpc.

**Review by lijunwangs — APPROVED** [review]
Looks good

**Review by lijunwangs — CHANGES_REQUESTED** [review]
There are bunch of CI fmt failures, please correct

**Comment by fanatid** [comment]
Updated!

**Review by lijunwangs — APPROVED** [review]
Looks good

**Pull request merged**
