### PR TITLE
Bugfix/test get rent collection accounts remove random account

### LINKED ISSUE #26172: test_get_rent_collection_accounts is flaky
#### Problem
`snapshot_minimizer::tests::test_get_rent_collection_accounts` is flaky in CI.

https://buildkite.com/solana-labs/solana/builds/76410#01818d58-351e-4766-9d43-25dfca44d585 failed with:
```
thread 'solana-cleanup-accounts-0' panicked at 'overflow is detected while summing capitalization: TryFromIntError(())', runtime/src/accounts_hash.rs:667:14
```

#### Proposed Solution
Analyze and fix

### PR DESCRIPTION
**Pull request by apfitzge**
#### Problem
There was a random pubkey generated during genesis config creation. This may have fallen in the rent collection range, and caused the test to fail.

This is branched off https://github.com/solana-labs/solana/pull/26177 which was causing build errors.

#### Summary of Changes
Use GenesisConfig::default instead, so there's no random account generated.

Fixes #26172

### CODE REVIEW

**Review by behzadnouri — DISMISSED** [review]
lgtm

**Comment by brooksprumo** [comment]
Also note that annoyingly there are multiple `create_genesis_config()` functions that do _slightly_ different things...

https://github.com/solana-labs/solana/blob/102fb98070aff3a831165ce1fa5763f71d00ecb4/runtime/src/genesis_utils.rs#L77-L87

https://github.com/solana-labs/solana/blob/102fb98070aff3a831165ce1fa5763f71d00ecb4/sdk/src/genesis_config.rs#L101-L113

This confused me for a while. Most notably for me, especially in tests, is that genesis_utils enables all features and genesis_config does not.

**Comment by solana-grimes** [comment]
:scream: New commits were pushed while the automerge label was present.

**Comment by brooksprumo** [comment]
Can probably rebase this PR on top of master to remove the changes already from https://github.com/solana-labs/solana/pull/26177.

**Pull request merged**
