### PR TITLE
Enable bench

### PR DESCRIPTION
**Pull request by sakridge**

### CODE REVIEW

**Comment by garious** [comment]
@sakridge, we're breaking bench so frequently now that if this really is only a 10 minute build (not 18), we should go ahead and merge it. Have you done any additional testing, or just the one run?

**Comment by sakridge** [comment]
@garious I've done about 5 runs because I was trying to get the same build machine to see the cached performance, although they all ended up around the same time. What other testing did you have in mind?

**Comment by garious** [comment]
That's good. Go ahead and merge it.

**Comment by garious** [comment]
Nice, only 8 minutes that time.

**Comment by sakridge** [comment]
Now it passes and still only 8 minutes, not bad...

**Pull request merged**
