### PR TITLE
bigtable: remove extra clones

### PR DESCRIPTION
**Pull request by fanatid**
extracted from #34213

Right now we clone `AccessToken` on every request to BigTable, also we clone it when making a token refresh. Inside `AccessToken` we clone [Credentials](https://docs.rs/goauth/latest/src/goauth/credentials.rs.html#9-22) struct which contains few strings and also clone 2 Arc. We can wrap everything into one Arc and significantly reduce the number of clones.

### CODE REVIEW

**Comment by fanatid** [comment]
@CriesofCarrots what can I do to make it merged? We do not need to clone `Credentials` with a lot of Strings inside :/

**Comment by CriesofCarrots** [comment]
Also, looks like you'll need to rebase to pick up the audit fix

**Comment by fanatid** [comment]
Updated!

**Review by CriesofCarrots — APPROVED** [review]

**Comment by fanatid** [comment]
Thank you!

**Pull request merged**
