### PR TITLE
Explorer: introduce program logs section on transaction details page

### PR DESCRIPTION
**Pull request by oJshua**
#### Problem
Transaction instruction logs are not easy to view, and not at all from the explorer. This would be a great debug tool for program developers.

#### Summary of Changes
Adds program log section on Explorer transaction details page

Fixes https://github.com/solana-labs/solana/issues/12209

### CODE REVIEW

**Comment by oJshua** [comment]
Depends on web3.js update.

**Comment by jstarry** [comment]
@oJshua is this still blocked on web3 changes?

**Comment by oJshua** [comment]
@jstarry still blocked. Just need to get a web3 release out.

**Comment by jstarry** [comment]
@oJshua do you have an example of what this looks like? Doesn't look like program log support has been released to any clusters yet right?

**Comment by oJshua** [comment]
Explorer-Solana (2)

**Review by jstarry — APPROVED** [review]

**Pull request merged**
