### PR TITLE
Dynamic network test changes

### PR DESCRIPTION
**Pull request by pgarg66**
- No sigverify if feature sigverify_cpu_disable is used
- Purge validators in the test if lag count increases beyond
  SOLANA_DYNAMIC_NODES_PURGE_LAG environment variable
- Other useful log messages in the test

### CODE REVIEW

**Comment by garious** [comment]
This is a misuse of cargo feature flags. We should only use those to control crate dependencies and not generally for conditional compilation. To disable sigverify from an integration test, you should add a parameter to FullNode and pass it down to the TPU and/or TVU and their respective SigverifyStage.

**Comment by pgarg66** [comment]
@garious , I'll change the code as you suggested.

**Comment by garious** [comment]
ok, usually folks do that without merging first.  Also, you added the executable bit to a bunch of Rust source code files. Can you put that back?

**Comment by pgarg66** [comment]
Sorry, I merged it after seeing thumbs up from @aeyakovenko . I'll also fix the executable bits for the source code. Not sure what caused that..

**Comment by garious** [comment]
Let's only use GitHub's code review mechanism and assume any emojis only indicates excitement for the work being done.

**Pull request merged**
