### PR TITLE
Fix a possible test hang in runtime::test_shared_buffer_sweep

### PR DESCRIPTION
**Pull request by sowhu**
#### Problem

The test may hang if the total number of threads it wants to start
is greater than the number of threads configured in the rayon
threadpool. 

#### Summary of Changes

Check to avoid this situation from happening.

Fixes #

### CODE REVIEW

**Comment by xiangzhu70** [comment]
could it be something like the below, which keeps threads as immutable?

let threads = std::cmp::max(8, rayon::current_num_threads())

**Comment by sowhu** [comment]
> could it be something like the below, which keeps threads as immutable?
> 
> let threads = std::cmp::max(8, rayon::current_num_threads())

Thanks. But it is not quite in accordance with the original intention. It wants to set the threads to 8 or a constant number. Only if this number is higher than the current_num_threads, we want to change it to current_num_threads. So for example, if rayon::current_number_thread() is 16 on the running system, we still want threads to be 8.

**Comment by sowhu** [comment]
> could it be something like the below, which keeps threads as immutable?
> 
> let threads = std::cmp::max(8, rayon::current_num_threads())

Thanks. But it is not quite in accordance with the original intention. It wants to set the threads to 8 or a constant number. Only if this number is higher than the current_num_threads, we want to change it to current_num_threads. So for example, if rayon::current_number_thread() is 16 on the running system, we still want threads to be 8.

**Comment by xiangzhu70** [comment]
my bad.  It should be "min", not "max".

let threads = std::cmp::min(8, rayon::current_num_threads())

**Comment by sowhu** [comment]
> my bad. It should be "min", not "max".
> 
> let threads = std::cmp::min(8, rayon::current_num_threads())

Good point. I have changed the code just as you suggested.

**Review by xiangzhu70 — APPROVED** [review]

**Pull request merged**
