### PR TITLE
Fix parent record locks usage in child banks

### PR DESCRIPTION
**Pull request by carllin**
#### Problem
After a leader -> validator transition, a child bank tracks the parent's account locks because the parent could still have uncommitted transactions. Currently, this means the validator will drop any transactions that touch the same accounts as an ongoing transaction in the parent.

#### Summary of Changes
1) Introduce record locks that track which accounts are in the record + commit phase in banking stage
2) Child banks only needs to track the record locks from the parent
3) When the child bank sees a transaction that touches an account in the parent's set of record locks (implying this account is in the middle of recording + committing), loop until that account is freed: https://github.com/solana-labs/solana/compare/master...carllin:Fix2?expand=1#diff-0104dfa96426a3a49428815872a0356eR357

Fixes #

### CODE REVIEW

**Comment by carllin** [comment]
hmmm link? We shouldn't need any guards for locks acquired in blocktree_processor because we shouldn't have any records or commits in blocktree_procesor's process_entries().

**Comment by rob-solana** [comment]
> hmmm link? We shouldn't need any guards for locks acquired in blocktree_processor because there aren't any records or commits in blocktree_procesor's process_entries().

https://github.com/solana-labs/solana/blob/e9f80e554233a9bee586d5c228199590345ad1a8/core/src/blocktree_processor.rs#L86

we don't verify that that every entry is self-consistent without a check after that line

> 
> The edits to the test test_parent_locked_record_accounts(), should cover the changes/calls to lock_acounts() and lock_record_acounts(), adding a test for the LockedAccountsResults changes

**Comment by carllin** [comment]
If there are conflicting locks within the same entry, then the lock results will contain an error for some of the transactions, and the bank will just not play those transactions right?

**Comment by rob-solana** [comment]
> If there are conflicting locks within the same entry, then the lock results will contain an error for some of the transactions, and the bank will just not play those transactions right?

it is a protocol error to construct an Entry whose Transactions cannot be processed in parallel (i.e. have data dependencies)

**Comment by carllin** [comment]
ok, so I should basically bail here: https://github.com/solana-labs/solana/pull/4159/files#diff-41caef3d0ec9e986f40e5e60e349b441R85 instead of just logging a metric. It seems like it'll be good to eventually have a way to start marking forks as dead

**Pull request merged**
