### PR TITLE
Update maintainers references

### PR DESCRIPTION
**Pull request by joeaba**
#### Problem
There are some old maintainer references that need to be updated

#### Summary of Changes
Update all maintainer references

### CODE REVIEW

**Review by mvines — COMMENTED** [review]
The changes to `web3.js/` should be made in a separate commit where a commit title like "chore: update maintainers reference" to make the build happy. 
Otherwise looks good to me

**Comment by mvines** [comment]
[revert: web3.js changes](https://github.com/solana-labs/solana/pull/29997/commits/4293fc84b4f445492f66010e0b31cf51b83f18db) won't cut it, the script is too smart for that. You'll need to rewrite the commits such that the only commit that touches web3.js uses the correct semantic release commit title convention

**Review by mvines — APPROVED** [review]

**Comment by steveluscher** [comment]
I wouldn't worry about it too much @joeaba. What @mvines said is correct, but I'd just jam it in, let it fail the web3.js build, and let the next web3.js commit paper over it.

**Comment by joeaba** [comment]
Thanks, Chido just fixed the build, so it should be good now

**Pull request merged**
