### PR TITLE
fix: fix flow type declaration

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
`flowgen` tool produced invalid flow type definition and we had no way to detect that.

#### Summary of Changes
- Fix flow type issue by removing `Exclude` usage
- Add flow type checker to build step
- Fix audit issues
- Update package-lock.json version
- Fix rollup replace plugin warnings

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
@t-nelson @oJshua @CriesofCarrots please update npm to v7 `npm install -g npm`

**Review by t-nelson — APPROVED** [review]
Pretty sure I'm not qualified to review this :upside_down_face: 

I can actually read the bits in connection.ts now though!

**Comment by jstarry** [comment]
You're qualified because you're awake 😉, thanks!

**Comment by t-nelson** [comment]
> You're qualified because you're awake wink, thanks!

I may be more qualified than I think. 'cause I got an updated local fork stuffed into spl-token/js and flow fixed :yawning_face:

**Comment by jstarry** [comment]
ignored CI failure because it was due to an earlier commit lint issue

**Pull request merged**
