### PR TITLE
add support auto-serde in Account and KeyedAccount (move Errors to help)

### PR DESCRIPTION
**Pull request by rob-solana**
#### Problem
 programs serialize and deserialize their state by hand making the code illegible

 #### Summary of Changes
 support state() and get_state() on Account()/KeyedAccount()
 export InstructionError to help expose, reduce circular dependencies

### CODE REVIEW

**Comment by garious** [comment]
Can you explain more why InstructionError needs its own module? We haven't needed that elsewhere in the codebase.

**Comment by garious** [comment]
What do you think about making this a method on CompiledInstruction instead? Seems more natural considering the error being called InstructionError.

**Comment by rob-solana** [comment]
maybe my next PR will illustrate where I'm going with this

**Comment by garious** [comment]
Can we hold off on this for a bit? I like it in spirit, but thinking that's a more powerful and less invasive way to do it. Might look something like this (and in `native_program.rs`):

```rust
     pub fn with_deserialized<T: Serialize + DeserializeOwned, F, E>(&mut self, func: F) -> Result<(), InstructionError>
    where F: Fn(&mut T) -> Result<(), E>
 {
        let mut state = deserialize(&self.data).map_err(|_| InstructionError::InvalidAccountData);
        func(&mut state).map_err(|err| InstructionError::CustomError(&serialize(err).unwrap());
        serialize_into(&mut self.data, state).map_err(|err| match *err {
            ErrorKind::SizeLimit => InstructionError::AccountDataTooSmall,
            _ => InstructionError::GenericError,
        })
    }
```

It's really that `DeserializedOwned` that catches my eye. With the pattern above, we might consider making that function borrow `Account.data` to drop all mallocs.

**Comment by garious** [comment]
What do you think about renaming `native_program.rs` to `instruction_processor_utils.rs` and making it a catch-all for utilities like this until some "best" patterns emerge? We don't really have much serde expertise yet and I don't think we're tapping its full potential. It ought to be possible to do a zero-copy deserialize to a `&mut` and then not need that `serialize_into()`.  Alternatively, we might consider bypassing serde entirely and the passing the instruction processor a *pointer* to the account and then having the processor do an unsafe dereference to a struct with a `repr(C)`.

**Comment by rob-solana** [comment]
> Can we hold off on this for a bit? I like it in spirit, but thinking that's a more powerful and less invasive way to do it. Might look something like this (and in `native_program.rs`):
> 
> ```rust
>      pub fn with_deserialized<T: Serialize + DeserializeOwned, F, E>(&mut self, func: F) -> Result<(), InstructionError>
>     where F: Fn(&mut T) -> Result<(), E>
>  {
>         let mut state = deserialize(&self.data).map_err(|_| InstructionError::InvalidAccountData);
>         func(&mut state).map_err(|err| InstructionError::CustomError(&serialize(err).unwrap());
>         serialize_into(&mut self.data, state).map_err(|err| match *err {
>             ErrorKind::SizeLimit => InstructionError::AccountDataTooSmall,
>             _ => InstructionError::GenericError,
>         })
>     }
> ```
> 
> It's really that `DeserializedOwned` that catches my eye. With the pattern above, we might consider making that function borrow `Account.data` to drop all mallocs.

is this better in terms of allocations?  it's a bit worse from the point of usability (I need 2 or 3 states at a time, so nested closures)

**Comment by garious** [comment]
@rob-solana, that code is the same for allocations, but the interface (except DeserializedOwned) allows for that implementation to be swapped out with a zero-copy deserialize and no `serialize_into`.

Agreed on usability, hence the suggestion to start building an arsenal in a `instruction_processor_utils.rs` library instead of committing to the path this PR is on.

**Comment by garious** [comment]
The part that bugs me the most about this PR is that it adds a dependency on InstructionError from account.rs.  Accounts are referenced by instructions. Accounts don't know anything about instructions. Even the Account.data is just an opaque data type.

**Pull request closed without merging**
