### PR TITLE
Migrate fullnode tests to create_tmp_sample_blocktree

### PR DESCRIPTION
**Pull request by garious**
#### Problem

Engineering access to ctrl^v, ctrl^c

#### Summary of Changes

`<delete>`

### CODE REVIEW

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by garious** [comment]
@jackcmay  this `stable-perf` error is failing across multiple PRs with the same ActiveStakers error. That test is fairly simple. It pushes a vote and then fails saying the account is not found. Is it possible your recent cargo work broke the perf build?

**Comment by jackcmay** [comment]
@garious It's possible, but looking at the log in this pr the failures appear to be failures in tests related to the topic of this pr.  Do these failing tests have dependencies elsewhere in the tree that are not being built after my change?  I did fix an issue with the `programs` test where `programs` was dependent on `native/noop` but was relying on it being built by something else in the tree.  `programs/Cargo.toml` was missing an explicit dependency on `native/noop`.

**Comment by jackcmay** [comment]
Does ci/test-stable-perf.sh run fine locally?

**Comment by garious** [comment]
@jackcmay, yes,  passes locally

**Comment by jackcmay** [comment]
I'm working on a change which should re-hide any dependency issues to unblock for now.  I also cannot recreate locally :-(

**Pull request merged**
