### PR TITLE
Initial ValidatorInfo program

### PR DESCRIPTION
**Pull request by CriesofCarrots**
Validators (for TdS and beyond) need a way to publish information about themselves.
This PR offers as a solution a simple registration CLI, tapping a new ValidatorInfo on-chain program. Validator info is stored in vCard (RFC 6350) format. The CLI offers the following fields (with vCard analog):

- Validator name (FN)
- Validator website (URL)
- Validator keybase id (UID)
- Validator details (NOTE)

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
@mvines , I am hoping for a few bits of direction from you:

1. Should I tap the getProgramAccounts RPC to do duplicate checking before registering a new validator? Currently, the register-validator CLI doesn't do any duplicate checking, so a validator could register itself as many times as it wants, assuming it has enough lamports to deposit 1 in the Info account to keep it open and cover fees.
2. There aren't a lot of options for VCard libraries in Rust. The one I found doesn't do any parsing; I would like to verify the VCard format in the ValidatorInfo program. Do you think it's worth me taking the time to write a parser?
3. Do you think I should make it harder for Validators to overwrite their previous info? Right now, if you provide the Info account pubkey and sign the transaction, it will go ahead an overwrite.

**Comment by mvines** [comment]
> @mvines , I am hoping for a few bits of direction from you:
> 
> 1. Should I tap the getProgramAccounts RPC to do duplicate checking before registering a new validator? Currently, the register-validator CLI doesn't do any duplicate checking, so a validator could register itself as many times as it wants, assuming it has enough lamports to deposit 1 in the Info account to keep it open and cover fees.

This is probably ok for now.  I'd expect we'd cross-reference the registration account with a vote account or the [current cluster nodes](/solana-labs.github.io/solana-web3.js/class/src/connection.js~Connection.html#instance-method-getClusterNodes) in the leaderboard UI to filter out old entries.  

> 2. There aren't a lot of options for VCard libraries in Rust. The one I found doesn't do any parsing; I would like to verify the VCard format in the ValidatorInfo program. Do you think it's worth me taking the time to write a parser?

Oh no.  I'm sorry for being unclear, I mentioned vCard mostly in jest as an example of something way over the top for our needs (I'll use more :rofl: emojis next time!!)  A stoopid linear list of name:string -> value:string is more than sufficient. 

I'd love to be able to use the existing `Config` program for this, like `solana-install` does, instead of writing a new program:
* https://github.com/solana-labs/solana/tree/master/programs/config_api
* https://github.com/solana-labs/solana/blob/3557975c1f42bbf29619beb3056eff8aae313253/install/src/update_manifest.rs#L2

We can just encode the data as a series of utf8-strings (name0value0name1value1..) with a u8 length at the start of each string.  That'll be easy to decode in Rust/JS.

One limitation of the Config program is that it doesn't allow for partial stores, see https://github.com/solana-labs/solana/blob/3557975c1f42bbf29619beb3056eff8aae313253/programs/config_api/src/config_instruction.rs#L23-L26, which could be an issue if the data in the validator config gets too large.  But I like the idea of solving this in the Config program for all future Config program users too.   

> 3. Do you think I should make it harder for Validators to overwrite their previous info? Right now, if you provide the Info account pubkey and sign the transaction, it will go ahead an overwrite.

Nope.  As long as they can prove ownership of the account, update away.

**Comment by CriesofCarrots** [comment]
Oh, ha! Cool, I'll strip all that vCard stuff out, then.

One question about using Config program, though... Don't we want these `ValidatorInfo` accounts to all be owned by a unique program id, as opposed to the Config program id?

**Comment by mvines** [comment]
> One question about using Config program, though... Don't we want these `ValidatorInfo` accounts to all be owned by a unique program id, as opposed to the Config program id?

I don't think it matters much, the front-end still needs to read/validate all the account contents anyway.  We could add unique u32/u64 value at the start of each ValidatorInfo config program account data to quickly filter out non-ValidatorInfo configs as a first pass when loading.   But yeah this definitely exposes that we don't have a nice program module concept yet :)

**Comment by CriesofCarrots** [comment]
@mvines , one other issue about using the Config program: I think the Validators should be able to make info updates by signing with their Validator keypair (not the Config account keypair). But this won't be feasible with the current Config processor. Edit Config? Or is that a valid argument for a separate program?

**Comment by mvines** [comment]
> @mvines , one other issue about using the Config program: I think the Validators should be able to make info updates by signing with their Validator keypair (not the Config account keypair).

Yeah definitely. 

> But this won't be feasible with the current Config processor. Edit Config? Or is that a valid argument for a separate program?

Potentially.   If we extended Config to support this, I think we'd allow multiple signatures to the Config store command.   The Config account keypair is still required, then the pubkey of any other signatures preset would be recorded in the account data as well as evidence of their authorization of the updated account content.  That seems generally useful.  wdyt?

> One limitation of the Config program is that it doesn't allow for partial stores, 

Actually with the larger Transaction size we now have,
https://github.com/solana-labs/solana/blob/578c2ad3ea1ecce9b9adac4196948008be957f4e/sdk/src/packet.rs#L5,
lack of partial stores is probably ok here.  ~1k of ValidatorInfo seems plenty

**Comment by CriesofCarrots** [comment]
> Potentially. If we extended Config to support this, I think we'd allow multiple signatures to the Config store command. The Config account keypair is still required, then the pubkey of any other signatures present would be recorded in the account data as well as evidence of their authorization of the updated account content. That seems generally useful. wdyt?

Yeah, I like it!
I was trying to avoid making Validators keep track of 2 keypairs for this (Validator identity and Config account), but I can probably come to terms with that.

**Pull request closed without merging**
