### PR TITLE
Watchtower improvements

### PR DESCRIPTION
**Pull request by im-0**
#### Problem

There are two problems with current `solana-watchtower`:

1. It is not always possible to tell to which cluster certain error message belongs if two `solana-watchtower` processes (one for the Testnet and one for the Mainnet) send notifications into the same one channel.
2. `Error: rpc-error: error sending request for url (https://api.testnet.solana.com/): connection closed before message completed` every two minutes. This problem seems to be rare and depends on ISP. Quick search on Discord shows that I am not the only one affected: 
image

#### Summary of Changes

* `Add watchtower option to add custom string into notifications` addresses first problem.
* `Add a builder for an HttpSender to support more client options` makes HTTP RPC client more configurable, with a possibility to add more configuration options in future.
* `Add watchtower option to specify RPC timeout` makes HTTP RPC timeout adjustable for `solana-watchtower`. This does not fix anything for me, but I decided to keep it as `solana` CLI has `--rpc-timeout` option too.
* `Allow reducing HTTP's pool idle timeout in watchtower` addresses second problem. As an alternative solution I also tried to enable TCP keeplive, without any success.

### CODE REVIEW

**Comment by im-0** [comment]
V2 patchset:
* Builder removed
* Regular timeout value used for `pool_idle_timeout`
* Rebased on current master

Default 30 second pool idle timeout fixes `connection closed before message completed` for me. Also, I could not think of any arguments why setting regular timeout and pool idle timeout to the same value may be bad.

**Review by mvines — APPROVED** [review]
looks good, thanks for the changes. 
I'll keep an eye on CI and hopefully we can get this merged soon

**Comment by mvines** [comment]
CI failure is unrelated

**Comment by buffalu** [comment]
https://discord.com/channels/428295358100013066/560496939779620864/1073855514217287690

seeing poor performance with our HTTP proxy when this timeout is used (we were using 100ms) bc it says the pool idle timeout and seems to need to re-establish connection very frequently

image

**Comment by mvines** [comment]
I have no particular affinity to `.pool_idle_timeout(timeout)`, would and approve a PR that backs it out

**Comment by im-0** [comment]
Maybe add the pool idle timeout as a separate option as I originally proposed? Just reverting this change will reintroduce the original problem.

**Comment by buffalu** [comment]
> I have no particular affinity to `.pool_idle_timeout(timeout)`, and would approve a PR that backs it out

what're thought on breaking api change vs new method?

**Comment by im-0** [comment]
Can be done without an API-breaking change:

* https://github.com/solana-labs/solana/commit/9ad472caf9272b5aa281ff29ab140f9933983cdc
* https://github.com/solana-labs/solana/commit/df4c46c3e0e336cb1e6a5cc8d6524645400e7a6a

**Pull request merged**
