### PR TITLE
wip: Add StakeProgramConfig sysvar

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

There is not a way to query the minimum stake delegation amount from a program.

#### Summary of Changes

- add StakeProgramConfig sysvar
- add feature-gate for sysvar
- set StakeProgramConfig in Bank::apply_feature_activations()
- add StakeProgramConfig to sysvar cache
- rename the Sysvar trait to LegacySysvar
- impl new Sysvar trait for StakeProgramConfig
- pass in StakeProgramConfig into stake_state via stake_instruction
- fixup tests

#### Outstanding Issue/Questions

- Versioning has not been implemented yet.
- How should programs get access to this sysvar? Since it is not an account, there may need to be a new api to handle fetching these new-style sysvars.
- Is it worthwhile to _not_ put this sysvar in an account? I don't want to waste a lot of time coming up with a new api if it won't end up being worth it.

### CODE REVIEW

**Comment by mvines** [comment]
How about a dedicated MinimumStakeDelegation sysvar.  This solves the versioning issue with "StakeProgramConfig" and also doesn't attempt to create a larger config thing when likely we will never need it

**Comment by brooksprumo** [comment]
> How about a dedicated MinimumStakeDelegation sysvar. This solves the versioning issue with "StakeProgramConfig" and also doesn't attempt to create a larger config thing when likely we will never need it

Yeah, I like that. It's what I originally had too. And, if this sysvar is *not* in an account, then I would think that'll allow any future stake-program-config-like sysvars to be added easily.

**Comment by jstarry** [comment]
> How should programs get access to this sysvar? Since it is not an account, there may need to be a new api to handle fetching these new-style sysvars.

Do you mean on-chain programs? They can directly use the syscall that you added to get the value. For off-chain clients, we will likely need a new `get_sysvar` rpc api (that can come later)

**Comment by brooksprumo** [comment]
Closing this PR, as going down the Sysvar approach has been abandoned in favor of adding a new instruction. See #24057 for more information.

**Pull request closed without merging**
