### PR TITLE
Unforced avx and avx2 features

### LINKED ISSUE #10126: AVX2 runtime check fails when compiled on hosts without AVX2
#### Problem

As per [RFC2045](https://github.com/rust-lang/rfcs/blob/master/text/2045-target-feature.md#motivation-and-summary) `#[target_feature(enable = "...")]` always emits code, said code is simply assumed to only be reachable on targets where the desired feature is available. This means our [AVX2 runtime check](https://github.com/solana-labs/solana/pull/10033) is always emitted and that the suggested remediation, to build on the target machine, is ineffective. The AVX runtime check is presumably similarly broken, but I have no access to HW to test on

#### Proposed Solution

We can get the intended behavior by switching to `#[cfg(target_feature = "avx2")]` and setting `-C target-cpu=native` in `RUSTFLAGS` for automation

cc/ @mvines

### PR DESCRIPTION
**Pull request by vkomenda**
#### Problem

AVX and AVX2 features were forced on x86 instead of being enabled when available on the target.

#### Summary of Changes

Flag checks are run only if the flags are enabled in `RUSTFLAGS`:
```
RUSTFLAGS="-C target-cpu=native" cargo build --release --all
```
or
```
RUSTFLAGS="-C target-feature=+avx -C target-feature=+avx2" cargo build --release --all
```

Fixes #10126 

#### Outstanding issues

Scripts and docs should be updated unless there is a better method without using `RUSTFLAGS`.

### CODE REVIEW

**Comment by t-nelson** [comment]
@vkomenda I'm glad to hear this resolved the issue you observed.  Thanks for picking it up! 🙏 

@mvines any preference on specifying `RUSTFLAGS`?  We could do it globally either; directly in the scripts or, by adding a `.cargo/config` to the project root. Alternatively, I think a `.cargo/config` in the `core` directory would just apply there. Either way, I suspect we're going to be enabling some dependency SIMD, so need to consider those side-effects

**Comment by mvines** [comment]
Set `RUSTFLAGS="-C target-cpu=native"` within `scripts/cargo-install-all.sh`?

**Comment by vkomenda** [comment]
@mvines, is it possible that that script is used for cross-compilation? I'm asking because `target-cpu=native` or `march=native` won't work then. I sent a related PR https://github.com/solana-labs/reed-solomon-erasure/pull/2. Otherwise, sure, I can add the flag in that script.

**Comment by mvines** [comment]
I don't think we have a formal cross-compilation workflow.  It seems like your rpi container work is likely taking the lead on that front right now, what works best for you?   I'm mostly neutral on this issue overall right now.

**Comment by vkomenda** [comment]
Hopefully this works as expected. The only problem now is how to build it locally. I used to `cargo build --release`. However now this also requires setting the correct `RUSTFLAGS`... Can the target CPU be computed in `build.rs` as an alternative?

**Comment by t-nelson** [comment]
@vkomenda yes that should work just fine! You can build by running the script directly, `scripts/cargo-install-all.sh`.  I was working with https://github.com/t-nelson/solana/commit/80c15f1e76fa0f82825c68541e0e387e7c090d3b at the end of last week and confirmed that the expected features were built-in in all cases.

@mvines I'm assuming we also want CI running this configuration, since that's how releases will be configured

**Comment by mvines** [comment]
> Hopefully this works as expected. The only problem now is how to build it locally. I used to `cargo build --release`. However now this also requires setting the correct `RUSTFLAGS`... Can the target CPU be computed in `build.rs` as an alternative?

Wait, `target-cpu=native` is not the default?   Having users need to set `RUSTFLAGS` before a normal `cargo build --release` to get binaries for *their* machine is going to be a footgun.  I was under the impression that we'd only need to fiddle with `RUSTFLAGS` in `scripts/cargo-install-all.sh` (the script that ultimately produces the release binaries), so that even though we build on machines with AVX2 the binaries would cleanly exit if run on a machine without AVX2

**Comment by vkomenda** [comment]
> Wait, `target-cpu=native` is not the default?

Correct. Earlier I tried compiling with the empty RUSTFLAGS and none of AVX or AVX2 were enabled. It was on a machine with AVX and without AVX2.

**Comment by mvines** [comment]
🤯 
Oh then a build.rs solution that sets RUSTFLAGS to include `target-cpu=native` seems way better, but then with a check for the `CI` env var in `scripts/cargo-install-all.sh` that overrides this to declare the exact CPU features we expect the release binaries to have.

**Comment by t-nelson** [comment]
AFAIK, we can commit a `.cargo/config` to project root and set `RUSTFLAGS` there

**Comment by mvines** [comment]
> AFAIK, we can commit a `.cargo/config` to project root and set `RUSTFLAGS` there

k, so `.cargo/config` configures the default in the monorepo to use `target-cpu=native` then we have a CI-envvar gated override in `scripts/cargo-install-all.sh` to ensure the release binary artifacts are build with predictable CPU flags regardless of what machine a particular CI build runs on.    Does that sounds right?

**Comment by t-nelson** [comment]
That's the way I understand it working. I'll take it for a test drive to ensure the implementation matches the docs

**Comment by t-nelson** [comment]
With this commit https://github.com/t-nelson/solana/commit/6d3d399a09729f3271ae0260a79715c49b1948ab, I was able to confirm the expected behavior.  That is, an AVX2-supporting build host always emits AVX2 code, while a non-supporting build host does not emit AVX2 upon `cargo build`, but does upon `scripts/cargo-install-all.sh ...`.  I can look into gating it on a `CI_RUSTFLAGS` or similar (and unifying where this happens)

**Comment by mvines** [comment]
nice sounds good

**Comment by ryoqun** [comment]
some validator is again experiencing odd errors `opcode invalid`. let's revive this pr in some way?

**Comment by ryoqun** [comment]
@vkomenda Hi, are you going to work on this in near future? I'd like this to move forward. If not possible, I'm happy to take this over. :)

**Comment by vkomenda** [comment]
> @vkomenda Hi, are you going to work on this in near future? I'd like this to move forward. If not possible, I'm happy to take this over. :)

I'm happy with you taking it over! I can help you of course if needed.

**Pull request closed without merging**
