### PR TITLE
Use iftop to collect network bandwidth usage

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
Need a mechanism to monitor network bandwidth usage, and identify packet drops in a connection (where connection = uniq(Src IP,  Src Port, Dest IP, Dest Port))

#### Summary of Changes
Use `iftop` to collect this information

Fixes #

### CODE REVIEW

**Comment by aeyakovenko** [comment]
I think we need to translate local interface address to the public IP as well.

**Comment by pgarg66** [comment]
> I think we need to translate local interface address to the public IP as well.

Yes, that's true. We can probably do that in post-processing using information from the cloud.

**Comment by pgarg66** [comment]
@mvines ok to merge?

**Comment by mvines** [comment]
One minor thing: we'd want the new pid file added to https://github.com/solana-labs/solana/blob/90461245f9db9b43721cc98058d592c6d2e37ae1/net/net.sh#L811

**Comment by mvines** [comment]
Maybe just generalize this to the following for the next time we add a new widget:
```diff
-for pid in solana/{blockexplorer,net-stats,fd-monitor,oom-monitor}.pid; do
+for pid in solana/*.pid; do
```

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Pull request merged**
