### PR TITLE
Use release as default in getting started docs

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

People running the benchmarks often get debug mode instead of release and get poor performance. Also need to explain environment variables to them.

#### Summary of Changes

Change docs to release mode.

Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
This is going to suck for dev right?   Can we just fix the docs instead? 

Really we shouldn't have people building from source for initial benchmarking at all, use the latest release.  That's a bigger doc change though as we don't ship multinode-demo/ scripts in the release

**Comment by sakridge** [comment]
> This is going to suck for dev right? Can we just fix the docs instead?
> 
> Really we shouldn't have people building from source for initial benchmarking at all, use the latest release. That's a bigger doc change though as we don't ship multinode-demo/ scripts in the release

Dunno.. generally I use release mode since debug mode is very slow. I'm not sure what others are using.

**Comment by mvines** [comment]
debug is my go to during dev, `cargo build; cargo run`

**Comment by sakridge** [comment]
> debug is my go to during dev, `cargo build; cargo run`

Well this wouldn't affect that.. only if you are using multinode-demo scripts right?

**Comment by mvines** [comment]
I used them together.   I'll `cargo build` stuff, then run `multinode-demo/` stuff, then `cargo build` stuff some more.

**Comment by sakridge** [comment]
> I used them together. I'll `cargo build` stuff, then run `multinode-demo/` stuff, then `cargo build` stuff some more.

Ok. I'll just add NDEBUG=1 to the docs.

**Comment by mvines** [comment]
lgtm

**Pull request merged**
