### PR TITLE
Unhide --block-production-method

### PR DESCRIPTION
**Pull request by apfitzge**
#### Problem
- New scheduler is in, there's more than one option here, it shouldn't be hidden.
- I forgot to do this previously

#### Summary of Changes
- Don't hide the `--block-production-method` cli arg for validator

Fixes #

### CODE REVIEW

**Comment by steviez** [comment]
To confirm - all of the available `BlockProductionMethod` values are ready for testnet ?

**Review by taozhu-chicago — APPROVED** [review]
lgtm

**Comment by apfitzge** [comment]
> all of the available BlockProductionMethod modes are ready for further testing / evaluation on testnet ?

Yep. There was previously only 1 variant `thread-local-multi-iterator` which corresponds to the old BankingStage. A new variant, `central-scheduler`, was added recently. I did not realize that the argument was hidden when I added the new variant, otherwise I'd have unhidden it when I added it then.

**Comment by steviez** [comment]
> > all of the available BlockProductionMethod modes are ready for further testing / evaluation on testnet ?
> 
> Yep. There was previously only 1 variant `thread-local-multi-iterator` which corresponds to the old BankingStage. A new variant, `central-scheduler`, was added recently. I did not realize that the argument was hidden when I added the new variant, otherwise I'd have unhidden it when I added it then.

Sweet. Once we take testnet v1.18, we can probably either switch some of our nodes over and/or ask for volunteers to give it a go

**Pull request merged**
