### PR TITLE
nit: cleanup feature status display

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

Feature descriptions have gotten long which bungles the cli display of feature status

#### Summary of Changes

Re-org so that columns stay in alignment

Fixes #

### CODE REVIEW

**Comment by jackcmay** [comment]
@mvines, you ok with changing the `feature status` output in this way so the descriptions aren't clipped or push out the status column?

**Comment by mvines** [comment]
> @mvines, you ok with changing the `feature status` output in this way so the descriptions aren't clipped or push out the status column?

Most likely.  What does the output look like now with this PR?

**Comment by t-nelson** [comment]
While you're in here I have a feature request, if you don't mind :slightly_smiling_face: 

Can we switch the field separator from a single space to space-pipe-space (` | `)?  That'll make the output `sort`able :wink:

**Comment by jackcmay** [comment]
@mvines Just switch the status and description columns
@t-nelson If @mvines approves then I'll commit this the put your suggestion in in a separate commit so that we fix bench

**Review by mvines — APPROVED** [review]
Approved since you're holding CI hostage :)

**Pull request merged**
