### PR TITLE
cluster exit rpc

### PR DESCRIPTION
**Pull request by aeyakovenko**
#### Problem

Need a way to kill the entire cluster before resetting the network.

#### Summary of Changes

Implement the cluster exit rpc.

Fixes #

### CODE REVIEW

**Comment by pgarg66** [comment]
@aeyakovenko , in what conditions would a node call cluster_exit()?

**Comment by aeyakovenko** [comment]
@pgarg66 when we reboot the network it will call this api with curl on one of our nodes

**Comment by mvines** [comment]
Why not send `fullnodeExit` to each node?

**Comment by aeyakovenko** [comment]
That would work. But we need a way to get the entire network

**Comment by mvines** [comment]
I think I need a motivating use case to understand the real goal here.  But there are a couple ways already to get the entire cluster:
* if it's a closed testnet, you just know
* use gossip to find all the peers

**Comment by aeyakovenko** [comment]
I want to restart 3rd party nodes when we kick the network. This does exactly what you suggested. It uses a single nodes gossip view to kill everyone

**Comment by mvines** [comment]
`--poll-for-new-genesis-block` is not sufficient?

**Comment by aeyakovenko** [comment]
That’s way better!

**Pull request closed without merging**
