### PR TITLE
Initialize broadcaster to entry count

### PR DESCRIPTION
**Pull request by rob-solana**
oddly, this PR doesn't change observed behavior between multinode-demo nodes, nor does it appear to have any effect on Stephen's multinode validator catchup test #450  (which is included in this PR)

### CODE REVIEW

**Comment by aeyakovenko** [comment]
Is the initialized count 0?

**Comment by rob-solana** [comment]
in the multi_node tests, the count (both window and broadcaster) start at zero.  In the multinode-demo/, with a 10,000 token mint, they both start at 16385.

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by garious** [comment]
@rob-solana, you merged a PR with `...` commit messages. This should have been squashed.

**Comment by rob-solana** [comment]
whoops, do you want me to attempt a fix, rewite history or just be more careful in the future?

**Comment by garious** [comment]
Be more careful in the future. And use `fixup!` instead of `...`.

**Comment by rob-solana** [comment]
ack

**Pull request merged**
