### PR TITLE
Remove recycler and its usage

### PR DESCRIPTION
**Pull request by pgarg66**
- The memory usage due to recycler was high, and incrementing with
  time.

### CODE REVIEW

**Comment by pgarg66** [comment]
Previous PR: https://github.com/solana-labs/solana/pull/1352
Issue: https://github.com/solana-labs/solana/issues/1164

**Comment by garious** [comment]
I'm okay with it, but if we ever wanted to run the recycler experiment again, it's going to be a whole lot of work.

**Comment by pgarg66** [comment]
Sounds good. Will wait for review from @aeyakovenko. Also, I'll run the perf numbers before landing this.

**Comment by pgarg66** [comment]
**Performance comparison**
Current tip of master is pretty bad shape. The testnet (1 leader, 5 validators, 2 clients) does not stay up for more 3 minutes. The TPS is also ~40K.
This PR increases the testnet uptime. It's been running for last 20 minutes. The TPS numbers and finality are comparable to the tip of master.

**Comment by garious** [comment]
Let's restore high TPS on the testnet and then evaluate this again. Hopefully this helps #1370. We can't assume the recycler doesn't remove a bottleneck at 100k TPS just because it's not the bottleneck at 40k TPS.

**Comment by pgarg66** [comment]
I retested performance with the tip of master (with and without this PR)
**Performance Results**
Tip(2e00be262eeabc7398d399f988ade980bda6f793): (without this PR)
screen shot 2018-09-27 at 8 59 50 am

(With this PR)
screen shot 2018-09-27 at 9 36 25 am

The memory usage is below 10% after 25 minutes. Without this change it grows linearly, and OOM after about 50 minutes.

**Pull request merged**
