### PR TITLE
draft: Repair peer selection by similar stake

### PR DESCRIPTION
**Pull request by jbiseda**
Looking for thoughts on this approach.

#### Problem
repair requests should be distributed more evenly across nodes. Eventual goal is to prioritize repair requests from staked nodes.

#### Summary of Changes
Weight repair peers by similarity in stake to the current node. Highly staked nodes should be biased to repair from other highly staked nodes. Unstaked nodes should be biased to repair from unstaked nodes.

See #28374 for comparison of staked/unstaked egress/ingress repair traffic based on different peer selection criteria and description of metrics.

Measurements taken after startup while node is catching up.

Distribution using these changes with an unstaked node on mainnet:
Screen Shot 2022-10-13 at 2 45 36 PM
Screen Shot 2022-10-13 at 2 46 37 PM

Distribution for highly staked node (simulated) on mainnet:
Screen Shot 2022-10-13 at 4 26 43 PM
Screen Shot 2022-10-13 at 4 27 44 PM

With metrics to track repair retry counts...

3 validator startup cycles:
Screenshot 2023-01-04 at 8 20 41 PM

startup and processing:
Screenshot 2023-01-04 at 8 21 30 PM

Fixes #

### CODE REVIEW

**Comment by behzadnouri** [comment]
> Distribution for highly staked node (simulated) on mainnet:

* Can you please explain what improvement the plots do actually represent?
* How are you simulating a highly staked node on mainnet?
* Why should different weighting for repair peers impact `shred_fetch_repair`?

**Comment by jbiseda** [comment]
> > Distribution for highly staked node (simulated) on mainnet:
> 
> * Can you please explain what improvement the plots do actually represent?
The plots (here and in #28374) show the repair request distribution and the subsequent received repair shred distributions when using different mechanisms for peer selection. I'm considering a more widely distributed set of repair peers for unstaked nodes to be a positive change. The plots here show how more unstaked nodes are used to process repair requests from an unstaked node using this peer selection mechanism.

> * How are you simulating a highly staked node on mainnet?
I just used the max stake value among the repair peers as the stake for the current node (rather than its actual stake of 0) when selecting repair peers.

> * Why should different weighting for repair peers impact `shred_fetch_repair`?
The metrics in `repair_service-my_requests` show the distribution of repair peers for outgoing requests. The `shred_fetch_repair` metrics show the distribution of responses to the requests. Using these you can see a rough correlation of the success rate of using staked vs unstaked peers for requesting repairs. This is more prominently displayed in #28374 comparing "Existing distribution" with "Only unstaked nodes" and comparing the number of repair requests sent to the number of shreds received. See the note at the end of the summary for #28374.

**Comment by behzadnouri** [comment]
I guess we are weighting peers by stake for at least 2 reasons:
* increase the cost of attacks for bad actors; peers with higher stake have more incentive to act in good faith.
* nodes with higher stake likely have more compute and bandwidth resources and can handle more load.

The downside is obviously too much congesting and overloading few nodes.

So some stake weight in peer selection do make sense, but the question is what functional mapping from stake to sampling probability achieves the right trade-off in terms of both:
1. security: partitioning and attack resistance, ...
2. efficiency: propagation speed, load distribution, avoiding congestion and packet drop, etc 

So I am wondering:
* What is the advantage of this stake similarity weighting schema compared to just dampening stake weights?
* Would this stake similarity expose the cluster to any sort of partitioning or other sort of attacks?

I guess this stake similarity weighting is a special case of
```
sampling-weight-of-peer = f(my-stake, peer-stake)
```
i.e sampling weights are a function of both my stake and the peer's stake, and in that aspect it is interesting. Even turbine can be seen similarly, i.e the probability that I receive a shred from node `x` is a function of my node's stake and stake of node `x`.

**Comment by jbiseda** [comment]
> So I am wondering:
> 
> * What is the advantage of this stake similarity weighting schema compared to just dampening stake weights?

There are results for dampening in #28374 for both `ln()` and `ln(ln())` for comparison. This approach does have a more significant impact for directing requests from unstaked nodes to other unstaked nodes.

> * Would this stake similarity expose the cluster to any sort of partitioning or other sort of attacks?

Will still need to determine what impact this would have or what adjustments would be needed. However, this should not have a substantial impact on how more highly staked nodes distribute their repairs (mostly to other highly staked nodes). The largest change would be the repair distribution for unstaked nodes so should have less impact on attacks.

> I guess this stake similarity weighting is a special case of
> 
> ```
> sampling-weight-of-peer = f(my-stake, peer-stake)
> ```
> 
> i.e sampling weights are a function of both my stake and the peer's stake, and in that aspect it is interesting. Even turbine can be seen similarly, i.e the probability that I receive a shred from node `x` is a function of my node's stake and stake of node `x`.

Yes, this is my intention. Turbine has an explicit distribution tied to stake to essentially distribute from higher stake to lower staked nodes. This creates a fuzzy distribution that favors stake-similar peers.

My goal is to have unstaked nodes be more self sufficient amongst themselves, reducing repair load on highly staked nodes. Having a wider distribution of repair requests should allow for prioritization of repairs based on stake weight without starving unstaked nodes.

Having an unstaked node repair from other unstaked nodes does seem to be working acceptably, but this measurement was made in isolation. Is the unstaked node able to repair from other unstaked nodes only because those nodes are repairing from highly staked nodes, or will this distribution work as expected if all nodes use this request distribution mechanism?

**Comment by behzadnouri** [comment]
> Having an unstaked node repair from other unstaked nodes does seem to be working acceptably, but this measurement was made in isolation. Is the unstaked node able to repair from other unstaked nodes only because those nodes are repairing from highly staked nodes, or will this distribution work as expected if all nodes use this request distribution mechanism?

I think the best would be to create a simulation for the cluster where these things can be measured. The simulation would:
* Obtain mainnet or testnet stakes from the RPC client, similar to: https://github.com/behzadnouri/solana/blob/f921eef3f/core/src/turbine_sim.rs#L43-L82
* Create an _in memory_ cluster with similar stake distribution plus unstaked nodes.
* Simulate repair requests, peer selection, packet drop, etc and measures congestion and failure rate.

I will have to do something similar for gossip; perhaps similar constructs might be useful for repair.

**Comment by behzadnouri** [comment]
> > Having an unstaked node repair from other unstaked nodes does seem to be working acceptably, but this measurement was made in isolation. Is the unstaked node able to repair from other unstaked nodes only because those nodes are repairing from highly staked nodes, or will this distribution work as expected if all nodes use this request distribution mechanism?
> 
> I think the best would be to create a simulation for the cluster where these things can be measured. The simulation would:
> 
> * Obtain mainnet or testnet stakes from the RPC client, similar to: https://github.com/behzadnouri/solana/blob/f921eef3f/core/src/turbine_sim.rs#L43-L82
> * Create an _in memory_ cluster with similar stake distribution plus unstaked nodes.
> * Simulate repair requests, peer selection, packet drop, etc and measures congestion and failure rate.
> 
> I will have to do something similar for gossip; perhaps similar constructs might be useful for repair.

https://github.com/behzadnouri/cluster-mocks
is my framework to simulate gossip across cluster using the same stake distribution as mainnet or testnet with the setup described above. I think something similar can also be used to simulate and evaluate peer selection probabilities in repair.

**Pull request closed without merging**
