### PR TITLE
More fullnode to validator renaming

### PR DESCRIPTION
**Pull request by garious**
#### Problem

Legacy term "fullnode" lingering

#### Summary of Changes

Rename all remaining uses of "fullnode" in Rust modules to "validator"

### CODE REVIEW

**Comment by garious** [comment]
@CriesofCarrots @jstarry, do we have external dependencies that use that `fullnodeExit` RPC?

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots @jstarry, do we have external dependencies that use that `fullnodeExit` RPC?

v1 of the Network Explorer does use fullnodeExit RPC. I'll pr this change. Not sure if we'll extend that functionality into v2 in any way.

**Comment by jstarry** [comment]
> @CriesofCarrots @jstarry, do we have external dependencies that use that `fullnodeExit` RPC?

Don't know of anything besides what Tyera called out

**Comment by garious** [comment]
Alright, shipping it. Let's see what falls over.

**Pull request merged**
