### PR TITLE
derive TransactionCost::{PartialEq, Eq}

### PR DESCRIPTION
**Pull request by apfitzge**
#### Problem
Writing tests for these is pretty inconvenient w/o equal comparison.
Was in the process of adding some more tests to `QosService` after #31542  when I encountered this

#### Summary of Changes
derive PartialEq and Eq

Fixes #

### CODE REVIEW

**Review by taozhu-chicago — COMMENTED** [review]
not sure if the default impl compares `writable_accounts` correctly - only the content of vec matters, not the order.

**Comment by apfitzge** [comment]
> not sure if the default impl compares `writable_accounts` correctly - only the content of vec matters, not the order.

🤔 yeah, I guess that is true. For my test cases I was always getting the costs from the same transactions so order was equivalent.

I think it should only be used in tests, so I'm happy to write a custom one that checks contents instead of directly Vecs.

**Comment by taozhu-chicago** [comment]
> > not sure if the default impl compares `writable_accounts` correctly - only the content of vec matters, not the order.
> 
> 🤔 yeah, I guess that is true. For my test cases I was always getting the costs from the same transactions so order was equivalent.
> 
> I think it should only be used in tests, so I'm happy to write a custom one that checks contents instead of directly Vecs.

Yeah, i think it's ok to use default impl for test. I guess don't really need "deep" compare in regular code?

**Review by taozhu-chicago — APPROVED** [review]
lgtm

**Pull request merged**
