### PR TITLE
RPC: Return the data length for get account requests

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
Clients have no way to fetch the size of an account without fetching the entire data buffer of an account.

#### Summary of Changes
Add a `space` field to the account response type so that even if a data slice config of length 0 is used, the size of the account can still be known

Fixes #

### CODE REVIEW

**Review by CriesofCarrots — APPROVED** [review]
Cool

**Comment by steveluscher** [comment]
This busted some `web3.js` tests. I'll fix 'em!

**Comment by steveluscher** [comment]
I didn't look too closely; this is written in such a way that you'll also get this value through account _subscriptions_ right?

**Comment by jstarry** [comment]
> I didn't look too closely; this is written in such a way that you'll also get this value through account subscriptions right?

That's correct, thanks for fixing the tests!

**Pull request merged**
