### PR TITLE
runtime: remove `Default` req on account scan interfaces

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

the accounts scanning interfaces have a _seemingly_ unnecessary `Default` requirement, which restricts what types can be used to collect in to.

#### Summary of Changes

switch to `FnMut` closures and move the accumulator construction out to the call sites

### CODE REVIEW

**Comment by t-nelson** [comment]
first commit is the interesting one. second is straightforward from there

**Comment by Lichtso** [comment]
Might be more effort than it is worth, but can't `scan_accounts()` return an `impl Iterator`? Then we could simply collect into a container at the call site.

**Review by jeffwashington — APPROVED** [review]
lgtm

**Comment by t-nelson** [comment]
> Might be more effort than it is worth, but can't `scan_accounts()` return an `impl Iterator`? Then we could simply collect into a container at the call site.

i'd considered that but a couple of its sibling methods have some extra logic and i opted for a consistent api across them instead

**Pull request merged**
