### PR TITLE
feat: support pre and post token balances

### PR DESCRIPTION
**Pull request by oJshua**
#### Problem
Web3 should support the pre and post token balances (for deltas) on a confirmed block.

#### Summary of Changes
Add type support for pre and post token balances on confirmed block metadata.

### CODE REVIEW

**Comment by mvines** [comment]
@oJshua - is this PR ready to land?

**Comment by oJshua** [comment]
@mvines this is ready to go.

**Comment by oJshua** [comment]
@mvines  Actually, I just noticed one thing I will fix.

**Comment by oJshua** [comment]
Test failing from something upstream

**Review by mvines — APPROVED** [review]

**Pull request merged**
