### PR TITLE
Resurrect packet recycler

### PR DESCRIPTION
**Pull request by pgarg66**

### CODE REVIEW

**Comment by pgarg66** [comment]
This change caused an OOM on testnet after about 15 minutes of uptime

```
[ 1109.629853] Out of memory: Kill process 11224 (solana-fullnode) score 1777 or sacrifice child
[ 1109.639460] Killed process 11224 (solana-fullnode) total-vm:91623764kB, anon-rss:47493432kB, file-rss:454140kB, 
shmem-rss:24532kB
```

**Comment by pgarg66** [comment]
Performance is comparable with and without this change

image

**Comment by pgarg66** [comment]
@garious , @aeyakovenko ,

given this (comments above), I think we should abandon this PR for now. Thoughts?

**Comment by aeyakovenko** [comment]
Yea. Agreed. We need some further investigation why perf didn’t change

**Comment by garious** [comment]
Sounds good

**Comment by pgarg66** [comment]
Sathish's test setup had only leader node, whereas this test had 10 validator nodes as well. That could have some implications.

Closing the PR for now.

**Pull request closed without merging**
