### PR TITLE
Benchmark the banking stage

### PR DESCRIPTION
**Pull request by garious**

### CODE REVIEW

**Comment by garious** [comment]
@rlkelly

**Comment by rlkelly** [comment]
that makes sense to me, I took a stab at this and got part of the way through it.  Do you think it makes sense at this point to start writing some test utils for generating mint + users + events and things like that?

**Comment by garious** [comment]
Yes, that'd be really great. These tests are too verbose, which is making them both difficult to grok and to spin up small variations.

**Comment by rlkelly** [comment]
sounds good, I'll take a look in a little bit

**Pull request merged**
