### PR TITLE
bump `lz4-sys` to 1.9.4 as per RUSTSEC-2022-0051

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

https://rustsec.org/advisories/RUSTSEC-2022-0051.html

#### Summary of Changes

bump `lz4-sys` to v1.9.4

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Can you just bump `lz4` to v1.24.0, please?

**Comment by CriesofCarrots** [comment]
https://github.com/solana-labs/solana/blob/46a48760db409c6f255c79f49c250fed0b16a288/runtime/Cargo.toml#L30

**Comment by t-nelson** [comment]
> https://github.com/solana-labs/solana/blob/46a48760db409c6f255c79f49c250fed0b16a288/runtime/Cargo.toml#L30

`cargo update` is lame

**Comment by t-nelson** [comment]
checks clear. going in

**Pull request merged**
