### PR TITLE
feat:add-ws-header

### PR DESCRIPTION
**Pull request by Yohox**
#### Summary of Changes
add connection ConnectionConfig: "wsHeaders"

### CODE REVIEW

**Comment by quick-pawiromitchel** [comment]
bumping this 👍

**Comment by steveluscher** [comment]
So, I remember now why I didn’t do this. The RPC websockets library that we use _throws the header config out_ when you’re running in the browser.

https://github.com/elpheria/rpc-websockets/blob/trunk/src/index.browser.ts#L27

We should find a way to make this not confusing to people (ie. we shouldn’t offer them a config param that we know not to work without doing something to minimize that footgun).

**Comment by steveluscher** [comment]
(In case it wasn’t clear, `rpc-websockets` drops the headers config because browsers don’t support setting headers. https://stackoverflow.com/a/4361358/802047

**Comment by steveluscher** [comment]
What was the context for this PR? Did you have a use case for headers in _Node_?

**Comment by Yohox** [comment]
I use the orca rpc ws-provider but the rpc ws-provider should contain the header "origin"

function getSolanaConnection(): Connection {
    if (!solanaConnection) {
        const solanaConfig = require('../../network_config/solana.json')
        const headers = {
            origin: 'https://www.orca.so'
        }
        solanaConnection = new Connection(solanaConfig.http_url, {
            httpHeaders: headers,
            wsHeaders: headers,
            commitment: 'singleGossip',
            confirmTransactionInitialTimeout: 60 * 1000
        })
    }
    return solanaConnection
}

**Comment by steveluscher** [comment]
The [`origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) header is not a header that you're allowed to set. It's a [forbidden header](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name).

> …the rpc ws-provider should contain the header "origin"

Can you tell me why? If you give me all of the information upfront, it will help me review this PR.

* What environment are you doing this in? Node? The browser?
* Why does the header need to be set to something in particular?
* Who are you (ie. what is your role in the transaction between the Orca RPC and the app; does the app belong to Orca? Is it a third party app?)
* Your ideas for mitigating [this problem](https://github.com/solana-labs/solana/pull/24833#issuecomment-1165657477).

Thank you!

**Comment by Yohox** [comment]
What environment are you doing this in? Node? The browser?
Node

Why does the header need to be set to something in particular?
I write a node app it should use the orca rpc node, but the orca(/raydium) rpc node should include the origin, if it don't include it will reject connect.

Who are you (ie. what is your role in the transaction between the Orca RPC and the app; does the app belong to Orca? Is it a third party app?)
it's the third party app.

**Comment by steveluscher** [comment]
> I write a node app it should use the orca rpc node, but the orca(/raydium) rpc node should include the origin, if it don't include it will reject connect.

Isn't this a feature and not a bug? Presumably Orca only wants to admit requests to its RPC that come from its own domains. Can you point me to some documentation where Orca recommends spoofing its domain to grant access to third parties?

**Comment by mohan00710** [comment]
When i use Quicknode Rpc endpoint i am getting ws error 

```
ws error: Unexpected server response: 401
/Users/mohan/Desktop/kanalabs-working/test/code-test/node_modules/@solana/web3.js/lib/index.cjs.js:6119
          throw new TransactionExpiredBlockheightExceededError(rawSignature);
                ^

TransactionExpiredBlockheightExceededError: Signature 4qMYHxkc1999ghCE1fE2SgA8EBd4FGUtJYs3roaGa6BXikSjnKzLoXrH5zdpr9tZjZm8sZbK2yZbYxyZsW9nbesc has expired: block height exceeded.
    at Connection.confirmTransaction (/Users/mohan/Desktop/kanalabs-working/test/code-test/node_modules/@solana/web3.js/lib/index.cjs.js:6119:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.sendAndConfirmTransaction (/Users/mohan/Desktop/kanalabs-working/test/code-test/node_modules/@solana/web3.js/lib/index.cjs.js:3118:101)
    at async /Users/mohan/Desktop/kanalabs-working/test/code-test/rpc.js:75:29 {
  signature: '4qMYHxkc1999ghCE1fE2SgA8EBd4FGUtJYs3roaGa6BXikSjnKzLoXrH5zdpr9tZjZm8sZbK2yZbYxyZsW9nbesc'
}
```

**Comment by steveluscher** [comment]
Hey folks! I’m going to close this. If you’re having 401 authentication trouble with your RPC provider, contact them for help!

**Comment by GDdark** [comment]
I want to implement a proxy for the front-end to the Node service
This requires the front end to pass in some authentication information in the header when calling Node's WebSocket.

It's better to support header in connection WebSocket

@steveluscher

**Comment by steveluscher** [comment]
https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api/4361358#4361358 has your solution, @GDdark.

**Pull request closed without merging**
