### PR TITLE
remove IPADDR, which was making Rob feel ill

### PR DESCRIPTION
**Pull request by rob-solana**
IPADDR is simple, which is nice, but not exactly what we need for testnet, where NAT'd
  folks need to join in, need to advertize themselves as on the interweb.

  myip() helps, but there's some TODOs: fullnode-config probably needs to
  be told where it lives in the real world (machine interfaces tell us dick),
  or incorporate something like the "ifconfig.co" code in myip.sh

### CODE REVIEW

**Comment by aeyakovenko** [comment]
@rob-solana don't you think we will need physical vs virtual IPs?  Basically `fullnode-config` should ask the network for its addr, figure out if its actually reachable on the ports it thinks it has open, but tell the actual node to bind to 0, or whatever the interface can connect tot the network.

**Comment by rob-solana** [comment]
this PR allows the user to decide whether he's going to run a network on his internal network or talk to the real world.  the default choice is to use the interface that presents in the real world (via http://ifconfig.co)

**Comment by garious** [comment]
rebase and shellcheck? Feel free to automerge on successful CI

**Comment by mvines** [comment]
(The publish-snap ci job is still red so auto merge will fail.  Fixing this today...)

**Pull request merged**
