### PR TITLE
CI - Disables Downstream Project actions

### PR DESCRIPTION
**Pull request by Lichtso**
#### Problem
In #32982, which in turn is necessary to upgrade Rust (see #32961), we change a public interface here in the monorepo, which is used by the SPL repo. Both repositories form a cycle of CI dependency.

#### Summary of Changes
Removes the GitHub action files "downstream-project-spl.yml" and "downstream-project-spl-nightly.yml".
This should be reverted once v1.17 is branched off.

### CODE REVIEW

**Comment by t-nelson** [comment]
i think we can be a little less intrusive with [`jobs.<job>.if`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif)
```
...
  jobs:
    job_name:
      if: false
      ...
    ...
```

**Comment by Lichtso** [comment]
The `if` clause is already used by some jobs, and I don't want to change them. This as it is, is a far more obvious revert IMO.

**Review by t-nelson — APPROVED** [review]
k

cc/ @yihau @joncinque

**Comment by joncinque** [comment]
Is it possible to only remove the CLI jobs and general test one? This looks like it's only affecting public CLI APIs, correct?

**Comment by t-nelson** [comment]
> Is it possible to only remove the CLI jobs and general test one? This looks like it's only affecting public CLI APIs, correct?

everything that touches `RemoteWallet` 'cause it's grossly over constrained :face_with_head_bandage:

**Comment by joncinque** [comment]
> everything that touches RemoteWallet 'cause it's grossly over constrained 🤕

That means that programs and tests are totally fine, right? Can we be a bit more selective about what we disable? We're working so hard on avoiding breaking changes in the SDK and I don't want us to slip up.

Thankfully, the remote wallet changes won't impact program developers, which is why I'm not advocating for a normal deprecation strategy.

**Comment by t-nelson** [comment]
> which is why I'm not advocating for a normal deprecation strategy

that makes one of us

**Pull request merged**
