### PR TITLE
Add Copy trait to FeeCalculator

### PR DESCRIPTION
**Pull request by svenski123**
#### Problem
FeeCalculator is a small struct (8 bytes) comprised solely of one primitive type

#### Summary of Changes
Add Copy trait to FeeCalculator
Pass FeeCalculator instances by value
Fixup all clippy warnings

### CODE REVIEW

**Comment by svenski123** [comment]
I was on the fence for FeeRateGovernor and RentCollector but then thinking that there may be more to this than a const T& vs T sort of thing I set my C/C++/SysV x86_64 ABI biases aside and re-read the Rust documentation for the Copy marker trait and looked at some dissaembled Rust code.

From what I could see, the Copy trait had no effect on how objects were passed - borrows (&) were always by pointer-in-register as were ownership-transfers of larger types (smaller types were in registers). When the memory needed to be copied (i.e. calling clone(), assigning from deferences or out of larger aggregates, etc.) the Copy traited types generated code typically used fewer transfers and larger registers (i.e. 256 bit wide YMMs) to copy data and padding at once.

In particular I didn't see any extra copying of Copy traited types which is what I was concerned about. As the Rust Copy trait docs point out, the Copy trait only tells Rust that a given type can be safely bit-wise copied, it doesn't mean that Rust will necessarily make more copies of Copy trait objects but rather when it does, it can copy memory indiscriminately in bulk and the original copy of the data remains valid and usable.

As far as using clone() to indicate an expensive operation, I wholeheartedly agree when heap allocations or other expensive operations (syscalls, etc.) are involved but this does not apply to a 48 byte (including padding) data structure of integers - AVX2 registers are 32 bytes wide and cache lines are typicallly 64 bytes wide; it is far more economical to just copy the shared data (or rather allow Rust to).

It is certainly a consideration that the FeeRateGovernor may need to be more complex than just 41 bytes of integer data and may no longer be Copyable - but should that need to change, clippy will identify all of the problem areas and the edits will be straightforward if perhaps tedious.

Of course the above notwithstanding, if it is still preferable to remove the Copy trait from the larger data types then I will happily oblige.

**Comment by ryoqun** [comment]
@svenski123 Thanks for sharing the detailed explanation. I learned a lot. So, 32-64 byte-ish `Copy` trait types should be ok in performance-wise in general? @sakridge How do you think about this?

If that's true, we might need to reconsider this issue too?: https://github.com/solana-labs/solana/issues/9032 (CC: @garious as the original issue author)

Btw, my quick testing shows `RentCollector` is 80-bytes long. Do you think is this type still good for `Copy`?

```
$ git diff ddae86fc5998b0bdc2f5ecad476a4d8cebfdc2f9
diff --git a/runtime/src/rent_collector.rs b/runtime/src/rent_collector.rs
index 6d95a45795..16ad88c0bb 100644
--- a/runtime/src/rent_collector.rs
+++ b/runtime/src/rent_collector.rs
@@ -71,3 +71,11 @@ impl RentCollector {
         }
     }
 }
+
+#[cfg(test)]
+mod tests {
+   #[test]
+   fn test_mem_size() {
+      assert_eq!(std::mem::size_of::<crate::rent_collector::RentCollector>(), 23);
+   }
+}
```
```
running 1 test
thread 'rent_collector::tests::test_mem_size' panicked at 'assertion failed: `(left == right)`
  left: `80`,
 right: `23`', runtime/src/rent_collector.rs:79:7
stack backtrace:
   0:     0x55ee2487f605 - backtrace::backtrace::libunwind::trace::h934f9000aebd3cdb
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55ee2487f605 - backtrace::backtrace::trace_unsynchronized::hcd6e39da2d76d8d6
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55ee2487f605 - std::sys_common::backtrace::_print_fmt::ha0ad3a34f556be49
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55ee2487f605 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8b081861d17846db
                               at src/libstd/sys_common/backtrace.rs:59

```


> clippy will identify all of the problem areas and the edits will be straightforward if perhaps tedious.

What's the exact clippy warning? I couldn't find one.. Closest was https://rust-lang.github.io/rust-clippy/master/#trivially_copy_pass_by_ref

> Of course the above notwithstanding, if it is still preferable to remove the Copy trait from the larger data types then I will happily oblige.

Thanks for being open-minded!

**Comment by garious** [comment]
How about a microbenchmark? My assumption was that pass-by-value (Copy) would be the same performance as pass-by-reference (borrow) for types up to 64 bits (not bytes), and that implementing Copy for anything larger would hide performance issues, where an implicit copy should have been a borrow.

**Comment by t-nelson** [comment]
Agree with @garious here.  I should have been more clear that my concern was with the pass-by-value case rather than arbitrary assignment

**Comment by svenski123** [comment]
You can pass '--emit asm' to rustc or 'objdump -Cd' rlib files to get the assembly but the compiler explorer at https://www.godbolt.org/ makes for an easy way look at and compare small pieces of code.

You can open two sets of source editor and compiler panes and then get a diff between the disassembled output. I used '-O -C  target-cpu=skylake' as compiler flags to get optimized AVX2 output.

Below is a sample 62 byte struct and some small functions - you can copy as is in one pane and again in the other without the Copy and one or two the functions that don't compile without Copy and see the differences.

As you can see the struct is always passed in memory with the address in RSI - this is true for both f(&Self) and f(Self) whether or not Copy is implemted. Return values are written to memory at offset RDI and then RAX is set to this address - so the caller can decide where the result goes without copying it.

With the standard 64 bit calling conventions, larger aggregates passed by value are always pushed on the stack but with rust it seems it passes larger aggregates by pointer. Rust does not have a defined ABI which allows it flexibility with passing and of course it knows the data's lifetime, references, mutability and ownership so it knows when memory can be safely shared avoiding unnecessary copies.

#[derive(Clone,Copy,Default)]
pub struct A { a:u64,b:i64,c:u32,d:i32,e:u128,f:i128,g:u16,h:u16,i:u8,j:i8}
impl A {
    pub fn new() -> Self { Self::default() }
    pub fn pass_ref_thru(&self) -> &Self { self }
    pub fn pass_ref_new(&self) -> Self { Self{..*self} }
    pub fn pass_ref_clone(&self) -> Self { self.clone() }
    pub fn pass_ref_copy(&self) -> Self { *self }
    pub fn pass_value_thru(self) -> Self { self }
    pub fn pass_value_new(self) -> Self { Self{..self} }
    pub fn pass_value_clone(self) -> Self { self.clone() }
    pub fn pass_value_copy(self) -> Self { self }
    pub fn dup_ref_thru(&self) -> (&Self, &Self) { (self, self) }
    pub fn dup_ref_new(&self) -> (Self, Self) { (Self{..*self}, Self{..*self}) }
    pub fn dup_ref_clone(&self) -> (Self, Self) { (self.clone(), self.clone()) }
    pub fn dup_ref_copy(&self) -> (Self, Self) { (*self, *self) }
    pub fn dup_value_thru(self) -> (Self, Self) { (self.clone(), self) }
    pub fn dup_value_new(self) -> (Self, Self) { (Self{..self}, Self{..self}) }
    pub fn dup_value_clone(self) -> (Self, Self) { (self.clone(), self.clone()) }
    pub fn dup_value_copy(self) -> (Self, Self) { (self, self) }
    pub fn apply_ref_func_ref(&self, f: Box<dyn Fn(&Self)->Self>) -> Self { f(self) }
    pub fn apply_value_func_value(self, f: Box<dyn Fn(Self)->Self>) -> Self { f(self) }
    pub fn apply_mut_ref_func_value(mut self, f: Box<dyn Fn(&mut Self)>) -> Self { f(&mut self); self }
    pub fn make_vec(&self, n: usize) -> Vec<Self> { std::iter::repeat(self).take(n).copied().collect() }
}

**Comment by svenski123** [comment]
The code below sheds a bit more light on this, basically:

- When calling func(param), caller copies param and passes pointer to copy to func()
- When calling func(&param), caller does not copy param and passes existing pointer
- The preceding applies to both Copy and non-Copy types
- When calling func(param) with a non-Copy type, the caller still makes a copy however any reference to the original afterwards results in a compile time error
- For Copy and non-Copy types, copying for func(param) is highly optimal (bulk AVX/AVX2)
- For Copy types, clone() code is identical to that generate for implicit moves
- For non-Copy types, clone() code is less optimal, utilising more numerous and narrow transfers

Finally, for small Copy struct types with no more than two fields totalling no more than 16 bytes, func(param) resulted in the struct being passed in registers rather in memory.

So the long and short of it seems to be:

- Small simple types should be Copy traited and should always be passed in as value parameters
- Larger types should be passed in as references and should be Copy traited if possible

It's worth pointing out that passing as value imposes the same copying overhead for both Copy and non-Copy types, though harder to abuse with non-Copy types as the loss of ownership usually results in compile errors. Still passing a non-Copy type by value through a chain of function call will likely impose a greater overhead than if a reference were passed through the chain.

Of course in the example below the boxed function reference forced the compiler to setup the stack and registers for an actual call - the rust compiler will normally be able to inline a lot of the smaller functions and so should optimise a lot of it away.

Provided function prototypes declare parameters as references for all but the smallest types, I wouldn't think there would be much risk of unintentional excessive implicit copying and that the benefits of Copy traiting all the plain data types would outweigh it.

```
#[derive(Clone, Copy)]
pub struct A {
    a: u64, b: u64, c: u32, d: u32,
    e: u16, g: u16, h: u8, i: u8,
}

pub fn sum1(a: &A,
            f: &Box<dyn Fn(A) -> u64>,
            g: &Box<dyn Fn(&A) -> u64>,
            ) -> u64 {
    f(a.clone()) + g(a)
}

pub fn sum2(a: A,
            f: &Box<dyn Fn(A) -> u64>,
            g: &Box<dyn Fn(&A) -> u64>,
            ) -> u64 {
    f(a.clone()) + g(&a)
}

pub fn sum3(a: &A,
            f: &Box<dyn Fn(&A) -> u64>,
            g: &Box<dyn Fn(A) -> u64>,
            ) -> u64 {
    f(a) + g(a.clone())
}

pub fn sum4(a: A,
            f: &Box<dyn Fn(&A) -> u64>,
            g: &Box<dyn Fn(A) -> u64>,
            ) -> u64 {
    f(&a) + g(a)
}
```

**Comment by svenski123** [comment]
> Btw, my quick testing shows `RentCollector` is 80-bytes long. Do you think is this type still good for `Copy`?

Yes, it's just ints, floats and padding.
All functions that take a RentCollector take it by reference so there's no overhead.

> > clippy will identify all of the problem areas and the edits will be straightforward if perhaps tedious.

> What's the exact clippy warning? I couldn't find one.. Closest was https://rust-lang.github.io/rust-clippy/master/#trivially_copy_pass_by_ref

For non-Copy to Copy: clone() a Copy type, clippy complains; remove clone() and maybe reference.
For Copy to non-Copy: Pass a non-Copy type and reference it later, you get compile errors; add clone().

That trivially_copy_pass_by_ref lint is exactly what I had in mind for smaller types <= 16 bytes being Copy and always passed by value; I note the trivial-copy-size-limit parameter in the lint defaults to 16.

**Comment by svenski123** [comment]
In the interests of allowing this PR to progress forward I have limited it to just FeeCalcuator.
Additionally I have also changed all function prototypes to pass FeeCalculator instances by value.

**Comment by garious** [comment]
It'll take me some time to digest everything you've written here, but regarding your comment: "FeeCalculator is a small struct (8 bytes) comprised solely of one primitive type", `FeeCalculator` will change over time. Some likely ones: `num_writable_account_fetches` and `num_readonly_account_fetches`. Might be lots more over time.

**Comment by ryoqun** [comment]
@svenski123 Thanks for another great write-up. I'm still learning regarding this area.

I think these observations are of particularly interesting:

>   * When calling func(param) with a non-Copy type, the caller still makes a copy however any reference to the original afterwards results in a compile time error

(This is sad, but it seems that this "Move" semantics are of Rust's imaginary notion and isn't codified behavior nor constrained by some hardware/architecture/ABI limitations and implementation-dependent so there might be room for improvement in the future: https://internals.rust-lang.org/t/pre-rfc-copy-like-trait-for-large-types/11852)


>   * For non-Copy types, clone() code is less optimal, utilising more numerous and narrow transfers

(Yeah, this seems to be true manifested as this bug report and its reply: https://github.com/rust-lang/rust/issues/69174#issuecomment-586550165)


Thusly, leading to this:

> * Small simple types should be Copy traited and should always be passed in as value parameters
> * Larger types should be passed in as references and should be Copy traited if possible

So, I'm more inclined to this pr's direction!



> > What's the exact clippy warning? I couldn't find one.. Closest was https://rust-lang.github.io/rust-clippy/master/#trivially_copy_pass_by_ref
> 
> For non-Copy to Copy: clone() a Copy type, clippy complains; remove clone() and maybe reference.
> For Copy to non-Copy: Pass a non-Copy type and reference it later, you get compile errors; add clone().

Yeah, these should certainly address some of concerns. I (and @garious probably) are concerned with the case: `Suggest (larger-than-threshold) structs (regardless of Copy/non-Copy) to be passed by refs`. And sadly, this isn't realized yet by clippy: https://github.com/rust-lang/rust-clippy/issues/4499

**Comment by ryoqun** [comment]
> Larger types should be passed in as references and should be Copy traited if possible

Oh, another thinking here is that if it's really big enough and passed around various functions without clear hierarchical ownership, maybe we should also consider `Rc`/`Cell`/`Box` or the some transient context `struct`.

**Comment by ryoqun** [comment]
>   * When calling func(param) with a non-Copy type, the caller still makes a copy however any reference to the original afterwards results in a compile time error

Ah, I've found stackoverflow question also: https://stackoverflow.com/questions/38571270/can-rust-optimise-away-the-bit-wise-copy-during-move-of-an-object-someday

**Comment by garious** [comment]
@svenski123, @ryoqun, I think I'm finally caught up here.  We should assume `FeeCalculator` will one day be large and also, that `rustc` will one day optimize away the `memcpy` when moving values. Under those two assumptions, I think we should only add `Copy` to types that are less than or equal to the size of a register, maybe two.  Some things not clear to me:
* Do we want to extend Copy to types beyond 8 bytes assuming the compiler will use speciality registers?
* Do we want to extend Copy to types larger than one register? I get that it'll be fast if only passing the one struct, but when passing more parameters, it'll increase the odds of register spilling when compared to a borrow.

Properties of Copy not valuable to this particular project:
* Developer convenience. I'd rather the developer work harder to do something with a higher runtime cost.
* Speeding up an otherwise inefficient `clone()`. I'd rather the priority be on getting rid of clones (and not hiding the clone with an implicit copy!) For example, how we pass `&Pubkey` in places where we drop that pubkey right into a struct; we shouldn't do that.

**Pull request closed without merging**
