### PR TITLE
Add Solanart program name

### PR DESCRIPTION
**Pull request by tpompon**
#### Problem

We would like to get our contract identified clearly on official Solana Explorer to facilitate user understanding and limit scams when they're inspecting transactions.

Contract: `CJsLwbP1iu5DuUikHEJnLfANgKy6stB2uFgvBBHoyxwz`

#### Summary of Changes

- Update the `utils/tx.ts` file to implement name and address of the Solanart contract

### CODE REVIEW

**Comment by jstarry** [comment]
Looks good but what's the difference between that program id and this one 5ZfZAwP2m93waazg8DkrrVmsupeiPEvaEHowiUP7UAbJ

**Comment by tpompon** [comment]
> Looks good but what's the difference between that program id and this one 5ZfZAwP2m93waazg8DkrrVmsupeiPEvaEHowiUP7UAbJ

Hey @jstarry, this address is for our program for Global Offers that makes possible bids on an entire collection and not just a single NFT, can I add it as well with the name `Solanart - Global offers` for example?

**Comment by jstarry** [comment]
Yeah feel free to add that one to this pr too

**Comment by tpompon** [comment]
> Yeah feel free to add that one to this pr too

Added

**Pull request merged**
