### PR TITLE
Terminology: fix grammar and punctuation

### PR DESCRIPTION
**Pull request by tredondo**
Please double check the edit to PoH.

### CODE REVIEW

**Comment by jstarry** [comment]
@tredondo can you please update your commit to exclude other doc changes

**Comment by tredondo** [comment]
I'm editing from the Github UI so it was easier to add back the CBC section. Feel free to remove it, no need for me to make another PR :)

**Comment by jstarry** [comment]
Closing because this reverts other doc fixes

**Comment by tredondo** [comment]
Hopefully the useful fixes can be cherry picked. Unfortunately I don't have the time to make them again.

**Pull request closed without merging**
