### PR TITLE
Revert "rbpf-cli: add coverage flag (#24704)"

### PR DESCRIPTION
**Pull request by dmakarov**
This reverts commit 69c98236f60fed8474585ed6619de5fb0d8e92ce.

#### Problem

The original changes upgraded a ton of cargo crates. Update should be done more carefully.

#### Summary of Changes

Revert 69c98236f60fed8474585ed6619de5fb0d8e92ce and update cargo crates for the reverted Cargo.toml.

### CODE REVIEW

**Comment by jstarry** [comment]
Shouldn't this just be a revert? What does this also update crates?

**Comment by dmakarov** [comment]
Now it should be reverted.

**Comment by dmakarov** [comment]
@CriesofCarrots does this look ok to merge?

**Comment by jstarry** [comment]
Can you split this into two commits? One that *only* does the revert and keeps the conflicts.. and one that fixes the conflicts?

**Comment by dmakarov** [comment]
> Can you split this into two commits? One that _only_ does the revert and keeps the conflicts.. and one that fixes the conflicts?

done.

**Comment by jstarry** [comment]
This still keeps around a number of version updates.. I opened a new PR here to do the revert more carefully https://github.com/solana-labs/solana/pull/25441

**Comment by dmakarov** [comment]
Closing because superseded by #25441

**Pull request closed without merging**
