### PR TITLE
web3.js: update commitment variants

### PR DESCRIPTION
**Pull request by oJshua**
#### Problem
web3 js sdk is using commitment variants that are deprecated as of #14797 

#### Summary of Changes
Update commitment variants.

Fixes https://github.com/solana-labs/solana/issues/14863

### CODE REVIEW

**Comment by jstarry** [comment]
Looks good, waiting until mainnet is updated to 1.5 first?

**Comment by CriesofCarrots** [comment]
> Looks good, waiting until mainnet is updated to 1.5 first?

🙏

**Comment by oJshua** [comment]
@jstarry Yeah, that was the plan! Looks like we have a mix of 1.4 / 1.5 at the moment.

**Comment by oJshua** [comment]
@CriesofCarrots do you think this is ready to ship?

**Comment by CriesofCarrots** [comment]
Yep :shipit:

**Pull request merged**
