### PR TITLE
infer shred stake distribution from deterministic shred seed

### PR DESCRIPTION
**Pull request by jbiseda**
#### Problem
Using a deterministic shuffle to determine shred distribution we can infer the total stake of nodes that should be on the same distribution path. We could provide this information to a client.

#### Summary of Changes
Here's a draft for calculating the expected total stake of the nodes that should have been on the shred's broadcast path. It's currently getting the sum of the stake of the shred recipient's neighborhood as well as the sum of the stake of the previous layer neighborhood.

Looking for thoughts on two different approaches:
1) run a fixed turbine stake calculation from the validator and report a single value indicating some stake distribution metric to the client. See `get_deterministic_shred_distribution_stakes_pct_by_slot_and_index`
2) when a slot has been successfully received, return the raw data about which shred indices were received over turbine to the client. The client side could include a stake computation identical to (1) or process the raw data as it saw fit. This also reduces the validator overhead to compute these values.

Some open questions comments:
- changes rely on activation of `feature_set::turbine_peers_shuffle::id()`.
- shreds take different distribution paths through different nodes, how do we condense the different stakes into a per-slot value? (this change takes the average across shreds)
- how do we reconcile repairs? (this change ignores slots which were repaired)
- would we want to provide this to a client with a new API? or additional information for `SlotUpdate`?
- would it be more useful to provide raw data, or just to have a simple signal that some predefined value has been reached?
- How long should per-slot turbine completion data be cached?

Here are some measurements to show data collected from an unstaked validator on testnet:

Breakdown of computed stake values per shred:
Screen Shot 2022-03-03 at 2 45 09 AM

turbine/recovered/repaired breakdown:
Screen Shot 2022-03-03 at 2 46 12 AM

`get_deterministic_shred_distribution_stakes_pct_by_slot_and_index` "percent" value:
Screen Shot 2022-03-03 at 2 46 54 AM

computation time:
Screen Shot 2022-03-03 at 2 53 34 AM

Fixes #

### CODE REVIEW

**Review by behzadnouri — COMMENTED** [review]
I did an initial pass here, but before the implementation details I feel like we need a better definition of what we want to calculate here; The description says:

> calculating the expected total stake of the nodes that should have been on the shred's broadcast path. It's currently getting the sum of the stake of the shred recipient's neighborhood as well as the sum of the stake of the previous layer neighborhood.

but I am myself very confused what is a good estimation for this which is a) useful and b) not easily subject to attacks or network partitions.



Might be good to schedule a meeting to discuss this.

> changes rely on activation of feature_set::turbine_peers_shuffle::id().

this feature is already pending activation on testnet; we can also activate it on mainnet shortly after mainnet is upgraded to v1.9. so no concern here.

> shreds take different distribution paths through different nodes, how do we condense the different stakes into a per-slot value? (this change takes the average across shreds)

yeah, this is not clear to me either. as I commented in the code, if this number comes out as say 20, I am not sure what 20 conceptually means.

**Comment by jbiseda** [comment]
I'm thinking it may be more useful to return the data about which shreds were received over turbine to the rpc client rather than computing a magic number in the validator. We could include some reference implementation on the client side similar to what is returned by `get_deterministic_shred_distribution_stakes_pct_by_slot_and_index`. This would also offload the expense of the computation to the client.

**Comment by aeyakovenko** [comment]
> Here I'm a bit confused, why do we need a "per-slot" value? It would be helpful to figure out what to do with this if we knew what we were trying to infer from this aggregate value.

@carllin @jbiseda I think we need per batch value.  for a recoverable batch 33/64, what is the aggregate non overlapping stake weight of the 33 shreds in the batch. For a block we need to return the min of all the batches.

**Comment by jbiseda** [comment]
> I think we need per batch value. for a recoverable batch 33/64, what is the aggregate non overlapping stake weight of the 33 shreds in the batch. For a block we need to return the min of all the batches. Then if min > 2/3 we should have a guarantee that block will be recovered and voted on.

@aeyakovenko I want to make sure I understand this calculation:
- For each shred we determine the nodes on the deterministic transmission path
- For each batch of shreds we take the union of nodes on the transmission path for each shred
- We calculate the sum of the stake for the union of nodes for the batch
- We take the min sum of the batches for the block
- If check this value against 2/3 of the total stake of all nodes

If this is the calculation then:
- for each shred the nodes on the path will look like `leader -> (maybe) intermediate node -> myself`
- union of nodes per batch will be `{leader, myself, ...at most 33 unique intermediate nodes}

**Comment by aeyakovenko** [comment]
@jbiseda 
> union of nodes per batch will be at most 66 + 2 nodes

what do you mean by that?

**Comment by jbiseda** [comment]
> @jbiseda
> 
> > union of nodes per batch will be at most 66 + 2 nodes
> 
> what do you mean by that?

For a given shred the retransmission path to the validator where we're performing this calculation shouldn't be more than 2 nodes. Then we would take the union of these nodes across the 33 shreds in the batch.

**Comment by aeyakovenko** [comment]
> For a given shred the retransmission path to the validator where we're performing this calculation shouldn't be more than 2 nodes. Then we would take the union of these nodes across the 33 shreds in the batch.

@jbiseda yea, I think that is right.  So to compute the total amount of stake that recovered the batch, out of the 33 that my node sees, does the intersection of all the retransmit peers > 2/3?  If shred 1 retransmitted to A, B, C, and 2 to B, C, D, is B + C > 2/3?  We basically want to know what percentage of the network is likely to have the shreds.

@carllin does that sound right?

**Pull request closed without merging**
