### PR TITLE
accessor for reading blockhash queue

### PR DESCRIPTION
**Pull request by apfitzge**
#### Problem
Want a way to check age of transactions in scheduler/worker and need the blockhash queue to do so.
Because of the way the multi-iterator works we go transaction-by-transaction so the currently exposed interface(s) are not sufficient.

#### Summary of Changes
Add accessor for read lock on bank's blockhash queue.

Fixes #

### CODE REVIEW

**Comment by jeffwashington** [comment]
I do not have any specific knowledge of this member. Change seems fine. Is there someone who understands the blockhash queue concept and side effect well?

**Comment by apfitzge** [comment]
> I do not have any specific knowledge of this member. Change seems fine. Is there someone who understands the blockhash queue concept and side effect well?

Looks like the last person to touch it was jstarry, so not sure who else would be familiar. Maybe @carllin who touched it about 2 years ago?

I guess the concern around this change is that holding the read-lock would block out the call to `Bank::register_tick` on block boundaries which takes the write-lock to add a hash.

The queue itself is small (hash map of <= 400 elements) and I could potentially just clone it everytime I see a new slot - that way I don't need to hold the lock while using it.
There's even a comment on the type: `/// Low memory overhead, so can be cloned for every checkpoint`

**Comment by jeffwashington** [comment]
how often will this be called? once per slot? tx? every N slots?

**Comment by apfitzge** [comment]
> how often will this be called? once per slot? tx? every N slots?

Once per `schedule_consume` loop, which may be called multiple times per slot.

It's already read-locked during processing to check the ages once per transaction batch, but I was basically using this to pre-filter on the scheduling side.

Re-thinking it, maybe I don't need this in the v0 and can follow-up as an optimization. The worker threads will already do the normal checks - though that might lead to smaller batche as we toss old txs away.

**Pull request closed without merging**
