### PR TITLE
Accounts DB proposal: Tiered-storage design and cold-storage format

### PR DESCRIPTION
**Pull request by yhchiang-sol**
#### Summary of Changes
This PR includes the proposal for the tiered-storage design and
cold-storage format for accounts DB.

It is an updated design proposal based on the previous proposal (#28550),
sketch implementation (#28790), and online/offline discussions with
jwash, brooks, and many Solana engineers.

### CODE REVIEW

**Comment by yhchiang-sol** [comment]
> if we can make this format flexible to changes. Specifically adding/removing fields within AccountMeta.

Yes, the format handles optional fields by storing flags in the account meta where each bit represents whether this account has an optional field.  And the optional field is stored in the data block.

**Comment by lurais** [comment]
hello , is there a brief implementation of the proposal ?  And is there a brief test about the implementation of the proposal? As far as I can see, there is only a format of the cold storage proposed now, is that right?

**Comment by CantelopePeel** [comment]
It's not entirely clear what happens to appendvec under this proposal. Does it get replaced?

**Comment by yhchiang-sol** [comment]
Revised and published a newer version of the proposal under SIMD: https://github.com/solana-foundation/solana-improvement-documents/pull/37

The new version includes both hot- and cold- storage formats.

**Comment by yhchiang-sol** [comment]
Moved the proposal back to `solana/docs/src/proposal`.  Here's the V3: https://github.com/solana-labs/solana/pull/30315

**Pull request closed without merging**
