### PR TITLE
Bump bpf-tools to version v1.3

### LINKED ISSUE #15944: SPL Lending program's compute budget requirements increased in master
#### Problem

Worked around with the following PR, but need to identify the source of the increase

https://github.com/solana-labs/solana-program-library/pull/1467

Possible causes:
- Rust toolchain changes from v1.39 to v1.50
- Updated LLVM
- Switch to using LLVM's builtins
- CPI data costs

### PR DESCRIPTION
**Pull request by dmakarov**
#### Problem

bpf-tools v1.2 caused a substantial increase in the compute budget of BPF programs. 

#### Summary of Changes

Update the version of bpf-tools in the SDK.

Fixes #15944

The compute budget is expected to be not bigger than before bpf-tools v1.2 were released.

### CODE REVIEW

**Comment by dmakarov** [comment]
I wonder why when I run programs/bpf/tests I see the instruction counts smaller than when the same test run on buildkite

- local results on linux

```
test assert_instruction_count ... Test program: "bpf_to_bpf"
  bpf_to_bpf : 13 (13)
Test program: "multiple_static"
  multiple_static : 8 (8)
Test program: "noop"
  noop : 45 (45)
Test program: "relative_call"
  relative_call : 10 (10)
Test program: "sanity"
  sanity : 175 (176)
Test program: "sanity++"
  sanity++ : 177 (177)
Test program: "struct_pass"
  struct_pass : 8 (8)
Test program: "struct_ret"
  struct_ret : 22 (22)
Test program: "solana_bpf_rust_128bit"
  solana_bpf_rust_128bit : 581 (581)
Test program: "solana_bpf_rust_alloc"
  solana_bpf_rust_alloc : 8941 (8941)
Test program: "solana_bpf_rust_dep_crate"
  solana_bpf_rust_dep_crate : 2 (2)
Test program: "solana_bpf_rust_external_spend"
  solana_bpf_rust_external_spend : 488 (499)
Test program: "solana_bpf_rust_iter"
  solana_bpf_rust_iter : 724 (724)
Test program: "solana_bpf_rust_many_args"
  solana_bpf_rust_many_args : 237 (237)
Test program: "solana_bpf_rust_noop"
  solana_bpf_rust_noop : 462 (473)
Test program: "solana_bpf_rust_param_passing"
  solana_bpf_rust_param_passing : 54 (54)
Test program: "solana_bpf_rust_ristretto"
  solana_bpf_rust_ristretto : 19212 (19212)
Test program: "solana_bpf_rust_sanity"
  solana_bpf_rust_sanity : 918 (918)
```
- local results on macos (the same as on linux)
```
test assert_instruction_count ... Test program: "bpf_to_bpf"
  bpf_to_bpf : 13 (13)
Test program: "multiple_static"
  multiple_static : 8 (8)
Test program: "noop"
  noop : 45 (45)
Test program: "relative_call"
  relative_call : 10 (10)
Test program: "sanity"
  sanity : 175 (176)
Test program: "sanity++"
  sanity++ : 177 (177)
Test program: "struct_pass"
  struct_pass : 8 (8)
Test program: "struct_ret"
  struct_ret : 22 (22)
Test program: "solana_bpf_rust_128bit"
  solana_bpf_rust_128bit : 581 (581)
Test program: "solana_bpf_rust_alloc"
  solana_bpf_rust_alloc : 8941 (8941)
Test program: "solana_bpf_rust_dep_crate"
  solana_bpf_rust_dep_crate : 2 (2)
Test program: "solana_bpf_rust_external_spend"
  solana_bpf_rust_external_spend : 488 (499)
Test program: "solana_bpf_rust_iter"
  solana_bpf_rust_iter : 724 (724)
Test program: "solana_bpf_rust_many_args"
  solana_bpf_rust_many_args : 237 (237)
Test program: "solana_bpf_rust_noop"
  solana_bpf_rust_noop : 462 (473)
Test program: "solana_bpf_rust_param_passing"
  solana_bpf_rust_param_passing : 54 (54)
Test program: "solana_bpf_rust_ristretto"
  solana_bpf_rust_ristretto : 19212 (19212)
Test program: "solana_bpf_rust_sanity"
  solana_bpf_rust_sanity : 918 (918)
```

**Comment by mvines** [comment]
(added v1.6 label since we don't want to wait for the v1.7 release line for this to hit users)

**Comment by dmakarov** [comment]
Do i need to manually cherry pick this commit on 1.6 branch?

**Comment by mvines** [comment]
@dmakarov - nope!  By adding the v1.6 label, mergify will do it for us (and humans are only required if there's a merge conflict).

cc: https://github.com/solana-labs/solana/blob/master/.mergify.yml#L69

**Comment by mvines** [comment]
Welp in this case there was a merge conflict

**Comment by dmakarov** [comment]
In this case I should submit a PR against v1.6 branch, correct?

**Comment by mvines** [comment]
That's one way.  Mergify had already created a PR at https://github.com/solana-labs/solana/pull/16088 with it's attempt at a backport.  I normally just push new commits to that PR branch to perform any necessary rebasing (`git push origin mergify/bp/v1.6/pr-16068`).   But I see your other PR so I'll close the mergify PR now

**Comment by mvines** [comment]
Not a big deal either way. I'm just lazy and find reusing the mergify branch easier

**Pull request merged**
