### PR TITLE
Land program addresses on the curve

### LINKED ISSUE #10131: process_instruction with signatures should use hash_to_curve implementation to generate addresses
#### Problem

process_instruction signature generation may generation invalid ed25519 code points, which could result in a security attack vector.  It's unknown if the discrete log holds for those points.

#### Proposed Solution

https://tools.ietf.org/html/draft-irtf-cfrg-hash-to-curve-06

Use the above standard after generating the hash.

tag: @jackcmay @t-nelson @sakridge

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

The Kudelski report identified that `create_program_address` may produce invalid public keys (off the curve)

#### Summary of Changes

land all those public keys on the curve

Fixes #10131

### CODE REVIEW

**Comment by jackcmay** [comment]
@t-nelson @sakridge Sounds like you guys have a good grasp on curve stuff, would love any input you may have

**Comment by jackcmay** [comment]
I'm looking specifically to find out if the method in these changes is ok, I'm thinking that by generating the pubkey based on hashed bytes as a secret key we are essentially giving away the secret key and these addresses are not secure.  If that's the case we will have to implement the hash2curve math and that's going to take some time to get right

**Comment by jackcmay** [comment]
Before the latest revision I was essentially feeding the hashed bytes to this function to create the public key which I think is secure:

```rust
    /// Internal utility function for mangling the bits of a (formerly
    /// mathematically well-defined) "scalar" and multiplying it to produce a
    /// public key.
    fn mangle_scalar_bits_and_multiply_by_basepoint_to_produce_public_key(bits: &mut [u8; 32]) -> PublicKey {
        bits[0]  &= 248;
        bits[31] &= 127;
        bits[31] |= 64;

        let pk = (&Scalar::from_bits(*bits) * &constants::ED25519_BASEPOINT_TABLE).compress().to_bytes();

        PublicKey(CompressedEdwardsY(pk))
    }
```

But mirroring the same on web3 resulted in a pulling a lot of internal code from `nacl`

**Comment by sakridge** [comment]
> Before the latest revision I was essentially feeding the hashed bytes to this function to create the public key which I think is secure:
> 
> ```rust
>     /// Internal utility function for mangling the bits of a (formerly
>     /// mathematically well-defined) "scalar" and multiplying it to produce a
>     /// public key.
>     fn mangle_scalar_bits_and_multiply_by_basepoint_to_produce_public_key(bits: &mut [u8; 32]) -> PublicKey {
>         bits[0]  &= 248;
>         bits[31] &= 127;
>         bits[31] |= 64;
> 
>         let pk = (&Scalar::from_bits(*bits) * &constants::ED25519_BASEPOINT_TABLE).compress().to_bytes();
> 
>         PublicKey(CompressedEdwardsY(pk))
>     }
> ```
> 
> But mirroring the same on web3 resulted in a pulling a lot of internal code from `nacl`

This one seems fine to me. Yea, I think you're right the PR is insecure in that the private key is easily derived.

**Comment by t-nelson** [comment]
> 
> This one seems fine to me. Yea, I think you're right the PR is insecure in that the private key is easily derived.

Agreed here.  Using an open secret, like in this PR, would be a footgun for anyone who naively choose to reuse it as a signing authority

**Comment by jackcmay** [comment]
@t-nelson Do you concur that the scalar multiply is a sufficient method?

**Comment by t-nelson** [comment]
@jackcmay I believe so. I should review the math though.

I'm curious as to why they want us to put the addresses _on_  the curve, where a private key definitely exists, but is currently difficult to find, rather than _off_ the curve where any correct implementation would reject attempting to verify a signature with the derived pubkeys.  Perhaps it's not a case of "on" and "off" so much as "definitely on" and "maybe on"?

There's some huge IETF spec about this I really should have read by now...

**Comment by jackcmay** [comment]
@t-nelson heh, yeah, interesting point.  Here is the issue that spawned this effort: https://github.com/solana-labs/solana/issues/10131

**Comment by aeyakovenko** [comment]
@t-nelson actually, not a bad idea.  can we fail those sigchecks for pubkeys that are off-curve easily?

**Comment by jackcmay** [comment]
@aeyakovenko I'm checking the computation load to check on curve.

**Pull request merged**
