### PR TITLE
RPC snapshot speed

### PR DESCRIPTION
**Pull request by bw-solana**
#### Problem
Downloading snapshot is the long pole for bootstrap startup time. We currently just take any RPC with the right snapshot and start downloading from it. If the speed is <10MBps, we will try a different node. We could be smarter to improve our chances of a speedy download.

This builds off of the groundwork done in #26892

#### Summary of Changes
1. Sort RPC nodes by distance from our node
2. Run a 15 second speed test on the node and sort nodes by speed. This algorithm has a floor speed, below which it will filter out the node as non-viable. There is also a "super node" speed threshold above which we won't bother testing more nodes and will move on with the "super node." For nodes in the middle, we will collect some number of viable nodes (currently 5) before moving on. We don't stop at the first viable node because there could be faster nodes out there and it's worth spending an extra 15 seconds or minute or so finding out.

### CODE REVIEW

**Comment by brennanwatt** [comment]
Some example logs from running with these changes:
```
[2022-08-15T19:53:15.223390270Z WARN  solana_validator::bootstrap] BWLOG: DA3h5TUuKXUZWYPAkU1WyhNjh8F5dQbChAJ89fU4fktm 65.108.46.153 - Helsinki, Finland - 7882644.753 meters away
[2022-08-15T19:53:30.563456795Z WARN  solana_download_utils] BWLOG: read 3351040 bytes in 4984 ms (656 kB/s) from http://65.108.46.153:8899/snapshot-146127608-HP2WDL6KY4gfSMgmeyKD1vt77pQk73xbMzZrRH8oaFYh.tar.zst
[2022-08-15T19:53:30.564533686Z WARN  solana_validator::bootstrap] BWLOG: RPC node failed speed test
[2022-08-15T19:53:30.794169571Z WARN  solana_validator::bootstrap] BWLOG: F5HqbLwdtLDoCLtdc3mAwMMJttCEyeJuj8cvakYeNygu 74.81.44.169 - Los Angeles, United States - 1306158.525 meters away
[2022-08-15T19:53:30.860743689Z WARN  solana_validator::bootstrap] BWLOG: 8U1mijLUN6qd9hTzHMHQ2uAwrAF5r2Y64DFAaVgGCd1W 3.238.80.193 - Ashburn, United States - 3627796.997 meters away
[2022-08-15T19:53:30.868413059Z WARN  solana_validator::bootstrap] BWLOG: 5xz57wZC6LVjRS2fTWFAGcvpn7erQ5jmgqPbR9BSTsrn 18.206.85.48 - Ashburn, United States - 3627796.997 meters away
[2022-08-15T19:53:30.868565819Z WARN  solana_validator::bootstrap] BWLOG: 9BZnoPqYhZyXFdVCHemZ6pNggdaEHmjBJwexYTTqsQUz 54.158.43.201 - Ashburn, United States - 3627796.997 meters away
[2022-08-15T19:53:30.870223512Z WARN  solana_validator::bootstrap] BWLOG: B6PrFqc6H9rwmTAdtSg8koH4TWsUPnaDMwye4hgmLA8G 44.202.186.131 - Ashburn, United States - 3627796.997 meters away
[2022-08-15T19:53:31.030238936Z WARN  solana_validator::bootstrap] BWLOG: B4nVu6L3pbwH9H7EbmGgA8q4NYT2nv9mthdyDKYBBrd4 148.251.67.238 - Falkenstein, Germany - 8459786.39 meters away
[2022-08-15T19:53:31.033083676Z WARN  solana_validator::bootstrap] BWLOG: DE37cgN2bGR26a1yQPPY42CozC1wXwXnTXDyyURHRsm7 142.132.128.132 - Falkenstein, Germany - 8459786.39 meters away
[2022-08-15T19:53:31.046742668Z WARN  solana_validator::bootstrap] BWLOG: BDfKc8m8ejgcLtpJ5LDokSDB9TYWA6LoXChWVHNumqFX 141.95.45.92 - Limburg an der Lahn, Germany - 8301725.518 meters away
[2022-08-15T19:53:31.108059524Z WARN  solana_validator::bootstrap] BWLOG: 6cgsK8ph5tNUCiKG5WXLMZFX1CoL4jzuVouTPBwPC8fk 37.120.245.150 - Bucharest, Romania - 9524991.616 meters away
[2022-08-15T19:53:50.806371448Z WARN  solana_download_utils] BWLOG: read 5639040 bytes in 5008 ms (1099 kB/s) from http://74.81.44.169:18899/snapshot-146127608-HP2WDL6KY4gfSMgmeyKD1vt77pQk73xbMzZrRH8oaFYh.tar.zst
[2022-08-15T19:53:50.807315904Z WARN  solana_validator::bootstrap] BWLOG: RPC node failed speed test
[2022-08-15T19:54:05.946297847Z WARN  solana_download_utils] BWLOG: read 4626688 bytes in 4990 ms (905 kB/s) from http://3.238.80.193:8545/snapshot-146127608-HP2WDL6KY4gfSMgmeyKD1vt77pQk73xbMzZrRH8oaFYh.tar.zst
[2022-08-15T19:54:05.947653439Z WARN  solana_validator::bootstrap] BWLOG: RPC node failed speed test
[2022-08-15T19:54:21.100136848Z WARN  solana_download_utils] BWLOG: read 4941056 bytes in 5002 ms (963 kB/s) from http://18.206.85.48:8545/snapshot-146127608-HP2WDL6KY4gfSMgmeyKD1vt77pQk73xbMzZrRH8oaFYh.tar.zst
[2022-08-15T19:54:21.101193395Z WARN  solana_validator::bootstrap] BWLOG: RPC node failed speed test
[2022-08-15T19:54:36.267258275Z WARN  solana_download_utils] BWLOG: read 5482752 bytes in 5027 ms (1064 kB/s) from http://44.202.186.131:8545/snapshot-146127608-HP2WDL6KY4gfSMgmeyKD1vt77pQk73xbMzZrRH8oaFYh.tar.zst
[2022-08-15T19:54:36.268245640Z WARN  solana_validator::bootstrap] BWLOG: RPC node failed speed test
[2022-08-15T19:54:51.402527933Z WARN  solana_download_utils] BWLOG: read 224374272 bytes in 5001 ms (43813 kB/s) from http://54.158.43.201:8545/snapshot-146127608-HP2WDL6KY4gfSMgmeyKD1vt77pQk73xbMzZrRH8oaFYh.tar.zst
[2022-08-15T19:54:58.466523868Z WARN  solana_validator::bootstrap] BWLOG: Download progress: DownloadProgressRecord { elapsed_time: 6.000493984s, last_elapsed_time: 6.000494062s, last_throughput: 42543996.0, total_throughput: 42543996.0, total_bytes: 33928726528, current_bytes: 255284992, percentage_done: 0.7524155, estimated_remaining_time: 791.4969, notification_count: 1 }
[2022-08-15T19:55:04.481423966Z WARN  solana_validator::bootstrap] BWLOG: Download progress: DownloadProgressRecord { elapsed_time: 12.01539157s, last_elapsed_time: 6.014897492s, last_throughput: 45033276.0, total_throughput: 43790130.0, total_bytes: 33928726528, current_bytes: 526155520, percentage_done: 1.5507671, estimated_remaining_time: 741.73083, notification_count: 2 }
```

**Comment by brennanwatt** [comment]
@sakridge and @mvines - Would appreciate if one of you could weigh in on this direction. Either location test or speed test seem useful? Scrap it and go all in on parallel downloads (#26402)? How do we measure our appetite for using these geo crates?

**Comment by KirillLykov** [comment]
Looks like speeding up downloading is nice-to-have from users prospective (https://github.com/solana-labs/solana/issues/28811)

**Comment by KirillLykov** [comment]
@brennanwatt do you feel like this work can be still used to help with https://github.com/solana-labs/solana/issues/28811?

**Comment by brennanwatt** [comment]
> @brennanwatt do you feel like this work can be still used to help with #28811?

Yes, I suspect there is still merit to combining the best capabilities and options from this PR and the community developed tool into the native client.

**Pull request closed without merging**
