### PR TITLE
Warn if vaildator appears to be repairing excessively

### PR DESCRIPTION
**Pull request by jbiseda**
#### Problem
It is possible for validators to stay in sync with a cluster solely using repair. This is substantially less efficient than receiving data using turbine and most likely indicates network related misconfiguration. Misconfigured nodes generating substantial repair traffic skews metric data.

#### Summary of Changes
Maintain slot repair history and generate warnings if a node appears to be excessively repairing slots while indicating that it is "caught up" with the cluster.

Fixes #

### CODE REVIEW

**Comment by t-nelson** [comment]
mind breaking the plumbing out to a separate commit to ease review? same pr is fine, just wanna see the functional changes in isolation to i don't miss anything

**Comment by jbiseda** [comment]
> The change seems overly intrusive (34 files, 347 loc) just to emit a warning, and most operators do not monitor logs anyways. On our side, we already have the ability to identify nodes repairing excessively from the existing metrics as in #33166, which is more convenient than inspecting logs.

Granted it touches lots of files, but it's pretty basic refactoring. Yes, we have the tools to investigate as in #33166, but it still requires an investigation. Inspecting logs is inconvenient for us, but more convenient for operators. If this reduces instances where we have to investigate I think it would be a win.

**Comment by jbiseda** [comment]
> Granted it touches lots of files, but it's pretty basic refactoring. Yes, we have the tools to investigate as in #33166, but it still requires an investigation. Inspecting logs is inconvenient for us, but more convenient for operators. If this reduces instances where we have to investigate I think it would be a win.

Do operators look at warnings in the log? @t-nelson ping @behzadnouri

**Comment by t-nelson** [comment]
> Do operators look at warnings in the log? @t-nelson ping @behzadnouri

does posting screenshots on discord constitute "looking"?

**Comment by jbiseda** [comment]
> > Do operators look at warnings in the log? @t-nelson ping @behzadnouri
> 
> does posting screenshots on discord constitute "looking"?

I guess I'm asking if it's worth trying to help operators with log messages? 🤷

**Comment by behzadnouri** [comment]
> > Granted it touches lots of files, but it's pretty basic refactoring. Yes, we have the tools to investigate as in #33166, but it still requires an investigation. Inspecting logs is inconvenient for us, but more convenient for operators. If this reduces instances where we have to investigate I think it would be a win.
> 
> Do operators look at warnings in the log? @t-nelson ping @behzadnouri

If the code change was small then adding some more logs was probably fine.
But in this case, my view is that we are not really getting enough value out of the added log message to justify the extra code or the maintenance burden incurred when changing the adjacent code in the future.

**Comment by t-nelson** [comment]
considering only the second commit, it's not so bad. the first is big 'cause `fmt` wrapped a bunch of function calls

**Comment by jbiseda** [comment]
The health status calculation is being changed by: #33651. I'll update this PR following that change.

**Comment by t-nelson** [comment]
how many nodes are typically in a state that would be logging with this? how frequently?

_we_ can already observe these nodes from metrics, right?

**Comment by jbiseda** [comment]
> how many nodes are typically in a state that would be logging with this? how frequently?

Not a huge amount, maybe ~1 per week in the top 100. I'll look across the full set of validators.

> _we_ can already observe these nodes from metrics, right?

Yeah, we see a bump in repair, then find the outliers. I was hoping this would help eliminate some noise.

**Pull request closed without merging**
