### PR TITLE
Add feature gate prompt and backport label automation

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
Lack of feature gate process and visibility

#### Summary of Changes
- Adds an optional prompt for "Feature Gate Details" when creating pull requests which requests devs to describe feature gate changes and conditions as well as add the new "feature-gate" label to their PR for visibility
- Adds automation for copying "feature-gate" labels to backport PR's
- Adds automation for applying the "feature-gate" label to PR's that change the `sdk/src/feature_set.rs` file

Fixes #

### CODE REVIEW

**Comment by t-nelson** [comment]
I wonder if we can automate adding the `feature-gate` label by scanning changes to `sdk/src/feature_set.rs`?

**Comment by jstarry** [comment]
> I wonder if we can automate adding the `feature-gate` label by scanning changes to `sdk/src/feature_set.rs`?

Ah great call, added that as well. I think it's still useful to automate copying the label for backports because some feature gate related changes don't change that file.

**Comment by t-nelson** [comment]
I think we'd only want to do it on `solana_sdk::declare_id` _additions_ though, right? otherwise we tag removals other other irrelevant updates too.  mergify may not be the tool for this job

**Comment by jstarry** [comment]
Oh true, well then I think the pull request template prompt should be sufficient for devs to develop the habit of annotating PRs with the label if they add feature gate changes. I'll revert the automation for adding the label

**Comment by t-nelson** [comment]
lmao. half of folks don't even fill it out until after creating the PR.  I get so many empty template emails.

I mean, I'm fine with the attempt. I'm just not optimistic it's going to be adhered to in any reliable manner

**Comment by jstarry** [comment]
Yeah it's a best effort thing to improve visibility. I'll at least find it useful for searching for my own feature-gate PR's. Good to go then?

**Comment by t-nelson** [comment]
yeah sure. I barely know how mergify works

**Pull request merged**
