### PR TITLE
Modified docs to replace any mention of rent with the rent-exempt bal…

### PR DESCRIPTION
**Pull request by bji**
…ance

concept, except in places of historical interest.

#### Problem

All accounts on Solana are rent-exempt as of epoch 534, and no new accounts can be created that would ever be charged "rent".  Therefore "rent" is not a concept that needs to be documented any more, and the presence of rent in documentation only serves to confuse new users.

#### Summary of Changes

Removed most mentions of "rent" from docs in preference to talking about "rent-exempt minimum balances" (which should also be renamed to just "minimum balance", but that's a change for another time), except in those places where there is historic interest in how Rent was originally proposed or designed (such as in proposal documents).

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
@nickfrosty and I think this is worth doing. Unfortunately, a bunch of the files you modified got moved to this repo: https://github.com/solana-foundation/developer-content
Nick says he'll take care of porting your suggestions over there. @bji, would you be willing to rebase this PR so it's just changes to the remaining files? I think it'll just be the proposals/implemented-proposals changes

**Comment by bji** [comment]
I tried to explain to someone on reddit why the rent concept is no longer applicable on Solana and no it's just minimum balances.  Their response in part:

"Why you replying to me? I literally read how it works. The commit was months ago, not a year, and the main webpage still talks about rent. What kind of foundation can't even update this after a so called year?

If you read the documentation it clearly says the rent was converted to this fee you try to misinform people about is different. They charge up front now. The rent was always for storage."

I don't know what else to do.  I really don't like seeing people confused and then angry, and I put the time into making a PR to fix the docs, and it keeps getting closed because it's stale.

**Comment by CriesofCarrots** [comment]
> I put the time into making a PR to fix the docs, and it keeps getting closed because it's stale.

I guess maybe you missed this comment? https://github.com/solana-labs/solana/pull/34278#issuecomment-1866875975

**Comment by bji** [comment]
> > I put the time into making a PR to fix the docs, and it keeps getting closed because it's stale.
> 
> I guess maybe you missed this comment? [#34278 (comment)](https://github.com/solana-labs/solana/pull/34278#issuecomment-1866875975)

Yes I missed it, sorry.  Will follow your instructions.

**Pull request closed without merging**
