### PR TITLE
Add perf counters for record/write stages

### PR DESCRIPTION
**Pull request by sakridge**

### CODE REVIEW

**Comment by rob-solana** [comment]
Looks rust channels don't have any APIs for examining queue depth.  Would a channel wrapper with `static names and queue depth counters be a more general, more complete solution?

**Comment by sakridge** [comment]
@rob-solana yea. the only thing is a lot of time we are putting a vec in the channel, so the channel doesn't know how big that vec is so the count of the channel is not super accurate. What do you think?

**Comment by sakridge** [comment]
I suppose the send() function of the wrapper could take a count of elements

**Comment by rob-solana** [comment]
when we recv(), the whole vector comes back out, right?

**Comment by rob-solana** [comment]
can we call serialized_size() on what's passed to send()?

**Comment by sakridge** [comment]
@rob-solana yes.. but seems like it doesn't represent how backed up the channel is. Big difference if there is a vec of 1 TX in the channel vs. vec of 10,000 txs which got coalesced somewhere. no?

**Comment by aeyakovenko** [comment]
is this draining the channel?

**Comment by sakridge** [comment]
@aeyakovenko no it doesn't drain it. That could be another solution for metrics, but a size limited sync_channel seems elegant way to apply backpressure in the pipeline and you kind of lose that.

**Comment by rob-solana** [comment]
obs, yep

**Comment by aeyakovenko** [comment]
@sakridge, so we will drop packets instead. We have no way to apply back pressure to clients. I would rather see the stage that’s stalled filled up so it’s clear what the problem is

**Pull request merged**
