### PR TITLE
Dynamically publish tarballs

### LINKED ISSUE #5952: solana-testnet pipeline creates tarballs when it doesn't need to
#### Problem

The build steps for the TPS testing pipeline (https://buildkite.com/solana-labs/solana-testnet/settings) spends 10-15 minutes each builds running `ci/publish-tarball.sh` in the "create build" step, even if these tarballs won't be used later.  The env var `$USE_PREBUILT_CHANNEL_TARBALL` determines if we will use the pre-builts or if we should build new ones based on a given PR/branch.

#### Proposed Solution

Move the pipeline to use the yaml-based steps in the buildkite GUI and put a conditional on whether or not `$USE_PREBUILT_CHANNEL_TARBALL` in order to determine if we should call the create step or not.

### PR DESCRIPTION
**Pull request by danpaul000**
#### Problem

solana-testnet pipeline wastes a bunch of time building tarballs that it might not use

#### Summary of Changes

Dynamically build the steps.yml file to skip the publish-tarball step if needed.

Fixes #5952

### CODE REVIEW

**Comment by danpaul000** [comment]
This change is tied to the new steps structure: https://buildkite.com/solana-labs/solana-testnet/settings

**Comment by mvines** [comment]
Looks like we could just as easily setup the buildkite pipeline like this in the GUI and not land this file at all:
```
steps:
  - command: "test -z $USE_PREBUILT_CHANNEL_TARBALL || ci/publish-tarball.sh"
    label: "maybe create build"

  - wait

  - command: "buildkite-agent pipeline upload ci/solana-testnet.yml"
    label: "pipeline"
```

**Comment by danpaul000** [comment]
> Looks like we could just as easily setup the buildkite pipeline like this in the GUI and not land this file at all:
> 
> ```
> steps:
>   - command: "test -z $USE_PREBUILT_CHANNEL_TARBALL || ci/publish-tarball.sh"
>     label: "maybe create build"
> 
>   - wait
> 
>   - command: "buildkite-agent pipeline upload ci/solana-testnet.yml"
>     label: "pipeline"
> ```

Awesome if that would work, I'll give it a shot.  The file does feel pretty clunky, I was just going off their dynamic pipeline doc: https://buildkite.com/docs/pipelines/defining-steps#dynamic-pipelines   As I'm not sure what syntax is supported in the web UI.

**Comment by danpaul000** [comment]
Okay that works, much cleaner.  The logic was backwards, so what we have now ended up with:
```steps:
  - command: "test -n \"$USE_PREBUILT_CHANNEL_TARBALL\" || ci/publish-tarball.sh"
    label: "maybe create build"

  - wait

  - command: "buildkite-agent pipeline upload ci/solana-testnet.yml"
    label: "pipeline"```

Tested and working.

**Pull request closed without merging**
