### PR TITLE
1.6 backport for poh and record improvements

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
> Jwash 1.6 backport

We're backporting Jwash to 1.6 now?

**Comment by t-nelson** [comment]
> > Jwash 1.6 backport
> 
> We're backporting Jwash to 1.6 now?

The perf improvements were too good to pass up!

**Comment by jeffwashington** [comment]
draft, candidate I'm working on with @sakridge

**Comment by jeffwashington** [comment]
> > Jwash 1.6 backport
> 
> We're backporting Jwash to 1.6 now?

I've been working on cloning myself, I thought maybe this would be a way to accomplish it. We'll see.

**Comment by jeffwashington** [comment]
@mvines 
Of the master prs I thought would help with spikes in testnet, the 2 commits left in this pr didn't make it to 1.6 yet. What do you recommend? Should I add the 1.6 tag to those 2 prs or has the 1.6 train sufficiently left the station?

**Comment by mvines** [comment]
> Should I add the 1.6 tag to those 2 prs or has the 1.6 train sufficiently left the station?

I think we can take a little bit of risk on 1.6 still.  I'm roughly thinking early May timeframe for when we'd want to start pushing a 1.6 upgrade for mainnet-beta

**Comment by jeffwashington** [comment]
these were done separately

**Pull request closed without merging**
