### PR TITLE
We need to publish solana-wen-restart so we can publish 1.18.0 later.

### PR DESCRIPTION
**Pull request by wen-coding**
Publish solana-wen-restart for now, otherwise we would have problem compiling 1.18.0 later.

### CODE REVIEW

**Comment by steviez** [comment]
Dang, didn't even have enough time to mark ship it but confirmed that I see the name is "reserved" and owned by a solana account:
https://crates.io/crates/solana-wen-restart

**Comment by t-nelson** [comment]
hmm... did this not trigger _any_ ci?  that's broken :thinking:

**Comment by steviez** [comment]
My comment was a joke at very fast request-for-review / ship-it / merge between you and Wen. I think Wen let it go through CI before adding us as reviewers; I see this build https://buildkite.com/solana-labs/solana/builds/103035

**Comment by wen-coding** [comment]
Yeah, I normally do that so I can fix all the lint errors before the reviewers had a chance ;-)

**Comment by t-nelson** [comment]
no i mean ci didn't trigger anything but the "is new crate name reserved" check. i think ideally we'd at least run `test-sanity.sh` as well

**Pull request merged**
