### PR TITLE
cli: block-production subcommand now uses SlotHistory sysvar when possible

### PR DESCRIPTION
**Pull request by mvines**
`solana block-production` reports broken numbers when run against a node that booted from a snapshot.  But the SlotHistory sysvar maintains the block production history for the last two epoch with perfect accuracy, so there's no need to use the spotty `getBlocks` RPC method when the requested range is within the data that SlotHistory holds

### CODE REVIEW

**Comment by t-nelson** [comment]
Are you aware of this "feature" of `SlotHistory` ?
https://github.com/solana-labs/solana/blob/5eb5d9b2f56a1f32cf812fcb19f4c5871b1f6a24/sdk/program/src/slot_history.rs#L50-L53

**Comment by mvines** [comment]
> Are you aware of this "feature" of `SlotHistory` ?
> https://github.com/solana-labs/solana/blob/5eb5d9b2f56a1f32cf812fcb19f4c5871b1f6a24/sdk/program/src/slot_history.rs#L50-L53

yeah that's fine.  That only happens on a warp

**Comment by t-nelson** [comment]
> > Are you aware of this "feature" of `SlotHistory` ?
> > https://github.com/solana-labs/solana/blob/5eb5d9b2f56a1f32cf812fcb19f4c5871b1f6a24/sdk/program/src/slot_history.rs#L50-L53
> 
> yeah that's fine. That only happens on a warp

:monocle_face: 
I was under the impression it happens every time the bitfield filled up.  The implementation of `oldest()` seems consistent with that interpretation

**Comment by mvines** [comment]
> 🧐
> I was under the impression it happens every time the bitfield filled up. The implementation of `oldest()` seems consistent with that interpretation

Nope, it doesn't!

**Pull request merged**
