### PR TITLE
replace serum-dex with openbook-dex

### PR DESCRIPTION
**Pull request by KirillLykov**
#### Problem

As part of CI checks, we build serum-dex which was migrated to openbook-dex.

#### Summary of Changes

Replace serum-dex with openbook-dex

### CODE REVIEW

**Comment by joncinque** [comment]
The change looks good, but the build is failing because the dex is still on Anchor 0.24, which is pinned to solana 1.9.  If  we can bump the Anchor dependency to 0.25 on the dex, that should allow for any later Solana minor version.

**Comment by KirillLykov** [comment]
> The change looks good, but the build is failing because the dex is still on Anchor 0.24, which is pinned to solana 1.9. If we can bump the Anchor dependency to 0.25 on the dex, that should allow for any later Solana minor version.

thanks for checking the error from CI. On dex side, it looks like there is anchor-lang version (0.24.2) and anchor-lang version:
```
dex/Cargo.toml:anchor-lang = ">=0.24.2"
dex/Anchor.toml:anchor_version = "0.18.2"
```

Not sure if I need to change the second as well.

**Comment by KirillLykov** [comment]
It looks a bit more involved with anchor: it requires solana-program version ~1.10.29 https://github.com/coral-xyz/anchor/blob/6baed77eb57d41455a5f3c1e026d86da756d1c8e/spl/Cargo.toml#L24

**Comment by joncinque** [comment]
Ah, it looks like they didn't relax the dependency until later.  Can you add an issue or comment, saying to remove the part that hardcodes using master once `anchor-lang` > 0.25.0 gets released?

**Comment by KirillLykov** [comment]
Issue to remove added lines from build script: https://github.com/solana-labs/solana/issues/28924

**Pull request merged**
