### PR TITLE
rbpf-cli: add coverage flag

### PR DESCRIPTION
**Pull request by dmakarov**
- adds DWARF parser using gimli
- adds coverage module to derive an execution trace to line numbers
- adds a gcov module to export a coverage profile to gcov intermediate JSON format
- add basic CLI logger

### CODE REVIEW

**Comment by jstarry** [comment]
This upgraded a ton of cargo crates, I think we need to back this out and update more carefully. cc @t-nelson @CriesofCarrots

**Comment by dmakarov** [comment]
I’ll revert it.

**Comment by dmakarov** [comment]
What should I do with the PR? Is there a way to have BPF program code coverage without updating too many dependencies?

**Comment by jstarry** [comment]
> What should I do with the PR? Is there a way to have BPF program code coverage without updating too many dependencies?

Can you take a look into why so many crates were bumped by the crates you added for this feature?

**Comment by dmakarov** [comment]
They were update because I ran `cargo update`.  CI check usually reports errors when Cargo.lock has outdated dependencies. So I ran `cargo update` and that must have updated all dependencies to versions that are most recent while still within the limits specified in Cargo.toml files.

**Comment by jstarry** [comment]
Ok, we don't do that. Please recreate your PR without running `cargo update`

**Pull request merged**
