### PR TITLE
Increase shred size to 10K

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
Change shred size to 10K for experiments

#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by pgarg66** [comment]
@sakridge FYI

**Comment by garious** [comment]
@pgarg66, why's this PR still hanging around?

**Comment by pgarg66** [comment]
@garious this was left open for reference for others who are doing perf testing.. I guess it can be closed now, since we are not pursuing this path...

**Comment by garious** [comment]
Seems odd to manage that communication with an open PR and not a constant.

**Comment by pgarg66** [comment]
Unfortunately, the tweak required change to more than a constant. Other option for me was to generate a patch and send that to anyone who was interested in experimenting with 10k sized shreds. Would that be the preferred approach?

**Comment by garious** [comment]
Nope. The preferred approach would be to add a constant. But not a priority right now. Maybe next time!

**Pull request closed without merging**
