### PR TITLE
some cleanup

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem

lookup + insert becomes just insert

#### Summary of Changes

Fixes #

### CODE REVIEW

**Review by HaoranYi — APPROVED** [review]
lgtm

**Review by jdavis103 — APPROVED** [review]
looks like a good simplification of the Rust logic.

**Comment by jeffwashington** [comment]
> looks like a good simplification of the Rust logic.
importantly, this is now 1 lookup instead of 2. Maybe not a big deal in this particular instance, but a useful pattern to note. For most of you, this is just practice on a pr as well as awareness of using `insert`'s return value to avoid a separate lookup as well as being an atomic operation.

**Review by apfitzge — APPROVED** [review]
looks good to me. simplifies the existing code by using the return value on hashset's insert

**Comment by HaoranYi** [comment]
> > looks like a good simplification of the Rust logic.
> 
> importantly, this is now 1 lookup instead of 2. Maybe not a big deal in this particular instance, but a useful pattern to note. For most of you, this is just practice on a pr as well as awareness of using `insert`'s return value to avoid a separate lookup as well as being an atomic operation.

What a coincidence. Here is another example, that I find this morning. 
https://github.com/solana-labs/solana/pull/24641

Maybe next rust compiler or clippy can detect this pattern in future.

**Review by brennanwatt — COMMENTED** [review]
LGTM

**Pull request merged**
