### PR TITLE
Populate test ledgers with a full slots to reduce test boilerplate

### PR DESCRIPTION
**Pull request by mvines**
The test changes needed for #2928 are quite large, and will work fine even without #2928 actually landed so I'm pulling these out into a separate PR and landing first to avoid rebase pain.

The changes here are to ensure tests always write out full ledger slots.  By doing so, we don't need to be concerned about ledger `last_entry_id`s in tests, since we can always use the `last_id`.   Slot-alignment should also be forward compatible for if/when we change `last_id` to be block based instead of tick based.

Funny story:  a couple long in the tooth `ignore`d replay_stage.rs tests looked at me funny while working on this patch so I deleted them for good measure.

### CODE REVIEW

**Comment by carllin** [comment]
Going forward, if we want to test starting ledgers with incomplete slots, crash recovery + startup for instance, how will we approach that?

**Comment by mvines** [comment]
> Going forward, if we want to test starting ledgers with incomplete slots, crash recovery + startup for instance, how will we approach that?
 
Use `blocktree.write_entries()` to write whatever you want, including partial slots

**Comment by garious** [comment]
sorry

**Comment by mvines** [comment]
Meh, better me

**Comment by garious** [comment]
automerge?

**Comment by mvines** [comment]
Move along, I got this

**Pull request merged**
