### PR TITLE
Terminology

### PR DESCRIPTION
**Pull request by pathoam**
#### Problem
Exchange terminology is confusing
#### Summary of Changes
Made the minimum set of terminology changes from #4720
 - tradeOrder -> Order
 - tradeRequest -> orderRequest
 - tradeCancel -> orderCancel

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Hey, @pathoam , it looks like you need to run `cargo fmt` to get by CI

**Comment by pathoam** [comment]
thanks for the tip, should be good now

**Comment by garious** [comment]
@jackcmay, did you start a review here and not submit it?

**Comment by jackcmay** [comment]
@garious Strange, I tried, must have fat-fingered something, will resubmit.

**Comment by CriesofCarrots** [comment]
@jackcmay, your review got dismissed on the force push:
image

Possibly that behavior is configurable somewhere

**Comment by mvines** [comment]
We can remove https://github.com/solana-labs/solana/blob/b50a3bae72c2aa19d1dffbc8f37c007a04f0448a/.mergify.yml#L7-L12 if it's bugging folks.  I enabled it as an experiment to see how we like it

**Comment by jackcmay** [comment]
This was prob my bad, I may have forgotten to `submit` the review

**Comment by garious** [comment]
@pathoam, go ahead and merge your own PRs after CI passes and you've gotten approvals from everyone you think might be affected or surprised by your change.

**Pull request merged**
