### PR TITLE
Install jq in docker

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

`jq` is missing...... T_T:

https://buildkite.com/solana-labs/solana/builds/98449#01890a36-b5e8-4438-8b4d-b81fb0a2bae7/3083-3084

image

#### Summary of Changes

add it

blocking #32169

### CODE REVIEW

**Comment by ryoqun** [comment]
@yihau hey, yet another favor from me. could you update docker images? thanks in advance. also, it seems the update wasn't still done after #32307 (i.e. wasm-pack is still `0.11.1`)

**Comment by yihau** [comment]
ah okay. one sec!

**Review by yihau — APPROVED** [review]
uploaded new images and retried your dev-utils pipeline 🤞

**Comment by ryoqun** [comment]
very thanks as always. the relevant ci step passed; merging this.

**Pull request merged**
