### PR TITLE
Use serde-bytes to serialize u8 efficiently

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

Serializing a sequence does so element by element which for byte sequences can be expensive.

#### Summary of Changes

Take advantage of serde-bytes for sequences of u8 data which will write the bytes in one operation which considerably speeds up the serialization process.

Fixes #

### CODE REVIEW

**Comment by garious** [comment]
Bummer, I saw that and assumed serde used it under the hood.  Going to use that to load Native and BPF modules too?

**Comment by jackcmay** [comment]
@garious Yup, I missed the one in `LoaderInstruction::Write`.  Is that what you were referring to or was there another?

**Comment by garious** [comment]
Yeah, exactly, but as I recall that instruction is implemented by two loaders, BPF and Native.

**Comment by jackcmay** [comment]
@garious `ShortVec` which is used quite is using the less-efficient method:
https://github.com/solana-labs/solana/blob/0fc3c7eee25040e7723311f280294952bf8df21c/sdk/src/short_vec.rs#L106

**Comment by garious** [comment]
Yeah, less than ideal library.  Luckily those vectors are ...short.

**Pull request merged**
