### PR TITLE
V1.17.11 version bump

### PR DESCRIPTION
**Pull request by steviez**
#### Summary of Changes
- Run `./scripts/increment-cargo-version.sh patch`
- Manually undo the hashbrown update

### CODE REVIEW

**Comment by steviez** [comment]
Per some discussion with Tyera, we realized that this action should be getting done automatically. However, the job failed:
https://github.com/solana-labs/solana/actions/runs/7200995161/job/19616164931

Will look at resolving that, Tyera and I both suspect that a script broke and was never updated when we moved to workspace inheritance

**Comment by CriesofCarrots** [comment]
Haha, @willhickey sniped you during that close-reopen: https://github.com/solana-labs/solana/pull/34452

**Comment by steviez** [comment]
> Haha, @willhickey sniped you during that close-reopen: #34452

lolol, I think his CI has like a 15-20 second lead on me; at least the line counts add up

**Comment by willhickey** [comment]
Oh bother I missed this.

Yeah, the automated solution fails for 2 reasons I'm aware of:
1) It no longer has permission to create a branch in the monorepo. I could let it create a branch in my fork instead. In theory it's possible to grant the action runner permission to create a branch but the last time I tried I couldn't make it work (forum posts allude to it being possible though)
2) the hashbrown dependency updating 

I'll get the automation working again at some point

**Review by willhickey — APPROVED** [review]

**Pull request merged**
