### PR TITLE
solana explorer: render program name, ix name, and account names from on chain idl for specific anchor programs

### PR DESCRIPTION
**Pull request by microwavedcola1**
This patch renders program name, ix name, and account names from on chain idl for whitelisted anchor programs. Tested with https://github.com/blockworks-foundation/voter-stake-registry program ix

image

### CODE REVIEW

**Comment by oJshua** [comment]
Screenshot 2022-03-09 at 13-39-17 Explorer Solana

@microwavedcola1 should this instruction have account names?

**Comment by microwavedcola1** [comment]
@oJshua thanks for checking, fixed it latest commit, now renders as expected
image

**Comment by oJshua** [comment]
Thanks @microwavedcola1. Sorry for the delay on this. Could you do a quick rebase to resolve conflicts?

**Review by oJshua — APPROVED** [review]

**Comment by microwavedcola1** [comment]
@oJshua  done!

**Comment by oJshua** [comment]
Thanks for this @microwavedcola1. Just a couple nits:

Screenshot 2022-03-23 at 09-52-30 Explorer Solana

Would it be okay if we camel case "voter stake registry"?

Screenshot 2022-03-23 at 09-53-04 Explorer Solana

We could put this in another PR, but it would be nice to have the instruction name appear in the program log.

**Comment by oJshua** [comment]
@microwavedcola1 -- what do you think about this? If it makes more sense to snakeCase the ixTitle, we can go back to that too. 

Screenshot 2022-03-23 at 11-28-10 Explorer Solana

**Comment by microwavedcola1** [comment]
@oJshua  changed to Title Case : PascalCase now, I agree looks better
image

**Comment by oJshua** [comment]
@microwavedcola1 Looks great! Thanks, will merge.

**Pull request merged**
