### PR TITLE
Helper function for filtering/creating clients in bench-exchange

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

code duplication

#### Summary of Changes

use function instead.

Fixes #

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Could this live in the solana-client crate (in thin_client, perhaps) so it would be easier to import into solana-bench-tps?

**Comment by sakridge** [comment]
@CriesofCarrots yes!

**Comment by sakridge** [comment]
Hmm..these would have to either live in the sdk, or the client would have to depend on core.
use solana::cluster_info::FULLNODE_PORT_RANGE;
use solana::contact_info::ContactInfo;

**Comment by sakridge** [comment]
Let's go with this, have a separate issue for bench-tps integration: #3908

**Comment by CriesofCarrots** [comment]
Works for me, thanks!
I'm leaning toward a separate various-bench-tools crate, as I imagine that there may be more shared methods like this, but we can see what the scope looks like.

**Comment by sakridge** [comment]
Yea we need common transaction count sampling and funding functions.

**Pull request merged**
