### PR TITLE
Update rust.md

### PR DESCRIPTION
**Pull request by videvide**
I believe this is better because you need Rust to be installed to complete the local development environment.

I've got everything up and running now so it's hard to recap exactly what happened but I'll try.

I installed the Solana CLI as the guide shows, but when I tried to execute solana-test-validator I ran into this error(https://stackoverflow.com/questions/70812395/aborted-core-dumped-in-solana-test-validator), this error also occurred when I downloaded and tried to execute the pre-built binary(silly mistake by me not to scroll further down). I then tried to build it from the source and got an error when I was trying to execute ./scripts/cargo-install-all.sh because Rust wasn't installed. It was something like 'cannot execute cargo'.

When I got that cargo error message it made me believe not having Rust was the underlying issue even for the first error.

I'm sorry for this messy report!

#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by apfitzge** [comment]
> I believe this is better because you need Rust to be installed to complete the local development environment.

I quickly scanned the local.md file and didn't see any part of it that requires rust, but might have missed something. Could you explain what part requires rust in the PR description?

**Comment by videvide** [comment]
> > I believe this is better because you need Rust to be installed to complete the local development environment.
> 
> I quickly scanned the local.md file and didn't see any part of it that requires rust, but might have missed something. Could you explain what part requires rust in the PR description?

Yes, that's correct. I've got everything up and running now so it's hard to recap exactly what happened but I'll try. 

I installed the Solana CLI as the guide shows, but when I tried to execute solana-test-validator I ran into this error(https://stackoverflow.com/questions/70812395/aborted-core-dumped-in-solana-test-validator), this error also occurred when I downloaded and tried to execute the pre-built binary(silly mistake by me not to scroll further down). I then tried to build it from the source and got an error when I was trying to execute ./scripts/cargo-install-all.sh because Rust wasn't installed. It was something like 'cannot execute cargo'.

When I got that cargo error message it made me believe not having Rust was the underlying issue even for the first error. 

I'm sorry for this messy report!

**Comment by apfitzge** [comment]
> When I got that cargo error message it made me believe not having Rust was the underlying issue even for the first error.

Building rust is definitely needed to build from source, but it shouldn't be for running the pre-built binaries.
I've been able to replicate the abort w/o and w/ cargo installed.

Follow this stackoverflow comment: https://stackoverflow.com/a/70937439/9967676:
```bash
solana-test-validator --log
```
which will hopefully give some additonal information.
The issue for me was AVX instructions, which were not present on my docker container rather than anything rust-related.

**Comment by videvide** [comment]
> > When I got that cargo error message it made me believe not having Rust was the underlying issue even for the first error.
> 
> Building rust is definitely needed to build from source, but it shouldn't be for running the pre-built binaries. I've been able to replicate the abort w/o and w/ cargo installed.
> 
> Follow this stackoverflow comment: https://stackoverflow.com/a/70937439/9967676:
> 
> ```shell
> solana-test-validator --log
> ```
> 
> which will hopefully give some additonal information. The issue for me was AVX instructions, which were not present on my docker container rather than anything rust-related.

Yes, that's what I did. And I've also read a bit more on self-contained binaries and realized it had nothing to do with Rust. I appreciate that you're confirming it! I'm sorry for wasting your time.

**Comment by apfitzge** [comment]
> I'm sorry for wasting your time.

No worries at all

**Pull request closed without merging**
