### PR TITLE
Add a SanitizedMessage type that caches writable accounts indexes

### PR DESCRIPTION
**Pull request by taozhu-chicago**
#### Problem
Would be good if `SanitizedMessage` can cache writable accounts for reusing, cause repeatedly calling `is_writable()` can be costly.

#### Summary of Changes
- Add `is_writable_account_cache: Vec<usize>` to `SanitizedMessage` variants. 
- Call `is_writable()` once during construction to populate `is_writable_account_cache: Vec<usize>`
- Add test

#### Fixes
Comments from #27263 ,

### CODE REVIEW

**Comment by taozhu-chicago** [comment]
@jstarry , can you please take a look at it, see if you OK with the approach? I like the idea of have SanitizedMessage cache is_writable call results, but uncomfort to change SanitizedMessage, at least its current usage, too much. Adding this additional enum type feels little patchy, would like to hear your thoughts.

**Comment by jstarry** [comment]
> The intention of adding an additional enum type is to be less invasive to existing `SanitizedMessage` user. Mainly didn't want to change API from readonly to mutable. But not so sure if this approach is intuitive. Are there other options?

Only the runtime should be using `SanitizedMessage` so it's fine to make changes to it in my opinion. I think that changing `SanitizedMessage` to a struct or changing its enum variants to each include the writables cache are both acceptable options.

> Using HashSet instead of Vec for quicker lookup by value, maybe will change the stored value from indexes to actual Pubkey

`Vec` is faster for lookup because it doesn't require a hash

**Comment by taozhu-chicago** [comment]
> changing its enum variants to each include the writables cache

That was one of my option too. Would it be OK to mandatory populate cache during SanitizedMessage construction, or introduce a new constructor that would populate cache (without changing existing behavior)?

**Comment by taozhu-chicago** [comment]
> `Vec` is faster for lookup because it doesn't require a hash

lookup by value with Vec is a linear search, some benchmarks on Rust Vec vs HashSet says Vec is faster if elements are 15 or less. But ig there isn't a huge difference in this use case.

**Comment by jstarry** [comment]
It's constant time lookup if you have a vec with the same length as account keys and store a boolean of whether each account is writable or not. And BitVec can be used to minimize space

**Comment by jstarry** [comment]
Mandatory filling the cache is fine imo

**Comment by taozhu-chicago** [comment]
> It's constant time lookup if you have a vec with the same length as account keys and store a boolean of whether each account is writable or not. And BitVec can be used to minimize space

Ah right! Made that changes in last commit. Thanks for the idea.

**Review by CriesofCarrots — APPROVED** [review]
Lgtm, but would be great to get Justin's ✅ too

**Comment by taozhu-chicago** [comment]
> Lgtm, but would be great to get Justin's ✅ too

Thanks for review, merging it now since it is blocking bunch of other PRs. Open to update if concerns raises.

**Review by jstarry — COMMENTED** [review]
Looks fine to me, thanks for adding this!

**Pull request merged**
