### PR TITLE
Add design doc for testing programs

### PR DESCRIPTION
**Pull request by garious**
#### Problem

A variety of problems can occur when developing applications. The current mechanisms for troubleshooting include trace-debugging and low-level testing against only the Bank and Runtime.

#### Summary of Changes

Describe a tiered approach to testing that would application developers to troubleshoot by breaking down the system into smaller, more manageable pieces, all implementing the same interface. Likewise, it would allow existing integration tests to bubble up to testnet deployments.

Towards #3058

### CODE REVIEW

**Comment by garious** [comment]
Yeah, probably one for clusters and one for the TPU.

**Comment by aeyakovenko** [comment]
CTF gets one from mk_client. It never sees. Fullnode.   That implementation should run against mainnet as well.

**Comment by garious** [comment]
Maybe better to say it this way, the thing that `mk_client()` returns should implement `Transact` and that's how CTF should send transactions to the cluster.  The other main implementation of `Transact` would be on `Tpu`. Like a good light client and unlike interacting with Bank, the interface should be asynchronous.  The `Tpu` version would just drop those transactions onto the channel that goes straight to `SigVerifyStage`. After recording, the channel that normally goes to `BroadcastStage` would go to `/dev/null`.

**Comment by garious** [comment]
There's no trait that "covers" all tiers, just Transact.

**Comment by aeyakovenko** [comment]
I guess I am confused on what the point of the tiers is.  

Is the goal to have a single test work with every tier?  

When would a developer write a test for any of the middle layers?  Why wouldn’t a dev only test against the program directly without any layers, and against the program running on a cluster?

**Comment by garious** [comment]
> I guess I am confused on what the point of the tiers is.

"To troubleshoot, the application should retarget a lower-level component, where
fewer errors are possible. Retargeting can be done with different
implementations of the Transact trait."

> Is the goal to have a single test work with every tier?

No, the goal is to be able to trivially move that single test between tiers. The developer would move up tiers to prove their program still works when more error conditions are present. They'd move down tiers to minimize dependencies and improve the reliability of their integration tests.

> Why wouldn’t a dev only test against the program directly without any layers, and against the program running on a cluster?

Those are two good options. Personally, I'd write all my unit-tests using only Runtime and integration tests against the highest level, non-I/O option, a socket-free TPU. Then, I'd want there to be a mechanism to trivially run that same TPU test against a cluster.

For reference,  here's an example of a unit-test using the Runtime:

https://github.com/solana-labs/solana/blob/master/programs/budget/src/budget_program.rs#L194

And here's one that shows how today's developer can't even climb as high as the Bank before losing error information and debug symbols:

https://github.com/solana-labs/solana/blob/master/programs/budget/tests/budget.rs#L25

By approving this PR, you'd be saying that the lossy Bank errors is unacceptable and that the underlying `BudgetError` that you see in the unit-tests ought to be available as high as a cluster test, which would be a consequence of it being available via the Transact trait.

**Comment by aeyakovenko** [comment]
@garious, lossy bank errors make sense for an application that’s subscribing for them.  A validator shouldn’t need to store that data if there is nothing expecting it.

If we ship a test framework in an SDK, the tpu  wouldn’t be a public component.  It is a really low level implementation detail that app developers don’t really need to think about. 


So what would move this from proposed to implemented?  Just a single implementation of Transact?

**Comment by garious** [comment]
> If we ship a test framework in an SDK, the tpu wouldn’t be a public component. It is a really low level implementation detail that app developers don’t really need to think about.

I respectively disagree. I'd encourage devs to point unit-tests to the Runtime (via the solana_runtime crate) and integration tests to the TPU (via a new `solana_tpu` crate).

> So what would move this from proposed to implemented? Just a single implementation of Transact?

If TPU and ThinClient implemented Transact.  Optionally, all programs' integration tests being updated from using Bank to TPU's Transact.

**Comment by aeyakovenko** [comment]
Ok!  I think the Transact trait could hide the plumbing. 

But are you going to expose  PohRecorder, ClusterInfo? That boundary is going to stay fluid while we optimize.

**Comment by garious** [comment]
I hope that PohRecorder could be a private module in  the solana_tpu crate.  ClusterInfo should stay in the solana crate. TPU shouldn't have a real dependency on ClusterInfo. ClusterInfo should implement a trait that allows TPU to push votes.

**Pull request merged**
