### PR TITLE
lol this is not a fix at all cc @jstrry

### PR DESCRIPTION
**Pull request by staccDOTsol**
#### Problem

lookuptables busted some buffer layout bs

#### Summary of Changes

just comment it out. busts some of the tx. not all

### CODE REVIEW

**Comment by staccDOTsol** [comment]
r/comment/trycatch

**Comment by staccDOTsol** [comment]
s/r/s

**Comment by jstarry** [comment]
Hey, thanks for raising the issue but there's not enough to go off of from this. If you get a stack trace with the error please open an issue, thanks!

**Comment by staccDOTsol** [comment]
gm @jstarry  I broke it again here's the trace

`/Users/jarettdunn/apiarbsold/node_modules/@solana/buffer-layout/lib/Layout.js:2098
            throw new RangeError('encoding overruns Uint8Array');
                  ^

RangeError: encoding overruns Uint8Array
    at Blob.encode (/Users/jarettdunn/apiarbsold/node_modules/@solana/buffer-layout/lib/Layout.js:2098:19)
    at /Users/jarettdunn/apiarbsold/node_modules/@solana/buffer-layout/lib/Layout.js:954:31
    at Array.reduce (<anonymous>)
    at Sequence.encode (/Users/jarettdunn/apiarbsold/node_modules/@solana/buffer-layout/lib/Layout.js:953:26)
    at Structure.encode (/Users/jarettdunn/apiarbsold/node_modules/@solana/buffer-layout/lib/Layout.js:1092:36)
    at MessageV0.serialize (/Users/jarettdunn/apiarbsold/node_modules/@solana/web3.js/lib/index.cjs.js:1130:51)
    at VersionedTransaction.sign (/Users/jarettdunn/apiarbsold/node_modules/@solana/web3.js/lib/index.cjs.js:2170:38)
    at file:///Users/jarettdunn/apiarbsold/solend.mjs:333:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by staccDOTsol** [comment]
funny enough this may just be when a tx is (still) too large

**Pull request closed without merging**
