### PR TITLE
Support tpu disable quic in net scripts

### PR DESCRIPTION
**Pull request by lijunwangs**
Support passing --tpu-disable-quic in validator launched by net scripts

### CODE REVIEW

**Review by CriesofCarrots — APPROVED** [review]

**Comment by KirillLykov** [comment]
I think bench-tps client requires option to enable quic as well.

Another thing is that it looks like quic will become default soon and option will be tpu-disable-quic [quic by default PR](https://github.com/solana-labs/solana/pull/26927/files). So these options in script will probably require renaming.

**Comment by KirillLykov** [comment]
@lijunwangs , looks like now QUIC is default ( https://github.com/solana-labs/solana/pull/27194).
I think having option `--tpu-disable-quic` would be beneficial also for these scripts

**Comment by lijunwangs** [comment]
> @lijunwangs , looks like now QUIC is default ( #27194).
> I think having option `--tpu-disable-quic` would be beneficial also for these scripts

Yes, it is funny -- I turned it to tpu-disable-quic now

**Review by CriesofCarrots — COMMENTED** [review]
Thanks for flopping! It looks like `multinode-demo/validator.sh` needs updating as well. Do you mind?

**Comment by lijunwangs** [comment]
> Thanks for flopping! It looks like `multinode-demo/validator.sh` needs updating as well. Do you mind?

Sure. I will take care of it. I am testing this. I found the cluster would not start up with --tpu-disable-quic turned on. Still debugging.

**Comment by lijunwangs** [comment]
> > Thanks for flopping! It looks like `multinode-demo/validator.sh` needs updating as well. Do you mind?
> 
> Sure. I will take care of it. I am testing this. I found the cluster would not start up with --tpu-disable-quic turned on. Still debugging.

It turns out the missing change multinode-demo/validator.sh was causing the issue as the member validator was started with default quic and the bootstrap was started with quic disabled.

**Pull request merged**
