### PR TITLE
Remove lamports-per-byte-year and lamports-per-epoch from rent as all…

### PR DESCRIPTION
**Pull request by michaelh-laine**
All accounts must now be rent exempt, the RPC only returns a rent exempt minimum, therefore there is no reason for the CLI to return lamports per byte year or lamports per epoch.

Changes:
remove these values from the CLI return as well as the underlying CliRentCalculation struct.

### CODE REVIEW

**Comment by michaelh-laine** [comment]
@steviez `test_run_test_load_program_accounts_partition_root` by the looks of it, as well as a segfault in another pipeline (local-cluster-slow-1) and compile error (local-cluster-slow-2), I don't think these are related to my change, would you mind confirming and rekicking CI if appropriate?

**Comment by steviez** [comment]
> @steviez `test_run_test_load_program_accounts_partition_root` by the looks of it, as well as a segfault in another pipeline (local-cluster-slow-1) and compile error (local-cluster-slow-2), I don't think these are related to my change, would you mind confirming and rekicking CI if appropriate?

Agreed that those failures do not appear to be a result of your change. That being said, I will likely defer to someone else to volunteer (or get voluntold 😄 ) for this PR, so hang tight. 

One quick note tho - changing the CLI output could hypothetically break someone that was parsing output. I haven't worked with the CLI as much so I'm not sure if that is something that is generally frowned upon at this level. At the very least, maybe a line item in release notes saying that we dropped the fields.

**Comment by michaelh-laine** [comment]
> > @steviez `test_run_test_load_program_accounts_partition_root` by the looks of it, as well as a segfault in another pipeline (local-cluster-slow-1) and compile error (local-cluster-slow-2), I don't think these are related to my change, would you mind confirming and rekicking CI if appropriate?
> 
> Agreed that those failures do not appear to be a result of your change. That being said, I will likely defer to someone else to volunteer (or get voluntold 😄 ) for this PR, so hang tight.
> 
> One quick note tho - changing the CLI output could hypothetically break someone that was parsing output. I haven't worked with the CLI as much so I'm not sure if that is something that is generally frowned upon at this level. At the very least, maybe a line item in release notes saying that we dropped the fields.

thanks, I took reassurance from the fact that the RPC API doesn't actually provide that data anymore. One thing I considered was adding a `--legacy` flag or using the --verbose flag to print the original output.

**Comment by steviez** [comment]
> thanks, I took reassurance from the fact that the RPC API doesn't actually provide that data anymore. 

Ahh, wasn't immediately aware of that. But, that seems like fairly good justification for us being alright with dropping this from CLI as well. Again, I'm going to officially defer for someone else at the moment tho

**Review by steviez — APPROVED** [review]
LGTM to me and as you pointed out, this aligns with the [JSON RPC API](https://docs.solana.com/developing/clients/jsonrpc-api#getminimumbalanceforrentexemption) dropping the additional values as well.

**Comment by CriesofCarrots** [comment]
> I'm not sure if that is something that is generally frowned upon at this level

@steviez, yes, this is a violation of our backward compatibility policy as a breaking change to a public client interface. Typically, we would want to deprecate the fields, rather than delete them.
(Not sure how you both determined that there was some sort of change to the JSON-RPC api, but `getMinimumBalanceForRentExemption` has only ever returned the rent-exempt minimum.)

I think we should revert this. I am mostly concerned about preserving the CliRentCalculation fields for `--output json`, so we could preserve the removal of the print statements, and populate the fields with default values instead of querying `rpc_client.epoch_schedule()`.

We don't have a great way to communicate deprecation in solana-cli output, so I'm open to ideas about how to do that.

**Comment by michaelh-laine** [comment]
Removed was an incorrect conclusion, I was under the perhaps incorrect impression there used to be a `getRent` or similar endpoint, but the `getMinimumBalanceForRentExemption` is explicit in that it is the amount for exemption.

Regardless those values aren't relevant anymore (unless there's a use case I'm missing) so I figured they should be removed from the CLI, however I did not consider the --output=json. I can rewrite this PR to return 0 for those values in the JSON?

**Comment by steviez** [comment]
@CriesofCarrots - This was a goof on my part; I was not fully aware of all that we outlined in the [Backwards Compatibility Policy](https://docs.solana.com/developing/backwards-compatibility).

My takeaway is that given that we're still on 1.x, we can mark items deprecated, but we shouldn't be ripping them out / changing things in an incompatible way. Ie, the JSON RPC API has [this](https://docs.solana.com/developing/clients/jsonrpc-api#json-rpc-api-deprecated-methods).

> We don't have a great way to communicate deprecation in solana-cli output, so I'm open to ideas about how to do that.

Yeah, I don't have any good suggestions here. We could make a note in release notes (if we remember) and emit a warning to standard error, but hypothetically, anyone who is using this command in an automated workflow wouldn't see that warning.

> I am mostly concerned about preserving the CliRentCalculation fields for --output json, so we could preserve the removal of the print statements

Makes sense on preserving the fields for `--output json` case. For the regular print statements that you were ok with removing, is the idea here that it is likely human readers using this mode / unlikely that someone is parsing the output and would get broken when they have a perfectly good json mode available?

**Comment by CriesofCarrots** [comment]
> or the regular print statements that you were ok with removing, is the idea here that it is likely human readers using this mode / unlikely that someone is parsing the output and would get broken when they have a perfectly good json mode available?

Yes, exactly. It's a compromise. Now that we have much broader support for `--output json`, it actually might be worth updating the backward compat policy to say explicitly that json compatibility will be preserved, while human-reader-focused Displays may be subject to change.

**Comment by steviez** [comment]
> to say explicitly that json compatibility will be preserved, while human-reader-focused Displays may be subject to change.

Cool, that seems like a pretty good middle ground to me:
- Keep the machines happy by not ripping out fields
- Keep the humans happy by removing eye clutter

**Pull request merged**
