### PR TITLE
Add incremental snapshots to RPC

### PR DESCRIPTION
**Pull request by brooksprumo**
Putting up this draft PR to get feedback on what's required to add Incremental Snapshots to RPC, for downloading an ISS.

Note: It will not build since the backing ISS code is not in here, and thus the checks will fail.

### CODE REVIEW

**Comment by brooksprumo** [comment]
@CriesofCarrots Are you the right person to take a look at this? I noticed your name on many lines of `git blame` for the RPC code. Mostly I'm wondering if there's anything that I've missed, or is obviously wrong.

After RPC, I'll be adding ISS stuffs to the gossip service as well.

**Comment by CriesofCarrots** [comment]
@brooksprumo , sure, I'll take a look!

**Comment by CriesofCarrots** [comment]
Looks fine from the rpc/client perspective. (And also draws my attention to the fact that the client is supporting some long-dead rpc methods... prob time to remove! Thx)

**Comment by brooksprumo** [comment]
@CriesofCarrots Thanks for taking a look!

**Comment by brooksprumo** [comment]
Link-back: Related to #17088

**Pull request closed without merging**
