### PR TITLE
chore: Update light-poseidon to 0.2.0

### PR DESCRIPTION
**Pull request by vadorovsky**
That new release contains an important change which prevents a potential DDoS.

* Lightprotocol/light-poseidon#32

Invoking `from_bytes_be` function light-poseidon 0.1.1 inverts all the inputs before performing a check whether their length exceeds the modulus of the prime field. Therefore, it was prone to an attack, where a mailicious user could submit long byte slices just to DDoS the validator, being stuck on inverting large byte sequences.

The update and mentioned change fixes the same issue as #33363 aims to address.

The new release contains also few other less important changes like:

* https://github.com/Lightprotocol/light-poseidon/pull/37
* https://github.com/Lightprotocol/light-poseidon/pull/38
* https://github.com/Lightprotocol/light-poseidon/pull/39

### CODE REVIEW

**Comment by vadorovsky** [comment]
@samkim-crypto

**Comment by vadorovsky** [comment]
@samkim-crypto

**Comment by vovacodes** [comment]
Can we merge this plz. We see the compile errors fixed in this PR because our Cargo.lock already resolves `light-poseidon` to `0.1.3` 

```
error[E0004]: non-exhaustive patterns: `PoseidonError::BytesToPrimeFieldElement { .. }` and `PoseidonError::BytesToBigInt` not covered
   --> /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-program-1.17.4/src/poseidon.rs:212:23
    |
212 |                 match error {
    |                       ^^^^^ patterns `PoseidonError::BytesToPrimeFieldElement { .. }` and `PoseidonError::BytesToBigInt` not covered
    |
note: `PoseidonError` defined here
   --> /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/light-poseidon-0.1.3/src/lib.rs:160:5
    |
145 | pub enum PoseidonError {
    | ----------------------
...
160 |     BytesToPrimeFieldElement { bytes: Vec<u8> },
    |     ^^^^^^^^^^^^^^^^^^^^^^^^ not covered
...
168 |     BytesToBigInt,
    |     ^^^^^^^^^^^^^ not covered
    = note: the matched value is of type `PoseidonError`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern, a match arm with multiple or-patterns as shown, or multiple match arms
    |
231 ~                     } => PoseidonSyscallError::InvalidWidthCircom,
232 ~                     PoseidonError::BytesToPrimeFieldElement { .. } | PoseidonError::BytesToBigInt => todo!(),
    |


```

**Comment by vadorovsky** [comment]
@vovacodes Apologies for that! I yanked the 0.1.3 version and I'm going to ship the breaking changes as 0.2.0, since we are breaking the API and adding new versions.

**Review by samkim-crypto — APPROVED** [review]
Looks good to me!

**Pull request merged**
