### PR TITLE
refactor and extract send batch logic

### PR DESCRIPTION
**Pull request by KirillLykov**
#### Problem

*Please review by commit*

This is PR contains prerequisite changes for the follow up PRs to add support of  durable nonce transactions.

#### Summary of Changes

* Extracted sending batch funding transactions logic to separate file
* Refactored code of `SendBatchTransactions` to be reusable later for durable nonce accounts creation

### CODE REVIEW

**Comment by jstarry** [comment]
It's really difficult to review a PR that refactors code and adds new functionality. Please do the refactoring separately so that reviewers can see what is actually changed.

**Comment by KirillLykov** [comment]
> It's really difficult to review a PR that refactors code and adds new functionality. Please do the refactoring separately so that reviewers can see what is actually changed.

I think the problem is that this PR moves some code to the new file and does refactoring since it doesn't really introduce anything new. So I will split it in several commits (one will move existing code to the new file). This way it is easier to review by commit and see code changes.

**Comment by KirillLykov** [comment]
@jstarry now it looks a bit better if check commit by commit

**Comment by KirillLykov** [comment]
> Thanks for splitting up the changes, it's easier to see what you've changed now. However, I'm still not clear on why these particular changes are useful for durable nonce transactions. Can you add more context to the description about what the purpose of splitting up the `FundingTransactions` trait and why you need a `Sliceable` trait?

Yeah, probably it is better to create a chain of PRs to achieve both goals of having small PRs and provide some reasoning of changes.
The commit which adds nonce accounts creation might be found in this PR: https://github.com/solana-labs/solana/pull/26215

**Comment by KirillLykov** [comment]
@jstarry any comments/concerncs on these changes?

**Review by joncinque — APPROVED** [review]
Thanks for splitting up the commits -- this looks good to me! The subsequent PR #26215 makes it very clear why this is needed.

**Pull request merged**
