### PR TITLE
issue #153 - panic cleanup

### PR DESCRIPTION
**Pull request by jackson-sandland**
Added more descriptive / identifiable error messages for all calls to `unwrap()` expect for inside the `bin` directory, tests, and benchmarking.

### CODE REVIEW

**Comment by aeyakovenko** [comment]
buildkite

**Comment by garious** [comment]
Nice! And somehow only one conflicting file. Can you rebase?

**Comment by garious** [comment]
Now two conflicts, sorry! Gotta keep these PRs small or move super fast. solana team is cranking!

**Comment by jackson-sandland** [comment]
@garious that is fast! I didn't want to create a PR for each file - but would have been simpler in hindsight :)

**Comment by garious** [comment]
Can you run `cargo fmt`? Make sure you upgraded to the latest Rust first! The new plugin will generate different code.

**Comment by jackson-sandland** [comment]
on it.

**Comment by garious** [comment]
Close enough, merging!

**Comment by jackson-sandland** [comment]
That was exhilarating :) but I'll make the PR smaller in the future.

**Pull request merged**
