### PR TITLE
Add Rust client proposal

### PR DESCRIPTION
**Pull request by garious**
#### Problem

Our Rust clients got messy and the parts of the test suite that use them got very slow.

#### Summary of Changes

Add a proposal for how to clean it up.

cc https://github.com/solana-labs/solana/issues/9225

### CODE REVIEW

**Comment by t-nelson** [comment]
It'd be great to see the error types spec out as well :pray:

My main request would be to strictly forbid supplying messages intended for users directly, in favor of surfacing the details required to construct them at the application level

**Comment by mvines** [comment]
Only concern is see here is that it's possible that not all underlying ThinClient implementations will be able to satisfy all the ThinClient methods.   For example I'd expect a BankClient to only use runtime/, so it would not be able to implement the RpcClient methods that rely on ledger/

**Comment by garious** [comment]
Barebones version in action: https://github.com/garious/solana-tokens/blob/master/src/thin_client.rs

A fun feature is that it implements the `Client` trait for `()`, which you can use to implement `--dry-run` behavior.  You just write `ThinClient(())` instead of `ThinClient(rpc_client)`.

**Comment by garious** [comment]
@t-nelson @mvines, added a commit. Thanks for the feedback!

**Pull request merged**
