### PR TITLE
Update to Rust 1.57.0

### PR DESCRIPTION
**Pull request by steviez**

### CODE REVIEW

**Comment by steviez** [comment]
@mvines - I blindly put this change up for PR before realizing I needed to follow the steps at:
https://github.com/solana-labs/solana/tree/master/ci/docker-rust

Can I get access to the Solana Docker Hub if we're good with adding more users? Just made an account with username `steviez10` (my GitHub username was already taken 😢 )

**Comment by mvines** [comment]
We need to get away from DockerHub actually. They're started to get really dumb with their pricing, and we can't add any more users without adding a subscription plan of some sort, which I've been resisting doing on principal

**Comment by mvines** [comment]
In the meantime I can carry this PR forward in the background tomorrow.  There aren't any new clippy complaints with 1.57 I take it?

**Comment by steviez** [comment]
>They're started to get really dumb with their pricing, and we can't add any more users without adding a subscription plan of some sort, which I've been resisting doing on principal

Fair enough

> In the meantime I can carry this PR forward in the background tomorrow. There aren't any new clippy complaints with 1.57 I take it?

`1.57` on stable is good to go without code changes 🎉 ; let me double check the nightly ... I realize I didn't retest nightly when I bumped it from 12/06 to 12/08. I'll leave a note when I've confirmed it is good to go

**Comment by steviez** [comment]
>In the meantime I can carry this PR forward in the background tomorrow. There aren't any new clippy complaints with 1.57 I take it?

I confirmed that the referenced stable and nightly version both build / run through clippy without warning. Ie, the following 4 commands all completed without error from project root:
```
$ ./cargo build --all
$ ./cargo clippy
$ ./cargo nightly build --all
$ ./cargo nightly clippy
```

**Comment by mvines** [comment]
I pushed the new 1.57 docker images and kicked CI here.  Seems happy so far, I'm optimistically adding the automerge label

**Comment by mvines** [comment]
achilles 🤕

**Pull request merged**
