### PR TITLE
web3.js - more esm friendly

### PR DESCRIPTION
**Pull request by Niputi**
#### Problem

currently esm browser file includes node-fetch which requires multiple polyfills to use

#### Summary of Changes

changed `node-fetch` to `ky-universal`
changed `url` module usage to `new URL` native js as the used `url` functions were marked as deprecated

this change requires node.js version 14 according to ky-universal

#### Fixes 

vite.js issue which can be observed in https://github.com/NorbertBodziony/vite-test as it requires several polyfills to work, making bundle heavier.

### CODE REVIEW

**Comment by Niputi** [comment]
dont understand why it errors out. `Options` does exist in `ky-universal`

**Comment by jstarry** [comment]
@Niputi looks like the error is due to a missing peer dependency on `ky` which is causing dependency resolution issues for `ky-universal`. Could you please add a dependency on `ky`?

**Comment by jstarry** [comment]
Looks like travis ci won't run until the conflict is fixed, can you rebase or merge master into this branch?

**Comment by Niputi** [comment]
sorry I have never done that before. not sure how to do it

**Comment by Niputi** [comment]
I think I did it

**Comment by jstarry** [comment]
Looks like the merge of `package-lock.json` didn't work out well because it still has merge conflict markers. You can create a new branch off of latest solana-labs/solana master and then force push to your `master` branch. Next time, when creating a PR, I recommend using a non-master branch btw

**Comment by jstarry** [comment]
Looks like you have some formatting issues from prettier, you'll need to run `npm run lint:fix`. There's a commitlint error too but feel free to ignore that.

**Comment by Niputi** [comment]
lint is fixed. getting a error at `npm run test:cover` now

**Comment by jstarry** [comment]
Thanks @Niputi, I'll take a look at this soon

**Comment by jstarry** [comment]
@Niputi I think we will be in better shape after the next few `buffer-layout` updates. Both your change to remove `assert` and my change to add the `buffer` polyfill should improve things quite a bit.

**Comment by jstarry** [comment]
We also need to remove `rollup-plugin-node-polyfills` because it injects weird polyfills that break some bundlers

**Comment by Niputi** [comment]
currently not home. helping with renovation of a house. Will get to it in the night

**Comment by Niputi** [comment]
closed in favor of https://github.com/solana-labs/solana/pull/18531 🙂

**Comment by jstarry** [comment]
Thanks @Niputi for getting this started, still have some work to do to fix CI if you want to help figure it out

**Pull request closed without merging**
