### PR TITLE
Reduce slot duration and consecutive leader slots

### LINKED ISSUE #4162: Consider 400ms slots
#### Problem
Confirmation time can be shorter.  Any reduction in slot time that doesn't introduce block failures translates into faster finality, and lower latency interfaces for applications, as well as a reduced attack surface for censorship.

#### Proposed Solution

Reduce slot time to 400ms

### LINKED ISSUE #4163: Rotate leaders on every slot
##### Problem

Right now leader rotation occurs every 8 slots:
https://github.com/solana-labs/solana/blob/9b50583641653b6cb34bc5eb6f3ee88364837279/sdk/src/timing.rs#L14

Consecutive leader slots introduce large periods of downtime, and allow for large periods where a single leader is ordering transactions.

##### Solution

Let's bring this back down to 1, which might require further optimizations like:
* Speculative signature verification
* Speculative transaction execution

cc: #4162

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
Slot duration and leader slots need to be reduced

#### Summary of Changes
Change slot duration to 400ms, and number of leader slots to 4

Fixes #4162 
#4163

### CODE REVIEW

**Comment by pgarg66** [comment]
> Cool, how much does this destroy TPS?

It went down to ~40K from ~65K

**Comment by aeyakovenko** [comment]
We might see a bunch more dropped blocks.  Theis a bank height metric vs slot height should indicate how often the network fails to converge.

**Comment by mvines** [comment]
> Fixes #4162
> #4163

Mind your github syntax here, this will only fix 4162 and not 4163.
cc: https://help.github.com/en/articles/closing-issues-using-keywords#closing-multiple-issues

**Comment by pgarg66** [comment]
> > Fixes #4162
> > #4163
> 
> Mind your github syntax here, this will only fix 4162 and not 4163.
> cc: https://help.github.com/en/articles/closing-issues-using-keywords#closing-multiple-issues

Thanks @mvines I understand. I do not want to close 4163, as the slots per leader will be 4 in this PR. Leaving 4163 open as we may want to try to reduce it to 1 slot.

**Pull request merged**
