### PR TITLE
Stop generating CLI usage doc

### PR DESCRIPTION
**Pull request by garious**
#### Problem

The auto-generated "CLI usage" is likely solving a problem no user has. Who leaves the command-line to load a webpage instead of staying a the command-line and typing `solana <command> --help`?

Also, it's broken in CI, but why fix what we can delete?

#### Summary of Changes

Stop generating CLI usage. Instead, leave only examples.

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
This will break a handful of links, mostly in the paper-wallet section.
Also, I'm not sure all the remaining examples are particularly helpful. If you want to keep cli/usage.md, maybe strip out all the Budget commands?

**Comment by t-nelson** [comment]
```
$ cd docs
$ git grep -Hn 'usage.md'
```

**Comment by garious** [comment]
Okay, I won't merge this until I've created new docs for those commands.

**Comment by garious** [comment]
To die another day

**Pull request closed without merging**
