### PR TITLE
Allow passing of program_id to programs

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

A transaction that contains the same key as a program ID and an account key will cause the runtime to panic.

Also, accounts that also exist as program IDs in a transaction cannot be passed to programs.  A program id in one instruction may want to be passed to a program in another instruction for cross-program-invocations

#### Summary of Changes

- Allow program IDs to be passed to programs

Fixes #

### CODE REVIEW

**Comment by jackcmay** [comment]
@garious @ParthDesai @rob-solana :eyes:

**Comment by garious** [comment]
Why did Cargo.lock change?

**Comment by jackcmay** [comment]
Dunno, that usually happens when I have `cargo watch` running in the background and I switch between different git branches

**Comment by jackcmay** [comment]
@garious For my understanding, what is the motivations to backport this to v1.0?

**Comment by garious** [comment]
@jackcmay, because of that panic. A client can knock down the leader with a transaction.

**Pull request merged**
