### PR TITLE
ci: fix spl downstream test script

### PR DESCRIPTION
**Pull request by yihau**
#### Problem

accidentally changed spl downstream test script

#### Summary of Changes

correct it

### CODE REVIEW

**Comment by yihau** [comment]
the env is defined in the `common.sh`

https://github.com/solana-labs/solana/blob/99cd1a51f5c9dd38725f4257f5b86ebd354cd935/ci/downstream-projects/common.sh#L11-L14

**Comment by joncinque** [comment]
@alessandrod actually needs to eventually disable the downstream SPL tests, and then I need to temporarily disable the downstream build for #30975 until SPL updates to 1.16, so can we hold off on merging this until those are both done?

**Comment by yihau** [comment]
sure! tbh, I would like to remove the whole downstream tests as well 🙈 I don't think it should live in our main pipeline. maybe another nightly job even not to run it.

**Comment by joncinque** [comment]
@yihau this can go in now! But just to be safe, could you rebase and re-run CI?

**Comment by yihau** [comment]
sure!

**Comment by solana-grimes** [comment]
:scream: New commits were pushed while the automerge label was present.

**Comment by yihau** [comment]
oh. we disable spl test in #30975. I will do some hack to check if spl works fine.

**Comment by yihau** [comment]
got fixed by https://github.com/solana-labs/solana/pull/32677

**Pull request closed without merging**
