### PR TITLE
sdk: move address lookup table out of solana-program

### PR DESCRIPTION
**Pull request by buffalojoec**
#### Problem
As part of the effort to migrate the Address Lookup Table program to Core BPF, we've decided to contain all relevant program information (instructions, state) inside of its crate.

In order to complete this effort, we need to remove the program's instructions, state, etc. from `solana-program`, otherwise we will face trait collisions.

#### Summary of Changes
As a temporary measure, I've moved it into the SDK, rather than `solana-program`, so that the rest of the monorepo needs no refactoring.

When the Address Lookup Table program has been successfully migrated to Core BPF, it should be removed from the SDK entirely.

### CODE REVIEW

**Comment by joncinque** [comment]
I might be missing some context, but what is this trying to accomplish? In the ideal case, we want ALT completely out of the SDK and have people use it from its own crate, no?

> In order to complete this effort, we need to remove the program's instructions, state, etc. from solana-program, otherwise we will face trait collisions.

Maybe I'm missing something, but what sort of issues do you mean by "trait collisions"? It seems like it would be fine to have a totally separate crate that defines the ALT types and instructions and then just deprecate everything in `solana-program`, no?

We have a nice opportunity with the 2.0 release to actually remove stuff, so let's avoid just moving it somewhere else!

On a separate note, looking at the layout of the crate, I wonder if we'll need to split out `Message` into its own crate, something like `solana-message`, which can work on-chain, and can safely depend on the ALT types without circular dependencies with `solana-program`.

**Comment by buffalojoec** [comment]
> I might be missing some context, but what is this trying to accomplish? In the ideal case, we want ALT completely out of the SDK and have people use it from its own crate, no?

Yes, I agree, but the change was huge. Address lookup table is used across over a dozen crates in the monorepo. I figured it might be best to do this piecemeal. This was an incremental step, both to unblock the Core BPF implementation and start the refactoring process.

If you want me to go for it all, I will.

> Maybe I'm missing something, but what sort of issues do you mean by "trait collisions"?

https://github.com/buffalojoec/core-bpf-alt/blob/d59237f08c0d4be53276b7900c56ebe58876ca8a/src/state.rs#L34-L36

> On a separate note, looking at the layout of the crate, I wonder if we'll need to split out Message into its own crate, something like solana-message, which can work on-chain, and can safely depend on the ALT types without circular dependencies with solana-program.

Yep, this is probably the way. In the same spirit, there might be more splitting out work we can do to alleviate some of that massive refactoring I mentioned.

**Comment by joncinque** [comment]
> This was an incremental step, both to unblock the Core BPF implementation and start the refactoring process.

If you want a more incremental step, how about moving the ALT types into a new separate crate in the monorepo rather than in `solana-sdk`? If we go forward with this change as is, and a release is published, we'll then need to go through another deprecation process to remove the ALT types from SDK.

Either way, I think it'll be cleaner to avoid the middle step and immediately use the ALT crate.

> I don't think deprecating the types will tell cargo to ignore the trait implementations on the deprecated types, will it?

No it won't unfortunately. That problem with AbiExample is more of a bug with the macro if it can't handle the same type name in different crates. We can fix that if we want at https://github.com/solana-labs/solana/tree/master/frozen-abi, but it's probably not worth it.

> Yep, this is probably the way. In the same spirit, there might be more splitting out work we can do to alleviate some of that massive refactoring I mentioned.

Yeah that's a great point. We could probably create some levels within `solana-program`, ie. have `Pubkey` all the way at the bottom, and `Message` at the top. That could also help devs in the future who only need the absolute basics for their program.

> One note is that we may need the Core BPF crate published before we can properly do some of this.

Yeah definitely, that's totally fine.

**Comment by buffalojoec** [comment]
Closing in favor of a broader SDK refactor.

**Pull request closed without merging**
