### PR TITLE
Check for log level before doing perf counter work

### PR DESCRIPTION
**Pull request by sakridge**

### CODE REVIEW

**Comment by sakridge** [comment]
Can you explain a bit more how you're proposing it works?

**Comment by aeyakovenko** [comment]
@sakridge `counter_info!` `counter_trace!` macros.  the log level is in the counter itself as a static const, so can be checked without an atomic

**Comment by sakridge** [comment]
Hmmm, seems to make the test faster but maybe not passing as much as before...

**Comment by sakridge** [comment]
@pgarg66 saying it works better in his tests for mutlinode_dynamic. Please approve if this is the case, thanks.

**Pull request merged**
