### PR TITLE
Explorer: upgradeable loader buffer data and program data display

### PR DESCRIPTION
**Pull request by oJshua**
#### Problem
The various accounts involved with a deployed upgradeable program are mysterious on the explorer.
Example (buffer account): https://explorer.solana.com/address/B8Qe8miJufJQcZMqSGoRGNGscrzcgrKjQFoU7fWjbP1q?cluster=devnet

#### Summary of Changes
Display data, data type, and allow user to copy. 

Fixes https://github.com/solana-labs/solana/issues/15198

### CODE REVIEW

**Comment by oJshua** [comment]
Explorer-Solana (22)

Explorer-Solana (21)

**Comment by oJshua** [comment]
Still sort of spinning on this one. It'd be nice to make the data displays collapsible.

**Comment by jstarry** [comment]
@oJshua I can't think of a reason someone would want to see this or copy to clipboard. Seems that users will want to verify this binary data against open source code or download the binary to redeploy somewhere else. Did you have a usecase in mind for showing the binary data?

**Comment by oJshua** [comment]
@jstarry I think I may have misinterpreted this task: https://github.com/solana-labs/solana/issues/15198. Do you know what additional parts that task needs? I'll revisit.

**Comment by jstarry** [comment]
Ah, I should have closed it with https://github.com/solana-labs/solana/pull/15836

**Pull request closed without merging**
