### PR TITLE
Purge by range scan and single delete

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Summary of Changes

Provide a delete_slot version of purge_slots for benchmarking.

### CODE REVIEW

**Comment by sagar-solana** [comment]
@sunnygleason I think this is better off here? 

#### Results of some preliminary benchmarking (AWS m5.2xlarge)

* Benchmarked using `core/tests/ledger_cleanup.rs`; 400 `benchmark_slots`, varying `max_ledger_slots`, varying `delete_range` vs `delete`
* Current setup (400_256_delete_range) has marginally higher latency
* Purging every 10 slots (400_10_delete_range) has lower latency, presumably because maintains smaller sizes (tighter envelope around disk usage)
* The old mechanism (400_10_delete) has lowest latency but higher CPU utilization
* NOTE: this is a small sample set of 400 slots; benchmarks were only run one time each, not run repeatedly; the benchmark can be run with different parameters to model different scenarios

image

[ledger_compaction_bench.xlsx](https://github.com/solana-labs/solana/files/3980736/ledger_compaction_bench.xlsx)

**Comment by sagar-solana** [comment]
@sunnygleason @pgarg66 @carllin just FYI,
I ran 3 testnets and here are my results. (gce 5 node cluster at 10k tx count with 2 clients)

#### Configurations:
1. with the range scan + individual delete followed by a compaction.
2. with DeleteRange followed by a compaction. 
3. with --limit-ledger-size 

Note for the configurations with --limit-ledger-size I ran with `MAX_LEDGER_SLOTS` set to 100 and the purge batch size set to 64. What that means is after the root slot goes past 100, we delete slots 0, then 0-64, then 0-128, then 0-192 and so on... I did this to make the purging a lot more frequent. 

Metrics covering all 3 runs are [here](https://metrics.solana.com:3000/d/testnet-edge/testnet-monitor-edge?orgId=2&from=1576711782558&to=1576715971152&var-datasource=Solana%20Metrics%20(read-only)&var-testnet=testnet-dev-sagar&var-hostid=All). 
Didn't seem to impact our usual metrics at all (@carllin see if something stands out?). 

The amount of time it was taking Ledger Cleanup service to purge the range of slots was slightly lower in the second run compared to the first.
image

The disk usage between both was quite similar (note the 3rd run doesn't report disk usage since the service is inactive)
image

Finally, the amount of time the call to write_batch (purple) was way higher when running the 1st configuration. The 2nd and 3rd configs were indistinguishable. 
image


Based on this, I think I will keep the DeleteRange mechanism over the manual range scans even though our raw benchmarks show that DeleteRange is slightly slower. It seems to not interfere with other parts of our system.

**Comment by sunnygleason** [comment]
@sagar-solana that makes total sense, it's good to know about the cpu/latency tradeoff of the 2 approaches.

**Comment by sagar-solana** [comment]
Yes the benchmarks are still super useful! If anything it shows that we can expand them to catch or run these use cases as well.

**Comment by carllin** [comment]
So using DeleteRange both lowers contention with other WriteBatches and is faster to execute? Makes sense, since it condenses all the individual deletes into one: https://github.com/facebook/rocksdb/wiki/DeleteRange. Not sure why the speedup in WriteBatch is so much greater than the speedup in the actual delete operation though. You would think that they would be comparable (aka the amount of time saved in the delete operation would be the amount of time saved in ccontention for the writebatch operaton)

**Comment by sagar-solana** [comment]
@carllin Yes calling DeleteRange is faster vs calling Delete on individual indexes, just like the docs explain. But space reclamation doesn't occur until we call Compact (in both cases). 
So what Sunny and I found is that even though DeleteRange is much faster to write the tombstone, when compaction occurs it ends up taking about ~2x as long to run when it encounters a Range tombstone as opposed to a bunch of little index tombstones. 

I ran the 3 tests above to see if what the benchmarks were showing us translated into testnet. It appears that it does not. 
Compaction over Delete Range tombstones ends up reducing write stalls dramatically(This is why write batch time is so much lower) and seems to take about as long as the older Index based Delete(run 1). 
In the end it seemed like neither configuration impacted tps or stability at all. But I stuck with the slower(according to tests and benchmarks) DeleteRange because it didn't result in big write stalls in window service. Makes sense?

**Comment by carllin** [comment]
@sagar-solana understood, but not sure why one would dramatically decrease write stalls over the other. Was looking at this: https://github.com/facebook/rocksdb/wiki/DeleteRange-Implementation#compaction, and maybe its because flushes to the lower levels are really fast?

**Comment by sagar-solana** [comment]
Yeah I'm not sure why one stalls while the other doesn't. It seems like it should have had the same cost but something in their implementation of ranged tombstones allows. It to not stall writes as much.

**Pull request closed without merging**
