### PR TITLE
fix:  rename wasm_bindgen init function to avoid collision with Rust based frontend framework

### PR DESCRIPTION
**Pull request by russellwmy**
#### Problem
When Solana SDK works with frontend framework like: yew.rs. It throws error on `wasm_bindgen` init function. 
Screenshot 2022-03-10 at 6 59 39 PM

#### Summary of Changes
Added a feature flag to disable internal `wasm_bindgen` init call.

Fixes https://github.com/solana-labs/solana/issues/23583

### CODE REVIEW

**Comment by mvines** [comment]
I don't love the idea of a new feature.  Renaming `init()` to something less generic seems ok though.  Perhaps `solana_program_init()`.

**Comment by russellwmy** [comment]
@mvines Good idea! I modified the function name to `solana_program_init`. Please review.

**Comment by mvines** [comment]
lgtm, but could I convince you to update the following tests with the new name as well?  CI will (should!) fail eventually as well
```
./sdk/tests/keypair.mjs
./sdk/tests/transaction.mjs
./sdk/program/tests/pubkey.mjs
./sdk/program/tests/hash.mjs
```

**Review by mvines — APPROVED** [review]
lgtm once CI is green, thanks for the fix!

**Pull request merged**
