### PR TITLE
Fetch blobs instead of packets in the RPU

### PR DESCRIPTION
**Pull request by garious**
Recommended approach by @aeyakovenko. TPU's FetchStage should be the
only special case.

### CODE REVIEW

**Comment by garious** [comment]
@rob-solana, is it possible that `test_leader_restart_validator_start_from_old_ledger` would fail due to this change? I'm not able to reproduce the failure locally.

**Comment by rob-solana** [comment]
I don't see how this change would affect those tests.

**Comment by garious** [comment]
Status of this PR: This change consistently breaks the `test_leader_restart_validator_start_from_old_ledger` integration test in (and only in) the perf configuration, @rob-solana and I don't know why, and I have not had time to debug.

@sakridge, this PR is low priority, but you're in best position to glance at the change and guess why it might affect the cuda build. If nothing stands out as obvious, I'll dig deeper. I'm hoping an artifact of fixing this PR will be a cuda/erasure unit test and/or a lower-level restart_validator unit test.

**Comment by garious** [comment]
Closing this under the assumption that we end up deleting the whole RPU instead. @CriesofCarrots, fyi.

**Pull request closed without merging**
