### PR TITLE
Detect vote hash mismatch even at run-sanity.sh

### PR DESCRIPTION
**Pull request by ryoqun**
#### Problem

https://github.com/solana-labs/solana/issues/12670#issuecomment-704134218

#### Summary of Changes

note that this test expected to fail.

### CODE REVIEW

**Comment by sakridge** [comment]
Would it better to have a flag to panic on this case?

**Comment by mvines** [comment]
> Would it better to have a flag to panic on this case?

Flag would be cool.   Plumbing that flag from `solana-validator` into the vote state seems really gnarly though, I don't know how we'd do that nicely

**Comment by sakridge** [comment]
> 
> 
> > Would it better to have a flag to panic on this case?
> 
> Flag would be cool. Plumbing that flag from `solana-validator` into the vote state seems really gnarly though, I don't know how we'd do that nicely

That's true. Plumbing would be a pain. Also security reviews don't like these kinds of flags to turn off checks.

On the other hand, these kind of log checks are kind of brittle and have a habit of being disabled without anyone noticing. Also seems like more of a pain to enable in more test situations. Generally we would always want to panic in this situation unless it's a specifically malicious test case to insert duplicate conflicting blocks into the system.

**Comment by ryoqun** [comment]
> > > Would it better to have a flag to panic on this case?
> > 
> > 
> > Flag would be cool. Plumbing that flag from `solana-validator` into the vote state seems really gnarly though, I don't know how we'd do that nicely
> 
> That's true. Plumbing would be a pain. Also security reviews don't like these kinds of flags to turn off checks.
> 
> On the other hand, these kind of log checks are kind of brittle and have a habit of being disabled without anyone noticing. Also seems like more of a pain to enable in more test situations. Generally we would always want to panic in this situation unless it's a specifically malicious test case to insert duplicate conflicting blocks into the system.

Yeah, I don't like the current state of this. After some thought, I think I'll just add a validator kill-switch if the validator's voted slot hash is mismatched to the supermajority rest of cluster.

This will be like combination of #11927 and #11727, which is done at the snapshot interval.

**Comment by ryoqun** [comment]
@mvines @sakridge (no rush) please take a look at the more proper solution for this in my previous comment.

**Comment by sakridge** [comment]
@ryoqun is there something wrong with this? Can we prioritize enabling this checking?

**Comment by ryoqun** [comment]
@sakridge There is nothing wrong with this. it's just that I couldn't get my hands on it. Currently, I'm focusing on various inflation and staking bugs. I talked about this a bit with @carllin, we can implement this with VoteTracker.

**Comment by sakridge** [comment]
> 
> 
> @sakridge There is nothing wrong with this. it's just that I couldn't get my hands on it. Currently, I'm focusing on various inflation and staking bugs. I talked about this a bit with @carllin, we can implement this with VoteTracker.

Is the builtins part of this change needed for the vote hash mismatch?

**Comment by ryoqun** [comment]
> > @sakridge There is nothing wrong with this. it's just that I couldn't get my hands on it. Currently, I'm focusing on various inflation and staking bugs. I talked about this a bit with @carllin, we can implement this with VoteTracker.
> 
> Is the builtins part of this change needed for the vote hash mismatch?

@sakridge oops, sorry. these was rebase leftover; fixed.

**Pull request closed without merging**
