### PR TITLE
Write & load bank snapshots in fullnode

### LINKED ISSUE #2475: Fullnode startup is slow
#### Problem

Currently, starting a fullnode queries the cluster for the full ledger and replays it.

#### Proposed Solution

The fullnode should first check for a recent ledger state snapshot locally and if unavailable, query another validator for one.

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Node restart is slow if running through all the bank entries from db_ledger.

#### Summary of Changes

Serialize the bank state every so often and write it to a file. Then on startup see if there is a snapshot file and load it. Fallback to db_ledger startup if any errors occur.

Note: had to switch back to std::collections::HashMap/HashSet, hashbrown doesn't serialize.

Fixes #2475

### CODE REVIEW

**Comment by sakridge** [comment]
I tested around 40,000 entries it takes db_ledger ~40 seconds to boot, but about 200-300ms from the snapshot. The snapshot gets to be around 5-8Mb in size, is generated about every 5 seconds and takes 300-500ms to write it.

**Comment by sakridge** [comment]
@rob-solana mentioned I should probably use a writer so that the whole thing doesn't need to be in memory, so I'll see if I can rework for that.

**Comment by garious** [comment]
@sakridge, I added a WIP label here. If either #2279 or #2289 lands, this feature might look very different.  I'm not opposed to landing this before those, but let's make sure we're all on the same page before we do.

**Comment by sakridge** [comment]
I did some more testing, the snapshot got up to about 50MB and took about 30 seconds to make the snapshot, ~99% of it is the serialize time. About 28MB was the last-ids and signatures, and 14MB accounts data. I hesitate to add 30 seconds into replay stage as I saw it get behind the latest head, so more work is necessary.

**Comment by aeyakovenko** [comment]
@sakridge, the idea for AppendVec is that the data can be mmapped directly.

**Pull request closed without merging**
