### PR TITLE
Move programs out of src/

### LINKED ISSUE #1928: Runtime depends on legacy programs
#### Problem

Runtime can't be moved to the SDK without pulling the "legacy" programs along with it.

#### Proposed Solution

Make `execute_transaction()` a method of a new `Runtime` object so that it can host legacy programs in a state variable. Add a `register_legacy_program()` method and use it from the Bank to register the legacy programs.

### PR DESCRIPTION
**Pull request by mvines**
This PR moves all programs, except for native_loader, out of `src/` into dynamic native programs under `programs/native/`.  This removes all non-sdk dependencies from `src/runtime.rs`, except for native_loader.

This resulted in a number of files defining the Transaction Instruction format for programs such as `system`, `vote`, `budget` moving into `sdk/`.

This PR is a little rough to review, it may be easier to look at the branch code directly: https://github.com/mvines/solana/tree/sig.  Some good places to look:
* much simplified `process_instruction` in [src/runtime.rs](https://github.com/mvines/solana/blob/sig/src/runtime.rs#L17)
* additional programs added to `add_builtin_programs` in [src/bank.rs](https://github.com/mvines/solana/blob/sig/src/bank.rs#L416)
* new programs under [programs/native](https://github.com/mvines/solana/tree/sig/programs/native), mainly just the same under `src/` but ported to use `KeyedAccounts`
* new program-specific files under [sdk/src/](https://github.com/mvines/solana/tree/sig/sdk/src)

Work in progress items:
* [x] `ci/test-stable.sh` under macOS doesn't pass.  Looks to be fun dynlib issues.  Linux is ok
* [x] Need to run some manual integration tests (eg, run tic-tac-toe on this PR)
* [x] rebase

Fixes #1928

### CODE REVIEW

**Comment by mvines** [comment]
hey!

**Comment by mvines** [comment]
@garious - requesting review with a couple WIP items still pending as I expect the fixes for them to be minor and shouldn't affect the overall structure of this PR

**Comment by garious** [comment]
This looks good to go in as-is. I especially like how runtime.rs has no legacy programs. It's amazing how many unfinished initiatives it exposes:

* bank adds built-in programs. If those were moved out, bank could theoretically be moved to the SDK, which would allow for LastIdNotFound, AccountInUse and DuplicateSignature unit testing
* Structs called Program that are actually State (I renamed BudgetState to BudgetProgram a few weeks ago under the "When in Rome" rule. It's cringeworthy.)
* That every Program would more appropriately be called Interpreter
* That ProgramError contains errors that'd only be produced by the runtime
* That Budget has a bunch of commented out voting code

**Comment by mvines** [comment]
> That Budget has a bunch of commented out voting code
😳 fixed!

**Comment by mvines** [comment]
(I added numbers to https://github.com/solana-labs/solana/pull/2003#issuecomment-444530844 for easy reference here)

1. No issue filed for this, I think that'll happen naturally when we are motivated to do so
2. Seems like you're on this one.
3. Same as 2
4. Added to #1993 
5. Opps, forgot to remove that stuff.

**Comment by mvines** [comment]
brace yourself 💥

**Pull request merged**
