### PR TITLE
fix to prevent minority overcommit attack

### LINKED ISSUE #7087: Fork choice rule can be tricked by a minority that overcommits to a fork.
#### Problem

Fork choice rule can be tricked by a minority that overcommits to a fork.

from @carllin:
somebody with 5% of the stake, will roughly in expectatoin be scheduled for 4 consecutve  slots in the schedule oncce every 3 days
so 16 consecutive slots
this 5% then aggressively votes on those slots, then withholds them from the rest of the 95% of the network
the rest of the network skiips those 16 slots, expring the last 4 votes on ther towers
then the 95% will ccontnue, buildng up another 16 votes on top oft hat tower, so net gain of 12 votes
and then the 5% broadcasts the 16 votes they had bult on top of ther tower, wth a net gaini of 16 votes
I think n this ccase . the 95% s now locked out for 2^16 . slots
so 7 hours

#### Proposed Solution

Fork choice rule should ignore forks that have a minority committed beyond the threshold.

tag: @carllin

### PR DESCRIPTION
**Pull request by ParthDesai**
#### Problem
Fork choice rule can be tricked by a minority that overcommits to a fork.

#### Summary of Changes
- Calculate top stakes for every bank.
- Modify fork selection algo to push all minority stake bank to bottom

Fixes #7087

#### Remaining:
- [ ] Rename `collect_vote_lockouts` to better suite its functionality now

cc: @aeyakovenko @carllin

### CODE REVIEW

**Comment by aeyakovenko** [comment]
Why can’t you use the StakeLockouts structure as is?  I think you only need to check if there is a minority at threshold + 1 without a supermajority at < threshold + 1

**Comment by ParthDesai** [comment]
@aeyakovenko That wouldn't exactly solve the problem.

Consider two forks competing to be chosen best forks: 

Fork 1 top stakes:
33 33 33 33 33 33 33 33

Fork 2 top stakes:
60 60 60 60 60 60 60 33

Both of these, would be qualified as attack as per your suggested design, Which would again allow attacker to manipulate selection algorithm to choose Fork1, but in reality Fork2 is more likely to be genuine fork. 

So, reason behind my design is to make distinction between these two clear, and prioritise fork2 over fork1.

**Comment by aeyakovenko** [comment]
Why would fork2 not have the 67%?

**Comment by ParthDesai** [comment]
> Why would fork2 not have the 67%? You need to do analysis with the `malicious + unavailable group < 33%`. So fork2 would be at supermajority.

@aeyakovenko Why would we want to assume `malicious + unavailable group < 33%`? Should we allow an attack if let's say in above case the 7% is unavailable?

**Comment by ParthDesai** [comment]
> > Why would fork2 not have the 67%? You need to do analysis with the `malicious + unavailable group < 33%`. So fork2 would be at supermajority.
> 
> @aeyakovenko What's reasoning behind our assumption of `malicious + unavailable group < 33%`? Should we allow an attack if let's say in above case the 7% is unavailable?

@aeyakovenko

**Comment by aeyakovenko** [comment]
@ParthDesai thats is just how fault tolerance is defined 2 + 1f.  A fault is a node that is either down, or misbehaving in some way.

**Comment by ParthDesai** [comment]
@aeyakovenko Hmm. I think what we could do here is: 

Collect top `min((threshold + 1), votes.length)` stakes for a slot.
Check if last `min(threshold, votes.length)` are at super majority.
Flag the slot as majority slot, if above statement is true.

Now, slots will be sorted in following way: 
First based on majority flag,
then based on fork_weight
then on slot id (descending)

**Comment by aeyakovenko** [comment]
@ParthDesai we could just cap the weight of the minority to be no more than the threshold until there is a supermajority above the threshold

**Comment by ParthDesai** [comment]
> @ParthDesai we could just cap the weight of the minority to be no more than the threshold until there is a supermajority above the threshold

@aeyakovenko This wouldn't work if `vote.length == threshold`

**Comment by ParthDesai** [comment]
> @ParthDesai we could just cap the weight of the minority to be no more than the threshold until there is a supermajority above the threshold

@aeyakovenko hmm.  this works out. But, will require more changes to existing lockout calculation algorithm. Let me give it a try.

**Comment by ParthDesai** [comment]
> > @ParthDesai we could just cap the weight of the minority to be no more than the threshold until there is a supermajority above the threshold
> 
> @aeyakovenko hmm. this works out. But, will require more changes to existing lockout calculation algorithm. Let me give it a try.

@aeyakovenko Capping the weight till threshold top stakes won't work. For example let's say threshold=8, and minority was scheduled for 11 and 12 slots:

vote state of minority fork is:
votes: 7 8 9 10 11 12 (Stake: 67)
Weight = 67*(2^6 - 2) = 4154

vote state of minority fork is:
votes: 7 8 9 13 14 (Stake: 33)
Weight = 33*(2^7 -2) = 4158

Alternatively, what we could do is, determine votes added in that slot, and if only minority votes are added, we can disregard that slot in fork_weight calculation. 

wdyt?

**Comment by aeyakovenko** [comment]
@ParthDesai i think the duplicate block/single round validation is going to make this redundant. Tag @carllin

**Pull request closed without merging**
