### PR TITLE
Add SPL Token 2022 to the list of known token ids

### PR DESCRIPTION
**Pull request by mvines**
There's a lot more to do wrt. integrating Token 2022 into the JSON RPC methods, this is just the tip of the spear.

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Yoink!

**Comment by CriesofCarrots** [comment]
This is step 1 of token-2022 rpc support, enabling RPC handling for token-2022 basic features (ie. those that are the same as spl-token v3.2):
- Instruction parsing
- Account decoding
- Token-specific RPC endpoints

Examples below

**Comment by CriesofCarrots** [comment]
Example 1, `getTokenAccountsByOwner`, and json-parsing of accounts for token-2022:

```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getTokenAccountsByOwner","params":["6J5DvqR4XX8zwMNG3XUf7c4ELYNHcyyPEJK9JjZPqfhJ",{"programId":"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"}, {"encoding":"jsonParsed"}]}' 127.0.0.1:8899 
{
  "jsonrpc": "2.0",
  "result": {
    "context": {
      "slot": 277
    },
    "value": [
      {
        "account": {
          "data": {
            "parsed": {
              "info": {
                "isNative": false,
                "mint": "Gpk8zJjpP3UhDo1QAhFQmnU3trL2iZxnZ6n75iLDVFdQ",
                "owner": "6J5DvqR4XX8zwMNG3XUf7c4ELYNHcyyPEJK9JjZPqfhJ",
                "state": "initialized",
                "tokenAmount": {
                  "amount": "0",
                  "decimals": 9,
                  "uiAmount": 0,
                  "uiAmountString": "0"
                }
              },
              "type": "account"
            },
            "program": "spl-token",
            "space": 165
          },
          "executable": false,
          "lamports": 2039280,
          "owner": "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
          "rentEpoch": 0
        },
        "pubkey": "7sgyaFEYF9iUpw8uvJShdAa4PPtKnkCJ77EJHZQKHnZo"
      }
    ]
  },
  "id": 1
}
```

**Comment by CriesofCarrots** [comment]
Example 2, json-parsing of token-2022 instructions:

```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getTransaction","params":["2wzhcJTeMuQ2FkYwuizTb6CkiDqKtqFMRUSTJxJyXaFHQZaMNJRFek1i1A3YLyxNXNzcx6fq9snJurReo33z6qYj",{"encoding":"jsonParsed","commitment":"confirmed"}]}' 127.0.0.1:8899
{
  "jsonrpc": "2.0",
  "result": {
    "blockTime": 1650404679,
    "meta": {
      "err": null,
      "fee": 10000,
      "innerInstructions": [],
      "loadedAddresses": {
        "readonly": [],
        "writable": []
      },
      "logMessages": [
        "Program 11111111111111111111111111111111 invoke [1]",
        "Program 11111111111111111111111111111111 success",
        "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb invoke [1]",
        "Program log: Instruction: InitializeAccount",
        "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb consumed 5142 of 1400000 compute units",
        "Program TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb success"
      ],
      "postBalances": [
        499999999992958200,
        2039280,
        1,
        1009200,
        1,
        1461600
      ],
      "postTokenBalances": [
        {
          "accountIndex": 1,
          "mint": "Gpk8zJjpP3UhDo1QAhFQmnU3trL2iZxnZ6n75iLDVFdQ",
          "owner": "6J5DvqR4XX8zwMNG3XUf7c4ELYNHcyyPEJK9JjZPqfhJ",
          "uiTokenAmount": {
            "amount": "0",
            "decimals": 9,
            "uiAmount": null,
            "uiAmountString": "0"
          }
        }
      ],
      "preBalances": [
        499999999995007500,
        0,
        1,
        1009200,
        1,
        1461600
      ],
      "preTokenBalances": [],
      "returnData": null,
      "rewards": [],
      "status": {
        "Ok": null
      }
    },
    "slot": 95,
    "transaction": {
      "message": {
        "accountKeys": [
          {
            "pubkey": "6J5DvqR4XX8zwMNG3XUf7c4ELYNHcyyPEJK9JjZPqfhJ",
            "signer": true,
            "writable": true
          },
          {
            "pubkey": "7sgyaFEYF9iUpw8uvJShdAa4PPtKnkCJ77EJHZQKHnZo",
            "signer": true,
            "writable": true
          },
          {
            "pubkey": "11111111111111111111111111111111",
            "signer": false,
            "writable": false
          },
          {
            "pubkey": "SysvarRent111111111111111111111111111111111",
            "signer": false,
            "writable": false
          },
          {
            "pubkey": "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
            "signer": false,
            "writable": false
          },
          {
            "pubkey": "Gpk8zJjpP3UhDo1QAhFQmnU3trL2iZxnZ6n75iLDVFdQ",
            "signer": false,
            "writable": false
          }
        ],
        "addressTableLookups": null,
        "instructions": [
          {
            "parsed": {
              "info": {
                "lamports": 2039280,
                "newAccount": "7sgyaFEYF9iUpw8uvJShdAa4PPtKnkCJ77EJHZQKHnZo",
                "owner": "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
                "source": "6J5DvqR4XX8zwMNG3XUf7c4ELYNHcyyPEJK9JjZPqfhJ",
                "space": 165
              },
              "type": "createAccount"
            },
            "program": "system",
            "programId": "11111111111111111111111111111111"
          },
          {
            "parsed": {
              "info": {
                "account": "7sgyaFEYF9iUpw8uvJShdAa4PPtKnkCJ77EJHZQKHnZo",
                "mint": "Gpk8zJjpP3UhDo1QAhFQmnU3trL2iZxnZ6n75iLDVFdQ",
                "owner": "6J5DvqR4XX8zwMNG3XUf7c4ELYNHcyyPEJK9JjZPqfhJ",
                "rentSysvar": "SysvarRent111111111111111111111111111111111"
              },
              "type": "initializeAccount"
            },
            "program": "spl-token",
            "programId": "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
          }
        ],
        "recentBlockhash": "2YNbNK1F8Ek6kL3Mh8yV4HeDX34XZqfgqWusoGqhw9Dn"
      },
      "signatures": [
        "2wzhcJTeMuQ2FkYwuizTb6CkiDqKtqFMRUSTJxJyXaFHQZaMNJRFek1i1A3YLyxNXNzcx6fq9snJurReo33z6qYj",
        "2swpagv9Eqfh86Ji7kv8rcfKLqiqriHC91axnbW1FZuouWd9x5haYrm1icQr845mFd4XXWw1idjo4L88AjJGycSd"
      ]
    }
  },
  "id": 1
}
```

**Comment by CriesofCarrots** [comment]
Example 3, `getTokenAccountBalance` of a token-22 account:

```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getTokenAccountBalance","params":["7sgyaFEYF9iUpw8uvJShdAa4PPtKnkCJ77EJHZQKHnZo"]}' 127.0.0.1:8899
{
  "jsonrpc": "2.0",
  "result": {
    "context": {
      "slot": 424
    },
    "value": {
      "amount": "0",
      "decimals": 9,
      "uiAmount": 0,
      "uiAmountString": "0"
    }
  },
  "id": 1
}
```

**Review by joncinque — APPROVED** [review]
Thanks for updating all these tests!  It'll be much easier to debug and improve in the future

**Pull request merged**
