### PR TITLE
Add epoch_rewards syscalls

### PR DESCRIPTION
**Pull request by HaoranYi**
#### Problem
Implementing solana-foundation/solana-improvement-documents#15 (comment) in pieces.

depends on 

https://github.com/solana-labs/solana/pull/32155

#### Summary of Changes

Add epoch_rewards syscalls

Fixes #

### CODE REVIEW

**Comment by HaoranYi** [comment]
> This PR will probably need a review from the runtime folks.

yeah. Once all the dependency PRs merged, we can rebase, make this one ready, and invite runtime folks for reviewing.

**Comment by alessandrod** [comment]
> But this file doesn't appear to have been touched in over a year, and doesn't include the new GetLastRestartSlot sysvar, so maybe it's not used anymore?

Hmm that looks like the right file, but it looks like it might have started bitrotting since the rename from bpf to sbf was made. And it looks like https://github.com/solana-labs/solana/pull/31957 added a program-test here https://github.com/solana-labs/solana/pull/31957/files#diff-0938dd00a3a7be5ef0b29fa1ddd966f4e9faac99e21c9bf5a14df2383d89f09c.

We have recently (last week) started being a bit more strict about not having programs/sbf tests, because ultimately those are the most important kind of tests from a runtime perspective and current coverage isn't great. @HaoranYi I'd really appreciate if you could add a test in `programs/sbf/rust/sysvar/src/lib.rs`. Then to run it you need to:

```
cd programs/sbf/rust/sysvar
cargo test --features test-bpf
```

Those tests currently aren't running as part of CI, I'll fix that part.

**Comment by HaoranYi** [comment]
> > But this file doesn't appear to have been touched in over a year, and doesn't include the new GetLastRestartSlot sysvar, so maybe it's not used anymore?
> 
> Hmm that looks like the right file, but it looks like it might have started bitrotting since the rename from bpf to sbf was made. And it looks like #31957 added a program-test here https://github.com/solana-labs/solana/pull/31957/files#diff-0938dd00a3a7be5ef0b29fa1ddd966f4e9faac99e21c9bf5a14df2383d89f09c.
> 
> We have recently (last week) started being a bit more strict about not having programs/sbf tests, because ultimately those are the most important kind of tests from a runtime perspective and current coverage isn't great. @HaoranYi I'd really appreciate if you could add a test in `programs/sbf/rust/sysvar/src/lib.rs`. Then to run it you need to:
> 
> ```
> cd programs/sbf/rust/sysvar
> cargo test --features test-bpf
> ```
> 
> Those tests currently aren't running as part of CI, I'll fix that part.

Yeah. Added.

**Comment by HaoranYi** [comment]
@alessandrod @brooksprumo Can you please review again? Thanks!

**Comment by HaoranYi** [comment]
@alessandrod did you get a chance to review this PR again? Thanks!

**Review by alessandrod — APPROVED** [review]

**Comment by Lichtso** [comment]
There seems to be a typo in "sol_get_epoch_rewrds_sysvar" [here](https://github.com/HaoranYi/solana/blob/48cf459a6404300fe688dc83e1b1a39d7fc045bc/programs/bpf_loader/src/syscalls/mod.rs#L280).

**Comment by HaoranYi** [comment]
https://github.com/solana-labs/solana/pull/32706

**Comment by t-nelson** [comment]
i'm seeing `test_sysvars` fail since this pr was merged, both in master locally and in ci on https://github.com/solana-labs/solana/pull/31640. the commit immediately before passes fine.

running (as per ci) with
```bash
cd programs/sbf/rust/sysvar
cargo run --manifest-path ../../../../sdk/cargo-test-sbf/Cargo.toml  -- --sbf-sdk ../../../../sdk/sbf test_sysvars
```

error is
```
thread 'test_sysvars' panicked at 'called `Result::unwrap()` on an `Err` value: TransactionError(InstructionError(0, ProgramFailedToComplete))', rust/sysvar/tests/lib.rs:54:57
```

full failure output in the aforementioned pr at https://buildkite.com/solana-labs/solana/builds/100062#0189dfb9-241b-4f80-a417-534adb0e1266/616-4138

i'm assuming there's some environment-dependent thing going on, being as this landed like 6wks ago?

cc/ @HaoranYi @alessandrod

**Comment by HaoranYi** [comment]
> i'm seeing `test_sysvars` fail since this pr was merged, both in master locally and in ci on #31640. the commit immediately before passes fine.
> 
> running (as per ci) with
> 
> ```shell
> cd programs/sbf/rust/sysvar
> cargo run --manifest-path ../../../../sdk/cargo-test-sbf/Cargo.toml  -- --sbf-sdk ../../../../sdk/sbf test_sysvars
> ```
> 
> error is
> 
> ```
> thread 'test_sysvars' panicked at 'called `Result::unwrap()` on an `Err` value: TransactionError(InstructionError(0, ProgramFailedToComplete))', rust/sysvar/tests/lib.rs:54:57
> ```
> 
> somehow the instruction processor _returns_ from
> 
> https://github.com/solana-labs/solana/blob/d26e3ff22bb5024793a8a03ad3303723cd390c66/programs/sbf/rust/sysvar/src/lib.rs#L137
> 
> despite there being no `?` on the statement 🤷‍♂️
> full failure output in the aforementioned pr at https://buildkite.com/solana-labs/solana/builds/100062#0189dfb9-241b-4f80-a417-534adb0e1266/616-4138
> 
> i'm assuming there's some environment-dependent thing going on, being as this landed like 6wks ago?
> 
> cc/ @HaoranYi @alessandrod

yeah. I will take a look.

**Comment by HaoranYi** [comment]
https://github.com/solana-labs/solana/pull/32803 should fix the tests.

**Pull request merged**
