### PR TITLE
Client fixes, poll for unique last id and cache clients

### PR DESCRIPTION
**Pull request by sakridge**
So we don't keep running up the port range

### CODE REVIEW

**Comment by garious** [comment]
Cool, but this makes it clear that we no longer have a client demo. It's a set of clients, working their hardest to beat up on fullnode. Can you document that somewhere? In the readme and/or the client-demo module documentation. We should consider renaming the module to make space for a far simpler client demo.  `multiclient-demo.rs`?

**Comment by garious** [comment]
Can you rebase on #435 after it goes in? It fixes 1 of 2 CI problems, and the 2nd is easy to spot/ignore.

**Comment by sakridge** [comment]
That has been the case for a while that we use multiple threads. User can pass -t to just get one thread.

**Comment by sakridge** [comment]
and yes, will rebase

**Comment by garious** [comment]
Ready for rebase

**Comment by garious** [comment]
@sakridge, rebase to run the latest CI, which is now quick and stable.

**Comment by garious** [comment]
Merged in #440

**Pull request closed without merging**
