### PR TITLE
Fix plumtree link

### PR DESCRIPTION
**Pull request by danpaul000**
#### Problem
A broken link to a third party site is causing the docs CI to fail.

#### Summary of Changes
Fix it, or should it be removed?

### CODE REVIEW

**Comment by danpaul000** [comment]
Greg, this was last touched in https://github.com/solana-labs/solana/commit/3357cebcdbb10f2f3afe1d871ec6756bbfb283f7

Should third party links like this be maintained, or removed?  Also, I can't tell if the working link is pointing to the same file as the original (filename is the same), having no context for what the original link pointed to.

**Comment by garious** [comment]
That's a valuable link. It explains the foundations for the protocol. Please try to track down where it moved. @aeyakovenko posted it originally.

**Comment by danpaul000** [comment]
@garious I am pretty sure the fixed link in my commit is correct.  The URL path just has some header dirs nowadays.  Does the content it links to look correct?

**Comment by garious** [comment]
I don't recall the original content. Happy to assume you got it right.

**Comment by danpaul000** [comment]
Confirmed with @aeyakovenko that the new link is good.

**Pull request merged**
