### PR TITLE
202  rust refactor

### PR DESCRIPTION
**Pull request by rlkelly**
pretty minor but figured i'd PR anyways.

### CODE REVIEW

**Comment by garious** [comment]
buildkite

**Comment by garious** [comment]
`git pull --rebase upstream master` please. And while you're in crdt, can you fix Anatoly's `CrdtToSmall` typo as well? That should be `CrdtTooSmall`.

**Comment by rlkelly** [comment]
all set 👍

**Comment by garious** [comment]
Thanks @rlkelly!!

**Pull request merged**
