### PR TITLE
Format the world

### PR DESCRIPTION
**Pull request by fee1-dead**
#### Problem

The project does not currently have a consistent style for imports.

#### Summary of Changes

This PR uses options in rustfmt that are currently unstable to enforce how imports are grouped. Merge all imports into one statement. The `rustfmt.toml` config is not kept as the options are unstable.

Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
I'd like to continue migrating the code base to the single `use { ... }` style, can rustfmt do that for us?

**Comment by fee1-dead** [comment]
Yes, theres `imports_granularity = "One"` https://rust-lang.github.io/rustfmt/?version=master&search=#One%5C%3A

**Comment by mvines** [comment]
heh that's cool.  I never bothered to investigate the rustfmt config options, there's a lot more there than I was expecting!

**Comment by fee1-dead** [comment]
I won't argue against your choice, but I am more comfortable with the `StdExternalCrate` group and `Module` granularity styles as those are what `rustc` uses.

**Comment by mvines** [comment]
I think this PR will need to wait until those options make it to the stable channel unfortunately.  I don't want to require everybody use unstable rustfmt

**Comment by fee1-dead** [comment]
> I think this PR will need to wait until those options make it to the stable channel unfortunately. I don't want to require everybody use unstable rustfmt

In that case, I will remove `rustfmt.toml` and keep the formatting changes.

**Comment by mvines** [comment]
Looks like there are now some conflicts here (not surprising).  I'll help usher this work in via https://github.com/solana-labs/solana/pull/21592

**Comment by mvines** [comment]
Thank you for teaching us a new rustfmt trick!

**Pull request closed without merging**
