### PR TITLE
parallel storage -> accounts folder

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem
When loading from a snapshot, mem-mapping and creating appendvecs is done in serial right now.
#### Summary of Changes
Do it in parallel while nothing else is going on.
Fixes #

### CODE REVIEW

**Comment by jeffwashington** [comment]
lemond, 200k slots, 147M accounts:
master: 2:17 (m:s)
this pr: 0:21 (m:s)
```
[2021-06-15T04:32:24.228611443Z INFO  solana_runtime::snapshot_utils] Loading bank from /home/jwash/solana/360M/snapshot/tmp-snapshot-qtiGBK/snapshots/752662/752662
[2021-06-15T04:32:34.298115619Z INFO  solana_runtime::serde_snapshot] 411182 slots remaining...
[2021-06-15T04:32:44.298632079Z INFO  solana_runtime::serde_snapshot] 356662 slots remaining...
[2021-06-15T04:32:54.298631553Z INFO  solana_runtime::serde_snapshot] 305505 slots remaining...
[2021-06-15T04:33:04.299034671Z INFO  solana_runtime::serde_snapshot] 259523 slots remaining...
[2021-06-15T04:33:14.299236024Z INFO  solana_runtime::serde_snapshot] 218355 slots remaining...
[2021-06-15T04:33:24.299765230Z INFO  solana_runtime::serde_snapshot] 180469 slots remaining...
[2021-06-15T04:33:34.299948501Z INFO  solana_runtime::serde_snapshot] 146027 slots remaining...
[2021-06-15T04:33:44.300336933Z INFO  solana_runtime::serde_snapshot] 115671 slots remaining...
[2021-06-15T04:33:54.300758513Z INFO  solana_runtime::serde_snapshot] 88405 slots remaining...
[2021-06-15T04:34:04.301279855Z INFO  solana_runtime::serde_snapshot] 64387 slots remaining...
[2021-06-15T04:34:14.301787104Z INFO  solana_runtime::serde_snapshot] 42937 slots remaining...
[2021-06-15T04:34:24.301952297Z INFO  solana_runtime::serde_snapshot] 24476 slots remaining...
[2021-06-15T04:34:34.302679075Z INFO  solana_runtime::serde_snapshot] 7903 slots remaining...
[2021-06-15T04:34:41.580001199Z INFO  solana_runtime::accounts_db] generating index: 881/200000 slots...

this pr:
[2021-06-15T04:49:04.506948617Z INFO  solana_runtime::snapshot_utils] Loading bank from /home/jwash/solana/360M/snapshot/tmp-snapshot-mY97qo/snapshots/752662/752662
[2021-06-15T04:49:23.509800264Z INFO  solana_runtime::accounts_db] generating index: 886/200000 slots...
```

**Comment by jeffwashington** [comment]
I haven't had much runtime on this yet, but I figured I'd send it your way to see what you think. Really, these 3 stages of unpack, create appendvec, generate_index should be able to be pipelined and done concurrently. We appear to be limited by a single threaded insertion into the btreemap. So, the sooner we start that, the shorter the overall time can be.

**Comment by sakridge** [comment]
> I haven't had much runtime on this yet, but I figured I'd send it your way to see what you think. Really, these 3 stages of unpack, create appendvec, generate_index should be able to be pipelined and done concurrently. We appear to be limited by a single threaded insertion into the btreemap. So, the sooner we start that, the shorter the overall time can be.

Yea it seems reasonable. Definitely agree on the pipelined unpack/append-vec/index-generation and even download if we could split the snapshot pieces smaller as from this comment: https://github.com/solana-labs/solana/issues/17019#issuecomment-834651767

**Review by sakridge — APPROVED** [review]
lgtm

**Pull request merged**
