### PR TITLE
[zk-token-sdk] Add overflow checks on release build

### PR DESCRIPTION
**Pull request by samkim-crypto**
#### Problem
In optimized release builds, overflow checks are disabled by default, which can lead to suppressed overflows and unexpected application behavior.

#### Summary of Changes
Add overflow checks on release build.

Note: Addresses an audit finding by Halborn: HAL-02.

Fixes #

### CODE REVIEW

**Review by joncinque — COMMENTED** [review]
We typically avoid adding overflow checks, like in token, but it's true that there's a lot of unchecked math in the zk token sdk, which might make it palatable here.

Have you retested any of the syscalls / zk proof instructions to see how much worse they perform with this change?

**Comment by samkim-crypto** [comment]
Yeah I now remember actually going through this same process for token-2022 also for Halborn. I dug out an old PR https://github.com/solana-labs/solana-program-library/pull/3588#issuecomment-1246341239.

After looking over the repo, I think the only real place where unchecked math is used in zk-token-sdk are a couple places in range proof, so it seems to make sense to just remove unchecked math altogether there, close this PR, and mark Halborn finding as acceptable.

**Comment by joncinque** [comment]
> so it seems to make sense to just remove unchecked math altogether there, close this PR, and mark Halborn finding as acceptable

That would be amazing! I was worried there was too much unchecked math when I just grep'ed `+`, but that could have been tests

**Comment by willhickey** [comment]
This repository is no longer in use. Please re-open this pull request in the agave repo: https://github.com/anza-xyz/agave

**Pull request closed without merging**
