### PR TITLE
Revert ledger-tool changes, fix master

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
#30352 broke master, crossing with #30755.  Changes in ledger-tool look spurious, so reverting them.

### CODE REVIEW

**Review by lijunwangs — APPROVED** [review]
Looks good

**Comment by CriesofCarrots** [comment]
Will merge early after coverage to unblock master

**Comment by cavemanloverboy** [comment]
I recall [my pr](https://github.com/solana-labs/solana/pull/30352) moving a variable named `exit` further up in the scope, which required a fully qualified `std::process::exit` function call. Not sure how that was circumvented here. will take a look and report back

**Comment by cavemanloverboy** [comment]
I recall [my pr](https://github.com/solana-labs/solana/pull/30352) moving a variable named `exit` further up in the scope, which required a fully qualified `std::process::exit` function call. Not sure how that was circumvented here. will take a look and report back.

**Comment by cavemanloverboy** [comment]
Ah yes, I had made a `new` and `new_with_receiver` method in `GeyserPluginService` which removed the requirement for the admin rpc service + validator exit for the ledger-tool.

**Pull request merged**
