### PR TITLE
short circuit largest_slot

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem
avoid work when finding slot in ancestors
#### Summary of Changes
^
Fixes #

### CODE REVIEW

**Comment by jeffwashington** [comment]
with this short circuit, [it doesn't help to change >= to >](https://github.com/solana-labs/solana/pull/16374)

**Comment by jeffwashington** [comment]
Some tests fail. Here's one bad line:
test_accounts_db_serialize1
rv: Some(1), current_max: 1, slot: 2
So, we find a root at slot 2, but we previously found an ancestor at slot 1 so we tried to skip looking at roots.

**Comment by jeffwashington** [comment]
all 3 failing tests from coverage:

accounts_db::tests::test_accounts_db_serialize1
bank::tests::test_bank_get_account_in_parent_after_squash2
bank::tests::test_purge_empty_accounts

**Comment by jeffwashington** [comment]
@sakridge Here are 3 tests which fail if we find a slot in ancestors but then don't try looking in the roots. I imagine that these tests are producing artificial data which is inconsistent with the way the data behaves in a real running system.

I can work on reworking these tests. Do you think that is valuable?

**Comment by sakridge** [comment]
> @sakridge Here are 3 tests which fail if we find a slot in ancestors but then don't try looking in the roots. I imagine that these tests are producing artificial data which is inconsistent with the way the data behaves in a real running system.
> 
> I can work on reworking these tests. Do you think that is valuable?

Yes, I believe so.

**Comment by jeffwashington** [comment]
This change would result in a change of behavior.

> https://github.com/solana-labs/solana/blob/92f4018b07524ef6a0c44492309bde04205a4b5a/runtime/src/bank.rs#L8139
This request to get an account from bank0 results in ancestors = {(0,0)} and roots = {0, 1}. So, we find the account at slot 0 due to ancestors and then if we don’t check roots, we don’t find the account in slot 1 of roots. So, we return the account as of slot 0. Is it legal to be in this situation? Perhaps if we are calculating hashes in accounts bg service on an older bank?

**Pull request closed without merging**
