### PR TITLE
chore: use sccache

### PR DESCRIPTION
**Pull request by yihau**
related to #26171 

- [x] test sccache works fine in CI/CD pipeline.
- [x] setup sccache to all buildkite agents

sccache config has setup on buildkite-agent server. This PR is only for

- remove old cache mechanism
- trigger sccache in docker container

### CODE REVIEW

**Comment by yihau** [comment]
just tested and the result. target folder is removed by each steps

| build steps \ cache method | cargo-target-cache | scache |
|----------------------------|--------------------|--------|
| build 134303714            |        real	4m20.960s<br>user	112m17.938s<br>sys	5m52.708s            |  real	5m51.370s<br>user	22m52.985s<br>sys	2m25.030s <br><br> Cache hits                            0<br>Cache misses                        922<br>Cache misses (C/C++)                366<br>Cache misses (Rust)                 556 |
| build 134303714            |        real	0m0.692s<br>user	0m0.575s<br>sys	0m0.116s            |   real	1m36.539s<br>user	22m34.121s<br>sys	2m23.897s  <br><br>Cache hits                          920<br>Cache hits (C/C++)                  366<br>Cache hits (Rust)                   554<br>Cache misses                          2<br>Cache misses (Rust)                   2 |
| build 9723a33d2            |        real	2m20.319s<br>user	46m14.406s<br>sys	1m26.461s         | real	4m2.598s<br>user	21m30.982s<br>sys	2m22.199s <br><br> Cache hits                          864<br>Cache hits (C/C++)                  366<br>Cache hits (Rust)                   498<br>Cache misses                         58<br>Cache misses (Rust)                  58|
| build 134303714            |         real	2m16.891s<br>user	44m36.418s<br>sys	1m21.895s           |  real	1m37.054s<br>user	22m25.801s<br>sys	2m23.270s  <br><br> Cache hits                          920<br>Cache hits (C/C++)                  366<br>Cache hits (Rust)                   554<br>Cache misses                          2<br>Cache misses (Rust)                   2|


<details>
  <summary>the test script</summary>

 ```bash
#!/bin/bash

function silent_checkout() {
        git checkout $1 >/dev/null 2>&1
}

function remove_target_and_build_with_target_cache() {
        rm -rf target/

        echo "=> pre command"
        source .buildkite/hooks/pre-command >/dev/null 2>&1
        echo "=> build"
        time cargo +1.60.0 build --release --bins -q
        echo "=> post command"
        source .buildkite/hooks/post-command >/dev/null 2>&1
}

function remove_target_and_build_with_sccache() {
        rm -rf target/

        echo "=> build"
        time RUSTC_WRAPPER=/var/lib/buildkite-agent/.cargo/bin/sccache cargo +1.60.0 build --release --bins -q
}


echo "delete all cache"
rm -rf /var/lib/buildkite-agent/cargo-target-cache/
rm -rf /var/lib/buildkite-agent/.cache/sccache/
rm -rf target/


echo "===== cargo-target-cache ====="

echo "==> checkout 134303714"
silent_checkout 134303714
remove_target_and_build_with_target_cache

echo "==> build again"
remove_target_and_build_with_target_cache

echo "==> checkout "9723a33d2
silent_checkout 9723a33d2
remove_target_and_build_with_target_cache

echo "==> checkout 134303714"
silent_checkout 134303714
remove_target_and_build_with_target_cache


echo "delete all cache"
rm -rf /var/lib/buildkite-agent/cargo-target-cache/
rm -rf /var/lib/buildkite-agent/.cache/sccache/
rm -rf target/


echo "===== sccache ====="

echo "==> checkout 134303714"
silent_checkout 134303714
remove_target_and_build_with_sccache
sccache --stop-server

echo "==> build again"
remove_target_and_build_with_sccache
sccache --stop-server

echo "==> checkout "9723a33d2
silent_checkout 9723a33d2
remove_target_and_build_with_sccache
sccache --stop-server

echo "==> checkout 134303714"
silent_checkout 134303714
remove_target_and_build_with_sccache
sccache --stop-server

 ```
</details>

**Comment by yihau** [comment]
Seems our target cache mechanism saves more time than sccache. I think if we just would like to get rid of cargo-target-cache, the result seems okay. If we really care about the build time, I think we can keep cargo-target-cache but store the cache on cloud storage.

**Comment by yihau** [comment]
do we give it a shot? or I maybe I can try to search another way to improve our cargo-target-cache

**Comment by alessandrod** [comment]
Might be worth trying with the sccache s3 backend? We use that for https://github.com/solana-labs/rust and it seems to work great

**Comment by yihau** [comment]
@alessandrod thank you for pointing it out!
for now I use a private bucket without any policy and use a key from a restricted user.

**Pull request merged**
