### PR TITLE
Naming consistency: snapshot_archives_dir

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

Snapshot names are overloaded, and there are multiple terms that mean the same thing. This is confusing. Here's a list of ones in the codebase that I've found:

```
- snapshot_dir
- snapshots_dir
- snapshot_path
- snapshot_output_dir
- snapshot_package_output_path
- snapshot_archives_dir
```

#### Summary of Changes

For all the ones that are about the directory where snapshot archives are stored, ensure they are `snapshot_archives_dir`. For the ones about the (bank) snapshots directory, set to `snapshots_dir`.

### CODE REVIEW

**Review by CriesofCarrots — COMMENTED** [review]
Wdyt about using `bank_snapshots_dir` instead of `snapshots_dir`? Maybe save some coders a trip to the comments in ` runtime/src/snapshot_config.rs` by making it self-explanatory...?
Otherwise, lgtm

**Comment by brooksprumo** [comment]
> Wdyt about using `bank_snapshots_dir` instead of `snapshots_dir`? Maybe save some coders a trip to the comments in ` runtime/src/snapshot_config.rs` by making it self-explanatory...?
> Otherwise, lgtm

@CriesofCarrots I love that you said this! I think the same thing, and have a PR for that already, just in draft. See PR #19346. I staged it in case the specific naming was an issue, so I can change one or the other more easily.

**Comment by CriesofCarrots** [comment]
> have a PR for that already, just in draft

Aha, I see it now! #19346 has my vote :)

**Comment by mvines** [comment]
> > have a PR for that already, just in draft
> 
> Aha, I see it now! #19346 has my vote :)

Ditto

**Comment by brooksprumo** [comment]
@CriesofCarrots @mvines OK, I'm closing this PR, and have marked PR #19346 as ready for review. Thanks for the input!

**Comment by brooksprumo** [comment]
@CriesofCarrots @mvines OK, I'm closing this PR, and have marked PR #19346 as ready for review. Thanks for the input!

**Pull request closed without merging**
