### PR TITLE
per-program data gathering

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by jeffwashington** [comment]
this approximates what is requested:
`ledger processing timing ExecuteTimings load_us 41005064 execute_us 108458243 store_us 41284818 details ExecuteDetailsTimings per_program_and_instruction {TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA {TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA ExecuteDetailsTimingsInner serialize_us 6358 create_vm_us 58346 execute_us 258212 deserialize_us 139 changed_account_count 134 total_account_count 7041 total_data_size 724550 data_size_changed 12045} Vote111111111111111111111111111111111111111 {Vote111111111111111111111111111111111111111 ExecuteDetailsTimingsInner serialize_us 0 create_vm_us 0 execute_us 0 deserialize_us 0 changed_account_count 0 total_account_count 637854 total_data_size 3868383054 data_size_changed 0} Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo {Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo ExecuteDetailsTimingsInner serialize_us 238 create_vm_us 69179 execute_us 43839 deserialize_us 6 changed_account_count 0 total_account_count 0 total_data_size 0 data_size_changed 0} 9qvG1zUp8xF1Bi4m6UdRNby1BAAuaDrUxSpv4CmRRMjL {9qvG1zUp8xF1Bi4m6UdRNby1BAAuaDrUxSpv4CmRRMjL ExecuteDetailsTimingsInner serialize_us 851 create_vm_us 903 execute_us 15233 deserialize_us 147 changed_account_count 264 total_account_count 363 total_data_size 12531156 data_size_changed 10732546} 11111111111111111111111111111111 {11111111111111111111111111111111 ExecuteDetailsTimingsInner serialize_us 0 create_vm_us 0 execute_us 0 deserialize_us 0 changed_account_count 588 total_account_count 63152 total_data_size 66516 data_size_changed 66516} HpiUjNPuvZyD3W2hf2pXcpFycDBAcxJvum7cXuB3ffUH {HpiUjNPuvZyD3W2hf2pXcpFycDBAcxJvum7cXuB3ffUH ExecuteDetailsTimingsInner serialize_us 10107 create_vm_us 6082 execute_us 71482 deserialize_us 4811 changed_account_count 0 total_account_count 888 total_data_size 31299040 data_size_changed 0} J4zdjSD86JsUqnF1qPfQLiD9hhkCU9fRbUAJp9cFoUJJ {J4zdjSD86JsUqnF1qPfQLiD9hhkCU9fRbUAJp9cFoUJJ ExecuteDetailsTimingsInner serialize_us 11967 create_vm_us 6102 execute_us 27460 deserialize_us 11067 changed_account_count 0 total_account_count 1253 total_data_size 71439258 data_size_changed 0} GrAkKfEpTKQuVHG2Y97Y2FF47y7Q5AHLK94JBy7Y5yv {GrAkKfEpTKQuVHG2Y97Y2FF47y7Q5AHLK94JBy7Y5yv ExecuteDetailsTimingsInner serialize_us 24 create_vm_us 33 execute_us 428 deserialize_us 10 changed_account_count 0 total_account_count 14 total_data_size 164175 data_size_changed 0} EhhTKczWMGQt46ynNeRX1WfeagwwJd7ufHvCDjRxjo5Q {EhhTKczWMGQt46ynNeRX1WfeagwwJd7ufHvCDjRxjo5Q ExecuteDetailsTimingsInner serialize_us 1167 create_vm_us 4497 execute_us 46203 deserialize_us 252 changed_account_count 240 total_account_count 984 total_data_size 12773700 data_size_changed 9758520} SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8 {SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8 ExecuteDetailsTimingsInner serialize_us 292 create_vm_us 225 execute_us 5179 deserialize_us 36 changed_account_count 64 total_account_count 84 total_data_size 2928694 data_size_changed 2601608} 9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin {9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin ExecuteDetailsTimingsInner serialize_us 4377996 create_vm_us 834924 execute_us 4750816 deserialize_us 4010907 changed_account_count 35520 total_account_count 169450 total_data_size 29686199044 data_size_changed 1444260960} EUqojwWA2rd19FZrzeBncJsm38Jm1hEhE3zsmX3bRc2o {EUqojwWA2rd19FZrzeBncJsm38Jm1hEhE3zsmX3bRc2o ExecuteDetailsTimingsInner serialize_us 6893599 create_vm_us 1542634 execute_us 6373965 deserialize_us 7527487 changed_account_count 29144 total_account_count 244666 total_data_size 49170195400 data_size_changed 1185009612} ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL {ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL ExecuteDetailsTimingsInner serialize_us 234 create_vm_us 183 execute_us 3495 deserialize_us 52 changed_account_count 72 total_account_count 90 total_data_size 1465110 data_size_changed 977814} CibzFAJREN88y1YMcVjG9o6HTHYqVkUmqiPmvyjPwMhg {CibzFAJREN88y1YMcVjG9o6HTHYqVkUmqiPmvyjPwMhg ExecuteDetailsTimingsInner serialize_us 786159 create_vm_us 975945 execute_us 35101679 deserialize_us 379231 changed_account_count 357766 total_account_count 536649 total_data_size 14572953556 data_size_changed 11644756088} JBn9VwAiqpizWieotzn6FjEXrBu4fDe2XFjiFqZwp8Am {JBn9VwAiqpizWieotzn6FjEXrBu4fDe2XFjiFqZwp8Am ExecuteDetailsTimingsInner serialize_us 14 create_vm_us 75 execute_us 631 deserialize_us 0 changed_account_count 0 total_account_count 1 total_data_size 3435 data_size_changed 0} RVKd61ztZW9GUwhRbbLoYVRE5Xf1B2tVscKqwZqXgEr {RVKd61ztZW9GUwhRbbLoYVRE5Xf1B2tVscKqwZqXgEr ExecuteDetailsTimingsInner serialize_us 17321 create_vm_us 2039 execute_us 128708 deserialize_us 12099 changed_account_count 1610 total_account_count 2953 total_data_size 269286411 data_size_changed 158614274}}
`

**Comment by sakridge** [comment]
Looks like `CibzFAJREN88y1YMcVjG9o6HTHYqVkUmqiPmvyjPwMhg` execution time seems to be on of the most expensive operations. 
@jackcmay @Lichtso @dmakarov Want to take a look?

| program | load | execute | store | total |
| - | - | - | - | - |
| all | 41 | 108 | 41 | 190 |
| serum v1 | 4 | 4 | 4 | 12 |
| serum v2 | 6 | 6 | 7 | 19 |
| Cibz | .8 | 35 | .4 | 36 |

**Comment by sakridge** [comment]
@jeffwashington do you mind re-capturing the metrics with the instruction count and also with `--bpf-jit` flag enabled?

**Comment by jeffwashington** [comment]
> @jeffwashington do you mind re-capturing the metrics with the instruction count and also with `--bpf-jit` flag enabled?

without --bpf-jit
https://docs.google.com/spreadsheets/d/1Kkna-mNNS8OCcsMouKPUjJBqiAINTW4nCZiSp_bd1bY/edit?usp=sharing

**Pull request closed without merging**
