### PR TITLE
uses structural sharing for stake-delegations hash-map

### PR DESCRIPTION
**Pull request by behzadnouri**
#### Problem
StakeDelegations is using Arc to implement copy-on-write semantics:
https://github.com/solana-labs/solana/blob/58c0db970/runtime/src/stake_delegations.rs#L14-L16

However a single delegation change will still clone the entire hash-map,
resulting in excessive memory use as observed in:
https://github.com/solana-labs/solana/issues/23061#issuecomment-1063444072

#### Summary of Changes

This commit instead uses immutable hash-map implementing structural
sharing:
> which means that if two data structures are mostly copies of each
> other, most of the memory they take up will be shared between them.
https://docs.rs/im/latest/im/

### CODE REVIEW

**Comment by behzadnouri** [comment]
@pgarg66 testing shows big improvement from the baseline in terms of memory use.
https://github.com/solana-labs/solana/issues/23061#issuecomment-1064700542

Also performance wise, I did some testing on mainnet and before/after metrics are inline.

**Comment by pgarg66** [comment]
This PR reduced the RAM usage significantly. The node (that's not making roots) is staying up for about 8 hours, compared to ~30 minutes.

I am re-running the test with the updated PR, as the past runs were with the first commit in the PR.

**Review by sakridge — APPROVED** [review]
cool! lgtm

**Review by pgarg66 — APPROVED** [review]
Re-ran the PR on the test node. Looks good.

**Comment by t-nelson** [comment]
@jstarry do we have any benches for the stakes cache?  The `im` types are cited to be slower than their `std` counterparts, with `ImHashMap` being the notable exception and allegedly on par with `HashMap`

**Comment by jstarry** [comment]
> @jstarry do we have any benches for the stakes cache?  The `im` types are cited to be slower than their `std` counterparts, with `ImHashMap` being the notable exception and allegedly on par with `HashMap`

Surprisingly no, thought I had written some

**Pull request merged**
