### PR TITLE
Use Ipv4Addr::{LOCALHOST, UNSPECIFIED} constants

### PR DESCRIPTION
**Pull request by kevinji**
#### Problem
No problem, just some code cleanup.

#### Summary of Changes
Use the `Ipv4Addr::{LOCALHOST, UNSPECIFIED}` constants instead of directly using `127.0.0.1` and `0.0.0.0`.

### CODE REVIEW

**Review by mvines — APPROVED** [review]
thanks, much nicer!

**Comment by steviez** [comment]
Agreed with mvines - use of the constant is great so thank you!

Not to punish a good deed with a follow-on request, but searching the repo, I see several more instances of `[127, 0, 0, 1]` in the following two files:
https://github.com/solana-labs/solana/blob/master/core/src/serve_repair.rs
https://github.com/solana-labs/solana/blob/master/faucet/src/faucet.rs

Any interest in updating those in this PR as well? No worries if not, beggars can't be choosers and we appreciate the contribution either way

**Comment by solana-grimes** [comment]
:scream: New commits were pushed while the automerge label was present.

**Comment by kevinji** [comment]
@steviez Just updated the PR to include changes to those two files.

**Review by steviez — APPROVED** [review]
Awesome, thanks for getting those last couple instances!

**Pull request merged**
