### PR TITLE
RPC: add `err` field to TransactionStatus, alongside the now deprecated `status` field

### PR DESCRIPTION
**Pull request by mvines**
part of #9297
```
$ curl -X POST -H "Content-Type: application/json" -d \
  '{"jsonrpc":"2.0", "id":1, "method":"getSignatureStatuses", "params":[["5Tkitrk8v5PKKkC9HXJRf7AsGwTXFzDqJJun13R1xYHgHAqc7XJRahkh5m7F3TAJH4UBd8GQNLPN6PKai4MHbiAg","Hty5t6NVok6LeiQkxpTz3MdcmxVHreFhKWTAdDkWjEwnY1RihxXUcvi2tukMjoa3gTBR5vDfMD5Skh3rQouUpm4"]]}' http://127.0.0.1:8899 | jq
```
produces:
```json
{
  "jsonrpc": "2.0",
  "result": {
    "context": {
      "slot": 1204
    },
    "value": [
      {
        "confirmations": null,
        "err": {                             <--- NEW!  
          "InstructionError": [
            0,
            "MissingRequiredSignature"
          ]
        },
        "slot": 954,
        "status": {
          "Err": {
            "InstructionError": [
              0,
              "MissingRequiredSignature"
            ]
          }
        }
      },
      {
        "confirmations": null,
        "err": null,                    <--- On success, err is null 
        "slot": 1116,
        "status": {
          "Ok": null
        }
      }
    ]
  },
  "id": 1
}
```

### CODE REVIEW

**Comment by mvines** [comment]
Adding an `err` field to https://github.com/solana-labs/solana/blob/3ae6e0b8ab5d128906b5d5a8296ef8e2fd87fb30/transaction-status/src/lib.rs#L22 will be a little tougher since TransactionStatusMeta is pulled directly from blockstore, so we'll need an `RpcTransactionStatusMeta` that wraps `TransactionStatusMeta` but includes the `err` field (or store the transaction error twice in blockstore)

**Comment by jstarry** [comment]
No comment, looks good to me!

**Comment by jstarry** [comment]
I'll add `RpcTransactionStatusMeta` to this PR

**Comment by mvines** [comment]
@jstarry - fyi I can hack on this in 12 hours or so too

**Pull request merged**
