### PR TITLE
replace `cross-fetch` with `isomorphic-unfetch`

### PR DESCRIPTION
**Pull request by wentokay**
#### Problem

`cross-fetch` injects `XMLHttpRequest` into the bundled outputs of web3.js and this is incompatible with workers, so web3.js cannot run inside web or service workers.

This also means it can't run inside server-based workers like 'cloudflare workers'

As a result it might be incompatible with some of the suggested deployment paths for popular tools like https://remix.run

Finally it is also adding extra unnecessary bloat into browsers where fetch is already supported e.g. `var xhr = new XMLHttpRequest();` in https://cdn.jsdelivr.net/npm/@solana/web3.js@1.43.1/lib/index.browser.esm.js

#### Summary of Changes

replace `cross-fetch` with [`isomorphic-unfetch`](https://github.com/developit/unfetch/tree/master/packages/isomorphic-unfetch) ponyfill

#### Compatibility

|                    | node | browser | worker |
| ------------------ | ---- | ------- | ------ |
| fetch             | ❌   | ✅      | ✅     |
| cross-fetch ([2.8kB](https://bundlephobia.com/package/cross-fetch@3.1.5))       | ✅   | ✅      | ❌     |
| isomorphic-unfetch ([591B](https://bundlephobia.com/package/isomorphic-unfetch@3.1.0)) | ✅   | ✅      | ✅     |

Tested as working for

- `node (commonjs)`
- `node (esmodules)`
- `browser <script type="text/javascript">`
- `browser <script type="module">`
- inside a serviceworker 

by running

`yarn build` && `yarn link` in this PR branch

then

`yarn link @solana/web3.js` & running each of the `package.json` scripts in https://github.com/wentokay/unfetch-test

related:

- #21388
- https://github.com/stytchauth/stytch-node/pull/121
- https://github.com/lquixada/cross-fetch/issues/78

### CODE REVIEW

**Comment by wentokay** [comment]
NB this doesn't update `package-lock.json`, idk which is the preferred lockfile

**Comment by wentokay** [comment]
I was unsure what to do with two lockfiles so I ran both `yarn install` and `npm install` although perhaps this is problematic?

**Comment by t-nelson** [comment]
whoever reviews this, please be vigilant of supply chain attacks.  we don't generally accept this type of change from external contributors

**Comment by steveluscher** [comment]
We’re actually going to eliminate the fetch polyfill entirely and ask that folks using Node older than 17.5 to bring their own polyfill. See #25014.

**Comment by steveluscher** [comment]
For instance, for Remix specifically: https://remix.run/docs/styling/v1/other-api/node

**Comment by steveluscher** [comment]
Thanks for opening this PR though! Super good call out about service workers.

**Pull request closed without merging**
