### PR TITLE
Move dedup into a separate fast stage before sigverify

### PR DESCRIPTION
**Pull request by ckamm**
#### Problem

Dedup is fast, but sigverify is around 25x slower on CPUs.

Dedup and sigverify together were unable to keep up with incoming data during a packet flood. This lead to the inbound queue for SigVerifyStage growing out of control, increasing memory use and the size of the next sigverify work-unit. Eventually sigverify-stage needed to process 70M packets and finished only 60+ seconds later. This stalled the banking stage.

See #24747 for details.

With dedup moved to an earlier stage we should be able to keep up with incoming packets if they are mostly duplicates.

~~If there are too many valid non-duplicate packets, we still run into the same problem...~~

#### Summary of Changes

Moved dedup/~~discard/shrink~~ to the FindPacketSenderStakeStage.

TODO:
- Rename FindPacketSenderStakeStage
- Add benchmarks
- General cleanup and testing
- ~~Actually discard should be moved back into SigVerify. Right now FindPacketSenderStakeStage could produce 10k-packet chunks at a pace that SigVerify can't deal with.~~

@sakridge

### CODE REVIEW

**Comment by KirillLykov** [comment]
Could you provide more details about specific type of requests that can be used to reproduce these spam transactions? In particular, how many unique transactions were among them, what is the type of transaction and if there are valid in terms of signatures, blockhash.

**Comment by ckamm** [comment]
> Could you provide more details about specific type of requests that can be used to reproduce these spam transactions? In particular, how many unique transactions were among them, what is the type of transaction and if there are valid in terms of signatures, blockhash.

The best data I have is this: https://github.com/solana-labs/solana/pull/24747#issuecomment-1111769463, which suggests around 90% duplicates, around 70% valid signatures out of the remainder.

**Comment by sakridge** [comment]
Just want to point out the dos tool which can generate transaction streams into the validator for testing: https://github.com/solana-labs/solana/tree/master/dos

**Comment by sakridge** [comment]
@ckamm want to also try this change to compare with master? https://github.com/solana-labs/solana/pull/24905

**Comment by ckamm** [comment]
> Just want to point out the dos tool which can generate transaction streams into the validator for testing: https://github.com/solana-labs/solana/tree/master/dos

Cool, thanks for the pointer! Is there a trick to getting high volume out of solana-dos? The best I've been getting with `--mode tpu --data-type transaction --valid-signatures --skip-gossip` and three processes is this:

```
with --unique-transactions

[2022-05-02T19:44:07.973525841Z INFO  solana_metrics::metrics] datapoint: find_packet_sender_stake-services_stats refresh_ip_to_stake_time_us=0i apply_sender_stakes_time_us=16466i send_batches_time_us=58i receive_batches_time_ns=172167i dedup_time_us=4884i total_batches=300i total_packets=31724i total_packets_dedup=0i
[2022-05-02T19:44:07.097456069Z INFO  solana_metrics::metrics] datapoint: tpu-verifier recv_batches_us_90pct=2i recv_batches_us_min=0i recv_batches_us_max=7i recv_batches_us_mean=1i verify_batches_pp_us_90pct=80i verify_batches_pp_us_min=40i verify_batches_pp_us_max=156i verify_batches_pp_us_mean=64i batches_90pct=5i batches_min=1i batches_max=7i batches_mean=3i packets_90pct=471i packets_min=5i packets_max=698i packets_mean=234i total_batches=451i total_packets=46998i total_excess_fail=0i total_valid_packets=46998i total_discard_time_us=38i total_verify_time_us=2974510i total_shrink_time_us=249i total_shrinks=0i

->
find_packet_sender_stake: 673ns/packet
sigverify: 63290ns/packet


without --unique_transactions

[2022-05-02T19:51:02.834899080Z INFO  solana_metrics::metrics] datapoint: find_packet_sender_stake-services_stats refresh_ip_to_stake_time_us=0i apply_sender_stakes_time_us=12587i send_batches_time_us=5306i receive_batches_time_ns=204857i dedup_time_us=3794i total_batches=425i total_packets=53730i total_packets_dedup=53727i

->
find_packet_sender_stake: 305ns/packet
```
I.e. there wasn't enough throughput to hit discard.

**Comment by ckamm** [comment]
I'll see if I can make a benchmark that simulates 1M packets/s over a few seconds, with a configurable percentage of duplicates and will then pipe that through both stages to see how it behaves.

**Comment by sanjeevgiri** [comment]
Is there any metric around cpu vs gpu based sigverify times? Could we benefit from making the MAX_SIGVERIFY_BATCH value configurable?

**Comment by ckamm** [comment]
> Is there any metric around cpu vs gpu based sigverify times? Could we benefit from making the MAX_SIGVERIFY_BATCH value configurable?

Yes, it may be sensible for it to be higher when using GPUs. The value will not limit tx/block.

**Comment by ckamm** [comment]
@sakridge I've written that benchmark to simulate high numbers of incoming tx and have not been able to cause the original code to behave improperly or be overwhelmed.

It makes sense, the stable state equation:
```
packets / packets_per_second = 
    10000 * verify_time_per_packet 
    + packets * dedup_time_per_packet
```
has a solution for `packets` as long as dedup isn't overwhelmed (`dedup_time_per_packet * packets_per_second < 1`).

In the test I send 1.5M packets_per_second. The observed number of num_packets per verifier() call is around 280k-300k. I measure verify_time_per_packet = 14us, dedup_time_per_packet = 160ns. 

That suggests to me that splitting out dedup or decreasing MAX_SIGVERIFY_BATCH won't have a large effect. 

So what happened in
```
time          secs between logs  total_packets  recv_batches_us_max
04/26/22 10:05 PM	 3.05	  681064	  4776
04/26/22 10:06 PM	33.10	13485331	 44663
```
(see https://github.com/solana-labs/solana/pull/24747#issuecomment-1113937759) where sigverify switched from mostly-idle to needing 30s to complete? 

Possibly the packet flood made the kernel really busy, causing the validator process to not get scheduled for a bit and also be significantly slower than normally. And then when it got scheduled again, the fetch stage was able to read 13M packets from the socket before sigverify got to work again?

I still think that for these exceptional situations there should be an early out in `streamer::recv_loop()` where there's a configurable number of batches that can possibly be in the queue at the same time. It would never get hit during regular operation and would avoid making everything worse when dedup/sigverify falls behind for outside reasons.

**Comment by KirillLykov** [comment]
> > Just want to point out the dos tool which can generate transaction streams into the validator for testing: https://github.com/solana-labs/solana/tree/master/dos
> 
> Cool, thanks for the pointer! Is there a trick to getting high volume out of solana-dos? The best I've been getting with `--mode tpu --data-type transaction --valid-signatures --skip-gossip` and three processes is this:
> 
> ```
> with --unique-transactions
> 
> [2022-05-02T19:44:07.973525841Z INFO  solana_metrics::metrics] datapoint: find_packet_sender_stake-services_stats refresh_ip_to_stake_time_us=0i apply_sender_stakes_time_us=16466i send_batches_time_us=58i receive_batches_time_ns=172167i dedup_time_us=4884i total_batches=300i total_packets=31724i total_packets_dedup=0i
> [2022-05-02T19:44:07.097456069Z INFO  solana_metrics::metrics] datapoint: tpu-verifier recv_batches_us_90pct=2i recv_batches_us_min=0i recv_batches_us_max=7i recv_batches_us_mean=1i verify_batches_pp_us_90pct=80i verify_batches_pp_us_min=40i verify_batches_pp_us_max=156i verify_batches_pp_us_mean=64i batches_90pct=5i batches_min=1i batches_max=7i batches_mean=3i packets_90pct=471i packets_min=5i packets_max=698i packets_mean=234i total_batches=451i total_packets=46998i total_excess_fail=0i total_valid_packets=46998i total_discard_time_us=38i total_verify_time_us=2974510i total_shrink_time_us=249i total_shrinks=0i
> 
> ->
> find_packet_sender_stake: 673ns/packet
> sigverify: 63290ns/packet
> 
> 
> without --unique_transactions
> 
> [2022-05-02T19:51:02.834899080Z INFO  solana_metrics::metrics] datapoint: find_packet_sender_stake-services_stats refresh_ip_to_stake_time_us=0i apply_sender_stakes_time_us=12587i send_batches_time_us=5306i receive_batches_time_ns=204857i dedup_time_us=3794i total_batches=425i total_packets=53730i total_packets_dedup=53727i
> 
> ->
> find_packet_sender_stake: 305ns/packet
> ```
> 
> I.e. there wasn't enough throughput to hit discard.

This tool is in active development and there are some PRs which are not yet landed (https://github.com/solana-labs/solana/pull/24412). 
The current branch which I'm using to experiment with the tool https://github.com/solana-labs/solana/pull/24930
It should be more potent in terms of rps because it generates some transactions in several threads (unique transactions). Not unique ones were kind of left behind this update, maybe it was wrong but it is easy to fix if any.

**Comment by sakridge** [comment]
Who wants to hookup GPU signing? https://github.com/solana-labs/solana-perf-libs/blob/233c4457fd8d425da99cb3db46b2be8eb8b98997/src/cuda-ecc-ed25519/sign.cu#L76

**Comment by ckamm** [comment]
What are your throughts on moving forward here? I think it could still be good to have dedup happen before FindPacketSenderStakeStage, but it seems less important to me. The important bit is #24961 .

**Comment by ckamm** [comment]
We've fixed what made findpacketsenderstake stage so slow, and now the performance difference between it and dedup doesn't matter enough to move it.

**Pull request closed without merging**
