### PR TITLE
Enable 0rtt

### PR DESCRIPTION
**Pull request by brennanwatt**
#### Problem
TLS handshake for resumed session can require 1 round trip, which costs latency. See #25011 

#### Summary of Changes

- Enable 0rtt quic connections when possible
- Add metrics for tracking connection & 0rtt success

### CODE REVIEW

**Comment by pgarg66** [comment]
Are majority of 0rtt attempts still being. rejected? Or has it been addressed in this PR.

**Comment by brennanwatt** [comment]
@pgarg66 They're still mostly being rejected. Played around with how endpoint's default client config was getting setup, but no breakthroughs yet

**Comment by sakridge** [comment]
Code looks good, just would be good to get some clarity on why it doesn't connect with 0rtt sometimes.

**Comment by pgarg66** [comment]
> @pgarg66 They're still mostly being rejected. Played around with how endpoint's default client config was getting setup, but no breakthroughs yet

Does trying 0rtt and then establishing connection using the full handshake (on 0rtt failure) add latency to the connection setup?

**Comment by brennanwatt** [comment]
> 

I wouldn't expect there to be anything beyond a trivial amount of extra instructions because we're not waiting for anything additional async - just a couple extra lines of inline execution. That said, I'll measure this so we can have some actual data to look at

**Comment by brennanwatt** [comment]
I think I understand what's happening now...

The code in master has a few possibilities:
1. The connection exists in the map, and we're able to successfully re-use it
2. The connection exists in the map, but we fail sending data (likely because of connection timeout), so we create a new connection
3. Connection does not exist in the map, we create new QUIC client and connection

Case 1 does not require any handshake and we immediately grab the cached connection and start sending data.
Case 3 must establish a new connection because we might have never connected before, and even if we did, the endpoint information has been recycled (not we could increase the max map size - currently 1024 entries - to retain more connections)
Case 2 is the one where we could improve things by enabling 0rtt to save one round trip. We have all of the necessary information to resume the connection.

**Comment by pgarg66** [comment]
> I think I understand what's happening now...
> 
> The code in master has a few possibilities:
> 
> 1. The connection exists in the map, and we're able to successfully re-use it
> 2. The connection exists in the map, but we fail sending data (likely because of connection timeout), so we create a new connection
> 3. Connection does not exist in the map, we create new QUIC client and connection
> 
> Case 1 does not require any handshake and we immediately grab the cached connection and start sending data. Case 3 must establish a new connection because we might have never connected before, and even if we did, the endpoint information has been recycled (not we could increase the max map size - currently 1024 entries - to retain more connections) Case 2 is the one where we could improve things by enabling 0rtt to save one round trip. We have all of the necessary information to resume the connection.
> 
> This means we shouldn't bother wasting time trying to make a 0rtt connection in the case where we have no current connection. We should only attempt this when the initial buffer send fails (and hope we can resume the connection without a full handshake)

To handle Case 2, we currently have a `keep_alive_interval` value low enough that it should prevent the connection from timing out. Maybe we can add some metrics and see how many times this case is happening.

**Comment by brennanwatt** [comment]
In single client/validator test net running bench-tps, I'm not seeing any connection timeouts. It's all either re-used connections or newly created connections that don't qualify for 0rtt.

So it seems like our internal policy is already capturing any expected benefits from 0rtt.

**Comment by brennanwatt** [comment]
> > @pgarg66 They're still mostly being rejected. Played around with how endpoint's default client config was getting setup, but no breakthroughs yet
> 
> Does trying 0rtt and then establishing connection using the full handshake (on 0rtt failure) add latency to the connection setup?

In a small sample set, it looks like trying to initiate 0rtt connection is adding ~10% overhead (1ms).

Baseline connection code:
```
[2022-05-09T16:06:41.387232830Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=8316i
[2022-05-09T16:06:41.387882385Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=8125i
[2022-05-09T16:06:41.387897439Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=8624i
[2022-05-09T16:06:41.387906160Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=8133i
```

When attempting 0rtt before falling back to 1rtt connection:
```
[2022-05-09T17:23:05.569953055Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=8755i
[2022-05-09T17:23:05.571141195Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=9180i
[2022-05-09T17:23:05.571643535Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=9915i
[2022-05-09T17:23:05.571655582Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=10477i
```

I'm thinking I'll change this PR to not attempt 0rtt when we know we must create a new connection and only attempt 0rtt when we think we have a good connection but the first send fails.

**Comment by pgarg66** [comment]
> > > @pgarg66 They're still mostly being rejected. Played around with how endpoint's default client config was getting setup, but no breakthroughs yet
> > 
> > 
> > Does trying 0rtt and then establishing connection using the full handshake (on 0rtt failure) add latency to the connection setup?
> 
> In a small sample set, it looks like trying to initiate 0rtt connection is adding ~10% overhead (1ms) for the failing case. It is saving a handful of ms in the success case (though the time seems to have large variation - likely due to threads getting backed up waiting for the connection mutex).
> 
> Baseline connection code:
> 
> ```
> [2022-05-09T16:06:41.387232830Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=8316i
> [2022-05-09T16:06:41.387882385Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=8125i
> [2022-05-09T16:06:41.387897439Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=8624i
> [2022-05-09T16:06:41.387906160Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=8133i
> ```
> 
> When attempting 0rtt before falling back to 1rtt connection:
> 
> ```
> [2022-05-09T17:23:05.569953055Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=8755i
> [2022-05-09T17:23:05.571141195Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=9180i
> [2022-05-09T17:23:05.571643535Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=9915i
> [2022-05-09T17:23:05.571655582Z INFO  solana_metrics::metrics] datapoint: conn-start-new us=10477i
> ```
> 
> When successfully establishing 0rtt connection:
> 
> ```
> [2022-05-09T17:46:06.766204445Z INFO  solana_metrics::metrics] datapoint: conn-start-0rtt us=2122i
> [2022-05-09T17:46:06.768588626Z INFO  solana_metrics::metrics] datapoint: conn-start-0rtt us=3634i
> [2022-05-09T17:46:06.770569116Z INFO  solana_metrics::metrics] datapoint: conn-start-0rtt us=5557i
> [2022-05-09T17:46:06.772547588Z INFO  solana_metrics::metrics] datapoint: conn-start-0rtt us=7408i
> ```
> 
> I'm thinking I'll change this PR to not attempt 0rtt when we know we must create a new connection and only attempt 0rtt when we think we have a good connection but the first send fails.

Yes, it makes sense. Unless there's a mechanism to have default/pre-established key material for new connection (which we should not), there's no way to perform 0rtt connections for such use case.

**Review by pgarg66 — APPROVED** [review]

**Pull request merged**
