### PR TITLE
Dynamic threshold for number of packets going into sigverify dedup

### PR DESCRIPTION
**Pull request by brennanwatt**
#### Problem
Current threshold for number of packets fed into dedup (as part of sigverify stage) is hard coded. This can result in one of two undesirable behaviors:
1. Shedding too many packets in the case where high powered machine could actually process more packets
2. Long latencies in dedup causing backpressure and bursts of dropped packets in the where low powered machine can't handle the hard coded number of packets

#### Summary of Changes
Use the existing measurements for dedup time to understand how many dedups per second the machine is capable of performing and use this to inform the threshold (with min/max bounds to avoid accidental runaway)

### CODE REVIEW

**Comment by brooksprumo** [comment]
Please rebase off master to fix/revert the status cache changes in this PR (I assume they were inadvertent, and just due to the timings of merges/PRs).

**Comment by brennanwatt** [comment]
@behzadnouri - I know you've been splitting out normal TPU vs. vote vs. shred sigverify stages, so let me know how compatible this is with the direction you're going

**Comment by behzadnouri** [comment]
> @behzadnouri - I know you've been splitting out normal TPU vs. vote vs. shred sigverify stages, so let me know how compatible this is with the direction you're going

https://github.com/solana-labs/solana/pull/26300 separates shreds-sigverify from tpu packets and this change won't impact it; so no concern about compatibility here.
However I am generally worried about dynamic adjustments which makes things much harder to understand and debug. Specially in the case of validator code which has so many different threads and non-stationary workload for each thread at any moment of time.

**Comment by sakridge** [comment]
This looks reasonable to me, would be interesting to see the test results with this with different hardware or reducing the threads smaller to see how it responds.

**Comment by brennanwatt** [comment]
@behzadnouri - What does that look like in practice? Stick with single threshold across all validators? Something else?

**Comment by brennanwatt** [comment]
> This looks reasonable to me, would be interesting to see the test results with this with different hardware or reducing the threads smaller to see how it responds.

Looking at data from MNB, per packet dedup timings range from about 150 to 800ns, which would equate to 62.5k to 333k packets that could be handled by dedup per iteration. This appears correlated with CPU0 Freq, with the fastest dedup machines running CPU0 at 4.5GHz.

Running DoS attack against my GCE validator, I'm seeing TPU verify deduper settling in at a threshold of 250k packets (200us per packet)
image

One interesting observation while collecting this data: Dedup runs faster when there are not duplicates being found. I'm assuming this is because we don't need to set flags in the packet, increment the num_removed counter, or possibly reset the filter entry.

**Comment by behzadnouri** [comment]
> @behzadnouri - What does that look like in practice? Stick with single threshold across all validators? Something else?

I don't have a definite answer, but lets say if we are targeting `x` tps (or whatever other performance measure), then that should give a ballpark what rate of packets each stage should be able to handle. So we would target for that and load-shed the rest.

Even when doing `cargo bench ...` on an idle machine, there is so much variations in how long each run takes. So doing dynamic thresholding based on timing execution on a running validator with so many different threads running concurrently and so much variations in load on each protocol at any moment, becomes very unpredictable and hard to debug.

All these validator protocols/threads are sharing machine resources, and that makes the impact of one or some dynamically trying to snatch resources from each other very hard to predict. 

One side effect for example can be the protocol with dynamic threshold will soak up resources from other protocols just because they did not have too much load, but then when the load increases on those protocols, we don't have resources to allocate to them because the dynamic threshold is calibrated to a high resource allocation for that other protocol, and would take time for that threshold to go down.

**Comment by brennanwatt** [comment]
> > @behzadnouri - What does that look like in practice? Stick with single threshold across all validators? Something else?
> 
> I don't have a definite answer, but lets say if we are targeting `x` tps (or whatever other performance measure), then that should give a ballpark what rate of packets each stage should be able to handle. So we would target for that and load-shed the rest.
> 
> Even when doing `cargo bench ...` on an idle machine, there is so much variations in how long each run takes. So doing dynamic thresholding based on timing execution on a running validator with so many different threads running concurrently and so much variations in load on each protocol at any moment, becomes very unpredictable and hard to debug.
> 
> All these validator protocols/threads are sharing machine resources, and that makes the impact of one or some dynamically trying to snatch resources from each other very hard to predict.
> 
> One side effect for example can be the protocol with dynamic threshold will soak up resources from other protocols just because they did not have too much load, but then when the load increases on those protocols, we don't have resources to allocate to them because the dynamic threshold is calibrated to a high resource allocation for that other protocol, and would take time for that threshold to go down.

I hear what you're saying, and it's very possible we're better off sticking w/ the KISS principle here. That said, there are 3 things that mitigate some of the concerns you've brought up:
1. Having a smoothing function to avoid rapid swings in packet threshold (i.e. new measurements only factor in ~3%)
2. Enforcing a minimum number of packets to re-compute bandwidth. Law of averages + large numbers on the input side helps keep the output side sane.
3. Min and max caps to keep the thresholds from going completely sideways. I haven't actually seen these get hit in practice, but they give me the warm and fuzzies that we're not going to accidentally choke sigverify or something

Regarding your comment on deriving the threshold from a performance target, this makes sense, but it's a bit tricky. Two issues come to mind:
1. Load is often non-uniform, so we shed packets during bursts of traffic. What is the max burst we think we need to handle?
2. We expect some amount of packet deduplication to reduce the number of packets hitting verify, so it seems we need to add some multiplier on the performance/burst target to allow for packets to get deduped and not accidentally shed unique packets

**Pull request closed without merging**
