### PR TITLE
Refactor account serialize in appendvec

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Lots of dupe logic in custom account serialize. Not sure if it's faster than bincode.

#### Summary of Changes

Remove dupe code.
Add benchmarks to justify custom serialize and also experiment with
safe solutions.

Benchmark seems to show manual serialize is ~60x faster than bincode serialize.

Fixes #

### CODE REVIEW

**Comment by garious** [comment]
How about `to_le_bytes()`? Compared to serde, that should be identical for primitive types. Compared to the current implementation (before this PR), the unsafe transmute is nicely tucked away, and endianess is automatically flipped on big-endian systems (which is only important for sending snapshots between validators).

**Comment by sakridge** [comment]
@garious I was planning on experimenting with to_le_bytes and write_u64 from byteorder. But I thought this cleans up a bit to be worth merging first.

**Comment by sakridge** [comment]
Would like to just have a pointer to the struct in the mmap but not sure how to fix up the userdata vec to work like that.

**Comment by garious** [comment]
So `to_le_bytes` was just added to Rust stable in the last release. I'd guess it renders `write_u64` obsolete. 

If you merged this PR would it make thinks way slower?

**Comment by sakridge** [comment]
@garious this PR doesn't change anything about the logic at all, it just refactors it into different functions. I would assume the compiler inlines these and expect the speed to be exactly the same as before this PR.

**Comment by sakridge** [comment]
@garious to_le_bytes also seems to be for a slightly different use-case. It returns a slice of those bytes, which I would then have to copy into the larger mmap'ed slice. write_u64 will just write the u64 into the slice I provide, so I can point it to the mmap slice directly. At least that's how I see it, correct me if I'm wrong.

**Pull request merged**
