### PR TITLE
Apply clippy feedback and add it to CI

### PR DESCRIPTION
**Pull request by garious**
Clippy is a great linter. Those just learning Rust should find its feedback on idioms and borrowing should find it especially helpful. This PR accepts nearly all Clippy advice, silencing just one because I don't want to clean up the sigverify bindings (@sakridge), and then adds Clippy to CI so that future PRs will be blocked if you don't acknowledge Clippy.

### CODE REVIEW

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by garious** [comment]
@sakridge, when Clippy tells you to pass an Arc by reference, it's most likely an indication that the function does not pass the Arc across a thread boundary and that therefore the `clone()` on the parameter can safely be removed.  In that PR, I removed the `clone()` calls from a bunch of the tests and benchmark, and all looks good. I can do a followup PR that attempts to remove the rest.

**Comment by sakridge** [comment]
@garious ok I guess the places where it was doing &ref.clone() still kind of threw me off then.

**Pull request merged**
