### PR TITLE
Upgrades Rust  from 1.66.1 to 1.67.1

### PR DESCRIPTION
**Pull request by brooksprumo**
https://blog.rust-lang.org/2023/01/26/Rust-1.67.0.html
https://blog.rust-lang.org/2023/02/09/Rust-1.67.1.html

### CODE REVIEW

**Comment by mvines** [comment]
Please don't merge this until the 1.15 branch exists, as this [1] change to `std::sync::mpsc` could have a destabilizing effect on our threads upon threads codebase and if so it'd be preferable to deal with it in the 1.16 timeframe


[1] https://blog.rust-lang.org/2023/01/26/Rust-1.67.0.html#stdsyncmpsc-implementation-updated

**Comment by yihau** [comment]
just updated stable and nightly images 🪖

**Comment by yihau** [comment]
sure! I will revert it back!

**Comment by yihau** [comment]
sure thing. just updated them and re-run your pipeline 👻

**Review by mvines — APPROVED** [review]
Yep! Thanks

**Pull request merged**
