### PR TITLE
make CrdsGossip thread-safe

### PR DESCRIPTION
**Pull request by behzadnouri**
#### Problem
Working towards reducing lock contention in gossip.

#### Summary of Changes
This commit makes `CrdsGossip` thread safe by wrapping inner crds field in `RwLock`.

### CODE REVIEW

**Review by carllin — APPROVED** [review]

**Review by sakridge — APPROVED** [review]
Nice, did it help?

**Comment by behzadnouri** [comment]
Not much. Very little on the `replay-loop-voting-stats.vote_push_us` metric running on TDS.

This plot below is the write lock contention on crds table in one of the call stacks when processing incoming gossip packets.
Apparently `std::sync::RwLock` on linux is reader-preferred (pthread default), which might contribute to write lock contentions. So, I am going to also try `parking_lot` which claims fair locking policy. But I am not expecting it will make a lot of difference. So no need to wait on merging in the voting-service commit.

lock-contention-process-gossip

**Comment by carllin** [comment]
Yeah, seems like all the contention would still exist around the crds table, probably need to use a concurrent hashmap to see any dramatic difference

**Comment by behzadnouri** [comment]
`replay-loop-voting-stats::vote_push_us`: Left side is `parking_lot`.
replay-loop-voting-stats vote_push_us_parking_lot_16s

I also implemented a writer-preferred RwLock on top of `std::sync::RwLock`, using an extra Mutex trick and similar result:  

replay-loop-voting-stats vote_push_us_rwlock_16s

**Pull request merged**
