### PR TITLE
new bank from file test

### PR DESCRIPTION
**Pull request by aeyakovenko**
compare bank loaded from the log file vs the one from the mint

### CODE REVIEW

**Comment by garious** [comment]
You don't initialize that file with a genesis block. https://github.com/solana-labs/solana/blob/master/src/mint.rs#L55

**Comment by garious** [comment]
Also, you can implement this test without any stages over here: https://github.com/solana-labs/solana/blob/master/src/entry_writer.rs#L124

**Comment by aeyakovenko** [comment]
@garious 
> Also, you can implement this test without any stages over here: https://github.com/solana-labs/solana/blob/master/src/entry_writer.rs#L124

i don't see exactly how?  do i hand append `alice.create_entries` and `ledger::next_entries(` and feed that to `new_bank.process_ledger`?  its not clearly obvious to me that should work, or if that is the intent of how the apis should come together

**Comment by garious** [comment]
@aeyakovenko, here's how the validator starts: https://github.com/solana-labs/solana/blob/master/multinode-demo/validator.sh#L75

cat genesis and all previous logs, and that's what should go to `process_ledger()`.

**Comment by garious** [comment]
If you did that in Rust (i.e. for a test), you'd `chain()` the line iterators.

**Comment by garious** [comment]
"do i hand append alice.create_entries and ledger::next_entries( and feed that to new_bank.process_ledger"

I did that locally and it works as expected. Why are you thinking it's not obvious that'd work?

**Comment by garious** [comment]
@aeyakovenko, see #516

**Comment by garious** [comment]
@aeyakovenko, does this test still add value? Help you debug?

**Comment by aeyakovenko** [comment]
>@aeyakovenko, does this test still add value? Help you debug?

@garious we can kill it

**Comment by aeyakovenko** [comment]
Fixed in #528

**Pull request closed without merging**
