### PR TITLE
Move last ids

### PR DESCRIPTION
**Pull request by aeyakovenko**
#### Problem

LastIds are a big class that can be moved out of the bank.

#### Summary of Changes

Moved LastIds into its own module.  No other changes besides moving the code around.

Fixes #

### CODE REVIEW

**Comment by garious** [comment]
There's no precedent for an error struct in its own module. Can you split BankError such that the ones related to LastIds move to its module?

Also, to minimize the churn, let's squeeze a name change into this PR. Rename that struct to EntryIdQueue and the bank field to `recent_ids`.

**Comment by garious** [comment]
Or `tx_status_queue: TxStatusQueue`

**Comment by garious** [comment]
If you prefer smaller PRs, the right one to do first is split BankError.

**Comment by mvines** [comment]
> Adding Request Changes to see if it blocks the automerge label.

I'm gonna bet "no", but not 100% sure.  🍿

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by mvines** [comment]
Looks like I lost my bet, excellent. 💸

**Comment by mvines** [comment]
Rebase to the tip of master to get unstuck

**Comment by aeyakovenko** [comment]
@garious they work locally

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by aeyakovenko** [comment]
@mvines @garious can we kill nightly?
https://buildkite.com/solana-labs/solana/builds/21#b7050d25-6611-47c8-bf30-2785bc96fd89
the other option is something line:
```
diff --git a/Cargo.toml b/Cargo.toml                                                                                                                                                                        
index dae58d92..2b6f5b2a 100644                                                                                                                                                                             
--- a/Cargo.toml                                                                                                                                                                                            
+++ b/Cargo.toml                                                                                                                                                                                            
@@ -21,6 +21,7 @@ erasure = []                                                                                                                                                                              
 ipv6 = []                                                                                                                                                                                                  
 test = []                                                                                                                                                                                                  
 unstable = []                                                                                                                                                                                              
+nightly = []                                                                                                                                                                                               
                                                                                                                                                                                                            
 [dependencies]                                                                                                                                                                                             
 bincode = "1.0.0"                                                                                                                                                                                          
diff --git a/ci/test-nightly.sh b/ci/test-nightly.sh                                                                                                                                                        
index 1a87c5b1..05ac23d2 100755                                                                                                                                                                             
--- a/ci/test-nightly.sh                                                                                                                                                                                    
+++ b/ci/test-nightly.sh                                                                                                                                                                                    
@@ -27,7 +27,7 @@ cargo_install_unless cargo-cov cargo cov --help                                                                                                                                           
                                                                                                                                                                                                            
 # Generate coverage data and report via unit-test suite.                                                                                                                                                   
 _ cargo cov clean                                                                                                                                                                                          
-_ cargo cov test --lib                                                                                                                                                                                     
+_ cargo cov test --lib --features=nightly                                                                                                                                                                  
 _ cargo cov report                                                                                                                                                                                         
                                                                                                                                                                                                            
 # Generate a coverage report with grcov via lcov.                                                                                                                                                          
diff --git a/src/compute_leader_finality_service.rs b/src/compute_leader_finality_service.rs                                                                                                                
index 0d46e7d1..84be8025 100644                                                                                                                                                                             
--- a/src/compute_leader_finality_service.rs                                                                                                                                                                
+++ b/src/compute_leader_finality_service.rs                                                                                                                                                                
@@ -145,7 +145,7 @@ impl Service for ComputeLeaderFinalityService {                                                                                                                                         
     }                                                                                                                                                                                                      
 }                                                                                                                                                                                                          
                                                                                                                                                                                                            
-#[cfg(test)]                                                                                                                                                                                               
+#[cfg(all(test, not(feature = "nightly")))]                                                                                                                                                                
 pub mod tests {                                                                                                                                                                                            
     use crate::bank::Bank;                                                                                                                                                                                 
     use crate::compute_leader_finality_service::ComputeLeaderFinalityService; 
```

**Comment by garious** [comment]
Afraid not. That generates the code coverage report and uploads it to buildkite.

**Comment by aeyakovenko** [comment]
@garious what about the other option.  Add feature=nightly to nightly builds so tests that are not stable on nightly can be ignored

**Comment by garious** [comment]
Well it's not the nightly that's the problem. Usually it's been the coverage instrumentation that's the problem, but only for tests with network I/O. Rather than add that flag, either moving tests to integration tests or making them proper unit tests would be preferred. Historically and unfortunately, everyone has taken the former choice.

**Comment by garious** [comment]
@carllin, there's a theme to the nightly failures:

```
failures:
--
  | compute_leader_finality_service::tests::test_compute_finality
  | fullnode::tests::test_validator_to_leader_transition
  | fullnode::tests::test_wrong_role_transition
  | leader_scheduler::tests::test_active_set
  | leader_scheduler::tests::test_avoid_consecutive_leaders
  | leader_scheduler::tests::test_max_height_for_leader
  | leader_scheduler::tests::test_multiple_vote
  | leader_scheduler::tests::test_scheduler
  | leader_scheduler::tests::test_scheduler_active_window
  | replay_stage::test::test_replay_stage_leader_rotation_exit
  | replay_stage::test::test_vote_error_replay_stage_leader_rotation
  | thin_client::tests::test_register_vote_account
```

**Comment by carllin** [comment]
@mvines, I'm running "cargo cov test --lib" on my machine and seeing the error "Unable to load: Custom { kind: Other, error: StringError("dlopen(/Users/carl/Projects/solana/target/cov/build/./debug/deps/deps/libsolana_vote_program.dylib, 130): image not found") }", looks like the native programs aren't being installed in the target/cov/build/debug directory for use by the code coverage tool.

**Comment by aeyakovenko** [comment]
@garious #2193 marked the tests as ignore

**Comment by mvines** [comment]
> @mvines, I'm reproducing the issue seen in nightly by running "cargo cov test --lib" on my machine and seeing the error "Unable to load: Custom { kind: Other, error: StringError("dlopen(/Users/carl/Projects/solana/target/cov/build/./debug/deps/deps/libsolana_vote_program.dylib, 130): image not found") }",
> 
> Looks like only the main solana library is being installed in the target/cov/build/debug directory for consumption by the code coverage tool.

Thanks for reporting this, it looks like we just need a `cargo cov build --all` to ensure everything is built before running coverage (cc: #2201)

**Pull request merged**
