### PR TITLE
CI large network test to check for swap and swappiness

### PR DESCRIPTION
**Pull request by pgarg66**

### CODE REVIEW

**Comment by pgarg66** [comment]
https://github.com/solana-labs/solana/issues/570

**Comment by mvines** [comment]
This feels very much like black magic.  Relying on a specific swapiness setting in particular is just gnarly.  You're **sure** we need this?

**Comment by pgarg66** [comment]
Low swappiness helps reducing use of swap space. 10 is picked from the tutorial I used for configuring the swap space. The test worked much consistently after setting the swappiness. I think, the best solution is to add more RAM. We can remove all this once we get there.

**Comment by mvines** [comment]
Bah let's just bite the bullet and give the VM more RAM.  Do you know how RAM much it needs without swap?

**Comment by pgarg66** [comment]
It currently has ~84GB. I added swap of 64GB. I would suggest adding a bit more, as swap was also getting heavily utilized with 170 nodes.

**Comment by garious** [comment]
Anything happening with this PR? @mvines, @pgarg66?

**Comment by mvines** [comment]
We can 🍄 it, fixed instead by increasing the available RAM on `ci-large`

**Pull request closed without merging**
