### PR TITLE
Add cargo-build-bpf

### PR DESCRIPTION
**Pull request by mvines**
`cargo-build-bpf` is a less opinionated version of `sdk/bpf/rust/build.sh`.  It:
* Doesn't care if you don't have a Xargo.toml or Cargo.toml in the current directory (both Cargo and Xargo search up the tree)
* Doesn't impose `--no-default-features --features program` on you
* When in the path, slides in to your normal cargo workflow as `cargo build-bpf ...`
* Gets installed by `solana-install ..` so it just works once you get the solana cli installed

#### Example: build parts of the tree for BPF:
```
$ cd sdk/
$ ../cargo-build-bpf --no-default-features --features program
```
```
$ cd programs/bpf/rust/sysval
$ ../../../../cargo-build-bpf --no-default-features --features program 
```
(note: once `program-sdk/` exists (https://github.com/solana-labs/solana/pull/12989), these extra args disappear)

#### TODO
* [x] Strip object like `do.sh` does
* [x] Add `--dump` flag to obsolete `do.sh dump ...`

### CODE REVIEW

**Comment by mvines** [comment]
Welp looks like I need to rewrite `cargo-build-bpf` in Rust to get at `cargo metadata` output sanely, probably for the best.

**Comment by mvines** [comment]
Neat, I cherry-picked this PR on top of #12989 and it works!

```
~/ws/s1/sdk/program$ ../../cargo-build-bpf 
+ exec /Users/mvines/ws/s1/sdk/bpf/dependencies/xargo/bin/xargo build --target bpfel-unknown-unknown --release
    Finished release [optimized] target(s) in 0.18s
```

**Comment by mvines** [comment]
Rewrote `cargo-build-bpf` in Rust and it's feeling really nice.  

```
~/ws/s1$ cd programs/bpf/rust/sha256
~/ws/s1/programs/bpf/rust/sha256$ cargo build-bpf
Running: /Users/mvines/ws/s1/sdk/bpf/rust/xargo-build.sh --no-default-features --features=program
   Compiling solana-frozen-abi v1.5.0 (/Users/mvines/ws/s1/frozen-abi)
   Compiling solana-sdk v1.5.0 (/Users/mvines/ws/s1/sdk)
   Compiling solana-bpf-rust-sha256 v1.5.0 (/Users/mvines/ws/s1/programs/bpf/rust/sha256)
    Finished release [optimized] target(s) in 4.83s
Running: /Users/mvines/ws/s1/sdk/bpf/scripts/strip.sh /Users/mvines/ws/s1/programs/bpf/target/bpfel-unknown-unknown/release/solana_bpf_rust_sha256.so /Users/mvines/ws/s1/programs/bpf/target/bpfel-unknown-unknown/deploy/solana_bpf_rust_sha256.so
```

Now wander over to SPL land:
```
$ cd ~/ws/spl/token/program
$ cargo build-bpf
Running: /Users/mvines/ws/s1/sdk/bpf/rust/xargo-build.sh --no-default-features --features=program
    Finished release [optimized] target(s) in 0.26s
Running: /Users/mvines/ws/s1/sdk/bpf/scripts/strip.sh /Users/mvines/ws/spl/target/bpfel-unknown-unknown/release/spl_token.so /Users/mvines/ws/spl/target/bpfel-unknown-unknown/deploy/spl_token.so
```


It's smart enough to know when it's not building a cdylib too:
```
~/ws/s1/frozen-abi$ cargo build-bpf
Note: solana-frozen-abi crate does not contain a cdylib target
Running: /Users/mvines/ws/s1/sdk/bpf/rust/xargo-build.sh
   Compiling solana-frozen-abi v1.5.0 (/Users/mvines/ws/s1/frozen-abi)
    Finished release [optimized] target(s) in 1.06s
```


and trying to build something silly produces a reasonable error output:
```
~/ws/s1/validator$ cargo build-bpf
Note: solana-validator crate does not contain a cdylib target
Running: /Users/mvines/ws/s1/sdk/bpf/rust/xargo-build.sh
Error: Failed to find Xargo.toml

Please create a Xargo.toml file in the same directory as your Cargo.toml with
the following contents:

  [target.bpfel-unknown-unknown.dependencies.std]
  features = []

```

**Comment by jackcmay** [comment]
Looking good, nice to see the build scripts tucked under a cargo subcommand

**Comment by mvines** [comment]
This is pretty much ready to land, latest commit deletes `do.sh` 👢

**Comment by mvines** [comment]
ooo, green CI.   Now's my chance!

**Pull request merged**
