### PR TITLE
chore: add missing members back to workspace.members

### PR DESCRIPTION
**Pull request by yihau**
#### Problem

found some members didn't in the workspace.members

#### Summary of Changes

- add `frozen-abi/macro`, `program-runtime`, `sdk/macro` and `sdk/program` to member list
- remove workspace filed from `storage-bigtable/build-proto` and add it to member list as well

### CODE REVIEW

**Comment by t-nelson** [comment]
hrm... thought i tried this once and it broke the build. ci seems happy here :thinking:

**Comment by yihau** [comment]
yeah, iirc you encountered an error. Originally I just tried to reproduce the issue but it passed haha 🤞

**Review by CriesofCarrots — COMMENTED** [review]
Seems okay? As long as all the crates and docs.rs publish like normal. I don't have any particular reason to think they won't; just concerned, since I don't know why we excluded these members in the first place.
I'm game to merge this and keep an eye on things when v1.15.0 is published.

**Review by t-nelson — APPROVED** [review]
> yeah, iirc you encountered an error. Originally I just tried to reproduce the issue but it passed haha crossed_fingers

maybe one of the toolchain upgrades resolved the issue since.  iirc it was some conflict in workspace resolution

fine by me

**Comment by yihau** [comment]
🪖

**Pull request merged**
