### PR TITLE
use staked connection for bench-tps in net scripts

### PR DESCRIPTION
**Pull request by KirillLykov**
#### Problem

After adding throttling to streamer bench-tps shows  ~50tps. To fix this we use staked connection.

### CODE REVIEW

**Comment by pgarg66** [comment]
Should we add an option to use unstaked client, as that's still a valid use-case?

**Comment by KirillLykov** [comment]
> Should we add an option to use unstaked client, as that's still a valid use-case?

I have a mixed feeling about it: tps is so low that I don't know if anyone needs this option.

**Comment by pgarg66** [comment]
> > Should we add an option to use unstaked client, as that's still a valid use-case?
> 
> I have a mixed feeling about it: tps is so low that I don't know if anyone needs this option.

A lot of clients of the network will continue to be unstaked. It'll be valuable to be able test that the use-case still works, even though TPS is low. We might want to improve the TPS of unstaked clients by launching multiple clients (or multiple QUIC connections).

**Comment by apfitzge** [comment]
We should also fix the multinode script(s), since those are also getting throttled, something like this?
```
diff --git a/multinode-demo/bench-tps.sh b/multinode-demo/bench-tps.sh
index fadea483ba..d1efea692d 100755
--- a/multinode-demo/bench-tps.sh
+++ b/multinode-demo/bench-tps.sh
@@ -25,5 +25,7 @@ default_arg --faucet "127.0.0.1:9900"
 default_arg --duration 90
 default_arg --tx-count 50000
 default_arg --thread-batch-sleep-ms 0
+default_arg --bind-address "127.0.0.1"
+default_arg --client-node-id config/bootstrap-validator/identity.json
 
 $solana_bench_tps "${args[@]}"
```

**Comment by KirillLykov** [comment]
pushed branch to wrong repo

**Pull request closed without merging**
