### PR TITLE
Replace blob with shred in book

### PR DESCRIPTION
**Pull request by pgarg66**
#### Problem
The book has references to `blob`, which should be replaced with `shred`.

#### Summary of Changes
Replace `blob` with `shred`

Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
image

**Comment by mvines** [comment]
asbcdeghigklmnopqrtuvwxyz? :)

**Comment by pgarg66** [comment]
> asbcdeghigklmnopqrtuvwxyz? :)

Sorry, will push another change.

**Comment by mvines** [comment]
no worries, it's just funny

**Pull request merged**
