### PR TITLE
changed atty library

### LINKED ISSUE #340: Migrate to portable `isatty` check
Instead of the `isatty` Linux/macOS-only dependency, how about:

https://github.com/softprops/atty

### PR DESCRIPTION
**Pull request by rlkelly**
Fixes #340

### CODE REVIEW

**Comment by garious** [comment]
@rob-solana, fyi

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by garious** [comment]
Can you run `cargo fmt` from rust 1.26.2 (latest stable)?

**Comment by rlkelly** [comment]
sure thing

**Pull request merged**
