### PR TITLE
Missing signature test

### LINKED ISSUE #3046: Bank panics if transaction has no signatures
#### Problem

The bank doesn't fail gracefully if sent a transaction with zero signatures.

#### Proposed Solution

Look at all the `signatures[0]` instances in Bank and evaluate if that functionality should be ignored (signature cache) or return an error.

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Transaction with 0 signature panics the banking-stage.

#### Summary of Changes

Test that sends a transaction with 0 signatures to a fullnode.

Fixes #3046

### CODE REVIEW

**Comment by sakridge** [comment]
Seems like this might be a problem:

```
thread 'solana-banking-stage-tx' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/
libcore/slice/mod.rs:2463:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:71
   9: <usize as core::slice::SliceIndex<[T]>>::index
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/slice/mod.rs:2463
  10: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/slice/mod.rs:2331
  11: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/vec.rs:1653
  12: solana_runtime::bank::Bank::check_signatures::{{closure}}
             at runtime/src/bank.rs:450
  13: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::fold::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/iter/mod.rs:1347
  14: core::iter::iterator::Iterator::fold::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/iter/iterator.rs:1696
  15: core::iter::iterator::Iterator::try_fold
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/iter/iterator.rs:1584
```

**Comment by garious** [comment]
@sakridge,  can you move this test down to bank.rs instead of using thin_client? In thin_client, it's an integration test and all your fixes are in the bank.  Also, it's not obvious to me if a leader should or should not reject a transaction with no signatures, which is what an integration test should verify. The Bank's behavior is more obvious and we can move forward with that today. It definitely should not panic, which is what it does today.  If the instructions in the transaction does not *require* a signature, it should successfully process the transaction.

**Comment by garious** [comment]
Also, the PR description doesn't reference #3046. Is that what you intended to fix here or did you find this independently?

**Comment by sakridge** [comment]
@garious found independently, didn't realize there was an issue already. Can move to a bank interface test. I also wasn't sure if we wanted to filter the TX at a different level.

**Pull request merged**
