### PR TITLE
hide commonly misused `--no-port-check` validator arg

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

followup to #30250. missed the worst one due to #30303 :facepalm: 

#### Summary of Changes

hide `--no-port-check`

### CODE REVIEW

**Comment by steviez** [comment]
Should we rip this out too then?
https://github.com/solana-labs/solana/blob/ce4251be99dc91509d052acfc7625c687d7d7f24/docs/src/running-validator/validator-start.md?plain=1#L434-L438

**Comment by t-nelson** [comment]
> Should we rip this out too then?
> 
> https://github.com/solana-labs/solana/blob/ce4251be99dc91509d052acfc7625c687d7d7f24/docs/src/running-validator/validator-start.md?plain=1#L434-L438

fff... yes!  no wonder so many configs have this flag.  gotta take... 2s off startup

nice catch!

**Comment by t-nelson** [comment]
aaaaaand it's gone!

**Review by steviez — APPROVED** [review]
LGTM

Outside of the scope of this PR, but we might also consider adding a warning message when any of these `--no-*-check` args are used. Something like "Make sure you know wtf you're doing" or "This arg might mask errors, try removing to debug".

I added something similar a little while back to spit a warning when someone specifies a deprecated arg (warnings were hit-or-miss on deprecated args prior)
https://github.com/solana-labs/solana/pull/28250/files#diff-59e2068dd4d49c21ab87f3a5d8792d2daca826ab6924b32413e551c0e3035f61R3336-R3345

**Comment by t-nelson** [comment]
or maybe "don't even come to discord looking for support with this in your cli args" :sweat_smile:

**Pull request merged**
