### PR TITLE
Stake merge inactive lockup

### LINKED ISSUE #17372: Allow stake accounts with expired lockups to be merged
#### Problem

The stake account merging logic currently enforces lockup equality, even if the lockups are no longer in force

#### Proposed Solution

Relax the merge logic to allow mismatched lockups so long as they're both expired

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

Stake accounts with mismatched, but expired lockups cannot be merged

#### Summary of Changes

Allow them to be

Fixes #17372

### CODE REVIEW

**Comment by t-nelson** [comment]
Open questions:
1) Should the stakes be mergeable with a matching custodian and corresponding signature?
2) Should an account with inactive lockup be mergeable into one with an active lockup?

**Review by CriesofCarrots — APPROVED** [review]
PR lgtm!
Regarding your questions:

> Should the stakes be mergeable with a matching custodian and corresponding signature?
> Should an account with inactive lockup be mergeable into one with an active lockup?

I can see the argument here, since the custodian can accomplish these merges with several transactions. However, my take is that it is not worth the additional code complexity to support the single operation.

If we do go this route, note that merging an account with inactive lockup into one with active lockup should also require the withdraw authority, as per https://github.com/solana-labs/solana/pull/17361.

**Comment by mvines** [comment]
> Open questions:
> 
> 1. Should the stakes be mergeable with a matching custodian and corresponding signature?
> 2. Should an account with inactive lockup be mergeable into one with an active lockup?

I vote no on both for now.  More complexity for both so let's wait for demand

**Review by mvines — APPROVED** [review]

**Comment by t-nelson** [comment]
Ok. We're all on the same page regarding the open questions.  Thanks for review!

**Pull request merged**
