### PR TITLE
ci: don't run openbook_dex downstream-project test temporarily

### PR DESCRIPTION
**Pull request by yihau**
#### Problem

seems their latest commit will broke their tests. I've made a PR there (https://www.github.com/openbook-dex/program/pull/22). will revert this PR when their test is fine.

### CODE REVIEW

**Comment by yihau** [comment]
just commented out one line. merge it on red.

**Comment by yihau** [comment]
cc @KirillLykov

**Comment by KirillLykov** [comment]
Looks like fixed here -- https://github.com/openbook-dex/program/pull/24

**Comment by yihau** [comment]
yeah! thank you! I opened another PR to track another issue https://github.com/solana-labs/solana/pull/29207

**Pull request merged**
