### PR TITLE
Bank snapshots

### LINKED ISSUE #2475: Fullnode startup is slow
#### Problem

Currently, starting a fullnode queries the cluster for the full ledger and replays it.

#### Proposed Solution

The fullnode should first check for a recent ledger state snapshot locally and if unavailable, query another validator for one.

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Full node startup is slow when many transactions have been processed.

#### Summary of Changes

Serialize a bunch of bank state into a snapshot and try to restore from that on boot.

TODO:
- [ ] error handling
- [ ] test more complicated forkings
- [ ] StatusCache::merges
- [ ] BankForkInfo generation
- [ ] snapshot flag plumbing

Fixes #2475

### CODE REVIEW

**Comment by garious** [comment]
This looks like a pretty substantial maintenance burden. Every time we add a field to anything in solana_runtime, we'll need to update some custom serialization routines? This stuff looks pretty mechanical at first glance. Think we could write a custom derive macro or something like that? https://doc.rust-lang.org/edition-guide/rust-2018/macros/custom-derive.html

**Comment by sakridge** [comment]
@garious that stuff is really hairy, but let me look into it.

**Comment by sakridge** [comment]
@sambley are you able to take over this PR/issue? #2475

**Comment by sambley** [comment]
@sakridge, sure I can take a look. Are all the TODOs listed in this pending to be done in addition to the custom serialization comment from Greg.

**Comment by sakridge** [comment]
@sambley yes, that's right.

**Comment by sakridge** [comment]
@sambley any chance to look at bank snapshots?

**Comment by sambley** [comment]
> @sambley any chance to look at bank snapshots?

@sakridge, just started taking a look at it. currently looking at #3425 and will work it after that.

**Comment by sakridge** [comment]
@sambley cool. thanks

**Comment by aeyakovenko** [comment]
Close this one?

**Comment by aeyakovenko** [comment]
AccountsDB supports a scan method that reads from storage.  Here is an example. https://github.com/solana-labs/solana/blob/master/runtime/src/accounts.rs#L305

Using the latest write version for each account/fork will allow you to rebuild the index.

**Pull request closed without merging**
