### PR TITLE
CLI cosmetic: make config get and verbose prints consistent

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
The results from `solana config get` and passing the `--verbose` flag with a command like `solana balance` are not consistent.

#### Summary of Changes
Make them consistent.
This updates the name of the "keypair" field to "Key Path" in preparation for remote wallet implementation. At present this is a purely cosmetic change, and does not alter the fields in the config or the input ags. I toyed with making those updates -- ie. `--keypair` arg to `--key-path` and `--url` to `--rpc-url` -- but it caused a ton of downstream churn in bash scripts (some of which use those args to target multiple crates, eg. solana-install, solana-faucet).

New responses:

```
$ solana config get
Config File: ~/.config/solana/cli/config.yml
RPC Url: http://testnet.solana.com:8899
Key Path: ~/keypair.json

$ solana balance --verbose
RPC Url: http://testnet.solana.com:8899
Key Path: ~/keypair.json
9 SOL
```

### CODE REVIEW

**Comment by garious** [comment]
How about hyphenated lowercase: `rpc-url:` and `keypair-path`?

**Comment by CriesofCarrots** [comment]
> How about hyphenated lowercase: `rpc-url:` and `keypair-path`?

Sure, that's okay with me.
Do you specifically want "keypair-path" instead of "key-path"?

**Comment by garious** [comment]
Yes, and url instead of endpoint

**Comment by CriesofCarrots** [comment]
> Yes, and url instead of endpoint

"keypair-path" seems weird to me in the context of remote wallets and bip 32 derivation (but it does reduce churn)

**Comment by garious** [comment]
wallet-path?

**Comment by garious** [comment]
No, not wallet-path, since we use it to identify a single keypair within a wallet.

**Comment by CriesofCarrots** [comment]
> No, not wallet-path, since we use it to identify a single keypair within a wallet.

That's why I settled on key-path.

**Comment by garious** [comment]
Sorry to do it, but just noticed other CLI commands like `epoch-info` using title case before the colon. Can you skim through more commands and simply make things consistent? Don't care much if title case or hyphenated lowercase.

**Comment by garious** [comment]
One nit, "RPC Url" -> "RPC URL"

**Comment by CriesofCarrots** [comment]
@garious getting this in and out of the way. Happy to follow up, if needed.

**Pull request merged**
