### PR TITLE
Start a drone in Local Cluster

### LINKED ISSUE #3592: Fix Local Cluster test start_and_exit_with_config
#### Problem

#3591 has added `local_cluster::test::test_local_cluster_start_and_exit_with_config` to ignore.

#### Proposed Solution

Figure out why the test is flaky and re-enable it. Primary suspect is the fact that the test exits immediately and so the replicator isn't able to setup its account by the time teardown has started. 
Make sure LocalCluster returns only once all configured entities are up and running. Might need a restructure of where gossip service is started within replicators

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

LocalCluster doesn't spawn a drone. This limits what we can test and pretty much breaks replicators. Replicators also don't correctly talk to the drone for their funding transactions.

#### Summary of Changes

Added a Drone to LocalCluster and an airdrop api to RpcClient. 
As a side effect, this even fixes that fullnode exit with config test.

Fixes #3592

### CODE REVIEW

**Comment by garious** [comment]
Might need to take a step back here and think about the higher-level problem.  Why does replicator depend on a drone? Why interact with it via RpcClient?

Vines and I are trying to boot airdrop support from JSON RPC. Not too excited about another dependency on it creeping in.  See https://github.com/solana-labs/solana/issues/1830

**Comment by sagar-solana** [comment]
Replicators use RPC to airdrop some tokens into their own accounts (which they then use to to fund their storage accounts) (they also used to pay 1 lamport fee which they no longer do via transfer_unsigned). 
 
I suppose I could remove the automatic account setup from replicators altogether. But then they will just exit if their accounts have no balance. If you think that's the better way forward I can rework this.

**Comment by aeyakovenko** [comment]
@sagar-solana, the funding can come from an arbitrary key, not just the drone.

**Comment by sagar-solana** [comment]
@aeyakovenko, yeah I renamed the functions, the generic transfer ones were unused for the most part.

**Pull request closed without merging**
