### PR TITLE
show rent model

### PR DESCRIPTION
**Pull request by rob-solana**
#### Problem
 rent's constraints aren't intuitive

 #### Summary of Changes
 support printing out some basics of the rent model

Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
This would make an awesome new cli subcommand: `solana show-rent`

**Comment by rob-solana** [comment]
> This would make an awesome new cli subcommand: `solana show-rent`

would you rather a new RPC or augmentation of current one?

**Comment by mvines** [comment]
I don't see an obvious existing RPC API that we could graft onto so prolly a new one.  But sombody adding a `solana show-rent` command isn't urgent and don't need to block this PR by any means

**Comment by rob-solana** [comment]
> I don't see an obvious existing RPC API that we could graft onto so prolly a new one. But sombody adding a `solana show-rent` command isn't urgent and don't need to block this PR by any means
```
    get_minimum_balance_for_rent_exemption(&self, data_len: usize)
```

**Comment by garious** [comment]
Seems like a natural extension of `solana fees`.

**Comment by rob-solana** [comment]
#7413

**Pull request merged**
