### PR TITLE
Lower broadcast shred limit to 16k

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Shreds

#### Summary of Changes

Send less shreds (limit to 16k each data and coding shreds)

Fixes #

### CODE REVIEW

**Review by behzadnouri — DISMISSED** [review]
lgtm, as long as @carllin does not see any issues with respect to long partitions / number of slots that we can skip

**Comment by mvines** [comment]
> lgtm, as long as @carllin does not see any issues with respect to long partitions / number of slots that we can skip

Do we have an estimate how many virtual ticks we can fit in 8k? That'll probably inform us on how quickly we need to start thinking about implementing virtual tick compression

**Comment by behzadnouri** [comment]
> > lgtm, as long as @carllin does not see any issues with respect to long partitions / number of slots that we can skip
> 
> Do we have an estimate how many virtual ticks we can fit in 8k? That'll probably inform us on how quickly we need to start thinking about implementing virtual tick compression

The `parent_offset` on the fat slot was `179541904 - 179491332 = 50572`, and that caused `147854` data shreds. If we limit data shreds to `8k`, that _roughly_ means we can skip:
```
8000 * 50572 / 147854 = 2736
```
slots which is like `2736 * 0.400 / 60 = 18` minutes.
Obviously this is without any tick compression.

**Comment by mvines** [comment]
> slots which is like 2736 * 0.400 / 60 = 18 minutes.

k, so putting it all together, a node that forks off will panic after 18 minutes with this PR (if/until tick compression is implemented). I think that's ok, just saying it out loud

**Comment by carllin** [comment]
Yeah should be ok, shouldn't halt the network unless we get many many small partitions

**Review by carllin — APPROVED** [review]

**Comment by carllin** [comment]
Are we sure this isn't attackable though if somebody starts spamming transactions to a leader? What is the max feasible size of transactions somebody can fit into `N` CU's in BankingStage?

**Comment by behzadnouri** [comment]
On a 2nd though, at some point we were seeing slots with `7345` shreds completed on testnet:
https://discord.com/channels/428295358100013066/979458235041988668/986385683100876851

so maybe `8192` is too tight.
Maybe better to set this to `16_384` for now, which would be half of current 32k limit.

**Comment by carllin** [comment]
I bet votes account for a lot of that space too, so to be safe we should really make sure that votes for X validators plus transactions for MAX_CU's cannot exceed this limit

**Comment by sakridge** [comment]
> Maybe better to set this to 16_384 for now, which would be half of current 32k limit.

Yea, that's reasonable to start with.

**Review by behzadnouri — APPROVED** [review]
lgtm, but given Carl's concerns regarding attack vectors, maybe hold off merging this until we have more evidence that this is entirely necessary.

So far testnet have been resilient to large blocks, and my feeling is that shreds getting into an infinite circular retransmit loop because of jito shred-streamer had more impact in the outage.

**Comment by overclock-validator** [comment]
> I bet votes account for a lot of that space too, which is why the data is so much higher on testnet, so to be safe we should really make sure that votes for X validators plus transactions for MAX_CU's cannot exceed this limit

Should votes and non votes have totally independent cu limits? A lot of non vote transaction activity commonly leads to the max block cu limit being hit prematurely into the block which causes votes to drop. Any bug where non vote cu's somehow get overcounted/counted too fast could lead to starvation of votes. Maybe a bit farfetched but yeah...

**Pull request closed without merging**
