### PR TITLE
Re-enable spl downstream build

### PR DESCRIPTION
**Pull request by KirillLykov**
#### Problem

Re-enable spl downstream build which was disabled after borsh upgrade.
See https://github.com/solana-labs/solana/issues/32378

### CODE REVIEW

**Comment by yihau** [comment]
btw, I'm thinking do we want to make this one happen in this same PR.  https://github.com/solana-labs/solana/pull/31363/commits/072884de57937e0f2aa541ba1d64f55a29bf733b

I modified it accidentally but the fix hasn't merged cuz some issues. 😢

**Review by yihau — APPROVED** [review]
(btw, this PR is good enough to me! I can fix the error in my original PR if it doesn't happen in this one!)

**Comment by KirillLykov** [comment]
> Thank you <3
> 
> btw, I'm thinking do we want to make this one happen in this same PR. [072884d](https://github.com/solana-labs/solana/commit/072884de57937e0f2aa541ba1d64f55a29bf733b)
> 
> I modified it accidentally but the fix hasn't merged cuz some issues. 😢

My understanding is that you propose to run test instead of build. I'm not sure about doing cargo-test-sbf because there is timeout 30min currently and I don't know how long test will take. 
I think we should not mix re-enabling build and enabling tests because each change might go wrong for some reason and it will be harder to track.

**Comment by yihau** [comment]
yeah. no problem. I can fix it in another PR.
tbh, we did test before. one of my reorg PR broke it. 
https://github.com/solana-labs/solana/blob/304c13dacc03de787f84543d6a3328425b1de61d/scripts/build-downstream-projects.sh#L72
(^^^ from the v1.14 branch)

**Review by joncinque — APPROVED** [review]
Looks good to me! It's too bad it doesn't run the job in this PR though

**Pull request merged**
