### PR TITLE
Update default STS parameters to the following based on performance data

### PR DESCRIPTION
**Pull request by lijunwangs**
Update default STS parameters to the following based on performance data
1. Batch size: 100
2. Batch rate: every 100 millisecond

### CODE REVIEW

**Comment by lijunwangs** [comment]
image

**Comment by lijunwangs** [comment]
Test | Normal/QUIC | Normal/UDP | Batch/QUIC | Batch/UDP
-- | -- | -- | -- | --
1 | 5230.566 | 6552.7744 | 5012.4805 | 6811.3433
2 | 5431.2363 | 6953.02 | 5419.191 | 6779.535
3 | 4714.8823 | 6746.4976 | 5528.698 | 6778.86
4 | 4677.667 | 6747.1406 | 5678.026 | 6676.997
5 | 4629.825 | 6811.479 | 5182.46 | 6784.7593
6 | 5061.081 | 6810.9375 | 5453.2495 | 6682.5474
7 | 4932.5806 | 6572.5146 | 5225.896 | 6811.6807
8 | 4977.989 | 6747.3003 | 5625.551 | 6649.8125
9 | 4957.2246 | 6746.7876 | 5298.9707 | 6839.3594
10 | 5018.0664 | 6812.064 | 5479.205 | 6648.837
11 | 4923.4116 | 6746.323 | 5420.7676 | 6737.081
12 | 4918.0425 | 6777.2075 | 5054.688 | 6723.1953
13 | 4443.6025 | 6779.4585 | 5770.0894 | 6714.2173
14 | 5011.042 | 6799.0317 | 5242.96 | 6715.1636
15 | 4982.7695 | 6778.9917 | 5678.4463 | 6813.7485
16 | 4750.223 | 6716.225 | 5252.53 | 6714.341
17 | 5255.7974 | 6779.537 | 5634.54 | 6745.9575
18 | 4749.5913 | 6779.4463 | 5715.8047 | 6747.3037
19 | 5314.558 | 6817.065 | 5698.2866 | 6779.7485
20 | 4774.669 | 6649.6504 | 5606.8696 | 6850.7954

**Comment by ryleung-solana** [comment]
Generally looks good - but have we tried other parameters, such as a larger batch size yet?

**Comment by t-nelson** [comment]
agreed that it'd be good to see a range of values. fewer runs would be fine

**Pull request closed without merging**
