### PR TITLE
Added leader id to the Entry struct

### PR DESCRIPTION
**Pull request by carllin**
Add leader id to the entries. Groundwork for fork detection.

### CODE REVIEW

**Comment by aeyakovenko** [comment]
@carllin this doesn't seem right, what is the purpose of having a leader id in the entry?

**Comment by aeyakovenko** [comment]
@carllin lets sync up on monday, i am not sure what you and @rob-solana had in mind. since the schedule is derived from the ledger, it might make sense to actually have the right leader sign their entries.  we should change the type to an enum then, one for Tick one for Entry

**Comment by garious** [comment]
Signing blobs, not entries might be the appropriate action. And this might more generically apply as the source_id in avalanche, not just the leader. @aeyakovenko, @carllin, @rob-solana

**Comment by aeyakovenko** [comment]
@garious i was thinking that initially, but if the schedule is ledger derived, the only correct ledger is signed by that leader, or virtual.  So having the signature in the Entry make sense

**Comment by aeyakovenko** [comment]
@carllin @garious this would also make it easy to reject unexpected ledgers.

**Comment by rob-solana** [comment]
I can't think of a legitimate attack on validator startup.  You can feed a validator anything, put it on any genesis block.  Do we have a problem with leader id at network startup?  The leader schedule needs to be calculable from genesis, an applicable long enough to get leader schedules steadied for rotation.

**Pull request closed without merging**
