### PR TITLE
pick the larger vec to extend for hash_dedup

### PR DESCRIPTION
**Pull request by HaoranYi**
#### Problem

Pick the larger vec to extend for hash_dedup

#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by jeffwashington** [comment]
why close this?

**Comment by HaoranYi** [comment]
I close it. 
I realized that what the PR did is wrong. The accumulated hash file vector must be ordered by the pubkey bin index, therefore they must be `reduced` in order. They can't be swapped based on size during reducing, which will mess up the order.

**Comment by jeffwashington** [comment]
well I think we have to be in order or we'll fail. so it must be preserving order. if pubkey b is in 'hashes' prior to pubkey 'a', then the merkle tree will be wrong. bins are sorted in pubkey order.

**Comment by jeffwashington** [comment]
if I imagine associative correctly:
(a, b) + (c,d) = (a) + (b, c, d) = () + (a, b, c) + (d)
I think they are in the same order.

**Pull request closed without merging**
