### PR TITLE
Change replicators to slot-based

### LINKED ISSUE #3217: Replicator should not use entry_height to download ledger blocks
#### Problem

entry_height is reset within slots, so a replicator can really only download from slot 0 at the moment.

#### Proposed Solution

Replicator should work from a range of slots to download.

### PR DESCRIPTION
**Pull request by sakridge**
#### Summary of Changes

Fixes #3217

### CODE REVIEW

**Comment by sakridge** [comment]
@sagar-solana heads up, working on this change.

**Comment by sagar-solana** [comment]
@sakridge, any plans for this PR? Maybe I can help?

**Comment by sakridge** [comment]
@sagar-solana yea. please take it over. I don't think i'll have time in the near-term.

**Comment by sakridge** [comment]
@sagar-solana or take whatever is useful to you.

**Pull request closed without merging**
