### PR TITLE
Update geyser interface to not require write locks

### PR DESCRIPTION
**Pull request by nickgarfield**
#### Problem
The current geyser plugin interface requires a mutable reference. This creates a massive bottleneck on plugins running geyser plugins that can cause nodes to slow down and fall behind the network. 

#### Summary of Changes
- In `geyser-plugin-interface`, it removes the `mut` reference on `update_account`, `update_slot_status`, `notify_end_of_startup`, `notification_transaction`, and `notify_block_metadata`.
- In `geyser-plugin-manager`, it replaces write locks with read locks on the plugin manager and changes plugin references to be non-mutable. 

Fixes #

### CODE REVIEW

**Comment by nickgarfield** [comment]
I was able to run this on local test validator + plugin and did not notice any issues. Will proceed with a canary on devnet / testnet.

**Comment by cavemanloverboy** [comment]
I think it would be good to understand why the plugin had these mut refs in the first place, and try to think through and see if it would break other plugins in a major way that isn't just changing these muts. At a first glance I can't think of any reason why these were mut in the first place.

**Comment by cavemanloverboy** [comment]
In particular, if a geyser plugin has its own state, like having a usize for number of times an event is seen, then they'll be forced to switch to atomics or a lock. This change is an improvement since the lock duration can be much shorter than the entire notify fn call.

**Comment by nickgarfield** [comment]
Just wanted to update that I cherry-picked this back onto v1.14 and canaried it on mainnet with one of our Clockwork nodes. No issues so far, and server still looks healthy. We need to monitor for longer, but this is an improvement over our other nodes which tend to fall behind after running for just a few hours.

**Review by lijunwangs — APPROVED** [review]
Looks good! Thanks for the help!

**Comment by CriesofCarrots** [comment]
@lijunwangs , no concerns about breaking the interface?

**Comment by lijunwangs** [comment]
> @lijunwangs , no concerns about breaking the interface?

Yes. The existing code will break when compiling. But I think that is the necessary evil. The performance is really critical here for the validator with plugins.

**Comment by cavemanloverboy** [comment]
It may be possible to remove the RwLock on the manager if all plugin functions (except for on_load and on_unload) only take a &self

**Comment by nickgarfield** [comment]
> It may be possible to remove the RwLock on the manager

This would actually be really big if we could remove the RwLock altogether. The read locks are significantly more expensive than a simple dereference. It looks like this can be done for all the notifiers, but the only other place where the write lock is used is in this `join()` function to call `unload()`. 

https://github.com/solana-labs/solana/blob/ee1717b24bb94682611029f7c007ee62df67c69a/geyser-plugin-manager/src/geyser_plugin_service.rs#L208

@lijunwangs if we also change the geyser interface from `unload(&mut self)` to `unload(&self)`, we could change all of the `Arc<RwLock<GeyserPluginManager>>` instances to a simple `Arc<GeyserPluginManager>` and save lots of time by avoiding the `.read()` calls. Do you see any hard reason to keep the mutable reference in `unload`?

**Comment by lijunwangs** [comment]
> > It may be possible to remove the RwLock on the manager
> 
> This would actually be really big if we could remove the RwLock altogether. The read locks are significantly more expensive than a simple dereference. It looks like this can be done for all the notifiers, but the only other place where the write lock is used is in this `join()` function to call `unload()`.
> 
> https://github.com/solana-labs/solana/blob/ee1717b24bb94682611029f7c007ee62df67c69a/geyser-plugin-manager/src/geyser_plugin_service.rs#L208
> 
> @lijunwangs if we also change the geyser interface from `unload(&mut self)` to `unload(&self)`, we could also change all of the `Arc<RwLock<GeyserPluginManager>>` instances to a simple `Arc<GeyserPluginManager>` and save lots of time by avoiding the `.read()` calls. Do you see any hard reason to keep the mutable reference in `unload`?

I don't think we can get rid of the RwLock on the connection manager to support dynamic load/unload of plugins. Fundamentally unload is incompatible with the other notifications. You cannot expect them to work simultaneously.

**Comment by cavemanloverboy** [comment]
If you only need a lock on unload, then you can have a mutex on a dummy type that is only taken when calling unload.

**Comment by nickgarfield** [comment]
> Removing the RwLock is essential.

At higher TPS it could definitely become issue, but the change from write locks to read locks seems to have at least resolved the immediate performance issues we were seeing. 

It looks like the plugin manager is marked mutable because of these `Vec::drain()` calls. I think we could leave `unload(&mut self)` unchanged and just move the RwLock from the plugin manager down to the individual `plugins` and `libs` properties. 

https://github.com/solana-labs/solana/blob/ee1717b24bb94682611029f7c007ee62df67c69a/geyser-plugin-manager/src/geyser_plugin_manager.rs#L45

**Comment by CriesofCarrots** [comment]
> Yes. The existing code will break when compiling. But I think that is the necessary evil. The performance is really critical here for the validator with plugins.

Okay, please don't backport this, then, and make sure there's lots of communication around the v1.16.0 minor release

**Comment by lijunwangs** [comment]
> > Yes. The existing code will break when compiling. But I think that is the necessary evil. The performance is really critical here for the validator with plugins.
> 
> Okay, please don't backport this, then, and make sure there's lots of communication around the v1.16.0 minor release

Sure. CC. @willhickey

**Comment by lijunwangs** [comment]
@willhickey How do we communicate such breaking changes at a release?

**Comment by staccDOTsol** [comment]
> I was able to run this with a local test validator + plugin and did not notice any issues. Will proceed with a canary on devnet / testnet.

morning! is this supposed to work on devnet now?

**Comment by staccDOTsol** [comment]
it may be my novice understanding of the ui that chatgpt built for me, but this not only shows the issue but also paints nice pretty picture at the same time :)

devnet node has been down ~24 hrs thus far, after the video

https://user-images.githubusercontent.com/22843601/220539247-d2c934da-cae9-449d-964e-6fa87de1e35c.mp4


https://user-images.githubusercontent.com/22843601/220539257-bffcb7b5-1204-4085-8775-a1ef24f04f57.mp4


https://user-images.githubusercontent.com/22843601/220539233-4b8c5670-4e1d-4a12-b930-e909e2ab311c.mp4


https://user-images.githubusercontent.com/22843601/220539240-9aa64d64-243d-4f98-bb4e-5e66247e2b32.mp4


https://user-images.githubusercontent.com/22843601/220539494-25d78c27-e76f-4a9d-952d-623c0fb5aa1e.mp4

**Pull request merged**
