### PR TITLE
Generate packet offsets for versioned messages

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
Sigverify does not support getting the correct packet offsets for the new versioned transactions.

#### Summary of Changes
Add detection for the message version prefix to properly handle versioned transactions in sigverify

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
downstream failure is unrelated to this change, this is ready for review!

**Review by t-nelson — APPROVED** [review]
lgtm!  It might be nice to adjust this a bit so the inevitable v1 in a smaller change set.  I won't block on that though

**Comment by jstarry** [comment]
> It might be nice to adjust this a bit so the inevitable v1 in a smaller change set. I won't block on that though

Can you elaborate on what you mean here? I intend to have versioning start at `0`

**Comment by t-nelson** [comment]
> Can you elaborate on what you mean here? I intend to have versioning start at 0

Sure!  My idea was just to set this code up so the addition of future versions is obvious.  Basically just a minor rework to a `match` over the version number and v0's implementation stuck under the corresponding arm

**Comment by jstarry** [comment]
> Sure! My idea was just to set this code up so the addition of future versions is obvious. Basically just a minor rework to a `match` over the version number and v0's implementation stuck under the corresponding arm

Ah, got it. Good call, updated.

**Review by t-nelson — APPROVED** [review]
re-re-lgtm!

**Pull request merged**
