### PR TITLE
Trace recycle() calls

### PR DESCRIPTION
**Pull request by rob-solana**

### CODE REVIEW

**Comment by rob-solana** [comment]
thought you might find this interesting, used it to find out that the validator's streamer IS punting blobs that are in the window to replicate_stage

**Comment by garious** [comment]
cc: #810

**Comment by garious** [comment]
@rob-solana, are you wanting to move forward with this PR? If so, it needs a rebase.

**Comment by rob-solana** [comment]
I'm ambivalent about whether to move this forward.  It has served its purpose, I think.

**Comment by rob-solana** [comment]
actually, I might as well land this.

**Pull request merged**
