### PR TITLE
fix: adds grab mint metadata for ft's

### PR DESCRIPTION
**Pull request by stellaw1**
#### Problem
Explorer needs to also grab mint metadata from metaplex for fungible tokens

#### Summary of Changes
Use the existing `Metadata.load` function from `@metaplex-foundation/mpl-token-metadata` that we use to fill the [metadata card](https://github.com/solana-labs/solana/blob/d6927365ed427cb21b9191fb0a48c51d031a8ab9/explorer/src/components/account/MetaplexMetadataCard.tsx) and use the new [fungible token metadata standard](https://docs.metaplex.com/token-metadata/specification#token-standards) to show wallet metadata on a mint page

Fixes #
#23748

### CODE REVIEW

**Comment by jstarry** [comment]
Unfortunately, I don't think we can merge this because it makes it too easy to spoof existing tokens. We need a way for the explorer to differentiate between the real mint and a fake mint.

**Comment by jstarry** [comment]
> Token-list today automerges everything even with collisions(there's 1055 collisions today). The problem seems to already exist.

That's not exactly true, there is dupe checking here: https://github.com/solana-labs/token-list/blob/16fc1b9736b3a75fcf2123deef33bc2afc843d62/automerge/automerge.go#L675

The problem is at least slightly handled on the token-list repo, if we display metaplex metadata for tokens on the explorer it opens the floodgates so we need counter measures. For now we could maybe just prepend "Unverified: " to token names that are retrieved from metadata

**Review by jstarry — COMMENTED** [review]
I think the "Unverified: " prefix is actually too subtle. Can you try adding a banner and sharing a screenshot of the result?

```html
        <div className="alert alert-danger alert-scam" role="alert">
          Warning! This token uses custom metadata and may have spoofed its name and logo to look like another token.
        </div>
        ```

**Comment by stellaw1** [comment]
of course! This is what it looks like

image

**Comment by jstarry** [comment]
Looks scary, perfect!

**Pull request merged**
