### PR TITLE
Switch to crossbeam channels for retransmit/streamer

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Retransmit could be faster without a lock. mpsc needs a lock for multiple consumers and we want multiple retransmit threads.

#### Summary of Changes

Switch to crossbeam crate for streamer channels.

Fixes #

### CODE REVIEW

**Comment by sakridge** [comment]
bench-streamer:
crossbeam:
performance: 870763.3880745815

original:
performance: 877445.2977628628

**Comment by sagar-solana** [comment]
> bench-streamer:
> crossbeam:
> performance: 870763.3880745815
> 
> original:
> performance: 877445.2977628628

huh, its worse somehow. odd. I guess crossbeam is sync'ing internally somewhere?

**Comment by sagar-solana** [comment]
Have you seen this? 
https://github.com/crossbeam-rs/crossbeam-channel/tree/master/benchmarks

**Comment by sakridge** [comment]
Also, bench_retransmitter gives 3.95-3.99ms for master vs. 4.002ms for crossbeam.

**Comment by sagar-solana** [comment]
probably not worth chasing then?

**Comment by sakridge** [comment]
> probably not worth chasing then?

true..

**Comment by sakridge** [comment]
Perf seems worse..

**Pull request closed without merging**
