### PR TITLE
fix tests for load returns None for zero lamport

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem

if we modify the load api to always return None for zero lamport accounts, then these tests will break.

#### Summary of Changes

Add helper functions to verify the index is as expected and the storage or write cache is as expected. This gives us the flexibility to change the behavior of load without breaking tests.

Fixes #

### CODE REVIEW

**Comment by jeffwashington** [comment]
@carllin , @brooksprumo sorry to wrangle you both. There can be subtle differences here and I want to make sure I'm still testing what I think the tests were intending to test.

**Comment by carllin** [comment]
Will this also affect getBalance() calls from RPC: https://github.com/jstarry/solana/blob/f91530e102c978ab2903943cc06454db79b961b1/rpc/src/rpc.rs#L635-L660? Or did zero lamport accounts always return 0 there

**Comment by jeffwashington** [comment]
everything from accounts/bank and up already converted zero lamport accounts to none

**Comment by jeffwashington** [comment]
https://github.com/solana-labs/solana/blob/981c9d07a40166460bd500878005099c024c76b8/runtime/src/accounts.rs#L657

**Comment by carllin** [comment]
Can we instead introduce a test-only api that differentiates between zero lamport accounts/non existing accounts?

**Comment by jeffwashington** [comment]
like #28271

**Comment by jeffwashington** [comment]
These are overlapping changes where I'm trying to make sense of the world.
Introducing this test api to support returning Some(empty) just requires we keep some deeper code alive that has a choice of whether to return None or Some(empty).

**Comment by jeffwashington** [comment]
https://github.com/solana-labs/solana/blob/1bd4a8c0fd693ddbc0376a95ff2905e8b19e293b/runtime/src/accounts_db.rs#L5174-L5180

**Comment by jeffwashington** [comment]
that's what the alive code would probably look like. (and another instance in this same function).

**Comment by jeffwashington** [comment]
we can certainly do either option. I was just trying to separate out here what it was that the tests were testing so we could support it no matter what. 
I was hoping to make no load api return Some(empty) ever to simplify all codepaths.

**Comment by jeffwashington** [comment]
> test-only get/load api

The trade off here is duplication of code for a test-only case so that we keep the option out of the runtime code, or sharing the same code, but providing the option. I want to make sure the tests are still testing enough runtime code and testing the other related code (clean, etc.) that still ensure in the future that we are behaving correctly.
When we duplicate code for tests, it could drift over time, not necessarily continuing to test the load code relative to the clean code like it does today.
I'm not sure the right choice to choose.
I'd probably share the code and leave the option in some code and try to get rid of any api that exposes the option.

**Pull request closed without merging**
