### PR TITLE
Revert "Run featurized tests on sub-packages"

### PR DESCRIPTION
**Pull request by garious**
Reverts solana-labs/solana#2867

See if this is what's causing our CI problems.

### CODE REVIEW

**Comment by jackcmay** [comment]
Looks like stable-perf is getting further than it was, ill try and recreate the issue locally.  @greg is there anything you can think of that would cause CI to fail with your changes and not on tip?

**Comment by garious** [comment]
I can't think of anything offhand.  The most noteworthy thing about those tests is that they assume the Vote program is built.  A stale Vote program would cause all sorts of trouble.

**Comment by jackcmay** [comment]
@greg, is there an explicit dependency on the vote program?

**Comment by garious** [comment]
Going to work on resolving the dependency issues. thanks @jackcmay!

**Pull request closed without merging**
