### PR TITLE
[zk-token-proof] Add benches for proof instructions

### PR DESCRIPTION
**Pull request by samkim-crypto**
#### Problem
The instructions for the zk-token-proof program have been assigned compute units, but there is no benchmark tests for these instructions.

#### Summary of Changes
Added benchmark code for the zk-token-proof program.

Fixes #

### CODE REVIEW

**Comment by samkim-crypto** [comment]
@taozhu-chicago, can I ask you for some advise in this PR?

I wanted to add the benchmarks that I used test and assign the compute units for the zk-token-proof [instructions](https://github.com/solana-labs/solana/blob/master/zk-token-sdk/src/zk_token_proof_instruction.rs). 

The processor for these instructions basically works as follows:
1. Verify the zk proof ([here](https://github.com/solana-labs/solana/blob/master/programs/zk-token-proof/src/lib.rs#L32-L35))
2. (optionally) Stores some data in an account if the proof succeeds [here](https://github.com/solana-labs/solana/blob/master/programs/zk-token-proof/src/lib.rs#L37-L68))

Currently, the benchmark code that I added in this PR tests step 1. Zkp's are expensive, so I imagine step 2 above is going to be very small compared to step 1, but do you think the bench also take into account step 2 as well (and CU's updated)? If so, are there examples of benchmarking code that tests native programs copying data into an account?

**Comment by taozhu-chicago** [comment]
> so I imagine step 2 above is going to be very small compared to step 1, but do you think the bench also take into account step 2 as well (and CU's updated)? If so, are there examples of benchmarking code that tests native programs copying data into an account?

I would also assume writing _some_ data into account would have relatively small cost. iirc @alessandrod did bench tests on loading account with different size of data, loading small amount of data (less than few Kilo bytes ?) costs almost nothing; but as data grew larger, the cost increase exponentially. I am not aware of other bench test on native programs copying data to account.

**Comment by samkim-crypto** [comment]
Had a direct communication with @alessandrod. The cost of storing context data into a specified context data account should be free given that:
- The context data is at most 650 bytes
- The context state account should be pre-allocated via the system program and the proof program simply writes data to this account. The cost of writing this data to the account should already be accounted for in the system program.

For this PR, I will just include the benchmark code. On a follow-up PR, I will address:
- https://github.com/solana-labs/solana/pull/31788#discussion_r1205886821
- https://github.com/solana-labs/solana/pull/31808#discussion_r1205946413

**Review by CriesofCarrots — COMMENTED** [review]
Should we add these [to CI](https://github.com/solana-labs/solana/tree/master/ci/bench)?

**Comment by yihau** [comment]
I think if we want to add this one to CI. part1.sh and part2.sh are both okay to be the candidate. their test time are similar. btw, we don't do too much thing to those benchmark results so I don't have too much can share atm. we can add them first then rerog later!

**Comment by samkim-crypto** [comment]
Okay thanks! I will add them to to the CI. 

@yihau One question is, does the format of the output of the benches to append to the logs important? The bench scripts in the ci outputs json format, but I can't seem to find that option available with `criterion` without using the `cargo-criterion` cli tool. Maybe for this PR, I can just add the scripts to run the benchmark tests and then we can address the logs on a separate PR?

**Comment by yihau** [comment]
sure. afaik banking-bench and accounts-bench are not json output format either. 🪖

**Comment by yihau** [comment]
the CI part looks good to me 🫶

**Review by CriesofCarrots — APPROVED** [review]

**Pull request merged**
