### PR TITLE
Fixed bug with mishmash of traces from different programs in single log

### PR DESCRIPTION
**Pull request by dk-neon**
#### Problem
When one executed program invoked another (sub)program, the trace log of the callee was written to the same log of the caller. There were no markers of which record is related to which program.

#### Summary of Changes
Transformed trace log to trace log stack. Now each instruction being executed has its own trace log.

#### Possible Drawback
The trace log of the callee is being dropped after returning execution to the caller. It's not a problem when we analyze logs just after instruction execution but having full logs might be useful in the future.

We in Neon Labs are implementing BPF tracing plugins support. For our implementation it's enough to get trace just after current (sub)program execution and sub-program's trace log is not needed after returning to a caller.

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
@Lichtso @alessandrod , can you one of you please look at this?

**Comment by dk-neon** [comment]
> `TransactionContext` is meant for info that should be accessible to the program (hence why it is located in the SDK). So the trace log should stay in the `InvokeContext`. We can still split it into one log per `InstructionContext` by simply having a `Vec<Vec<TraceLogEntry>>` in `InvokeContext` and indexing it in the same order as `InstructionContext`.

Thanks for your note, I will update my implementation.

**Comment by Lichtso** [comment]
Another option might be to add it to [`SyscallContext`](https://github.com/solana-labs/solana/blob/6e4ecc67587f8ff277a54b08d6ec229080354df7/program-runtime/src/invoke_context.rs#L94). That one is part of the `InvokeContext` and already synchronized with the `InstructionContext` push and pop. The downside however is that it gets deleted and thus wouldn't be available at the end of the transaction. So it is probably best to implement the `Vec<Vec<TraceLogEntry>>` thing.

**Comment by Lichtso** [comment]
@dk-neon Can you move `trace_log` from transaction_context.rs back into invoke_context.rs as discussed?

**Comment by dk-neon** [comment]
> @dk-neon Can you move `trace_log` from transaction_context.rs back into invoke_context.rs as discussed?

Yes, I'm working on it right now and I'm going to finish it today.

**Comment by dk-neon** [comment]
@Lichtso I've rewritten my solution as discussed, it became even simpler. Please take a look!

**Comment by Lichtso** [comment]
> --> programs/sbf/tests/programs.rs:151:68
>     |
> 151 |                     trace_log = Some(vm.env.context_object_pointer.trace_log.clone());
>     |                                                                    ^^^^^^^^^ unknown field
>     |
> 

Should be `vm.env.context_object_pointer.trace_log_stack.last().unwrap()` here as well, I think.

**Comment by dk-neon** [comment]
> > --> programs/sbf/tests/programs.rs:151:68
> > |
> > 151 |                     trace_log = Some(vm.env.context_object_pointer.trace_log.clone());
> > |                                                                    ^^^^^^^^^ unknown field
> > |
> 
> Should be `vm.env.context_object_pointer.trace_log_stack.last().unwrap()` here as well, I think.

Thank you! I've fixed this and locally all tests from this command have passed, please run the CI.

**Review by Lichtso — APPROVED** [review]

**Pull request merged**
