### PR TITLE
Use the accounts and status cache from parents up to finalized bank for calls.

### PR DESCRIPTION
**Pull request by aeyakovenko**
#### Problem

Bank api calls do not fall through to parent banks for account and signature status retrieval.

#### Summary of Changes

Use the status cache and accounts from the parents to query for data.

Fixes #

### CODE REVIEW

**Comment by garious** [comment]
This awesome, but needs a boat load of unit-tests. We can't expect this kind of thing to be implicitly covered by other tests because of how often small unit-tests operate within a single entry of a single fork.

**Comment by aeyakovenko** [comment]
> This awesome, but needs a boat load of unit-tests. We can't expect this kind of thing to be implicitly covered by other tests because of how often small unit-tests operate within a single entry of a single fork.

I think just `Bank::parents` need a unit test?  the rest of the apis are covered by their respected modules.   Because of how borrow checker works, the pointer vector needs to be in the same stack frame as the call, so that part is hard to test on its own.

**Comment by garious** [comment]
Sure. For parents(), see test_bank_forks_parent for a similar test.

**Comment by aeyakovenko** [comment]
@garious added tests that make sure that parent's data is actually used as expected.

**Pull request merged**
