### PR TITLE
make runtime depend on bpf_loader

### PR DESCRIPTION
**Pull request by rob-solana**
#### Problem
 wallet deploy_program test fails without cargo build --all

 #### Summary of Changes
 make runtime depend on bpf_loader

### CODE REVIEW

**Comment by rob-solana** [comment]
STR
```
[rwalker@ruffian solana]$ git clean -xdf
[rwalker@ruffian solana]$ cargo test --manifest-path wallet/Cargo.toml deploy_program -- --nocapture --test-threads 1
```

**Comment by rob-solana** [comment]
@jackcmay I'm stuck.  I can't figure out why coverage is barfing...

**Comment by rob-solana** [comment]
rebased

**Comment by jackcmay** [comment]
@rob-solana I'm looking into the coverage failure

**Comment by rob-solana** [comment]
I think I've figured it out, looks like storage's genesis_utils, which I want to remove anyway

**Comment by rob-solana** [comment]
@sagar-solana most recent commit is the one I care that you review

**Comment by jackcmay** [comment]
@rob-solana Here is an alternative that splits the bpf loader to match the rest of the programs.
https://github.com/solana-labs/solana/pull/4636

**Comment by rob-solana** [comment]
> @rob-solana Here is an alternative that splits the bpf loader to match the rest of the programs.
> #4636

nice.  that's good work, too.

**Pull request merged**
