### PR TITLE
bump shlex to 1.3.0

### PR DESCRIPTION
**Pull request by yihau**
#### Problem

audit failed: https://buildkite.com/solana-labs/solana/builds/107049#018d3232-7df3-45e2-b6b8-d08915431674

#### Summary of Changes

bump shlex to 1.3.0

### CODE REVIEW

**Review by CriesofCarrots — APPROVED** [review]

**Comment by t-nelson** [comment]
omg another dep that cba to tag releases :my-eyes-are-bleeding:

**Comment by t-nelson** [comment]
looks like 1.2.1 is sufficient? or is the advisory misspecified?

**Comment by t-nelson** [comment]
?????????????????????

Screenshot from 2024-01-22 12-08-27

**Comment by yihau** [comment]
oh. it's green. I think it should be okay to merge this one to unblock master!

**Comment by t-nelson** [comment]
> IMO a different version for v1.17 shouldn't hold up a merge for master

that means we're _not_ testing a dependency change before sending it to MB. dunno how that can be interpreted as safe

**Pull request merged**
