### PR TITLE
Support solana-web3.js batching

### PR DESCRIPTION
**Pull request by epicfaace**
#### Summary of Changes

Fixes https://github.com/solana-labs/solana/issues/23627 by adding a config option autoBatch to Connection that, if set to true, batches all JSON RPC requests so they are sent every 50ms.

### CODE REVIEW

**Comment by t-nelson** [comment]
we can't break API like this.  i don't think we want this to be the default behavior anyway (imposed batching delay).  can you make it a separate function?

**Comment by epicfaace** [comment]
> we can't break API like this. i don't think we want this to be the default behavior anyway (imposed batching delay). can you make it a separate function?

Hi @t-nelson -- this isn't a breaking change, the default behavior is still the same as before. The batching behavior is only triggered when you pass in `autoBatch: true` to the connection options. Does that work?

**Comment by epicfaace** [comment]
> this isn't a breaking change, the default behavior is still the same as before. The batching behavior is only triggered when you pass in `autoBatch: true` to the connection options. Does that work?

Hi @t-nelson -- see my comment above. Does this work for you? Let me know if you'd like me to make any additional changes.

**Review by steveluscher — CHANGES_REQUESTED** [review]
Neat! I like batching, in principle. _If_ we do it, we should do it with a _global lock_ that people can opt into in _userspace_.

For a long time, this is how React itself performed batching.

```
React.unstable_batchedUpdates(() => {
  setSomeState(true);
  callSomeMethodThatMaybeSetsSomeState(123);
  if (something) {
    setSomething(something);
  }
});
```

Essentially, the implementation was something like:

```
function unstable_batchedUpdates(cb) {
  _batch = true;
  try {
    cb();
  } finally {
    _batch = false;
  }
}
```

…and that `_batch` variable was accessible by whatever needed to make the batch-or-not-to-batch decision.

Ours might look something like this:

```
connection.batchRequests(() => {
  connection.requestAirdrop();
  methodThatMightMakeARequest();
  if (needBlockTime) {
    connection.getBlockTime();
  }
});
```

From there, there would be a _ton_ of work to actually make that work.

Things that would need to be resolved:

* Right now `_rpcBatchRequest` is written in such a way that one error nukes the entire batch. It doesn't understand that the return value of a batch is an _array_ of the successes and and an _array_ of the errors. If even one request in a batch errors, it nukes the whole promise: https://github.com/steveluscher/solana/blob/5eae7b708c45979cc3573e6be2b932e87bd9ec38/web3.js/src/connection.ts#L1061-L1067. That will need to be fixed. Mental note for me that this sort of means `getParsedTransactions` is broken, for some definition of broken.
* The API I've suggested above is _really_ confusing if you're used to request method being async. How would you write the above if `methodThatMightMakeARequest` _depended_ on `requestAirdrop` finishing first? Is that two batches now? Is it even possible to build a dependency tree of which calls depend on which results, so that you can prepare exactly the number of batches necessary?

**Comment by epicfaace** [comment]
Still working on this

**Comment by epicfaace** [comment]
> _If_ we do it, we should do it with a _global lock_ that people can opt into in _userspace_.

@steveluscher thanks for the feedback. Isn't that (global lock people can opt into in userspace) what this PR enables? Or did you have something else in mind?

**Comment by steveluscher** [comment]
This PR can be implemented as a `customFetch` on `Connection`! You should repurpose it as such, and open source it.

More detail, here: https://github.com/solana-labs/solana/issues/23627#issuecomment-1147770729

**Pull request closed without merging**
