### PR TITLE
Dos all the things

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

No tools to dos

#### Summary of Changes

Add a tool to send random inputs to validators on gossip.

Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
Can you please swap out https://github.com/solana-labs/solana/blob/29abfebb681fb94c288cc76ebee064825bb04154/system-test/stability-testcases/gossip-dos-test.sh#L40 to use `dos` too?

**Comment by sakridge** [comment]
> Can you please swap out
> 
> https://github.com/solana-labs/solana/blob/29abfebb681fb94c288cc76ebee064825bb04154/system-test/stability-testcases/gossip-dos-test.sh#L40
> 
> to use `dos` too?

How can I verify it's doing the right thing? cc @danpaul000

**Comment by mvines** [comment]
> > Can you please swap out
> > https://github.com/solana-labs/solana/blob/29abfebb681fb94c288cc76ebee064825bb04154/system-test/stability-testcases/gossip-dos-test.sh#L40
> > 
> > to use `dos` too?
> 
> How can I verify it's doing the right thing? cc @danpaul000

Just that it doesn't crash after 10 minutes of spamming

**Comment by sakridge** [comment]
> > > Can you please swap out
> > > https://github.com/solana-labs/solana/blob/29abfebb681fb94c288cc76ebee064825bb04154/system-test/stability-testcases/gossip-dos-test.sh#L40
> > > 
> > > to use `dos` too?
> > 
> > 
> > How can I verify it's doing the right thing? cc @danpaul000
> 
> Just that it doesn't crash after 10 minutes of spamming

Ok, I was more worried about the new version not doing anything and thus always passing, than the test failling. It seems to be working in both ways in that i see lots of gossip messages, and the validator seems ok.

**Comment by danpaul000** [comment]
> > > > Can you please swap out
> > > > https://github.com/solana-labs/solana/blob/29abfebb681fb94c288cc76ebee064825bb04154/system-test/stability-testcases/gossip-dos-test.sh#L40
> > > > 
> > > > to use `dos` too?
> > > 
> > > 
> > > How can I verify it's doing the right thing? cc @danpaul000
> > 
> > 
> > Just that it doesn't crash after 10 minutes of spamming
> 
> Ok, I was more worried about the new version not doing anything and thus always passing, than the test failling. It seems to be working in both ways in that i see lots of gossip messages, and the validator seems ok.

Running the test against your latest commit here: https://buildkite.com/solana-labs/system-performance-tests/builds/1510

Instructions to reproduce this are in the doc pinned to the #performance-results channel topic (https://docs.google.com/document/d/1h1nYR7uwCNxntkKCvbsx64rVPGhhcH1Ub47rVYYVFZw/edit?usp=sharing) .  See the section called "Steps to Run a Pre-Configured Performance Test (Nightly/Weekly Regressions or On-Demand)"

**Pull request merged**
