### PR TITLE
refactor cost_update code path

### PR DESCRIPTION
**Pull request by taozhu-chicago**
#### Problem
Before add back EMA cost calculation, want to clean up the code path.

#### Summary of Changes
- code refactoring
- using receiver.iter instead of `try_iter` to remove the need of passing `exit` flag;
- make `upsert...` ops infallible
- add trigger to report large changes in cost calculation 

Fixes #

### CODE REVIEW

**Comment by t-nelson** [comment]
there are four changes in the description, why aren't their four commits/PRs? :sweat_smile: 

way easier to review a 500 line diff when the changes are in concise, isolated chunks

**Comment by jstarry** [comment]
Agreed with @t-nelson. It's also best not to do refactoring and code changes in the same PR

**Comment by taozhu-chicago** [comment]
Not disagree, breaking it up to smaller PRs. First 2: #23645  #23647

**Comment by taozhu-chicago** [comment]
> Not disagree, breaking it up to smaller PRs: #23645, #23647, #23651, #23654, #23656

@t-nelson @jstarry @carllin Sorry for spamming your inbox today. I hold off one more until above PRs are merged. Thanks for reviewing.

**Comment by t-nelson** [comment]
np! same integral, easier to consume.  do any of these depend on others?  Looking for order of review optimization :slightly_smiling_face: 

Thanks for breaking this up!

**Comment by taozhu-chicago** [comment]
> do any of these depend on others? Looking for order of review optimization 🙂

No dependencies between them, there will be some merge conflicts since they touch same code base, but shouldn't be big deal. Thanks for taking time to review these changes.

**Comment by t-nelson** [comment]
thanks! I'll start this evening and go by PR# in that case :slightly_smiling_face:

**Comment by taozhu-chicago** [comment]
broke into smaller PRs, closing this one

**Pull request closed without merging**
