### PR TITLE
fix double count of account index del stats

### PR DESCRIPTION
**Pull request by HaoranYi**
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by brooksprumo** [comment]
Where's the first/other call to `self.stats().insert_or_delete_mem(false, self.bin)`

**Comment by HaoranYi** [comment]
> Where's the first/other call to `self.stats().insert_or_delete_mem(false, self.bin)`?

It is called on line 297, inside `remove_if_slot_list_empty_value`

**Comment by brooksprumo** [comment]
> > Where's the first/other call to `self.stats().insert_or_delete_mem(false, self.bin)`?
> 
> It is called on line 297, inside `remove_if_slot_list_empty_value`

Gotcha, thanks! I see the issue now.

Since `remove_if_slot_list_empty_value()` is just a fancy `.is_empty()` _and_ doesn't perform a remove at all
https://github.com/solana-labs/solana/blob/eab4bce668b978fb719b4ccf0d5200b316976c0c/runtime/src/in_mem_accounts_index.rs#L260-L267
I think a better solution would be to remove `remove_if_slot_list_empty_value()` and have the callers do `.is_empty()` directly. Then the calls to `insert_or_delete_mem(false, ...)` will be (1) obvious and (2) not double counted. Wdyt?

**Comment by HaoranYi** [comment]
> > > Where's the first/other call to `self.stats().insert_or_delete_mem(false, self.bin)`?
> > 
> > 
> > It is called on line 297, inside `remove_if_slot_list_empty_value`
> 
> Gotcha, thanks! I see the issue now.
> 
> Since `remove_if_slot_list_empty_value()` is just a fancy `.is_empty()` _and_ doesn't perform a remove at all
> 
> https://github.com/solana-labs/solana/blob/eab4bce668b978fb719b4ccf0d5200b316976c0c/runtime/src/in_mem_accounts_index.rs#L260-L267
> 
> 
> I think a better solution would be to remove `remove_if_slot_list_empty_value()` and have the callers do `.is_empty()` directly. Then the calls to `insert_or_delete_mem(false, ...)` will be (1) obvious and (2) not double counted. Wdyt?

Yes. Agree. since `remove_if_slot_list_empty_value()` is used in multiple places, Can we leave it for another refacotr pull request?

**Review by brooksprumo — APPROVED** [review]

**Comment by brooksprumo** [comment]
> I think the reason for `remove_if_slot_list_empty_value`, an optimization, to shorten the holding of the lock on slot_list.

The read lock should be dropped at the end of the expression though.

**Comment by HaoranYi** [comment]
yeah. I think you are right.

**Pull request merged**
