### PR TITLE
Fullnode rpc to exit with unsafe config

### PR DESCRIPTION
**Pull request by aeyakovenko**
#### Problem

Leader failure fault tolerance for an in-process LocalCluster requires the node to expose an exit mechanism via an RPC.  This mechanism is only available with the JsonRpcConfig::Unsafe fullnode option.

#### Summary of Changes

* Config option to guard availability of the exit rpc
* test to check that default is safe
* test to verify nodes exit and fails to exit with the safe config
* pass an `exit` signal from the fullnode through to TPU and TVU

Fixes #

### CODE REVIEW

**Comment by garious** [comment]
Can you find a better term than "unsafe"? Rust uses that term for the user to communicate to the compiler "your memory-safety rules are too conservative, back off, I got this".

**Comment by aeyakovenko** [comment]
@garious, debug seems to benign.  A super safe way to do this would be to have 1 config item per “unsafe” test.  So I could call this DebugRpcFullnodeExit

**Comment by garious** [comment]
sure or "TestOnly"

**Comment by mvines** [comment]
I'd rather the flag be very specific, `DebugEnableRpcFullnodeExit`, or something.   This avoids creating a generic home for people to later sneak in other unrelated flags.  

But this change overall is great, once it lands I'll expose it as a flag to the fullnode program since I'd like to use it in the bash integration tests and network deployment scripts

**Pull request merged**
