### PR TITLE
Fuck this whole web3.js thing

### PR DESCRIPTION
**Pull request by steveluscher**
burn-koala

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Really? That's in our commit history for all time now?

**Comment by platonicsocrates** [comment]
> Really? That's in our commit history for all time now?

funniest thing I've seen all day 😂

keep buidling!

**Comment by PaulFidika** [comment]
Good first issue

**Comment by nicholas-ewasiuk** [comment]
🫡

**Comment by codebender828** [comment]
lol

**Pull request merged**
