### PR TITLE
Pass SOLANA_METRICS_CONFIG along to oom-monitor.sh

### LINKED ISSUE #5002: OOM events are not getting reported to metrics
eg:
```bash
solana@tds-solana-com-blockstreamer:~/solana$ cat oom-monitor.log 
Out of memory event detected, solana-validato killed
Influx data point: oom-killer,victim=solana-validato,hostname=tds-solana-com-blockstreamer killed=1
Influx user credentials not found
Out of memory event detected, solana-validato killed
Influx data point: oom-killer,victim=solana-validato,hostname=tds-solana-com-blockstreamer killed=1
Influx user credentials not found
```

The "Influx user credentials not found" error indicates that the event was not sent to metrics

### PR DESCRIPTION
**Pull request by mvines**
Fixes #5002

@danpaul000 - FYI

### CODE REVIEW

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Comment by mvines** [comment]
> Isn't SOLANA_METRICS_CONFIG an exported env var?

Normally yes.  But that `sudo` filters it out

**Comment by danpaul000** [comment]
> > Isn't SOLANA_METRICS_CONFIG an exported env var?
> 
> Normally yes. But that `sudo` filters it out

Got it, thanks.

**Comment by solana-grimes** [comment]
:broken_heart: Unable to automerge due to CI failure

**Pull request merged**
