### PR TITLE
Improve logging on various error conditions

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by mvines** [comment]
`tvu::tests::test_replicate` failed

**Comment by garious** [comment]
A lot of those aren't server errors. They're client errors that the server caught. `debug!` seemed appropriate.

**Comment by mvines** [comment]
Can I meet you in the middle with `info!`?  While they are client errors, having them visible by default is super helpful when trying to figure out why your transaction or some other client-operation failed

**Comment by mvines** [comment]
> Can I meet you in the middle with info!

I'm hearing a yes, good enough for me :)

**Pull request merged**
