### PR TITLE
Update and fix transaction error documentation

### PR DESCRIPTION
**Pull request by jackcmay**
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by jackcmay** [comment]
How about phase two?  And if switching transaction to `thiserror` how about switching instruction error as well?

**Comment by garious** [comment]
sure

**Comment by jackcmay** [comment]
> How about switching it to thiserror and adding a test with those nice descriptions in an error message?

@garious What tests did you have in mind?

**Comment by garious** [comment]
Ideally, something very high-level, like a CLI call that provides a detailed error message.

**Pull request merged**
