### PR TITLE
Add release-with-debug profile

### PR DESCRIPTION
**Pull request by willhickey**
#### Problem
Canaries should build the validator with debug info. Once the profile is added a separate PR to the cluster ops repo will update the canary build script to use the new profile.

@steviez anything else we should include in this profile to facilitate debugging?

### CODE REVIEW

**Review by steviez — COMMENTED** [review]
I had previously been using a flag to force frame pointers; however, it seems those may not be necessary per this Discord comment:
https://discord.com/channels/428295358100013066/910937142182682656/1147063924060074045

So I think this may be sufficient. @alessandrod - Are you aware of any other flags we should be using?

Also, there was some chatter in Discord about generating split debug symbols + posting those somewhere (to avoid bloating actual binary size). If we want to tie that in here, we might consider adding:
https://doc.rust-lang.org/cargo/reference/profiles.html#split-debuginfo
```
split-debuginfo = "packed"
```

**Comment by alessandrod** [comment]
I think we should probably go with
```
debug = "2"
split-debuginfo = "packed"
```

When compiling with the dev profile rust uses debug = "2" so it's probably the most tested path. And we're putting it in a separate file so unless it blows up file size, we might as well generate as much as possible to help debugging.

**Comment by steviez** [comment]
> When compiling with the dev profile rust uses debug = "2" so it's probably the most tested path. And we're putting it in a separate file so unless it blows up file size, we might as well generate as much as possible to help debugging.

Agreed. Looks like "2" is equivalent to "true" so think Will just needs to add the split debug line

**Comment by alessandrod** [comment]
> Agreed. Looks like "2" is equivalent to "true" 

Oh sweet, TIL

**Comment by willhickey** [comment]
This works as is but I still need to update scripts/cargo-install-all.sh so it allows a --profile arg.

I'm going to be OOO the next couple of weeks. If anyone wants this as is feel free to merge it. Otherwise I'll make the script changes when I get back.

**Review by steviez — APPROVED** [review]
This is essentially what I have been using and looks like a good starting point. Can always add stuff later

**Pull request merged**
