### PR TITLE
Refactor storage stage to only use one work thread

### LINKED ISSUE #3986: Storage Stage uses an internal thread to send transactions
#### Problem

Storage stage uses a second thread internally just to send transactions to the leader. 

#### Proposed Solution

Maybe we can get rid of this thread and send the transactions from the main storage loop.

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

see https://github.com/solana-labs/solana/issues/3986

#### Summary of Changes

Minor cleanup of storage stage

Fixes #3986

### CODE REVIEW

**Comment by sagar-solana** [comment]
> No error handling or retry of failed transactions possible and doing a bunch of IO work in the mining thread will reduce the time you have to do the storage validation.

Hardly any IO work, no? Just sending out 1 tx at a time with no waiting around. Not polling for txs to show up could be an issue and a regression from before, but it's an issue that every other system level transaction (like votes) has.

**Comment by sakridge** [comment]
> > No error handling or retry of failed transactions possible and doing a bunch of IO work in the mining thread will reduce the time you have to do the storage validation.
> 
> Hardly any IO work, no? Just sending out 1 tx at a time with no waiting around. Not polling for txs to show up could be an issue and a regression from before, but it's an issue that every other system level transaction (like votes) has.

We are already doing no IO work in the processing thread, why make it worse? I don't get the argument that since other systems have the problem then it's ok to have it here. Is there some plan to fix that?

**Comment by sagar-solana** [comment]
> We are already doing no IO work in the processing thread, why make it worse? I don't get the argument that since other systems have the problem then it's ok to have it here. Is there some plan to fix that?

I mean that the IO should have no perceivable impact. We could go back to having a dedicated tx tread later if we conclude this has a performance impact. 

As for the vote delivery thing, yeah I agree that's not justified. Honestly there's no reason the tx should just disappear or fail. That's out hope with Votes as well. We could start gossipping these too if we see that delivery is an issue or that they need rapid processing. If you're really opposed to this approach for the reasons you mentioned I can just scrap it. Your call :)

**Comment by sakridge** [comment]
> Honestly there's no reason the tx should just disappear or fail. 

There's a bunch of reasons. UDP packet loss is very common especially in large networks and on flaky open internet connections. The network can just be bogged down and the leader will just drop it. Or it gets queued for too long and gets BlockHashTooOld. There are a ton of paths for transactions to get dropped.

**Comment by sagar-solana** [comment]
hah, fair enough. We can stick it onto gossip along side votes then. Votes have a rapid processing pathway.

**Comment by sakridge** [comment]
> hah, fair enough. We can stick it onto gossip along side votes then. Votes have a rapid processing pathway.

Ok, these are not as latency-sensitive as votes are for the network to move forward, but it's not a bad idea.

**Pull request closed without merging**
