### PR TITLE
Upgrade to Rust 1.51.0

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by mvines** [comment]
Some new clippy to deal with...

**Comment by mvines** [comment]
@behzadnouri - hey could I get you to look at the `test_pull_request_time_pruning` failure here?   When I run this test locally with this PR it passes.   Maybe a timing issue of some sort?  The failure seems consistent in CI and `cluster_info.rs` wasn't touched in this PR

**Comment by behzadnouri** [comment]
> @behzadnouri - hey could I get you to look at the `test_pull_request_time_pruning` failure here?   When I run this test locally with this PR it passes.   Maybe a timing issue of some sort?  The failure seems consistent in CI and `cluster_info.rs` wasn't touched in this PR

yes, i have a pending pr for this.
Can you please change *2 to *4 in this line:

https://github.com/solana-labs/solana/blob/cfe7a4340b9ebce91c8bd80bf37a6782fe738975/core/src/cluster_info.rs#L4769

**Comment by mvines** [comment]
> yes, I have a pending pr for this.
> Can you please try changing *2 to *4 in below line?

wilco.  Thanks!

**Comment by ryoqun** [comment]
cool, we can finally use const generics. thanks for working on this :)

**Pull request merged**
