### PR TITLE
Add SolFlare guide to docs

### PR DESCRIPTION
**Pull request by danpaul000**
#### Problem
There is no reference or guide to SolFlare in the docs

#### Summary of Changes
Add it.

### CODE REVIEW

**Comment by danpaul000** [comment]
@garious I didn't add anything for staking yet, but it's a pretty straightforward content add, though your initial request didn't necessarily include that ask.  Does this layout draw enough distinction between Keystore vs Ledger?  90% of SolFlare use is identical regardless of the utility which holds the private key.

**Comment by garious** [comment]
@aeyakovenko, is this what you had in mind?

**Comment by garious** [comment]
Let's wait for Anatoly's feedback here, but once he's good with the structure, I'm thinking screenshots would help a bunch.

**Comment by aeyakovenko** [comment]
I think so. I think ledger folks wanted it to be on the site solflare site directly

**Comment by danpaul000** [comment]
"Them" being solflare or them being Ledger?  I really don't want us to be responsible for content on someone else's site.  We need some SolFlare docs on our main docs page anyway.

**Comment by danpaul000** [comment]
I've added staking info, but am going to hold off on making and editing screenshots right now, as its a lot of tedium for low ROI.  It is now unclear to me from our various communications if this entire doc is actually needed at all.

**Comment by garious** [comment]
Sounds good

**Comment by danpaul000** [comment]
@garious thoughts on getting this in as is, regardless of any other docs or whatever that might be needed for Ledger?

**Pull request merged**
