### PR TITLE
Add accounts-tool subcommand under ledger-tool

### PR DESCRIPTION
**Pull request by yhchiang-sol**
#### Summary of Changes
Add accounts-tool subcommand under ledger-tool

#### Test Plan
```
$ ./target/debug/solana-ledger-tool accounts-tool
solana-ledger-tool-accounts-tool
Tool for analyzing accounts
```

### CODE REVIEW

**Comment by steviez** [comment]
I'm not fully sold one way or another, but did you consider re-using the existing `accounts` command as opposed to creating a new one?

**Comment by yhchiang-sol** [comment]
> I'm not fully sold one way or another, but did you consider re-using the existing accounts command (and sticking your new commands under accounts) as opposed to creating a new one?

Yes, but it seems to me the existing `accounts` subcommand is designed to work with other commands like this

```
             ("genesis", Some(arg_matches)) => {
                 let genesis_config = open_genesis_config_by(&ledger_path, arg_matches);
                 let print_accounts = arg_matches.is_present("accounts");
```

and its help also mentioned it `Print account stats and contents after processing the ledger`.

If we reuse the existing `accounts`, then I think we also need to move the "genesis" command to `ledger-tool/src/accounts.rs`.  Or do I miss something?

**Comment by steviez** [comment]
> Yes, but it seems to me the existing accounts subcommand is designed to work with other commands like this
> ...
> If we reuse the existing accounts, then I think we also need to move the "genesis" command to ledger-tool/src/accounts.rs. Or do I miss something?

I believe you're mistaken here. There is the pre-existing `accounts` subcommand
https://github.com/solana-labs/solana/blob/ce4251be99dc91509d052acfc7625c687d7d7f24/ledger-tool/src/main.rs#L2147-L2148
that is completely separate from the`genesis` subcommand which has an `accounts` argument:
https://github.com/solana-labs/solana/blob/ce4251be99dc91509d052acfc7625c687d7d7f24/ledger-tool/src/main.rs#L1803-L1811
if one wanted to run `solana-ledger-tool genesis --accounts --ledger ..`. There are other commands that also have an optional `accounts` argument, such as `verify`
https://github.com/solana-labs/solana/blob/ce4251be99dc91509d052acfc7625c687d7d7f24/ledger-tool/src/main.rs#L1901-L1904

> and its help also mentioned it Print account stats and contents after processing the ledger.

Right, so the two options I see are:
1) Add a new top-level subcommand (as this PR does), and place your new subcommands under it
2) Repurpose the existing `accounts` subcommand to
    - Take an optional subcommand, if unspecified, stick with the existing behavior of printing accounts after processing ledger
    - Run other command if specifed
    
So, the usage for 2) would look like:
```
// Run existing accounts command (allow unspecified subcommand for backwards compat)
solana-ledger-tool accounts ...

// Maybe also run existing accounts command (name pending)
solana-ledger-tool accounts print ...

// Run new subcommand of accounts ASDF
solana-ledger-tool accounts ASDF ...
```
The hierarchy for 2) would look similar to how the `bigtable` command is setup; I'd encourage you to check out that code and/or run `solana-ledger-tool bigtable --help` to help visualize this extra layer of subcommands.

**Comment by yhchiang-sol** [comment]
> that is completely separate from the genesis subcommand which has an accounts argument:

Aghh, got it!  The arg and subcommand namings are somewhat confusing :joy:.
Will definitely go with option 2.

**Comment by yhchiang-sol** [comment]
Damn.  The move is much bigger than I think.  There're many local functions that need to move to a shared mod.

**Pull request closed without merging**
