### PR TITLE
Document transaction module

### PR DESCRIPTION
**Pull request by brson**
This adds documentation and examples to the solana_sdk::transaction module and the Transaction type.

To facilitate practical examples that use RpcClient I added a new hidden module called `example_mocks` that contains stub definitions of RpcClient. This allows the examples to appear to use RpcClient without creating a circular dependency, and without writing `ignore`ed examples. If this technique is acceptable I'll probably use it elsewhere too.

There's a single running example here that is just modified slightly as needed per function. It's a pretty huge amount of code, but I am trying to write examples that are more-copy-pastable than I have previously, and have fewer hidden, inscrutable, variables.

Please note [this issue](https://github.com/solana-labs/solana/issues/22012) I filed about the confusingly named constructors for the Transaction type.

### CODE REVIEW

**Comment by brson** [comment]
The CI failure is related to building my new `example_mocks` module with the `program` feature. Looking into it.

**Comment by brson** [comment]
I've pushed a commit that hopefully fixes CI.

**Comment by brson** [comment]
I don't think the new CI error is related to this pr.

**Comment by jstarry** [comment]
> I don't think the new CI error is related to this pr.

Correct, it's fixed on master now

**Review by CriesofCarrots — APPROVED** [review]
Very nice. This looks great to me as-is.
I do 100% agree with your points in #22012, incidentally. Will ponder a viable way to improve the situation...

**Pull request merged**
