### PR TITLE
Add Bank::set_bpf_compute_budget_override()

### PR DESCRIPTION
**Pull request by mvines**
From a program unit test environment, I want to be able to ratchet down the compute budget to avoid future regressions to my optimized program code.

### CODE REVIEW

**Comment by jackcmay** [comment]
Not too happy about moving the bpf_loader specific compute budget back into the bank.  Maybe instead we write a utility that digests the logs and reports the consumption which the test could then validate against?

**Comment by mvines** [comment]
> Not too happy about moving the bpf_loader specific compute budget back into the bank.

Seems like we need to rename ComputeBudget/compute_budget to BpfComputeBudget/bpf_compute_budget.

ComputeBudget as it's currently named does not sound BPF-specific at all.  Ideally we could configure the BpfLoader *before* it's given to the bank/message_processor

I'm pretty opposed to log parsing to fail unit tests.  That's a pretty unergonomic solution vs. simply adjusting the compute limit upfront.

**Comment by jackcmay** [comment]
Agreed, message parsing is fragile.  I like the idea of configuring the bpf loader loader and handing it off to the message processor, maybe as part of a "loaders" list

**Comment by mvines** [comment]
Can I tempt you with the top commit?   It renames ComputeBudget to BpfComputeBudget, which I think is a major improvement to readability.  

I'm still adding `Bank::set_bpf_compute_budget_override()` in this PR, but at least it's now more clearly scoped.

**Comment by jackcmay** [comment]
One of the ideas around ComputeBudget was that it was a concept that applied to whatever loader was running, so a generic syscall namespace would apply and not need to be bpf specific.  Underneath renaming the struct sounds fine since the current implementation is specific, but mainly because that's the only loader we have.  That's one of the reasons I wanted to move it into the loader, it then naturally becomes bpf loader specific and its scope is clear.

**Comment by mvines** [comment]
Folding this into https://github.com/solana-labs/solana/pull/13286

**Pull request closed without merging**
