### PR TITLE
wallet: Add show-vote-account command

### PR DESCRIPTION
**Pull request by mvines**
#### Problem
A validator is unable to easily view their staking account

#### Summary of Changes
```
$ solana-wallet show-vote-account 7yvFtwnqUuXChF6tnD2aKpGESJwSG6hfbCJ4MYz1VB6j
account lamports: 42
node id: FA9zGu8woPQK9pxzDZjc36Gn8Zk9HM3czzNzueKEY1V2
authorized voter id: 7yvFtwnqUuXChF6tnD2aKpGESJwSG6hfbCJ4MYz1VB6j
credits: 15
commission: 0
root slot: 14
votes:
- slot=15, confirmation count=31
- slot=16, confirmation count=30
- slot=17, confirmation count=29
- slot=18, confirmation count=28
- slot=19, confirmation count=27
- slot=20, confirmation count=26
- slot=21, confirmation count=25
- slot=22, confirmation count=24
- slot=23, confirmation count=23
- slot=24, confirmation count=22
- slot=25, confirmation count=21
- slot=26, confirmation count=20
- slot=27, confirmation count=19
- slot=28, confirmation count=18
- slot=29, confirmation count=17
- slot=30, confirmation count=16
- slot=31, confirmation count=15
- slot=32, confirmation count=14
- slot=33, confirmation count=13
- slot=34, confirmation count=12
- slot=35, confirmation count=11
- slot=36, confirmation count=10
- slot=37, confirmation count=9
- slot=38, confirmation count=8
- slot=39, confirmation count=7
- slot=40, confirmation count=6
- slot=41, confirmation count=5
- slot=42, confirmation count=4
- slot=43, confirmation count=3
- slot=44, confirmation count=2
- slot=45, confirmation count=1
```

Part of #3481

### CODE REVIEW

**Comment by mvines** [comment]
@rob-solana anything else you'd want to see in the output?

**Comment by rob-solana** [comment]
in a future that I haven't made real yet, lamports != stake.  if wallet relied on rpc to get stake information, that'd obviate the need to rewrite wallet when passive staking comes in

**Comment by rob-solana** [comment]
also of note: commission is a percentage with 32-bit resolution (i.e. 0x7FFF_FFFF means 50% commission), might be nice to have that as human readable

**Comment by rob-solana** [comment]
as-is this is perfectly accurate, but I don't want anyone to assume that lamports == stake

**Comment by mvines** [comment]
> in a future that I haven't made real yet, lamports != stake. if wallet relied on rpc to get stake information, that'd obviate the need to rewrite wallet when passive staking comes in

Do we actually have an RPC API for stake information? 

> also of note: commission is a percentage with 32-bit resolution (i.e. 0x7FFF_FFFF means 50% commission), might be nice to have that as human readable

Oops, I meant to do that but forgot.  Updated the PR with this now.

> as-is this is perfectly accurate, but I don't want anyone to assume that lamports == stake

Well it sorta does in the code now.  But yeah once we fully bring in the staking program then this command's implementation can be updated too.

**Comment by rob-solana** [comment]
> > in a future that I haven't made real yet, lamports != stake. if wallet relied on rpc to get stake information, that'd obviate the need to rewrite wallet when passive staking comes in
> 
> Do we actually have an RPC API for stake information?
> 

no, but I infer a requirement for such from #3481 

> > also of note: commission is a percentage with 32-bit resolution (i.e. 0x7FFF_FFFF means 50% commission), might be nice to have that as human readable
> 
> Oops, I meant to do that but forgot. Updated the PR with this now.
> 
> > as-is this is perfectly accurate, but I don't want anyone to assume that lamports == stake
> 
> Well it sorta does in the code now. But yeah once we fully bring in the staking program then this command's implementation can be updated too.

Ok, killer.  I'm glad we're on the same page.  This stuff isn't obvious, IMHO.

**Comment by mvines** [comment]
Cool does that mean r+ or is there something more/different you’d like to see in this PR?

**Comment by rob-solana** [comment]
sorry: r+

**Pull request merged**
