### PR TITLE
Removed some dead code from replay stage

### PR DESCRIPTION
**Pull request by lijunwangs**
#### Problem
Some code in replay stage related for bank_forks are dead and confusing. Removed
#### Summary of Changes
Removed some dead code related to bank_forks from replay_stage
Fixes #

### CODE REVIEW

**Comment by mvines** [comment]
But the commit in here doesn’t modify banking stage 🙃

**Comment by lijunwangs** [comment]
> banking

e

**Comment by lijunwangs** [comment]
Oh. I meant replay_stage

**Comment by carllin** [comment]
@lijunwangs I'm going to be re-introducing a lot of this code here: https://github.com/solana-labs/solana/pull/18160, so I think we can close this for now.

**Comment by lijunwangs** [comment]
close as Carl suggested

**Pull request closed without merging**
