### PR TITLE
Aggregate vote instruction counters and report them as datapoints 

### PR DESCRIPTION
**Pull request by HaoranYi**
#### Problem
https://github.com/solana-labs/solana/issues/24319

https://github.com/solana-labs/solana/issues/24414

For rpc node, the metric agent is unable to catching up with the log at *info* level. `vote-native` is one of the heaviest loggers.
`("vote-native", 11763907)`. 

Every vote instruction will submit one counter point, which is overwhelming for the metric agent to process.

#### Summary of Changes

- Aggregate vote instruction counters into datapoint and report one datapoint per interval.

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
Because of the way that logs and metrics are tied together, we need this to be info level so that vote metrics are sent for all nodes. This is one of the top line metrics we track so I think we should keep the metric but move it to a place where votes can be counted in aggregate to reduce the log spam

**Comment by HaoranYi** [comment]
OK. I will open another issue to track this work.

**Comment by HaoranYi** [comment]
https://github.com/solana-labs/solana/issues/24414

**Comment by jstarry** [comment]
A new `InvokeContext` is created per transaction so that's not a good place to aggregate. How about aggregating inside `BankUtils::find_and_send_votes`?

**Comment by jstarry** [comment]
A new `InvokeContext` is created per transaction so that's not a good place to aggregate. How about aggregating inside `BankUtils::find_and_send_votes`?

**Comment by HaoranYi** [comment]
> A new `InvokeContext` is created per transaction so that's not a good place to aggregate. How about aggregating inside `BankUtils::find_and_send_votes`?

Yeah. We could aggregate there. I think there are 3 ways
1. do it in BankUtils::find_and_send_votes - by looking at the transaction result.
2. do it in bank.rs::load_and_execute_transactions - by looking at the loaded transactions.
3. do it in cote_processors - same as before.

I would like to keep the aggregate in the same place as before, which seems to have less impact for other componets. How about changing the stats to static ref and have the InvokeContext holding a reference to the stats?

**Comment by HaoranYi** [comment]
Sure. we can do it there. I think it might be more efficient to do it there. 

Do we need to care for two counters - one for  Vote and VoteSwitch(_, _), the other for VoteState(_) and VoteStateSwitch? Can we just do one counter?

**Comment by jstarry** [comment]
Oh, I didn't realize there was a different counter used for the vote instructions. @carllin do you have any preference for how these metrics are reported? Are they still needed?

**Comment by HaoranYi** [comment]
@carllin What's your thoughts for these two vote instruction counters? Do we still need them? Thanks!

**Comment by HaoranYi** [comment]
We no longer need these counter. The following pull requests remove them. 
https://github.com/solana-labs/solana/pull/24696

**Pull request closed without merging**
