### PR TITLE
FeeCalculator: Default lamports_per_signature to 1 instead of 0

### PR DESCRIPTION
**Pull request by mvines**

### CODE REVIEW

**Comment by rob-solana** [comment]
I bet a lot of stuff blows up with this...

**Comment by mvines** [comment]
> I bet a lot of stuff blows up with this...

🤕

**Comment by garious** [comment]
Looks like this will create a big maintenance burden. The tests shouldn't assume `lamports_per_signature` is the only parameter.

**Comment by mvines** [comment]
I see value in going through the exercise of getting all the tests to pass with a non-zero fee.  In a couple cases I've found valid issues in non-test code that needed to be fixed.  Once the tests are green we can take a look at the end result and determine what we want to keep and what can be thrown away.

**Comment by mvines** [comment]
@garious - wdyt about encoding a `FeeCalculator` in the genesis block as a first step towards making fees more dynamic.

**Comment by garious** [comment]
Yes, definitely.

**Comment by rob-solana** [comment]
can you hang back on FeeCalculator in genesis?  I've touched every genesis line :(

**Comment by mvines** [comment]
> can you hang back on FeeCalculator in genesis? I've touched every genesis line :(

Oh sure.   Got a PR coming up tomorrow sometime  that I can rebase on?

**Comment by rob-solana** [comment]
> > can you hang back on FeeCalculator in genesis? I've touched every genesis line :(
> 
> Oh sure. Got a PR coming up tomorrow sometime that I can rebase on?

god I hope so.  I'm so burned out on genesis

**Comment by mvines** [comment]
Heh, ok well lemme know if I can help in any way

**Comment by garious** [comment]
> god I hope so. I'm so burned out on genesis

That's what He said. And so He rested.

**Comment by mvines** [comment]
The parts I want to keep from this PR have been extracted

**Pull request closed without merging**
