### PR TITLE
Explorer: introduce Coingecko price cards on mint pages

### PR DESCRIPTION
**Pull request by oJshua**
#### Problem
Now that Coingecko ids are available in the token-list, we can provide more price details. 

#### Summary of Changes
Add price card to token mint details page.

Explorer-Solana (9)

If the Coingecko ID isn't avail:
Explorer-Solana (10)

### CODE REVIEW

**Comment by oJshua** [comment]
@jstarry does this look okay design-wise to you? It does space out the token title a bit more.

**Comment by jstarry** [comment]
Looks fine to me but if you're up for it, I think moving the card below the header (and breaking it into a few cards on large screens) would look nicer:

Screen Shot 2021-07-15 at 10 04 39 AM

https://themes.getbootstrap.com/preview/?theme_id=6063

**Comment by oJshua** [comment]
Explorer-Solana (11)

Thanks for the suggestion @jstarry !

**Comment by jstarry** [comment]
Looks so much better! Can you move the "Price last updated" disclaimer up to one of those widgets? It looks weird next the decimals
Screen Shot 2021-07-19 at 2 54 06 PM

**Comment by jstarry** [comment]
One last thing, looks like there isn't a loader for the price info. Any reason you excluded it?

**Comment by oJshua** [comment]
@jstarry The loading block is in place now, thanks for the reminder. I also broke up the cluster stats page version.

**Comment by jstarry** [comment]
Sweet, ship it!

**Pull request merged**
