### PR TITLE
clippy 0.1.70: 2023-03-18: Apply suggestions, disable false positives

### PR DESCRIPTION
**Pull request by ilya-bobyr**
#### Problem
Clippy does not like a few things in the current `master`

#### Summary of Changes
Apply suggestions, and disable a few false positives with an explanatory comment.

### CODE REVIEW

**Comment by ilya-bobyr** [comment]
I can split this into multiple PRs – one per package, if anyone thinks it would simplify the review process.

**Comment by CriesofCarrots** [comment]
Can you please add to the problem statement details about why we care about lints from this particular version of nightly? (Also, see https://github.com/solana-labs/solana/pull/30664 for discussion about which nightly the monorepo will adopt with rust v1.68)

**Comment by CriesofCarrots** [comment]
> If we do not want to deal with this for now, I can probably just close it.

We tend to do these sorts of fixes in one fell swoop when we upgrade the version of rust on the master branch, which means we can usually avoid transient nightly warnings.

We could move forward with these changes, minus all the comments about `redundant_async_block`, as minor cleanup, but I'd also be fine with punting until we upgrade to rust v1.69

**Comment by ilya-bobyr** [comment]
> > If we do not want to deal with this for now, I can probably just close it.
> 
> We tend to do these sorts of fixes in one fell swoop when we upgrade the version of rust on the master branch, which means we can usually avoid transient nightly warnings.

Makes sense.

> We could move forward with these changes, minus all the comments about `redundant_async_block`, as minor cleanup, but I'd also be fine with punting until we upgrade to rust v1.69

I'll just close it for now.  Sorry for the noise.
And thank you for looking into it so quickly!

**Pull request closed without merging**
