### PR TITLE
fix: reduce Connection keep-alive timeout to 1 second fewer than the Solana RPC's keep-alive timeout

### LINKED ISSUE #27859: socket hang up (ECONNRESET) - Web3js
#### Problem

We at Triton One have seen many developers facing an error like this when using the web3js:

```
FetchError: request to https://client.rpcpool.com/ failed, reason: socket hang up
    at ClientRequest.<anonymous> (/home/ec2-user/processes/dex-webserver-mainnet-multi/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketOnEnd (node:_http_client:478:9)
    at TLSSocket.emit (node:events:539:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

I've been collecting some tcp dump from our servers and I can see in the vast majority of times this is caused due to an RST packet sent by our HAproxy Loadbalancer which abruptly closes the connection in the client side, see this screenshot as an example.
image

IP: 204.16.246.170 (Load Balancer managed by Triton)
IP: 18.237.101.162 (Client)

1) Notice the Load Balancer first sends a FIN flag indicating to the client the socket will close.
2) Shortly afterwards the client attempts to PUSH data to a read/write-closed socket.
3) The server responds with a TCP RST flag.
4) Nodejs handles this abrupt 'disconnection' with the error above.

This seems to be a common issue across many nodejs applications when I search through stackoverflow.com. While the client can simply ignore it and re-connect, this raises complains from our customers that are expecting to extract maximum read performance from our servers.

#### Proposed Solution

Here's a few proposed solutions:

1) Remove HTTP keep-alive functionality completely from Web3js so it closes sockets as soon as the client gets a response.

2) Enforce client-side timeouts in the http keep-alive settings, e.g: https://github.com/solana-labs/solana-web3.js/blob/master/src/agent-manager.ts#L13 could be set as `{keepAlive: true, maxSockets: 25, timeout: 30000};` (30s) or shorter?

_Note: 2) won't likely solve the issue completely but potentially reduce the error rate as the errors don't happen in a fixed interval, it varies on every application. Some customers see it every X minutes while others see it pretty much every few seconds. So here i'm proposing that the client closes the socket before the LB does to avoid the client abruptly closing the connection_ 

3) Destroy socket just after sending a new request, see this interesting discussion on nodejs repo https://github.com/nodejs/node/issues/27428. I can see at the bottom folks have created a PR in May attempting to fix this, it may be good for Node developers to have a look.

### PR DESCRIPTION
**Pull request by steveluscher**
#### Problem

When contacting an RPC that's behind a load balancer, clients can often send an RPC request down a free socket, only to discover that socket has since been disposed of. These requests will fail.

Based on this excellent article on [tuning keep-alive](https://connectreport.com/blog/tuning-http-keep-alive-in-node-js/), this is what I think I've learned.

* The underlying HTTP library that the Solana RPC uses (`hyper`) has a [default keep-alive timeout of 20s](https://github.com/hyperium/hyper/blob/fdffc1d52ff719ec3f69facd9cb920e6cc0506d7/src/proto/h2/client.rs#L66).
* Typical `Node.js` servers have a [default keep-alive timeout of 5s](https://nodejs.org/api/http.html#serverkeepalivetimeout).
* When the RPC is behind a load balancer, a higher ‘free socket timeout’ in the load balancer can result in the RPC closing the socket, but the load balancer (ergo, the client) thinking that it's still open. The next request will fail.

[image](https://connectreport.com/blog/tuning-http-keep-alive-in-node-js/#502-errors-and-their-sources-in-your-application)

I believe the solutions to be as follows:

1. Let people supply their own agents or disable agents altogether should they like to do some tuning #29125.
2. Reduce the timeout of our _default_ agent to the Solana RPC's timeout, minus one second (20s - 1s = 19s) #29130.
3. RPC providers should maybe do the same – setting their _load balancer_ timeouts to 1 second less than the Solana RPC's timeout (20s - 1s = 19s).

#### Summary of Changes

* Replaced our custom agent implementation with the `agentkeepalive` module.
* Set the free socket timeout to the Solana RPC's timeout minus one second (20s - 1s = 19s)

Fixes #27859, hopefully.

### CODE REVIEW

**Comment by steveluscher** [comment]
Thoughts, @dancamarg0, @linuskendall, @brianlong?

**Comment by steveluscher** [comment]
@0xCactus, @y2kappa, would you like a strategy to test this out before I land it? You can either patch in the changes yourself, or I can publish a release candidate package just for you, that you can add to your `package.json`.

**Comment by 0xCactus** [comment]
@steveluscher yup i can help test it out. Would prefer a release candidate package

**Comment by steveluscher** [comment]
It's all yours, @0xCactus. You can `yarn add @solana/web3.js@pr-29130`.

**Comment by 0xCactus** [comment]
getting the following error @steveluscher 
```
{"level":50,"time":1670443877071,"pid":28,"hostname":"4169baa11267","service":"monitor","source":"pino ","error":{},"type":"account","msg":"monitor crashed: Error: failed to get info about account H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG: TypeError [ERR_INVALID_PROTOCOL]: Protocol \"https:\" not supported. Expected \"http:\""}
```

**Comment by steveluscher** [comment]
Damnit. My bad. I'll publish a new package for you in a moment.

**Comment by steveluscher** [comment]
Sorry for the delay @0xCactus. Try `yarn add @solana/web3.js@1.70.0-pr-29130-2`

**Comment by steveluscher** [comment]
Alright, @0xCactus has this running in production at the moment. Let's give it a few days and see if there's improvement. Anyone else is free to pull down that version and give it a shot too!

**Comment by 0xCactus** [comment]
@steveluscher  fyi our service has been relatively more stable since switching to use the change from this PR. Though it didn't seem to completely fix the issue. Yesterday, @dancamarg0 tweaked the keep-alive on their server to 19s and we saw the socket hang up issue occurring on the client side consistently every minute

**Comment by dancamarg0** [comment]
Just to point out the current keep-alive timeout is set to 60s, that's the setting we've been running for weeks for @0xCactus

**Comment by steveluscher** [comment]
Wait, so here's what I think I got from the two messages above:

* Triton One did _not_ change the keep-alive timeout on your RPC; it's still 60s.
* That notwithstanding, you were running smoothly until yesterday when the hangup issue re-appeared, worse than before.

Are those two statements accurate?

**Comment by dancamarg0** [comment]
1) Yes. Triton One did not change the keep-alive timeout on your RPC; it's still 60s.

2) He was running smoothly until yesterday where I changed the keep-alive timeout from 60s to 19s as per your recommendation

So a higher timeout actually seems to fix the issue after your patch apparently? I'll also collect some TCP data to see how often we see RST packets in 0xcactus RPC now and get back if I have any interesting data

**Comment by steveluscher** [comment]
> So a higher timeout actually seems to fix the issue after your patch apparently?

Interesting! When it comes right down to it, the goal is for the client's timeout to be _just_ a bit less _any_ of the other timeouts in the chain, so that the client always gives up on the free connection before any of the middle or end pieces do.

Maybe there's a chance that if both the client and the load balancer are set to 19s that there's a small window of time in which the load balancer is dead but the client thinks it's still alive. You probably don't want to keep doing my testing in production for me, but it would be _really_ interesting if you set the load balancer to match the RPC server @dancamarg0 (20s) and see if that performs just as well as 60s.

**Comment by steveluscher** [comment]
Alright. I'm shipping this. Thanks for everyone's contributions here.

1. Customers saw success with this change and particular configurations of their RPC endpoints, success being the disconnection rate falling to zero.
2. For those whose RPC endpoints configuration is _still_ incompatible with these defaults now have the option to supply their own, or to turn off keep-alive altogether, using https://github.com/solana-labs/solana/pull/29125

**Pull request merged**
