### PR TITLE
Add ERC20-like Token program (v0.9)

### PR DESCRIPTION
**Pull request by mvines**
See #1343

This PR currently has 0 tests (which is why it's marked WIP).  Will fill those in next, but I wanted to share for some initial review.

However the SDK side of this is https://github.com/solana-labs/solana-web3.js/pull/19 with a fair number of tests that all pass with this PR running.

Note: this is going into v0.9 first because that's what the SDK currently runs against.  Will merge to `master` as a second step.

### CODE REVIEW

**Comment by mvines** [comment]
@garious - can you please take a first pass at this.   My goal here is to support the identical feature set as ERC20 (expressed in a slightly different way) and not a bit more.

[token-program.js](https://github.com/solana-labs/solana-web3.js/pull/19/files#diff-354c13dd2d6bfc2304eba5bca32685a0) on the SDK side might help with some context too.

**Comment by garious** [comment]
To compile this to a bytecode (like BPF or Wasm) and submit it to the chain from a transaction.  Or are you thinking we just statically link this one as-is and start advertising support for spinning up erc20-like tokens on the solana testnet?

**Comment by mvines** [comment]
> Or are you thinking we just statically link this one as-is and start advertising support for spinning up erc20-like tokens on the solana testnet?

Yeah, this for now.   Then once the SDK program submission is built out, the program gets rewritten and probably moves directly into the SDK repository.

**Comment by garious** [comment]
Got a Pillbox ticket to track adding this to master?

**Comment by mvines** [comment]
Yeah, referenced right at the top of the PR

**Pull request merged**
