### PR TITLE
Added methods for initializing ProgramTest with an existing Keypair

### PR DESCRIPTION
**Pull request by totikom**
See #21087 for details of the problem.

### CODE REVIEW

**Comment by mvines** [comment]
Hi, thanks for this PR. I'm a little confused by how this PR solves anything. It seems a little convenient to be able to provide the "payer" keypair but it's also pretty easy to execute a system transfer transaction to fund that same "payer" keypair from the account that `.start()` currently returns.  
However this seems entirely unrelated to the owner of accounts added by `.add_account()` before calling `.start()`

**Comment by totikom** [comment]
>However this seems entirely unrelated to the owner of accounts added by .add_account() before calling .start()

That is the case! It seems, that it is a common usecase, than you first "create" a user with some accounts, and then let her "interact" with your program for testing.

In other words, create a `Keypair` and several accounts owned by that `Keypair`.
Then send transactions with that (writable) accounts, signed by the `Keypair`, so program under test will be allowed to change the state of that accounts.

**Comment by jstarry** [comment]
> That is the case! It seems, that it is a common usecase, than you first "create" a user with some accounts, and then let her "interact" with your program for testing.

What's wrong with using the default payer from program test for this usecase?

**Comment by mvines** [comment]
Right.  The `owner` keypair for the pre-created (`.add_account()`) accounts could even be an unfunded keypair.  The `payer` keypair in this case is only used to pay the transaction fee.

**Comment by totikom** [comment]
> What's wrong with using the default payer from program test for this usecase?

Currently, the default payer is created via `start()` method on `ProgramTest` struct.
However, you can not add accounts to the testsuite after you called `start()`
(`add_account()` exists only on `ProgramTest`, but it is consumed by `start()`).

**Comment by mvines** [comment]
Right. What I fear is that you don’t understand the account model yet and are simply asking for something that’s not really necessary though

**Pull request closed without merging**
