### PR TITLE
Improve BPF SDK dependency caching

### LINKED ISSUE #10369: BPF SDK cloning of dependent repositories may be causing us to be throttled
#### Problem

The BPF SDK downloads and clones various dependencies. To improve performance it caches downloaded binaries but does not cache cloned repositories. Cloning these dependencies repository during CI appears to be causing us to be throttled by isp/github.

#### Proposed Solution

Cache cloned repositories

### PR DESCRIPTION
**Pull request by jackcmay**
#### Problem

BPF dependencies can be expensive to download/untar/clone

#### Summary of Changes

Improve dependency caching by:
- Avoid copying by downloading directly to the cache
- Reduce untar time by untaring into cache
- Cache cloned repos

Fixes #10369

### CODE REVIEW

**Comment by jackcmay** [comment]
@mvines You mentioned 

> cloning https://github.com/solana-labs/rust-bpf-sysroot.git: uncached but also  anonymous http

Can you elaborate?

**Comment by mvines** [comment]
I github grants a better rate limit if you believe `git clone` over ssh instead of http, since it can identify you.   But if we're caching the clone then this is probably a moot point

**Comment by jackcmay** [comment]
@mvines Think we should backport this to 1.1 too?

**Comment by mvines** [comment]
Sure

**Pull request merged**
