### PR TITLE
hold lock to speed up insert

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem
Validator startup time is commonly experienced. Generating the index is a large part of that time.
#### Summary of Changes
Hold the accounts index lock while many inserts are done.
Fixes #

### CODE REVIEW

**Comment by jeffwashington** [comment]
10s faster to load validator
 master:INFO  solana_metrics::metrics] datapoint: generate_index total_us=74934823i scan_stores_us=21244497i
 this change: solana_metrics::metrics] datapoint: generate_index total_us=64532862i scan_stores_us=23246957i

**Comment by jeffwashington** [comment]
@carllin still tests to write. What do you think of this idea?

**Comment by carllin** [comment]
> @carllin still tests to write. What do you think of this idea?

I think it's a good one,  it stood out when looking at the results of your latest metrics as well 😃 

Can't argue with the results!

**Comment by jeffwashington** [comment]
I reworked it again and ran it on lemond instead of wiggins. Different cpu, mem, snapshot, etc.

with change:
 generate_index total_us=47022182i scan_stores_us=22914989i

master:
generate_index total_us= 81614843i scan_stores_us=24490653i

**Review by sakridge — APPROVED** [review]
lgtm

**Pull request merged**
