### PR TITLE
Cleanup - Various feature gates

### PR DESCRIPTION
**Pull request by Lichtso**
#### Problem
Since epoch 321 (almost a year ago) various features were activated (on all three clusters) but their feature gating logic was never cleaned up.

#### Summary of Changes
Removes feature gating logic of the following features:

1. vote_withdraw_authority_may_change_authorized_voter
2. limit_secp256k1_recovery_id
3. spl_token_v3_4_0
4. spl_associated_token_account_v1_1_0
5. disable_fee_calculator
6. vote_authorize_with_seed
7. merge_nonce_error_into_system_error
8. instructions_sysvar_owned_by_sysvar
9. require_static_program_ids_in_transaction
10. include_account_index_in_rent_error
11. filter_votes_outside_slot_hashes
12. reject_vote_account_close_unless_zero_credit_epoch
13. bank_transaction_count_fix
14. check_syscall_outputs_do_not_overlap

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Doing this all in one PR seems like a bad idea to me

**Comment by Lichtso** [comment]
I can spit it up if you like, but opening 14 PRs did not seem so good either.

**Comment by mvines** [comment]
I feel separate PRs is the way to go as well. I understand the pain, I know it'll take longer, etc. Reviews for each 14 PR should be pretty obvious though, certainly should tag the original feature-gate author for that review too.
The effort here is very much appreciated though, it's absolutely a net good!

**Comment by CriesofCarrots** [comment]
> I can spit it up if you like, but opening 14 PRs did not seem so good either.

Yeah, what Michael said. Unless any of them are too intertwined with each other, I am in favor of 14 different PRs

**Comment by Lichtso** [comment]
Ok, let me just get this PR through CI, then I will close it and reopen as split PRs.

**Pull request closed without merging**
