### PR TITLE
Update canary readme

### PR DESCRIPTION
**Pull request by willhickey**
* Move the canary readme to a more appropritate directory name
* Add the new canaries

More details and new dashboard links coming soon.

### CODE REVIEW

**Comment by willhickey** [comment]
A bunch of the system dashboard links don't work... because we don't have system metrics from those nodes yet. I'm working on that but I'd like to get this merged as a starting point so I can link to it from other internal docs.

**Comment by mvines** [comment]
Content looks good. This doesn't feel like something that should be landed in the source tree and managed as a part of a release. By it's very nature it refers to multiple release lines, and updates to canaries doesn't really need the same approval process as new validator code.  How about a wiki page?

**Comment by t-nelson** [comment]
> How about a wiki page?

or cluster-ops repo?

**Comment by willhickey** [comment]
Closing in favor of cluster-ops

**Pull request closed without merging**
