### PR TITLE
Revert "Add new vote state version that replaces Lockout with LandedV…

### PR DESCRIPTION
**Pull request by steviez**
…ote to a… (#29524)"

#### Problem
Per some Discord chatter, the commit being reverted made master diverge on consensus:
https://discord.com/channels/428295358100013066/439194979856809985/1087579317552296017

#### Summary of Changes
This reverts commit d77f0a22c7fd5746164e2789219eb48c065a18c1.

### CODE REVIEW

**Review by AshwinSekar — APPROVED** [review]
thanks for the speedy response!

**Comment by steviez** [comment]
Ok, I have a local ledger with snapshot at slot `183801344`:
- With the commit (d77f0a2) that this PR reverts, I see the wrong hash produced on slot `183801345`
- With the parent of that commit (46614c0), I see the correct hash
In this context, wrong and correct are based off of the correct hash that was produced on another node. Thus, I feel very confident that the commit this PR is reverting is indeed the problem.

Pushing in before I have all greens since `master` is currently broken

**Comment by bji** [comment]
Thanks for your fast response.  I'm uncertain what test case was missed that would have covered this, and also what the specific cause of the mismatched hash was.  The obvious reason would be a change in vote account state, but the persisted version of vote account state is not changed unless the feature is enabled, so that couldn't have happened.

The only difference I can surmise then is that the in-memory struct that represents a vote account is used in calculating the hash and includes the new fields.

**Comment by steviez** [comment]
By the way, here is the good and the bad hash for any potentials readers:
```
# Correct hash
[2023-03-21T06:58:51.417094011Z INFO  solana_runtime::bank] bank frozen: 183801345
hash: CR1XQXCAUNPJocQfpCHKEfBWsrX5h3nghfQe3zBoyrw4
accounts_delta: 5QNNWSBYpwrLw1orWfvvT14Vim1QHQTjNUuETuLZdVzr
signature_count: 1597
last_blockhash: 7H6nrvuTgheDFuFaXMXSqVRnJS5jGjASzm6iFqMVWnNx
capitalization: 543375403424210403,
stats: BankHashStats {
	num_updated_accounts: 4740,
	num_removed_accounts: 29,
	num_lamports_stored: 3125528942524548,
	total_data_len: 25181032,
	num_executable_accounts: 0
}

# Incorrect hash
[2023-03-21T07:05:37.769535933Z INFO  solana_runtime::bank] bank frozen: 183801345
hash: 97nuHJnWQ2mpDYhDkV2hg9bDnsVMHD6CCUN2mL3GKTY8
accounts_delta: CQTTeQYYfnSBaBTsWdvJdvAy7mgcXG4YMCj4E9PivQzZ
signature_count: 1597
last_blockhash: 7H6nrvuTgheDFuFaXMXSqVRnJS5jGjASzm6iFqMVWnNx
capitalization: 543375403424210403,
stats: BankHashStats {
	num_updated_accounts: 4740,
	num_removed_accounts: 29,
	num_lamports_stored: 3125528942524548,
	total_data_len: 25181032,
	num_executable_accounts: 0
}
```

All the numbers (cap, num updated, etc) line up, so I am inclined to agree with bji that there is some difference in account state that changes the account hash for vote account(s), which in turn changes the accounts_delta (cumulative hash for all updated accounts)

**Pull request merged**
