### PR TITLE
Implemented feature for assigning more credits to votes that land closer

### PR DESCRIPTION
**Pull request by bji**

### CODE REVIEW

**Review by bji — COMMENTED** [review]
I just want a confirmation that this approach is good.  If it's OK, I'll take the time to write tests ...

**Comment by jstarry** [comment]
Hey @bji, it's too late to get this into v1.8, I'm going to close this. Maybe you can target v1.9 though, is this for #19002?

**Comment by bji** [comment]
Sure no problem.  In the process of doing analysis using prior epoch's data of what the effect would be of credits earned by all mainnet-beta validators.  With evidence that this has desirable results, I will make a push for 1.9.

**Comment by t-nelson** [comment]
To be clear, every change set should first target the master branch.  Nothing goes directly in to stabilizing or stable

**Pull request closed without merging**
