### PR TITLE
bench-tps in a cargo test

### PR DESCRIPTION
**Pull request by sakridge**
#### Problem

Have to run a whole bunch of bash scripts and cargo re-compiles everything a million times when trying to run bench-tps on a single machine.

#### Summary of Changes

Refactor bench-tps so it can run on a LocalCluster and run in a cargo test.

Fixes #

### CODE REVIEW

**Comment by garious** [comment]
This is a nice example of why we don't want to be using `<NAME>Transaction` modules anymore. If you first dropped that dependency, you wouldn't need to Arc everything to move forward.

**Comment by sakridge** [comment]
@garious Arc all the things!

**Comment by sakridge** [comment]
@garious drone has to sign the transaction, and it eats the keypair if not arced, how does the non-Transaction::* module sign transactions without the keypair?

**Comment by garious** [comment]
@sakridge, the drone should eat the keypair and then no other transactions should be signed by that keypair.

**Comment by sakridge** [comment]
@garious yea I guess LocalCluster::funding_keypair would have to work differently in that case.

**Pull request merged**
