### PR TITLE
Add Transaction Documentation

### LINKED ISSUE #5114: Transaction format isn't documented
#### Problem

Transactions are not documented in the book.

#### Proposed Solution

Add transactions to the book

### PR DESCRIPTION
**Pull request by TristanDebrunner**
#### Problem

The Transaction format is largely undocumented.

#### Summary of Changes

Add documentation for Transactions and Instructions to the book

Fixes #5114

### CODE REVIEW

**Comment by garious** [comment]
I'll need to think more on this. The organization seems awkward. There will be three audiences:

1. Those that just want to know the binary format of a transaction
2. Those that want to use Rust helper libraries
3. Those building web-based dApps that want to know the shortest path

@jstarry, @mvines to advise on the last bullet. Do we want to point people to solana-web3.js or are we compiling the Rust libraries to wasm now? If the latter, how to use it?

**Comment by mvines** [comment]
> Do we want to point people to solana-web3.js or are we compiling the Rust libraries to wasm now? 

solana-web3.js for now.  wasm is still The Future!

**Comment by garious** [comment]
@TristanDebrunner, how about "Anatomy of a Transaction" just after "Anatomy of a Validator"?

**Comment by TristanDebrunner** [comment]
@garious how's this look? I left the API sections, as they seemed to fit there. Edited to correct the Transaction serialization description.

**Comment by garious** [comment]
Awesome, thanks. I'll read through this later today, push any edits directly, and then merge it.

**Comment by garious** [comment]
Good stuff. I may make some changes, but can do so in a separate PR.

**Pull request merged**
