### PR TITLE
fix single-pool path for ci

### PR DESCRIPTION
**Pull request by 2501babe**
#### Problem
single-pool path changed

#### Summary of Changes
change it here

### CODE REVIEW

**Comment by yihau** [comment]
hey. we migrated spl tests to Github Actions: https://github.com/solana-labs/solana/blob/master/.github/workflows/downstream-project-spl.yml 
sorry for the misleading 😢 will have a clean-up PR for it

**Comment by 2501babe** [comment]
ohh ok. should we still correct this script? the issue was trent was trying to use `ci/run-local.sh`, not sure if theres a new workflow for that

**Comment by yihau** [comment]
ah yeah. in this case I guess we should keep this one atm. thank you!

**Comment by 2501babe** [comment]
sorry i need a review to press da button

**Review by yihau — APPROVED** [review]
🪖

**Pull request merged**
