### PR TITLE
Wait to null blob window

### PR DESCRIPTION
**Pull request by sakridge**

### CODE REVIEW

**Comment by garious** [comment]
What if the blobs are in the replicate channel when the window goes to recycle them?

**Comment by sakridge** [comment]
@garious that's why it's wip.. unlikely that they are, but I guess we need the weak ref thing to fix that.

**Comment by sakridge** [comment]
Isn't this problem is what ref counting is suppose to solve :)

**Comment by garious** [comment]
Yes, but I don't know how to pass Weak refs across threads. :(

**Comment by aeyakovenko** [comment]
I was thinking it would be in an object that’s wrapped with an arc rwlock

**Comment by garious** [comment]
No luck on my end. Best information I can find is that it's doable in Rust nightly with the `alloc` crate. https://doc.rust-lang.org/alloc/, which is incompatible with libc. There's chatter about stabalizing that crate in the very near feature.

**Comment by sakridge** [comment]
I also see that the DuplicateSignature error is coming with or without this change.

**Pull request merged**
