### PR TITLE
kill multinode

### PR DESCRIPTION
**Pull request by aeyakovenko**
#### Problem

Multinode is neither a pure integration test, or pure unit test.

#### Summary of Changes

Kill it with fire.

Fixes #

### CODE REVIEW

**Comment by sakridge** [comment]
I don't get the argument that something has to be 'pure' integration or 'pure' unit, these terms have different meanings to different people and there is no one accepted definition for unit or integration test just guidelines. I think tests at all levels can be useful depending on the situation. The argument should be that test x is too fragile to refactoring or flaky or not useful or whatever you're seeing.

**Comment by aeyakovenko** [comment]
> The argument should be that test x is too fragile to refactoring or flaky or not useful or whatever you're seeing.

Kind of the same thing as saying it is not a "pure X" test.  

The point of the "pure" constraints is to reduce the fragility, flakiness and support load required for maintaining the tests.  If there is a bunch of implementation specific tests, and the implementation changes, those tests can be deleted.  If there are a bunch of interface specific tests, and the implementation changes but not the interface, those tests are still useful.

**Comment by rob-solana** [comment]
mind blowing that test coverage only goes down by 0.1%...  do we believe that?

**Comment by garious** [comment]
@rob-solana, it shouldn't change at all. We're supposed to `cargo test --lib` for coverage. If not, it's a bug.

**Comment by garious** [comment]
@aeyakovenko,  I think "bad ROI" is an acceptable reason to delete these tests.

**Comment by mvines** [comment]
Let’s run these tests under coverage.  If they dont move the needle I’m ok with removing them like this

**Comment by aeyakovenko** [comment]
@mvines, how do we do that?  Our rust coverage tooling is a bit of black magic for me

**Comment by mvines** [comment]
I'll do it and report back here

**Comment by aeyakovenko** [comment]
Awesome, can you include the harness test.  I think booting covers a big pile of code.

**Comment by mvines** [comment]
https://github.com/solana-labs/solana/pull/3050#issuecomment-468872917

**Comment by mvines** [comment]
> can you include the harness test

I'm not sure what you mean?

From my previous comment, #3050 seem to indicate that `tests/multinode.rs` improves line coverage by 0.6%.   Ugh

**Pull request merged**
