### PR TITLE
replay stats report time since last new root

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem
log ms since last root. useful to get an idea of how quickly a validator is making roots.
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by brooksprumo** [comment]
I see people post screenshots that show bank/block times, I'm guessing the root time is not something we can directly get with our current metrics?

**Comment by jeffwashington** [comment]
good question. I'm not sure. Can you find me a metric showing what you recall seeing?

**Comment by sakridge** [comment]
Should be able to get this from this datapoint:
```
datapoint_info!(
    "bank-forks_set_root"
```

**Comment by jeffwashington** [comment]
I don't see a metric that gives me what I'm looking for:
how many roots/s or how many ms per root. Getting an idea of progress of the validator in a metric.
elapsed_ms tells me how long it took to SET the root. I want to know how often we are logging 'new root'.
I'm evaluating validators catching up with large snapshots as in kin sim.
Now, the frequency of the metric being logged could also give me the metric I'm looking for. Is there a way in influx to turn the timestamps into a y axis value?
Here's a sample output from bank-forks_set_root:
```
datapoint: bank-forks_set_root elapsed_ms=3i slot=111310571i total_parent_banks=2i total_banks=35i total_squash_cache_ms=3i total_squash_accounts_ms=0i total_squash_accounts_index_ms=0i total_squash_accounts_cache_ms=0i total_squash_accounts_store_ms=0i total_snapshot_ms=0i tx_count=778i prune_non_rooted_ms=0i drop_parent_banks_ms=0i prune_slots_ms=0i prune_remove_ms=0i dropped_banks_len=2i
```

**Comment by sakridge** [comment]
Just either `count("bank-forks_set_root) ... group by 1s` That would give you how many set_roots are called each second or `sum("total_parent_banks") ... group by 1s` gives you the total number of rooted slots in a second. No?

**Comment by sakridge** [comment]
This is another interesting option:
https://www.influxdata.com/blog/tldr-influxdb-tech-tips-april-28-2016/

elapsed() function:

> SELECT elapsed(value,1s) FROM response WHERE ticket='1'

**Comment by jeffwashington** [comment]
Ah. I will try that.

**Pull request closed without merging**
