### PR TITLE
use bank.id() where we want 'slot'; bank.slot_height() is not slot

### PR DESCRIPTION
**Pull request by rob-solana**
#### Problem
 bank.slot_height() is computed from bank.tick_height(), which is not
 the same as this Bank's slot, which is actually bank.id()

 #### Summary of Changes
 use bank.id() where we want the Bank's slot
 put a comment where things get weird with bank.slot_height() testing

### CODE REVIEW

**Comment by garious** [comment]
I don't understand. Novel of an explanation please.

**Comment by rob-solana** [comment]
there is no tick required at the beginning of a slot, that means bank.tick_height() of a fresh child is the same as that of the parent, which means that asking a bank "what slot do you represent" cannot be calculated from bank.tick_height() from which bank.slot_height() derives.  when we're communicating "we're on slot X" we can't use bank.tick_height(), we need to use an assigned value.

**Comment by garious** [comment]
Why not `bank.slot_height() + 1`?

**Comment by rob-solana** [comment]
if bank.slot_height() is wrong, bank.slot_height() +1 can't be any better...

when a child is freshly created, the value is correct.  once a single tick has been observed, bank.slot_height() + 1 is off by one...

**Pull request merged**
