### PR TITLE
Disable any optimization for improved coverage

### PR DESCRIPTION
**Pull request by ryoqun**
Let's see what overall improvement could be. :)
This worked locally with some subset of tests.

### CODE REVIEW

**Comment by garious** [comment]
Neat, no failures! I would have expected at least one test to fall over from increased memory usage after disabling optimizations.

**Comment by ryoqun** [comment]
@garious Heh, I even didn't think that the memory usage issue might arise.. In coverage, we're testing only pure unit tests, not integration test and local cluster test.

Sad thing is that the coverage didn't increase as much as I hoped... And coverage report isn't reliable.

**Comment by garious** [comment]
Coverage report being unreliable is a longtime annoyance. I assume it's a caching issue. Want to take a stand at debugging?

**Comment by ryoqun** [comment]
@garious Yeah, I can't take anymore... So I've did already. #7576

**Comment by ryoqun** [comment]
> # [Codecov](https://codecov.io/gh/solana-labs/solana/pull/7546?src=pr&el=h1) Report
> 
> > Merging [#7546](https://codecov.io/gh/solana-labs/solana/pull/7546?src=pr&el=desc) into [master](https://codecov.io/gh/solana-labs/solana/commit/141131f3a62f8b85314e5c70985f98d9321ba155?src=pr&el=desc) will **not change** coverage.
> > The diff coverage is `n/a`.
> 
> ```diff
> @@          Coverage Diff           @@
> ##           master   #7546   +/-   ##
> ======================================
>   Coverage    81.7%   81.7%           
> ======================================
>   Files         244     244           
>   Lines       49807   49807           
> ======================================
>   Hits        40704   40704           
>   Misses       9103    9103
> ```

Cool, We've made the coverage so stable that I've come to see this no-coverage-change message for the first time. ;)

**Comment by ryoqun** [comment]
Also, this means this PR does nothing... xD So closing this for now!

**Pull request closed without merging**
