### PR TITLE
Bump rust-rocksdb to 0.19.0 tag

### PR DESCRIPTION
**Pull request by steviez**
https://github.com/rust-rocksdb/rust-rocksdb/releases/tag/v0.19.0

### CODE REVIEW

**Review by yhchiang-sol — APPROVED** [review]
Thanks for upgrading rocksdb version!

**Review by yhchiang-sol — CHANGES_REQUESTED** [review]
Looks like there're some dependencies need to be fixed. 

```
cargo-build-bpf child: target/debug/cargo-build-sbf --sbf-sdk /var/lib/buildkite-agent/builds/gcp-agent/solana-labs/solana/sdk/bpf --manifest-path sdk/Cargo.toml --arch bpf
--
  | Updating crates.io index
  | error: failed to select a version for the requirement `librocksdb-sys = "^0.8.0"`
```

**Comment by behzadnouri** [comment]
For reference, current status:
https://discord.com/channels/428295358100013066/560503042458517505/1005314069860982927

There is also a new advisory requiring an upgrade:
```
Crate:     rocksdb
Version:   0.18.0
Title:     Out-of-bounds read when opening multiple column families with TTL
Date:      2022-05-11
ID:        RUSTSEC-2022-0046
URL:       https://rustsec.org/advisories/RUSTSEC-2022-0046
Solution:  Upgrade to >=0.19.0
```

**Comment by steviez** [comment]
> For reference, current status: https://discord.com/channels/428295358100013066/560503042458517505/1005314069860982927
> 
> There is also a new advisory requiring an upgrade:
> 
> ```
> Crate:     rocksdb
> Version:   0.18.0
> Title:     Out-of-bounds read when opening multiple column families with TTL
> Date:      2022-05-11
> ID:        RUSTSEC-2022-0046
> URL:       https://rustsec.org/advisories/RUSTSEC-2022-0046
> Solution:  Upgrade to >=0.19.0
> ```

Per https://discord.com/channels/428295358100013066/560503042458517505, this is being pushed in for the advistory despite temporarily breaking downstream-projects (spl namely)

**Pull request merged**
