### PR TITLE
v1.16: unpin tokio for various client crates

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
When we moved to workspace dependencies in v1.16, the tokio dependency was inadvertently changed in a bunch of client crates from the permissive "1" to the pinned version we require in rpc/validator. This causes issues for some downstream projects that use our client crates and don't want to use the ancient tokio v1.14.1.

#### Summary of Changes
Commit 1 relaxes the tokio dependency in the 2 specific client crates that we know are causing issues
Commit 2 reverts all the tokio changes inadvertently made in #29893 by making the un-tilded "1.14.1" the workspace default, and only strictly pinning `solana-core`, `solana-rpc` and `solana-rpc-test` (this also affects a couple client crates missed by #26957)

I prefer the workspace-wide change, but can roll back the 2nd commit if you prefer.

Closes #32943

### CODE REVIEW

**Review by mvines — APPROVED** [review]
wfm, thanks

**Comment by t-nelson** [comment]
the newly tilded crates are the ones where the unidentified (sync primitive?) hangs were occurring?

**Comment by CriesofCarrots** [comment]
> the newly tilded crates are the ones where the unidentified (sync primitive?) hangs were occurring?

Yes, exactly.

**Review by t-nelson — APPROVED** [review]
:shipit:

**Comment by buffalu** [comment]
YAS LFG

**Pull request merged**
