### PR TITLE
Add accounts-summary subcommand to ledger-tool

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
No easy way to get stats on the current number of active accounts

#### Summary of Changes
- Add `ledger-tool accounts-summary` subcommand for viewing a high level summary of active accounts

```
---
Accounts Summary:
  - Total accounts: 56
  - Total storage bytes: 561639
  - Rent paying accounts: 0
---
Top Program Accounts:
  1. Feature111111111111111111111111111111111111 Total: 29
  2. Sysvar1111111111111111111111111111111111111 Total: 8
  3. NativeLoader1111111111111111111111111111111 Total: 8
  4. BPFLoader2111111111111111111111111111111111 Total: 4
  5. 11111111111111111111111111111111 Total: 3
  6. Config1111111111111111111111111111111111111 Total: 1
  7. Vote111111111111111111111111111111111111111 Total: 1
  8. Stake11111111111111111111111111111111111111 Total: 1
  9. TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA Total: 1
```

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
Ideally these stats can be cached and served from the RPC API for use in the explorer as well

**Comment by jstarry** [comment]
@mvines is this useful? I created it as a one-off but thought it might be nice to check in

**Comment by ryoqun** [comment]
@jstarry I think these are useful maybe onset of this: https://github.com/solana-labs/solana/issues/10090

Also, there is laying my spl-token total cap checker grouped by mint, in my local repo.... I'll try to bring it finally....

**Comment by jstarry** [comment]
Thanks for pointing that issue out @ryoqun, I will expand this PR to include the other info listed there

**Comment by ryoqun** [comment]
> @jstarry I think these are useful maybe onset of this: #10090
> 
> Also, there is laying my spl-token total cap checker grouped by mint, in my local repo.... I'll try to bring it finally....

loong late self-reply: but here's the branch: https://github.com/ryoqun/solana/tree/spl-token-distribution

**Comment by jstarry** [comment]
Thanks @ryoqun! This one has fallen in priority but when I get some down time I'll try to wrap it up

**Comment by ryoqun** [comment]
@CriesofCarrots do you happen to have rebased version of https://github.com/ryoqun/solana/tree/spl-token-distribution locally? or, the branch worked as-is for the recent run of it?

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots do you happen to have rebased version of https://github.com/ryoqun/solana/tree/spl-token-distribution locally? or, the branch worked as-is for the recent run of it?

@ryoqun , sort of. I needed it rebased on v1.6 for mainnet-beta: https://github.com/CriesofCarrots/solana/tree/v1.6-spl-token-distribution
Also, I added code to track and print the number of 0-amount token accounts.

**Comment by ryoqun** [comment]
> > @CriesofCarrots do you happen to have rebased version of https://github.com/ryoqun/solana/tree/spl-token-distribution locally? or, the branch worked as-is for the recent run of it?
> 
> @ryoqun , sort of. I needed it rebased on v1.6 for mainnet-beta: https://github.com/CriesofCarrots/solana/tree/v1.6-spl-token-distribution Also, I added code to track and print the number of 0-amount token accounts.

(fyi, I'm revisiting this out-of-tree branch yet again)

**Pull request closed without merging**
