### PR TITLE
log write cache contents from purge_slots_from_cache_and_store

### PR DESCRIPTION
**Pull request by jeffwashington**
#### Problem

#24710

Log all pubkeys & hashes for accounts that are in slots we purge. Goal is to pinpoint the discrepancy in the slot that caused the accounts hash on the slot to differ.

#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by jeffwashington** [comment]
do we want to gate this info on us being the leader?

**Comment by jeffwashington** [comment]
do we expect the cache to have been flushed by the time we are here?

**Comment by jeffwashington** [comment]
1.9 still has random write cache evictions by slot.

**Comment by jeffwashington** [comment]
> 1.9 still has random write cache evictions by slot.

master and possibly 1.10 do not randomly evict from the write cache any more. I made that change after talking with @carllin .
I remind us of that here in case there is some issue related to the accounts being in the write cache vs being in an append vec.

**Review by carllin — DISMISSED** [review]

**Pull request merged**
