### PR TITLE
crate-features: cc cargo bump: required for Apple Silicon support on solana_client

### PR DESCRIPTION
**Pull request by nixxholas**
https://github.com/ctz/sct.rs/pull/7/files
https://github.com/briansmith/ring/issues/1063

Signed-off-by: nixxholas <nixholas@icloud.com>

#### Problem

Adopt support for Apple Silicon on 1.6.x.

#### Summary of Changes

Simply bumping the cc dependency would resolve the issue.

### CODE REVIEW

**Comment by mvines** [comment]
This should be simple, but it causes other dependencies to blow up :-/

**Comment by nixxholas** [comment]
> This should be simple, but it causes other dependencies to blow up :-/

Actually, there are many more dependencies required if we scope beyond solana-client. num_cpus should be referenced from the independent num_cpus instead of via cc.

**Comment by nixxholas** [comment]
Checking against the entire Solana suite, `reed-solomon-erasure` has a breaking dependency for arm as of now. I will carry on with develop on x86 for now until an update comes out.

https://github.com/darrenldl/reed-solomon-erasure

https://stackoverflow.com/questions/66661891/using-march-native-flag-with-clang-on-apple-m1
https://developer.apple.com/forums/thread/672654

**Comment by nixxholas** [comment]
Irrelevant due to: https://github.com/solana-labs/solana/pull/16346

**Pull request closed without merging**
