### PR TITLE
web3.js: Add Sysvar PubKeys

### PR DESCRIPTION
**Pull request by fanatid**
Closes https://github.com/solana-labs/solana/issues/21090

### CODE REVIEW

**Review by CriesofCarrots — COMMENTED** [review]
Sure, seems like a no-brainer. However, `SysvarFees` is deprecated as of v1.9.0, so I'm reluctant to add that one.

**Comment by fanatid** [comment]
Yeah, I know :disappointed: Should I remove it, or are we still good to go?

**Comment by CriesofCarrots** [comment]
> Yeah, I know 😞 Should I remove it, or are we still good to go?

Let's remove

**Comment by fanatid** [comment]
Removed.

**Pull request merged**
