### PR TITLE
Account for forward delay in transaction simulation

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
- Bank transaction simulation doesn't account for forwarding delays which means that a transaction could pass simulation but fail processing after forwarding

#### Summary of Changes
- Account for forwarding delay in simulation

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
I just removed the "fix" for last valid slot and this PR is just about transaction simulation now

**Review by CriesofCarrots — DISMISSED** [review]
Looks good. Could you add a comment about that adjustment? Maybe something about simulating worst-possible forwarding scenario

**Comment by jstarry** [comment]
Added a comment

**Comment by ryoqun** [comment]
(it seems this pr reduced its scope after I saw this for the first time; anyway meddling with `MAX_PROCESSING_AGE` and the like reminds me of #9423, well writing tests for it has been on my todo list for toooo long time. I haven't still get there...)

**Pull request merged**
