### PR TITLE
Limit GPU Shred verify to large batches of Shreds

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

Verifying Shreds on GPU may not be as fast as we hoped.

#### Summary of Changes

Limited GPU usage for Shred verification to 16k shreds or more.

The plot below shows mean shred verify time(in mircos) per sig-verify thread with GPU verify on the left and CPU verify on the right. 

gpu-vs-not

### CODE REVIEW

**Comment by aeyakovenko** [comment]
what's the difference with CPU utilization between the two runs.  timing of that stage isn't the only vector to optimize since its overlapping with a bunch of other work.

**Comment by sagar-solana** [comment]
@aeyakovenko I'll follow up with that in a few mins. I'm pretty sure we have sufficient cpu compute remaining :)

**Comment by aeyakovenko** [comment]
@sagar-solana but, whats the point of moving this to the CPU, if it doesn't impact latency and reduces cpu utilization.  that extra CPU can be used for more erasure coding, and more packets, etc...  The way we speed things up, move stuff of CPU as much as we can, overlap the pipelines as much as we can.

**Comment by sagar-solana** [comment]
It's almost 4 times slower on average to go to gpu with our current shred loads. It slows window and replay down where we're already on millisecond sensitivity.

**Comment by aeyakovenko** [comment]
@sagar-solana but its a different stage, so its overlapping with the other stages.

**Comment by sagar-solana** [comment]
Yeah you're right and this is just a theory but maybe verify is taking so long that now the batches it delivers back to window for processing are so large that window becomes cpu bound, delaying replay even more. 
So verify delays replay, then verify finishes, gives a very big batch to window, delaying replay even more.

**Comment by aeyakovenko** [comment]
you can tag the packets with a timestamp on recv and retransmit or store in block tree and record the delta between the two counters.

**Comment by aeyakovenko** [comment]
> window for processing are so large that window becomes cpu bound, delaying replay even more.

It's no more CPU bound, since the total amount of work is the same.

**Comment by sagar-solana** [comment]
it's more bursty work though. If you look at cpu verify the time is much lower and so are the number of shreds on average. Likely resulting in better peak-to-avg tvu usage.

**Comment by sagar-solana** [comment]
FYI, CPU usage peaks at 1100% (11/16 cores maxed out) with this work on window. 1 core is fully used by iftop and 1 core is fully used by bzip when making a snapshot. So total usage is 13/16 cores maxed. 

With gpu verify the peak usage is 880% so overall 10/16 cores maxed.

**Comment by aeyakovenko** [comment]
@sakridge wdyt, looks like 20% reduction in CPU utilization.  seems like a win.  I think latencies will improve once pinning is stable as well.

**Comment by aeyakovenko** [comment]
@sagar-solana can you add the CPU metrics to graphana ;)

**Comment by sagar-solana** [comment]
> can you add the CPU metrics to graphana ;)

How do you want me to do this? I found https://github.com/azuqua/spork.rs that I can maybe use and have a thread spun up to report it every second or so?

**Comment by sagar-solana** [comment]
So no to this @aeyakovenko ?

**Comment by aeyakovenko** [comment]
@sagar-solana up to @sakridge.

**Comment by sakridge** [comment]
@sagar-solana I think the limit is too high, the shreds will never go to GPU. Can you try 64 or 128? 
We can work on the batching as well.

**Comment by aeyakovenko** [comment]
@sakridge why would we ever send them to the CPU though?  I don't see a big deal with eating that latency there since its almost all overlapping.

**Comment by sakridge** [comment]
> @sakridge why would we ever send them to the CPU though? I don't see a big deal with eating that latency there since its almost all overlapping.

It's just not a good use of the GPU to send it a really small batch. You are using at least 1 SM and 1 of 8 hardware queues for 10-20ms just for 1 signature where you could do that on CPU in 100us.

**Comment by sagar-solana** [comment]
> the shreds will never go to GPU
@sakridge, that was kinda the point xD I don't think it becomes more efficient until much higher numbers. From the data I looked even batches of 4k shreds were faster on CPU.

**Comment by aeyakovenko** [comment]
> @sakridge, that was kinda the point xD I don't think it becomes more efficient until much higher numbers. From the data I looked even batches of 4k shreds were faster on CPU.

obviously thats not true, since CPU usage drops by 20%

**Comment by sagar-solana** [comment]
> obviously thats not true, since CPU usage drops by 20%

I'm only talking about the GPU being faster than CPU. I think it happens much later than the 64 limit we currently use. At least according to the datapoints I looked at where spikes upto 4k shreds took longer on GPU than on CPU

**Comment by aeyakovenko** [comment]
@sagar-solana, length of time that is overlapped by pipelining isn't something that we need to optimize.  so just because its faster, doesn't mean anything.

**Comment by sagar-solana** [comment]
What pipeline is this unblocking though? It's taking upto 200ms to verify a batch of shreds, which would take less than 200ms to replay. One 1 validator at any given time is doing both TPU/TVU. The rest of them are waiting for window to insert shreds and then for replay to play entries. 

When window takes 200+ms to insert into blocktree replay is idling. I'm sure there's a way to track and prove this. but just looking at the replay times with and without this PR show these delays.

**Comment by sagar-solana** [comment]
@sakridge @aeyakovenko 
I was working on a fix for repair on colo. The repair fix shows massive performance gains on colo since colo's network is lossy (PR soon). 
After that I disabled GPU shred verify on colo and it broke 110k tps across 3 nodes over a 5 min window. 

colo_insane


This(on the right) is tower/consensus stability with CPU shred verify. The runs on the left had GPU shred verify and the delays were causing forks. 

colo_stable

The gaps in confirmation go away as a result.
image

**Comment by aeyakovenko** [comment]
@sakridge @sagar-solana thats awesome!  I guess the next step is making sure we don’t split transactions over shreds and doing tx sigverify and shred sigverify in one go.

**Comment by carllin** [comment]
@aeyakovenko, @sakridge, do we have benchmarks that show at what number off shreds we expect GPU to outperform CPU for verification

**Comment by sakridge** [comment]
> > the shreds will never go to GPU
> 
> @sakridge, that was kinda the point xD I don't think it becomes more efficient until much higher numbers. From the data I looked even batches of 4k shreds were faster on CPU.

@sagar-solana 

That doesn't match my data, I printed the time and batch size on cpu and gpu runs:

I'm showing a cutoff around 32 in outright speed in average signatures per ms:

| cutoff | GPU | CPU |
| - | - | - |
| 16 | 6.5 | 6.7 |
| 32 | 7.7 | 6.8 |
| 64 | 8.7 | 7.6 |
| 128 | 10.7 | 8.5 |

cpu:
```
[2019-11-07T00:30:34.981079782Z INFO  solana_core::sigverify_shreds] verify_shreds_cpu: 118 time: 28ms
[2019-11-07T00:30:34.992864311Z INFO  solana_core::sigverify_shreds] verify_shreds_cpu: 118 time: 24ms
[2019-11-07T00:30:34.993395499Z INFO  solana_core::sigverify_shreds] verify_shreds_cpu: 128 time: 19ms
[2019-11-07T00:30:34.996625989Z INFO  solana_core::sigverify_shreds] verify_shreds_cpu: 126 time: 15ms
```

gpu:
```
[2019-11-07T00:03:12.589038639Z INFO  solana_core::sigverify_shreds] verify_shreds_gpu: 856 time: 13 ms
[2019-11-07T00:02:37.256224015Z INFO  solana_core::sigverify_shreds] verify_shreds_gpu: 668 time: 22 ms
[2019-11-07T00:02:37.256771278Z INFO  solana_core::sigverify_shreds] verify_shreds_gpu: 130 time: 13 ms
```

That doesn't even account for the fact that 2 sigverifies are going at a time on GPU.

**Comment by sagar-solana** [comment]
@sakridge any reason this would behave totally differently during a testnet?

**Comment by sakridge** [comment]
> @sakridge any reason this would behave totally differently during a testnet?

That is data from a testnet

**Comment by sagar-solana** [comment]
Okay any other way we can justify the fact that tps is higher/replay is less janky with CPU verify in a testnet?

**Comment by sakridge** [comment]
> Okay any other way we can justify the fact that tps is higher/replay is less janky with CPU verify in a testnet?

It's slower at lower batch sizes... did you try the cutoff?

**Comment by sagar-solana** [comment]
> It's slower at lower batch sizes... did you try the cutoff?

Negative, I outright disabled it and stability goes up noticeably. Just tore down my colo testnet :( I'll try this PR again later if you want.

**Comment by sagar-solana** [comment]
Just going to push that repair fix up and then I can try to find a cutoff point. sg?

**Comment by sagar-solana** [comment]
@sakridge with pinning enabled we don't need this anymore ?

**Comment by sakridge** [comment]
> @sakridge with pinning enabled we don't need this anymore ?

Probably we don't *need* it but I think we might be able to go faster with a low-ish cutoff like 64 or 128.

**Pull request closed without merging**
