### PR TITLE
Add exchange program

### PR DESCRIPTION
**Pull request by jackcmay**
#### Summary of Changes

Fixes #

### CODE REVIEW

**Comment by garious** [comment]
Thanks for using all the latest conventions! Any chance you can get that Transaction module out of there, and replace it with a Script module? All the other Transaction modules are on their way out.

**Comment by garious** [comment]
Looks like you don't even need the Script module and you can just delete the Transaction module.

**Comment by jackcmay** [comment]
@greg Are you thinking that I can get rid of the exchange_transaction modules?  If so, are you thinking the clients would call `Transaction::new()` themselves?  One thing to notice in the transaction module is that `new_account_request`, `new_trade_request`, and `new_swap_request` all use mvines trick to create an account.  That should probably not be up to the user.

**Comment by garious** [comment]
@jackcmay, you can create a Script instead of a Transaction https://github.com/solana-labs/solana/blob/master/programs/budget_api/src/budget_script.rs#L29.  It lets you create an API without a dependency on Keypair, Blockhash, or a fee. Leave it to the client to get a blockhash, create a transaction, and sign it (since it needs that on every retry anyway).

**Comment by garious** [comment]
@jackcmay, update: I think apps should be sending contracts messages. In current code, there is no Message object. The closest thing is the unsigned Transaction with a default blockhash and default fee. We can create those with `Transaction::new(instructions)`. Until we have `Message::new(instructions)`, that's what apps should pass to clients.

Over in the program crates, they don't need to know anything about Transactions or Messages. They can just define instructions and how to process them.

**Pull request merged**
