### PR TITLE
Reorg Storage program to look more like the others

### PR DESCRIPTION
**Pull request by garious**
#### Problem

Storage program has different file and naming conventions than the others.

#### Summary of Changes

* Break up lib.rs
* Rename StorageProgram to StorageInstruction
* Rename StorageProgramState to StorageContract
* Added StorageInstruction constructors
* Boot StorageTransaction

### CODE REVIEW

**Comment by sakridge** [comment]
Hmm. we have a StorageState already in storage_stage...

**Comment by garious** [comment]
Yikes, StorageState with `state` field holding a StorageStateInner? Can you think of more precise names for those?  Maybe even StorageStageState, perhaps?  But "...Inner" yuck! Call it what it is, not where it is.

**Comment by sakridge** [comment]
Sure. We can go with new names for those.. maybe SharedStorageStageState for outer and StorageStageState for what is the Inner one.

**Comment by sakridge** [comment]
But StorageState vs. StorageProgramState is a less precise name.

**Comment by garious** [comment]
@sakridge, I agree StorageState isn't very precise as soon as its outside the storage program crate. I renamed it to StorageContract. What do you think? Better? Worse?

**Comment by sakridge** [comment]
@garious StorageContract is good.

**Pull request merged**
