### PR TITLE
Bump version to v1.16.6

### PR DESCRIPTION
**Pull request by willhickey**

### CODE REVIEW

**Comment by willhickey** [comment]
The hashbrown version is oscillating every time we bump the v1.16 version and I'm not sure why:
#32419 0.11.2 -> 0.12.3
#32509 0.12.3 -> 0.11.2
This one: 0.11.2 -> 0.12.3

I'll dig into this.

**Review by lijunwangs — APPROVED** [review]
LGTM

**Comment by t-nelson** [comment]
:neutral_face: 

```
$ ./cargo tree --invert hashbrown 2>&1 | tail -n3 | while read hb; do ./cargo tree --invert $hb --depth 1; done
+ exec cargo +1.69.0 tree --invert hashbrown@0.11.2 --depth 1
hashbrown v0.11.2
├── borsh v0.9.3
└── borsh v0.10.3
+ exec cargo +1.69.0 tree --invert hashbrown@0.12.3 --depth 1
hashbrown v0.12.3
├── indexmap v1.9.3
└── lru v0.7.8
+ exec cargo +1.69.0 tree --invert hashbrown@0.13.2 --depth 1
hashbrown v0.13.2
├── ark-ec v0.4.2
└── ark-poly v0.4.2
```

**Comment by t-nelson** [comment]
i think we need to bring back the auto-reject of version bumps with extraneous changes. obv too easy to miss this stuff

**Comment by willhickey** [comment]
Manually reverted the hashbrown Cargo.lock changes. I'm looking into better ways to prevent this going forward.

**Review by steviez — APPROVED** [review]
> I haven't reviewed these version bump PRs before, so I'm not sure what else to look out for. Since @steviez has reviewed previous version bump PRs, I've requested a review here too, to double check me. TIA!

With Will's adjustment, change looks limited to "1.16.5" ==> "1.16.6" so LGTM! The hashbrown thing can seemingly be investigated / mitigated while pushing this in to unblock other v1.16 BPs

**Pull request merged**
