### PR TITLE
explorer: NextJS migration

### PR DESCRIPTION
**Pull request by nixxholas**
#### Problem
https://github.com/solana-labs/solana/issues/25987 introduces the potential backwards incompatibility of modern packages. With the explorer base currently built on top of Webpack 4 via create-react-app 4 (CRA4), we will need to migrate the project (without performing a massive rework) to another modern framework to absolve this.

#### Summary of Changes
1. Migration to [NextJS](https://nextjs.org/)
2. Support for Webpack 5 (Right out of the box)
3. Added image proxy as a work around to NextJS allowed [domains limit](https://github.com/vercel/next.js/blob/42f838e15632f0289a3da359d95000e6a833e7b5/packages/next/server/config.ts#L220-L224) - See [image-proxy](https://github.com/solana-fm/solana/blob/nextjs-migration/explorer/pages/api/image-proxy.ts)

#### Additional Changes
1. Requires CI switch to `next` from `create-react-app`

### CODE REVIEW

**Comment by nixxholas** [comment]
Hey guys, any updates on this? We will proceed to update compat if needed

**Comment by nixxholas** [comment]
Bump! We will start porting updates over.

**Comment by steveluscher** [comment]
Starting a discussion here: https://discord.com/channels/428295358100013066/531947850007969828/1001239968930349147

**Comment by nixxholas** [comment]
We've updated the branch with the recent updates. If this goes stale again, we will update it upstream again.

Core devs, seeking your assistance for this!

**Comment by BingHuang-Chin** [comment]
Current implementation of image proxy with `https://github.com/Blazity/next-image-proxy` is not stable, you might want to consider using DuckDuckGo's proxy instead `https://proxy.duckduckgo.com/iu/?u=<link_to_image>`.

The reason why NextJS requires an image proxy is due to their [security feature](https://nextjs.org/docs/api-reference/next/image#domains) with a limit of 50 whitelisted domains max which is not ideal to render images from multiple sources.

**Comment by ngundotra** [comment]
We really need to do this

**Pull request closed without merging**
