### PR TITLE
Eagerly receive records in sleepy tick producer

### PR DESCRIPTION
**Pull request by jstarry**
#### Problem
When the sleepy poh tick producer runs for tests, it doesn't process new Poh records while it sleeps. This causes some tests to get artificially delayed because they need to wait for the Poh recorder to confirm that each tx was recorded.

#### Summary of Changes
Move sleep duration to the record receiver timeout so that sleeps don't slow down new tx records

Fixes #

### CODE REVIEW

**Comment by jstarry** [comment]
This knocked 5s off the `test_rpc_subscriptions` test on my local machine

**Comment by jstarry** [comment]
@CriesofCarrots do you mind giving this a quick look?

**Comment by CriesofCarrots** [comment]
> do you mind giving this a quick look?

Will do today, sorry for the delay!

**Review by CriesofCarrots — APPROVED** [review]
Yep, makes sense to me. Thanks for noticing this!

**Pull request merged**
