### PR TITLE
Reduce Avalanche redundancy and implement traditional fanout

### LINKED ISSUE #3922: Fix Data Plane fanout
#### Problem

It appears that the Dataplane fanout isn't working as expected. Prime suspect being the set of stakes not being the same across all nodes. 
Another possible issue could be that nodes retransmit blobs back to the leader.

#### Proposed Solution

Triage this and figure out why blobs aren't being delivered in time correctly. Temporarily move the Data Plane fanout out of the way of our large(200+) node clusters.

Tag: @aeyakovenko @pgarg66

### PR DESCRIPTION
**Pull request by sagar-solana**
#### Problem

Avalanche has a little too much redundancy in the lower layers. While no issues have been observed with this, a traditional fanout implementation should have sufficient redundancy. The upper layers (leader to layer-1 and layer-1 to layer-2) rely on this reduced redundancy with no problem. 

#### Summary of Changes

Implemented a traditional fanout of nodes in Avalanche. An optimized implementation of the previous `grow` behavior where instead of sending blobs to _every_ next-layer neighborhood, each neighborhood is tasked with only sending blobs to `fanout` neighborhoods. This doesn't change the number of nodes each node has to communicate with (still `fanout * 2 - 1`) but does significantly reduce redundancy in lower layers.

Updated book and diagrams to reflect updated design. 

Tested with 37 nodes and a fanout of 2 on a CPU only testnet.
avalanche_fanout_2

Fixes #3922 #2955

### CODE REVIEW

**Comment by garious** [comment]
I think the piece I've been missing all along is: what the leader does is not base case. The leader's job is to seed base case (which ideally would be called Neighborhood 0).  The inductive step is then between the level containing Neighborhood 0 (which ideally would be called Level 0) and the next level (Level 1). With Fanout=2, Level 1 would contain Neighborhood 1 and 2. Level 2 would contain 4 neighborhoods.

If I have that right, it seems like this document would be much clearer of we had 3 [simple] diagrams instead of this one:

1. A diagram showing how the Leader seeds validators in Neighborhood 0
2. A diagram showing how a validator (or two) in neighborhood 0 communicates to 1 and 2
3. A diagram of just Neighborhoods (0, 1, 2, 3, 4, 5, and 6)

What I'm most curious about is if that third diagram ends up looking exactly like our original Avalanche diagram, but with neighborhoods instead of individual validators.

**Comment by sagar-solana** [comment]
Yes, that's exactly it. I'll update the indices to start at 0 and work on new diagrams. 3 _should_ look identical to the original design.

**Comment by aeyakovenko** [comment]
@sagar-solana do lower layers still rely on many neighborhoods for the block?

Next thing to do is to randomize the neighborhoods based on some leader defined seed.  Otherwise there is a stake weighted eclipse attack here.

**Comment by sagar-solana** [comment]
@aeyakovenko, not any more (It could result in 100000x packet traffic in lower layers). With this PR, lower layers have the same level of redundancy that the upper layers have.

> Next thing to do is to randomize the neighborhoods based on some leader defined seed. Otherwise there is a stake weighted eclipse attack here.

Yeah we could totally do that. Currently avalanche is structured based on confirmed stake. If no stake is found, we sort by node id (Pubkey). The seed is something we could stick in the blobs maybe. Given that we're using confirmed stake and that it falls back to id, it should be less susceptible to Eclipse attacks right?

Alternatively we could discuss some mechanism through which we allow each neighborhood to randomly push to N non-child next-layer neighborhoods alongside the usual. That should bring back some cross-neighborhood redundancy without flooding the network.

**Comment by aeyakovenko** [comment]
> Yeah we could totally do that. Currently avalanche is structured based on confirmed stake. If no stake is found, we sort by node id (Pubkey). The seed is something we could stick in the blobs maybe. Given that we're using confirmed stake and that it falls back to id, it should be less susceptible to Eclipse attacks right?

PoH hash in each blob, that is biased by the leader anyways and is a fairly random seed.  The idea would be to build a stake weighted tree, so higher the weight the more likely you end up at the top.

**Comment by sagar-solana** [comment]
@aeyakovenko, blobs don't have a poh right now, I think in the future they'll have the leader_id in them. So we _should_ be able to use that as a seed. 

>  The idea would be to build a stake weighted tree, so higher the weight the more likely you end up at the top.

Isn't that what we already have ? Can you elaborate on how it's different from what we're doing right now :)

**Comment by aeyakovenko** [comment]
@sagar-solana 
blob signature is probably the easiest source of randomness, since we don't need to unpack the blob to get it. 

1. sort the nodes by stake weight and pubkey
2. do a weighted selection with the blob signature as the seed to generate the broadcast tree
3. forward the blob.

This is done per blob, so the tree permutes every time.

**Comment by sagar-solana** [comment]
@aeyakovenko, Alright I'm on the same page now. 

So I'll file an issue for this. It could be something as simple as shuffling the nodes in a layer based on a seed per blob (might be expensive?) to generate a pretty solid set of neighborhoods. I like that sound of a super dynamic broadcast tree like this.

**Comment by aeyakovenko** [comment]
@sagar-solana the tree covers the full network, so it will hit the leaves eventually.

**Pull request merged**
