### PR TITLE
Reduce quic multi write test packets count

### PR DESCRIPTION
**Pull request by lijunwangs**
#### Problem

The tests test_quic_client_multiple_writes fails sporadically because all 4000 packets might not be sent all in the allotted time.
The issue is likely more easily showing up since the receive_window change when we reduce the receive_window for non-staked nodes.

#### Summary of Changes
Reduce the count to 3000

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
Could we make this less dependent on send speed (and potentially flaky) by sending a distinctive packet last and waiting for it before the `check_packet` asserts? We'd need to keep the 5s (or whatever) timeout.

**Comment by lijunwangs** [comment]
> Could we make this less dependent on send speed (and potentially flaky) by sending a distinctive packet last and waiting for it before the `check_packet` asserts? We'd need to keep the 5s (or whatever) timeout.

That is not trivial.     fn send_wire_transaction_batch_async(&self, buffers: Vec<Vec<u8>>) -> TransportResult<()> {
just spawn the txns onto the Runtime and then returns Ok before really confirming they are sent. Secondly, there is another async fact on the server side, a sent txns does not mean it has been processed by the server.

**Comment by CriesofCarrots** [comment]
Hmm, okay. It'd be great to find some deterministic fix here, but if this change helps, go for it.

**Comment by ryleung-solana** [comment]
I take this to imply we're effectively reducing the bandwidth for non-staked nodes. Just to confirm, is this intended? Agreed though that while a more deterministic solution is desired, it's really hard to make that happen.

**Pull request merged**
