### PR TITLE
rpc: performance fix for getProgramAccounts

### PR DESCRIPTION
**Pull request by ckamm**
#### Problem

The result accounts were pushed into a fresh vector one-by-one, which produced significant slowdowns for very large responses (visible when exceeding thousands of accounts).

#### Summary of Changes

Pre-allocate the right capacity - the result length is known.

### CODE REVIEW

**Comment by ckamm** [comment]
Optionally these could also be rewritten to use iterators, like
```
           keyed_accounts
                .into_iter()
                .map(|(pubkey, account)| {
                    Ok(RpcKeyedAccount {
                         pubkey: pubkey.to_string(),
                         account: encode_account(&account, &pubkey, encoding, data_slice_config)?,
                    })
                })
                .collect::<Result<Vec<_>>>()?
```

**Comment by jstarry** [comment]
> Optionally these could also be rewritten to use iterators, like
> 
> ```
>            keyed_accounts
>                 .into_iter()
>                 .map(|(pubkey, account)| {
>                     Ok(RpcKeyedAccount {
>                          pubkey: pubkey.to_string(),
>                          account: encode_account(&account, &pubkey, encoding, data_slice_config)?,
>                     })
>                 })
>                 .collect::<Result<Vec<_>>>()?
> ```

I typically prefer this approach, do you mind updating?

**Comment by ckamm** [comment]
@jstarry Not at all, that's what I did initially, then undid to keep the patch solely about the performance aspect. :)

**Comment by jstarry** [comment]
lgtm once the checks are fixed, thanks for this!

**Review by CriesofCarrots — COMMENTED** [review]
Looks like you just need to remove the `Ok(..?)` wrappers in two of your iterators, then gtg.
Thanks for this!

**Comment by ckamm** [comment]
> Looks like you just need to remove the `Ok(..?)` wrappers in two of your iterators, then gtg.

Could you elaborate? I'm intentionally making the `map()` produce an iterator over `Result<_>`, so I can deal with the potential error inside the closure. Is there a better way to write it?

**Comment by jstarry** [comment]
Screen Shot 2021-09-16 at 11 07 35 AM

**Comment by brianlong** [comment]
When this is ready, please prepare a version of v1.6.25 with these changes for staging & user testing. Apps are eager to test this out on the large mainnet account set for Serum Program V3.

**Review by jstarry — APPROVED** [review]

**Review by CriesofCarrots — APPROVED** [review]
Thanks again!

**Pull request merged**
