### PR TITLE
Disable rocksdb auto compaction

### PR DESCRIPTION
**Pull request by mvines**
cc: https://github.com/solana-labs/solana/issues/8116

### CODE REVIEW

**Comment by brianlong** [comment]
@mvines I am now running a modified version of v0.22.9 on my SLP node since that is where the problem seems to be the worst. I made the change that you suggest here. I also added the same statement in get_db_options().

I have questions about the OPTIONS-* files in `validator-ledger/rocksdb/`. I see two OPTIONS files there -- In the first file, OPTIONS-00024, disable_auto_compactions=false. In the second file, OPTIONS-00029, disable_auto_compactions=true (with one exception). It looks like the code change modified the contents of 00029, but not 00024.

Do you know where OPTIONS-00024 comes from? Why are there two options files? How do I drop/modify the first file?

```
brianlong@solana-slp:~/validator-ledger/rocksdb$ cat OPTIONS-000024 | grep disable_auto
  disable_auto_compactions=false
  disable_auto_compactions=false
  disable_auto_compactions=false
  disable_auto_compactions=false
  disable_auto_compactions=false
  disable_auto_compactions=false
  disable_auto_compactions=false
  disable_auto_compactions=false
  disable_auto_compactions=false
  disable_auto_compactions=false
brianlong@solana-slp:~/validator-ledger/rocksdb$ cat OPTIONS-000029 | grep disable_auto
  disable_auto_compactions=false
  disable_auto_compactions=true
  disable_auto_compactions=true
  disable_auto_compactions=true
  disable_auto_compactions=true
  disable_auto_compactions=true
  disable_auto_compactions=true
  disable_auto_compactions=true
  disable_auto_compactions=true
  disable_auto_compactions=true
```
The LOG files still shows heavy compaction activity.
// @sunnygleason

**Comment by brianlong** [comment]
More data from my modified SLP node. Interesting pattern on the disk utilization chart. I presume this is the manual compaction being triggered on a regular cycle. The underlying trend is up, so we are probably not deleting old data when we should be.

Screen Shot 2020-02-19 at 9 09 52 AM

**Comment by brianlong** [comment]
Here is a look at `du` on my `validator-ledger` folder. It seems like we could be more aggressive in deleting older snapshots. Also, more aggressive in deleting data within the `rocksdb` folder.

[validator-ledger-du.txt](https://github.com/solana-labs/solana/files/4226579/validator-ledger-du.txt)

**Comment by brianlong** [comment]
FYI, I purged & restarted this morning to avoid hitting 100% disc utilization.

**Comment by mvines** [comment]
> Here is a look at `du` on my `validator-ledger` folder. It seems like we could be more aggressive in deleting older snapshots. Also, more aggressive in deleting data within the `rocksdb` folder.
> 
> [validator-ledger-du.txt](https://github.com/solana-labs/solana/files/4226579/validator-ledger-du.txt)

Once https://github.com/solana-labs/solana/issues/8168 is fixed, we should see an improvement in the size of the `accounts/` directory at else.

The large number of snapshots in your `du` output is a little surprising, something seems a little wrong there

**Comment by brianlong** [comment]
I realize that this PR will be closed soon since we have moved on. However, I thought you might enjoy this Disk Usage chart from my modified SLP node. It looks like a Rorschach ink-blot test. What pattern do you see? I see a handlebar mustache. #WeirdChart

Screen Shot 2020-02-21 at 10 52 43 AM

**Pull request closed without merging**
