### PR TITLE
test for debit of TX fees on full process_transaction()

### PR DESCRIPTION
**Pull request by rob-solana**
#### Problem
 TX fees are debited from account[0] in account.rs on successful load
   https://github.com/solana-labs/solana/blob/9f046a023e72c703529ad6f4ee9703c8def26c4c/runtime/src/accounts.rs#L647
 AND in bank.rs

 #### Summary of Changes
 remove the bank.rs debit

### CODE REVIEW

**Comment by rob-solana** [comment]
tag @garious

**Comment by garious** [comment]
Sounds like a whole class of very important tests are missing.

**Comment by garious** [comment]
Thinking more on this, I don't think this is a double fee.  It's attempting to take a fee when the accounts are rolled back.  Perhaps a more elegant solution would be to take the fee before cloning the account. In any case, it needs to be impossible to add or delete that line without seeing a test fail.

**Comment by garious** [comment]
Yes!

**Comment by rob-solana** [comment]
my mistake was thinking that store() might for some reason also ignore program error, but I realized it couldn't possibly

**Pull request merged**
